### ISSUE TITLE
5-5 Heterogenous nightly failure: no such datastore and post to vc sdk error: connection reset by peer

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6752] opened 2017-11-13 15:38 UTC
Looks like for some reason, it properly recieved nfsDatastore as an image-store parameter, but then failed to query the VC for that datastore?
```
Nov  9 2017 20:14:44.381-06:00 DEBUG vSphere resource cache populating...
Nov  9 2017 20:14:44.478-06:00 DEBUG Cached dc: 
Nov  9 2017 20:14:44.625-06:00 DEBUG Cached cluster: 
Nov  9 2017 20:14:45.017-06:00 DEBUG Cached pool: 
Nov  9 2017 20:14:45.065-06:00 DEBUG Cached folders: 
Nov  9 2017 20:14:45.065-06:00 DEBUG Error count populating vSphere cache: (1)
Nov  9 2017 20:14:45.065-06:00 DEBUG new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
Nov  9 2017 20:14:45.066-06:00 INFO  Validating supplied configuration
Nov  9 2017 20:14:45.066-06:00 DEBUG Setting scratch image size to 8000000 KB in VCHConfig
Nov  9 2017 20:56:40.596-06:00 DEBUG no such datastore &url.URL{Scheme:"ds", Opaque:"", User:(*url.Userinfo)(nil), Host:"nfsDatastore", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
Nov  9 2017 20:56:40.596-06:00 INFO  Suggesting valid values for --image-store based on "nfsDatastore"
Nov  9 2017 20:56:40.647-06:00 ERROR Unable to list datastores: NotAuthenticated
Nov  9 2017 20:56:40.697-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.746-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.794-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.845-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.894-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.943-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.994-06:00 DEBUG no such network "bridge"
Nov  9 2017 20:56:41.044-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:41.045-06:00 DEBUG Network configuration:
```

[5-5-Heterogeneous-ESXi.zip](https://github.com/vmware/vic/files/1467433/5-5-Heterogeneous-ESXi.zip)

**Comment by AngieCris** [comment] 2017-11-27 17:14
The log message
```
Nov  9 2017 20:14:45.065-06:00 DEBUG Error count populating vSphere cache: (1)
Nov  9 2017 20:14:45.065-06:00 DEBUG new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
```
seems to appear in every successful vic-machine create as well. 
The place where it broke is:
```
Nov  9 2017 20:56:40.596-06:00 DEBUG no such datastore &url.URL{Scheme:"ds", Opaque:"", User:(*url.Userinfo)(nil), Host:"nfsDatastore", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
Nov  9 2017 20:56:40.596-06:00 INFO  Suggesting valid values for --image-store based on "nfsDatastore"
```
and after this line, all subsequent finding/listing of datastore and network fails with `NotAuthenticated`

**Comment by AngieCris** [comment] 2017-11-27 22:18
The complete log:
```
Nov  9 2017 20:14:43.322-06:00 INFO  ### Installing VCH ####
Nov  9 2017 20:14:43.322-06:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Nov  9 2017 20:14:43.322-06:00 DEBUG client network: IP {<nil> <nil>} gateway <nil> dest: []
Nov  9 2017 20:14:43.322-06:00 DEBUG public network: IP {<nil> <nil>} gateway <nil> dest: []
Nov  9 2017 20:14:43.322-06:00 DEBUG management network: IP {<nil> <nil>} gateway <nil> dest: []
Nov  9 2017 20:14:43.322-06:00 DEBUG VCH DNS servers: []
Nov  9 2017 20:14:43.322-06:00 DEBUG Unable to locate existing server certificate in cert path
Nov  9 2017 20:14:43.323-06:00 INFO  Generating self-signed certificate/key pair - private key in VCH-0-2203/server-key.pem
Nov  9 2017 20:14:44.064-06:00 WARN  Configuring without TLS verify - certificate-based authentication disabled
Nov  9 2017 20:14:44.064-06:00 DEBUG --target=https://10.162.30.233
Nov  9 2017 20:14:44.064-06:00 DEBUG --user=<censored>
Nov  9 2017 20:14:44.064-06:00 DEBUG --password=<censored>
Nov  9 2017 20:14:44.064-06:00 DEBUG --thumbprint=22:1E:1F:85:74:47:49:20:21:C3:71:A1:E2:F6:25:59:D4:D0:7F:6A
Nov  9 2017 20:14:44.064-06:00 DEBUG --name=VCH-0-2203
Nov  9 2017 20:14:44.064-06:00 DEBUG --compute-resource=cls
Nov  9 2017 20:14:44.064-06:00 DEBUG --image-store=nfsDatastore
Nov  9 2017 20:14:44.064-06:00 DEBUG --volume-store=nfsDatastore/VCH-0-2203-VOL:default
Nov  9 2017 20:14:44.064-06:00 DEBUG --bridge-network=bridge
Nov  9 2017 20:14:44.064-06:00 DEBUG --public-network=vm-network
Nov  9 2017 20:14:44.064-06:00 DEBUG --container-network=vm-network:public
Nov  9 2017 20:14:44.064-06:00 DEBUG --no-tlsverify=true
Nov  9 2017 20:14:44.064-06:00 DEBUG --insecure-registry=harbor.ci.drone.local
Nov  9 2017 20:14:44.064-06:00 DEBUG --appliance-iso=bin/appliance.iso
Nov  9 2017 20:14:44.064-06:00 DEBUG --bootstrap-iso=bin/bootstrap.iso
Nov  9 2017 20:14:44.064-06:00 DEBUG --force=true
Nov  9 2017 20:14:44.064-06:00 DEBUG --timeout=30m0s
Nov  9 2017 20:14:44.064-06:00 DEBUG --debug=1
Nov  9 2017 20:14:44.065-06:00 DEBUG Creating VMOMI session with thumbprint 22:1E:1F:85:74:47:49:20:21:C3:71:A1:E2:F6:25:59:D4:D0:7F:6A
Nov  9 2017 20:14:44.381-06:00 DEBUG Session Environment Info: 
Nov  9 2017 20:14:44.381-06:00 DEBUG vSphere resource cache populating...
Nov  9 2017 20:14:44.478-06:00 DEBUG Cached dc: 
Nov  9 2017 20:14:44.625-06:00 DEBUG Cached cluster: 
Nov  9 2017 20:14:45.017-06:00 DEBUG Cached pool: 
Nov  9 2017 20:14:45.065-06:00 DEBUG Cached folders: 
Nov  9 2017 20:14:45.065-06:00 DEBUG Error count populating vSphere cache: (1)
Nov  9 2017 20:14:45.065-06:00 DEBUG new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
Nov  9 2017 20:14:45.066-06:00 INFO  Validating supplied configuration
Nov  9 2017 20:14:45.066-06:00 DEBUG Setting scratch image size to 8000000 KB in VCHConfig
Nov  9 2017 20:56:40.596-06:00 DEBUG no such datastore &url.URL{Scheme:"ds", Opaque:"", User:(*url.Userinfo)(nil), Host:"nfsDatastore", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
Nov  9 2017 20:56:40.596-06:00 INFO  Suggesting valid values for --image-store based on "nfsDatastore"
Nov  9 2017 20:56:40.647-06:00 ERROR Unable to list datastores: NotAuthenticated
Nov  9 2017 20:56:40.697-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.746-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.794-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.845-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.894-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:40.943-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:40.994-06:00 DEBUG no such network "bridge"
Nov  9 2017 20:56:41.044-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:41.045-06:00 DEBUG Network configuration:
Nov  9 2017 20:56:41.045-06:00 DEBUG 	Network: bridge NetworkEndpoint: &{{  bridge } true <nil> {<nil> <nil>}  [] false}
Nov  9 2017 20:56:41.146-06:00 DEBUG no such network "vm-network"
Nov  9 2017 20:56:41.194-06:00 ERROR unable to list networks: NotAuthenticated
Nov  9 2017 20:56:41.243-06:00 DEBUG Checking firewall with management network IP {<nil> <nil>}
Nov  9 2017 20:56:41.243-06:00 ERROR Firewall check SKIPPED
Nov  9 2017 20:56:41.243-06:00 ERROR   datastore not set
Nov  9 2017 20:56:41.243-06:00 ERROR License check SKIPPED
Nov  9 2017 20:56:41.243-06:00 ERROR   datastore not set
Nov  9 2017 20:56:41.243-06:00 ERROR DRS check SKIPPED
Nov  9 2017 20:56:41.243-06:00 ERROR   datastore not set
Nov  9 2017 20:56:41.245-06:00 DEBUG Configuring without client verification due to empty certificate authorities
Nov  9 2017 20:56:41.245-06:00 DEBUG URL: https://harbor.ci.drone.local/v2/
Nov  9 2017 20:56:46.248-06:00 DEBUG URL: http://harbor.ci.drone.local/v2/
Nov  9 2017 20:56:51.251-06:00 WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Nov  9 2017 20:56:51.252-06:00 INFO  Insecure registries = harbor.ci.drone.local
Nov  9 2017 20:56:51.252-06:00 ERROR Compatibility check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR   datastore not set
Nov  9 2017 20:56:51.252-06:00 ERROR --------------------
Nov  9 2017 20:56:51.252-06:00 ERROR Post https://10.162.30.233/sdk: read tcp 10.17.109.217:35428->10.162.30.233:443: read: connection reset by peer
Nov  9 2017 20:56:51.252-06:00 ERROR NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --public-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --client-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --management-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR An existing distributed port group must be specified for bridge network on vCenter: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error adding container network "public": NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Firewall check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR License check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR DRS check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR Compatibility check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR Create cannot continue: configuration validation failed
Nov  9 2017 20:56:51.300-06:00 ERROR --------------------
Nov  9 2017 20:56:51.301-06:00 ERROR vic-machine-linux create failed: validation of configuration failed
```

The validation steps are:
1. target
2. credentials
3. compute
4. storage
5. network 
6. license and certificate 
...
This failure occurred in step 4, storage validation, and it's caused by failing to find datastore:
```
Nov  9 2017 20:56:40.596-06:00 DEBUG no such datastore &url.URL{Scheme:"ds", Opaque:"", User:(*url.Userinfo)(nil), Host:"nfsDatastore", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
```
This failure happens because govmomi's `DatastoreList(context, path)` function returns an error
(https://github.com/vmware/vic/blob/master/vendor/github.com/vmware/govmomi/find/finder.go#396)
This error returned is not immediately printed along with the log message, but captured and printed later, in the log enclosed by `-----------------------`.
which means the error returned by the `DatastoreList()` is captured in:
```
Nov  9 2017 20:56:51.252-06:00 ERROR --------------------
Nov  9 2017 20:56:51.252-06:00 ERROR Post https://10.162.30.233/sdk: read tcp 10.17.109.217:35428->10.162.30.233:443: read: connection reset by peer
Nov  9 2017 20:56:51.252-06:00 ERROR NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --public-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --client-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error checking network for --management-network: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR An existing distributed port group must be specified for bridge network on vCenter: NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Error adding container network "public": NotAuthenticated
Nov  9 2017 20:56:51.252-06:00 ERROR Firewall check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR License check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR DRS check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR Compatibility check SKIPPED
Nov  9 2017 20:56:51.252-06:00 ERROR Create cannot continue: configuration validation failed
Nov  9 2017 20:56:51.300-06:00 ERROR --------------------
```

All previous validation steps before storage validation (target, credentials, compute) succeeded, so in the part of the log enclosed by `-----`, there should not be any error messages returned from these steps, and because those validation errors are printed in order, the first error message:
```
Nov  9 2017 20:56:51.252-06:00 ERROR Post https://10.162.30.233/sdk: read tcp 10.17.109.217:35428->10.162.30.233:443: read: connection reset by peer
``` 
is the error returned by `DatastoreList()`, that caused the `no such datastore &url.URL{Scheme:"ds", Opaque:"", User:(*url.Userinfo)(nil), Host:"nfsDatastore", Path:"", RawPath:"".......` log message. 
And subsequent log errors `network NotAuthenticated` all result from this error. 


`10.162.30.233` is the VC IP, and `VC_IP/sdk` is the API endpoint of VC. When talking to the VC to query datastores, govmomi sends a POST request to the API endpoint. 
Then the connection is reset to `VC_IP:443` where hostd is at. It looks like something's messed up in the VC side, instead of bugs in vic-machine code (I think?)

**Comment by mlh78750** [comment] 2017-12-06 04:16
Are we still seeing these failures? Was this just an intermittent issue with VC in the CI? Could this also be 2005701? If this is a one off, let's close until there is a reproduction.

**Comment by hickeng** [comment] 2018-01-03 21:26
I doubt it's 2005701 as that really should be ESX specific - it's unverified but I'd hope that VC can handle much higher levels of event traffic than ESX.
Regardless we should be able to handle a dropped connection - this is the same core problem as #6673 - we need a way to trigger re-authentication when we *know* that that's the problem.
We cannot do so as an inline retry at a low level, and we cannot catch all issues (they are inlined in responses for PropertyCollectors for example), but we could add NotAuthenticated to the known set of errors in the tasks package. We would need to provide a mechanism by which a session can be re-authenticated.
Ideally all of this should be packaged away in the vmomi-gateway portion of the code so it's not a concern to the main consumers of the SDK.

**Comment by hickeng** [comment] 2018-01-03 22:17
I'm actually going to close this in favour of #6673 for addressing the re-authentication aspect.
Why VC dropped the connection is something I don't want to chase at this time without a recreate.

**Closed by hickeng** 2018-01-03 22:17 UTC
Labels: kind/bug, priority/high, team/lifecycle
