### ISSUE TITLE
Docker API Server: Support attach streaming

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#99] opened 2016-02-19 03:13 UTC
Subtask of #32 

Docker run -it busybox results in the following operations (assuming image is already present)
create
start
attach

So to fully support docker run we need to have the attach function. This is somewhat unique within the API as it's an unbounded stream response.

The snippet below is an example of the HTTP level request/response for an attach operation: 
```
ghicken@docker-dev:~/bonneville/binary/42$ telnet 10.136.29.75 2376
Trying 10.136.29.75...
Connected to 10.136.29.75.
Escape character is '^]'.
POST /v1.19/containers/6d/attach?stderr=1&stdin=1&stdout=1&stream=1 HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/vnd.docker.raw-stream



/ #
/ #

/ #
/ # echo date
echo date
date
/ #
/ # date
date
Fri Feb 19 03:02:32 UTC 2016
```

**Comment by hickeng** [comment] 2016-04-21 17:28
@sflxn if this is a duplicate of #362 please chose one to close - if not can you alter the titles to make the difference apparent.

**Comment by sflxn** [comment] 2016-05-06 17:08
Closing due to duplicate of #362.

**Closed by sflxn** 2016-05-06 17:08 UTC
Labels: area/apis, area/docker, component/docker-api-server
