### ISSUE TITLE
Nightly 5-14-Remove-Container-OOB

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#6084] opened 2017-08-22 20:49 UTC
This test will remove a containerVM via govc, but when installing to a vSphere cluster we disable the vSphere VM remove functionality so that we control when containerVMs can be removed.

We will need to re-enable the vSphere method prior to attempting the removal OOB.  This is strictly a test issue and not a code issue.

[5-14-Remove-Container-OOB-08202017.zip](https://github.com/vmware/vic/files/1243337/5-14-Remove-Container-OOB-08202017.zip)

**Comment by cgtexmex** [comment] 2017-08-22 20:59
set priority to high as this will fail every night...

**Comment by chengwang86** [comment] 2017-08-23 19:23
Does it just start to fail recently? I remember it didn't fail before.

**Comment by cgtexmex** [comment] 2017-08-23 19:26
I couldn't find any historical data on the test, so not sure...it's been failing this past week.

**Comment by chengwang86** [comment] 2017-08-23 19:28
I checked out our previous emails for nightly tests. It started to fail on Aug 2nd. Let's see what nightly test related PR were merged on/before that day.

**Comment by cgtexmex** [comment] 2017-08-23 19:40
Based on the git history looks like the test had been disabled for other issues and was just recently enabled.

**Comment by chengwang86** [comment] 2017-08-23 19:49
You are right. It was disabled by PR https://github.com/vmware/vic/pull/5089 since May 10th.

**Comment by chengwang86** [comment] 2017-08-23 20:16
This is reproducible in my local manual test.

The fix is simple as you suggested:
```
govc object.method -name Destroy_Task -enable %{TEST_DATACENTER}/vm/%{VCH-NAME}/${vm}
govc vm.destroy %{VCH-NAME}/${vm}
```

**Comment by chengwang86** [comment] 2017-08-23 21:55
The fix is blocked until we bump the integration-test image to use govc 0.15, since `govc object.method` is introduced since 0.15.

**Comment by chengwang86** [comment] 2017-08-23 22:16
@cgtexmex @mhagen-vmware On a second thought, since we disable OOB VM deletion intentionally in our code, this failure is expected. So instead of enabling `Destroy_Task` before OOB removal, we might do `Should Contain  ${out}   ... is disabled by VIC` after the govc cmd.

**Closed** 2017-08-28 13:24 UTC
Labels: component/test, priority/high
