### ISSUE TITLE
Longevity 6.5 - busybox image still in docker images ${output} after a successful docker rmi ${busybox} command 

### ISSUE THREAD

**Issue by rogeliosanchez** [vmware/vic#6107] opened 2017-08-24 21:48 UTC
**VIC version:**
vic_1339

[container-logs.zip](https://github.com/vmware/vic/files/1250328/container-logs.zip)
[html_and_xml_files.zip](https://github.com/vmware/vic/files/1250329/html_and_xml_files.zip)

**Comment by chengwang86** [comment] 2017-08-24 23:21
In the regression test, we do `docker pull busybox` twice. Therefore, in the second `docker pull busybox`, we expect to see outputs such as `layer already exists`. 

However, from log.html, I find 
```
(first docker pull)
Running command 'docker -H 10.17.109.7:2376 --tls pull busybox 2>&1'.
${output} = Using default tag: latest
latest: Pulling from library/busybox
9e87eff13613: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
9e87eff136...
```

```
(second docker pull)
Running command 'docker -H 10.17.109.7:2376 --tls pull busybox 2>&1'.
${output} = Using default tag: latest
latest: Pulling from library/busybox
add3ddb21ede: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
add3ddb21e...
```

```
Running command 'docker -H 10.17.109.7:2376 --tls images 2>&1'.
${output} = REPOSITORY          TAG                 IMAGE ID            CREATED                  SIZE 
busybox             latest              d20ae45477cb        Less than a second ago   1.13 MB 
busybox          ... ...
```

It seems that we pulled two different busybox images which resulted in the error that `docker images` showing the existence of `busybox` after `docker rmi busybox`.

As a comparison, here is the `docker images` output from a successful run:
```
Running command 'docker -H 10.17.109.7:2376 --tls images 2>&1'.
${output} = REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              efe10ee6727f        4 weeks ago         1.13 MB
```

**Comment by chengwang86** [comment] 2017-08-24 23:24
Here is what I find on vanilla docker
```
cheng@ubuntu:~/go/src/github.com/vmware/vic$ docker images
REPOSITORY                                         TAG                 IMAGE ID            CREATED             SIZE
busybox                                            latest              efe10ee6727f        5 weeks ago         1.13 MB

cheng@ubuntu:~/go/src/github.com/vmware/vic$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
add3ddb21ede: Pull complete 
Digest: sha256:b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692
Status: Downloaded newer image for busybox:latest

cheng@ubuntu:~/go/src/github.com/vmware/vic$ docker images
REPOSITORY                                         TAG                 IMAGE ID            CREATED             SIZE
busybox                                            latest              d20ae45477cb        24 hours ago        1.13 MB
busybox                                            <none>              efe10ee6727f        5 weeks ago         1.13 MB
```
So it seems that the `latest` busybox images has been updated recently. So what we see on vic is the same with what I find on vanilla docker, and this failure is expected.

**Comment by chengwang86** [comment] 2017-08-25 15:32
So my proposed solutions are:

-  use local harbor instead of dockerhub for docker pull in the longevity test
- ignore this failure. As long as the busybox image is not updated very frequently, our longevity test should be fine

**Comment by cgtexmex** [comment] 2017-08-25 15:55
IMO the ideal solution would be to pull by digest (busybox@sha256:b82b5740006c1ab823596d2c07f081084ecdb32fd258072707b99f52a3cb8692), but that would run into issues because of #5187.  So another option would be to pull a version of busybox that doesn't change -- `busybox:1.24.1` comes to mind...so pull and remove by a specific tag instead of defaulting to `latest`

**Comment by mhagen-vmware** [comment] 2017-08-25 16:15
closing issue, this is a one in a million+ fluke.  If they had updated the image 10 seconds earlier or later it would not have caused any issues.  They just happened to update the image within a 13 second window between our two pull attempts.

**Closed by mhagen-vmware** 2017-08-25 16:15 UTC
Labels: component/test, priority/high

**Comment by mhagen-vmware** [comment] 2017-08-25 16:16
When we have a more comprehensive CI plan moving forward part of that plan will need to be a harbor instance that will be used for testing like this that we control and prevents any sort of random image changes that are not approved by us.
