### ISSUE TITLE
VCH creation failed with "cannot validate certificate error" even with --thumbprint option

### ISSUE THREAD

**Issue by tschwaller** [vmware/vic#4112] opened 2017-03-01 21:59 UTC
**VIC engine version:** 0.8.0

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

The following shell script was used on Ubuntu 16.04.

```
#!/bin/bash

set -x

#export VCENTERSERVER="vcsa.vmware-sddc.test-bosch.com"
export VCENTERSERVER="10.116.131.11"
export VCENTERDATACENTER="PoC-Datacenter"
export VCENTERCLUSTER="EMEA-Cluster"
export VSPHEREUSER="tschwaller"
export VSPHEREPASSWORD="VMware1!"
export VSPHEREDATASTORE="vsanDatastore-reg2"
export PUBLICNETWORK="VM Network"
export VCHINTERNALNETWORK="VCH-Development"
export THUMBPRINT="C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5"
export VCHTLS=1
export VCHNAME="VCH-Development"
export VCHIP="10.116.131.47"
export VCHGATEWAY="10.116.131.254/24"

export HARBORVMIP="10.116.131.45"
export LOG_OUTPUT="vic-product-machine.log"

./vic-machine-linux create --debug 1 --name ${VCHNAME} \
           --target "${VCENTERSERVER}"/"${VCENTERDATACENTER}" --thumbprint "${THUMBPRINT}" \
           --user "${VSPHEREUSER}" \
           --password "${VSPHEREPASSWORD}" \
           --compute-resource "${VCENTERCLUSTER}" \
           --bridge-network "${VCHINTERNALNETWORK}" \
           --public-network "${PUBLICNETWORK}" \
           --public-network-ip "${VCHIP}" \
           --public-network-gateway "${VCHGATEWAY}" \
           --image-store "${VSPHEREDATASTORE}"  \
           --insecure-registry "${HARBORVMIP}" \
           --volume-store "${VSPHEREDATASTORE}"/"${VCHNAME}"-volumes:default \
           --timeout 10m0s \
           ${VICMACHINETLSFLAG} #>> "${LOG_OUTPUT}" 2>&1
```

**Steps to reproduce:**

Error can only be reproduced in the actual environment (in others it works)

**Actual behavior:**

VCH creation fails. The command did also not work when I replaced the DNS name by an IP address.

**Expected behavior:**

VCH creation works.

**Logs:**

Here is the output of the script (debugging output activated in Bash and in vic-engine-linux):

```
+ export VCENTERSERVER=10.116.131.11
+ VCENTERSERVER=10.116.131.11
+ export VCENTERDATACENTER=PoC-Datacenter
+ VCENTERDATACENTER=PoC-Datacenter
+ export VCENTERCLUSTER=EMEA-Cluster
+ VCENTERCLUSTER=EMEA-Cluster
+ export VSPHEREUSER=tschwaller
+ VSPHEREUSER=tschwaller
+ export 'VSPHEREPASSWORD=VMware1!'
+ VSPHEREPASSWORD='VMware1!'
+ export VSPHEREDATASTORE=vsanDatastore-reg2
+ VSPHEREDATASTORE=vsanDatastore-reg2
+ export 'PUBLICNETWORK=VM Network'
+ PUBLICNETWORK='VM Network'
+ export VCHINTERNALNETWORK=VCH-Development
+ VCHINTERNALNETWORK=VCH-Development
+ export THUMBPRINT=C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5
+ THUMBPRINT=C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5
+ export VCHTLS=1
+ VCHTLS=1
+ export VCHNAME=VCH-Development
+ VCHNAME=VCH-Development
+ export VCHIP=10.116.131.47
+ VCHIP=10.116.131.47
+ export VCHGATEWAY=10.116.131.254/24
+ VCHGATEWAY=10.116.131.254/24
+ export HARBORVMIP=10.116.131.45
+ HARBORVMIP=10.116.131.45
+ export LOG_OUTPUT=vic-product-machine.log
+ LOG_OUTPUT=vic-product-machine.log
+ ./vic-machine-linux create --debug 1 --name VCH-Development --target 10.116.131.11/PoC-Datacenter --thumbprint C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5 --user tschwaller --password 'VMware1!' --compute-resource EMEA-Cluster --bridge-network VCH-Development --public-network 'VM Network' --public-network-ip 10.116.131.47 --public-network-gateway 10.116.131.254/24 --image-store vsanDatastore-reg2 --insecure-registry 10.116.131.45 --volume-store vsanDatastore-reg2/VCH-Development-volumes:default --timeout 10m0s
INFO[2017-03-01T22:27:35+01:00] ### Installing VCH ####
time=2017-03-01T22:27:35.415001310+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495]
WARN[2017-03-01T22:27:35+01:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
DEBU[2017-03-01T22:27:35+01:00] public network: IP {"10.116.131.47" "ffffff00"} gateway {"10.116.131.254" "ffffff00"} dest: []
DEBU[2017-03-01T22:27:35+01:00] VCH DNS servers: []
INFO[2017-03-01T22:27:35+01:00] Using public-network-ip as cname where needed - use --tls-cname to override: 10.116.131.47
time=2017-03-01T22:27:35.415085937+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:924]
time=2017-03-01T22:27:35.415768836+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
time=2017-03-01T22:27:35.416309564+01:00 level=debug msg=[ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [537.492µs]
INFO[2017-03-01T22:27:35+01:00] Loaded server certificate VCH-Development/server-cert.pem
INFO[2017-03-01T22:27:35+01:00] Loaded CA with default name from certificate path VCH-Development
time=2017-03-01T22:27:35.416918622+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
time=2017-03-01T22:27:35.417461340+01:00 level=debug msg=[ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [541.146µs]
INFO[2017-03-01T22:27:35+01:00] Loaded client certificate with default name from certificate path VCH-Development
time=2017-03-01T22:27:35.417692425+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:924] [2.604709ms]
time=2017-03-01T22:27:35.417703651+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1068]
DEBU[2017-03-01T22:27:35+01:00] Not generating server or client certs, nothing for generateCertificates to do
time=2017-03-01T22:27:35.417718956+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1068] [14.739µs]
time=2017-03-01T22:27:35.417727581+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:867]
time=2017-03-01T22:27:35.417737869+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:867] [7.125µs]
time=2017-03-01T22:27:35.417746909+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495] [2.746752ms]
DEBU[2017-03-01T22:27:35+01:00] --target=https://10.116.131.11/PoC-Datacenter
DEBU[2017-03-01T22:27:35+01:00] --user=<censored>
DEBU[2017-03-01T22:27:35+01:00] --password=<censored>
DEBU[2017-03-01T22:27:35+01:00] --thumbprint=C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5
DEBU[2017-03-01T22:27:35+01:00] --name=VCH-Development
DEBU[2017-03-01T22:27:35+01:00] --compute-resource=EMEA-Cluster
DEBU[2017-03-01T22:27:35+01:00] --image-store=vsanDatastore-reg2
DEBU[2017-03-01T22:27:35+01:00] --volume-store=[vsanDatastore-reg2/VCH-Development-volumes:default]
DEBU[2017-03-01T22:27:35+01:00] --bridge-network=VCH-Development
DEBU[2017-03-01T22:27:35+01:00] --public-network=VM Network
DEBU[2017-03-01T22:27:35+01:00] --public-network-gateway=10.116.131.254/24
DEBU[2017-03-01T22:27:35+01:00] --public-network-ip=10.116.131.47
DEBU[2017-03-01T22:27:35+01:00] --insecure-registry=[10.116.131.45]
DEBU[2017-03-01T22:27:35+01:00] --timeout=10m0s
DEBU[2017-03-01T22:27:35+01:00] --debug=1
time=2017-03-01T22:27:35.418008967+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles:77]
time=2017-03-01T22:27:35.418027311+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:162]
time=2017-03-01T22:27:35.418035641+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:133]
time=2017-03-01T22:27:35.418055969+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:133] [18.884µs]
time=2017-03-01T22:27:35.418081486+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2017-03-01T22:27:35.418092276+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [14µs]
time=2017-03-01T22:27:35.418103652+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2017-03-01T22:27:35.418110659+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [6.473µs]
time=2017-03-01T22:27:35.418117398+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:162] [90.06µs]
time=2017-03-01T22:27:35.418129716+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:162]
time=2017-03-01T22:27:35.418135685+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:133]
time=2017-03-01T22:27:35.418151690+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:133] [15.064µs]
time=2017-03-01T22:27:35.418159575+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2017-03-01T22:27:35.418166206+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [6.14µs]
time=2017-03-01T22:27:35.418173445+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188]
time=2017-03-01T22:27:35.418179835+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:188] [5.797µs]
time=2017-03-01T22:27:35.418188339+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:162] [58.192µs]
time=2017-03-01T22:27:35.418193928+01:00 level=debug msg=[ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles:77] [188.589µs]
time=2017-03-01T22:27:35.418214640+01:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:86]
time=2017-03-01T22:27:35.451167016+01:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:86] [32.942052ms]
ERRO[2017-03-01T22:27:35+01:00] Create cannot continue: failed to create validator
ERRO[2017-03-01T22:27:35+01:00] --------------------
ERRO[2017-03-01T22:27:35+01:00] vic-machine-linux failed: Failed to connect to 10.116.131.11: Post https://10.116.131.11/sdk: x509: cannot validate certificate for 10.116.131.11 because it doesn't contain any IP SANs
```

**Comment by dougm** [comment] 2017-03-01 23:39
@tschwaller can you include the output of the following command:

`curl -s --verbose -k https://10.116.131.11/sdk/vim.wsdl >/dev/null`

And if you could also re-run the vic-machine create command, but omit the --thumbprint flag and value and include that output.  Thanks.

**Comment by andrewtchin** [comment] 2017-03-02 18:29
watching

**Comment by tschwaller** [comment] 2017-03-05 01:18
Output of `curl -s --verbose -k https://10.116.131.11/sdk/vim.wsdl >/dev/null` is below. The VCSA is using a self signed certificate (standard installation of VCSA with no cert changes). The error message 
`common name ... does not match '10.116.131.11'` is strange indeed! I replaced the real customer name with `CUSTOMERNAME` in all the outputs.

<pre>
<b>curl -s --verbose -k https://10.116.131.11/sdk/vim.wsdl >/dev/null>/dev/null</b>

*   Trying 10.4.103.143...
* Connected to 10.4.103.143 (10.4.103.143) port 8080 (#0)
* Establish HTTP proxy tunnel to 10.116.131.11:443
* Proxy auth using Basic with user 'de\syo7fe'
> CONNECT 10.116.131.11:443 HTTP/1.1
> Host: 10.116.131.11:443
> Proxy-Authorization: Basic ZGVcc3lvN2ZlOlNEREN2bXcyMDE3IQ==
> User-Agent: curl/7.50.1
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 176 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: vcsa.vmware-sddc.test-CUSTOMERNAME.com (does not match '10.116.131.11')
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=vcsa.vmware-sddc.test-CUST)OMERNAME.com,C=US
*        start date: Mon, 28 Nov 2016 15:34:49 GMT
*        expire date: Mon, 23 Nov 2026 15:34:49 GMT
*        issuer: CN=CA,DC=vsphere,DC=local,C=US,ST=California,O=vcsa.vmware-sddc.test-CUSTOMERNAME.com,OU=VMware
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /sdk/vim.wsdl HTTP/1.1
> Host: 10.116.131.11
> User-Agent: curl/7.50.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 5 Mar 2017 00:48:23 GMT
< Cache-Control: no-cache
< Connection: Keep-Alive
< Content-Type: text/xml; charset=utf-8
< X-Frame-Options: DENY
< Content-Length: 1293257
<
{ [16153 bytes data]
* Connection #0 to host 10.4.103.143 left intact
</pre>

Here is the output of the same command with the FQDN instead of the IP and this one looks better.

<pre>
<b>curl -s --verbose -k https://vcsa.vmware-sddc.test-CUSTOMERNAME.com/sdk/vim.wsdl >/dev/null</b>

*   Trying 10.4.103.143...
* Connected to 10.4.103.143 (10.4.103.143) port 8080 (#0)
* Establish HTTP proxy tunnel to vcsa.vmware-sddc.test-CUSTOMERNAME.com:443
* Proxy auth using Basic with user 'de\syo7fe'
> CONNECT vcsa.vmware-sddc.test-CUSTOMERNAME.com:443 HTTP/1.1
> Host: vcsa.vmware-sddc.test-CUSTOMERNAME.com:443
> Proxy-Authorization: Basic ZGVcc3lvN2ZlOlNEREN2bXcyMDE3IQ==
> User-Agent: curl/7.50.1
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 176 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: vcsa.vmware-sddc.test-CUSTOMERNAME.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=vcsa.vmware-sddc.test-CUSTOMERNAME.com,C=US
*        start date: Mon, 28 Nov 2016 15:34:49 GMT
*        expire date: Mon, 23 Nov 2026 15:34:49 GMT
*        issuer: CN=CA,DC=vsphere,DC=local,C=US,ST=California,O=vcsa.vmware-sddc.test-CUSTOMERNAME.com,OU=VMware
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /sdk/vim.wsdl HTTP/1.1
> Host: vcsa.vmware-sddc.test-CUSTOMERNAME.com
> User-Agent: curl/7.50.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 5 Mar 2017 01:01:08 GMT
< Cache-Control: no-cache
< Connection: Keep-Alive
< Content-Type: text/xml; charset=utf-8
< X-Frame-Options: DENY
< Content-Length: 1293257
<
{ [15816 bytes data]
* Connection #0 to host 10.4.103.143 left intact
</pre>

And here is the output of the `vic-machine-linux create` command with `--thumbprint` deleted.

<pre>
<b>./vic-machine-linux create --name VCH-Development --target 10.116.131.11/CUSTOMERNAME-PoC-Datacenter --user tschwaller --password 'VMware1!' --compute-resource EMEA-Cluster --bridge-network VCH-Development --public-network 'VM Network' --public-network-ip 10.116.131.47 --public-network-gateway 10.116.131.254/24 --image-store vsanDatastore-reg2 --insecure-registry 10.116.131.45 --volume-store vsanDatastore-reg2/VCH-Development-volumes:default --timeout 10m0s</b>

INFO[2017-03-05T01:56:56+01:00] ### Installing VCH ####
WARN[2017-03-05T01:56:56+01:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2017-03-05T01:56:56+01:00] Using public-network-ip as cname where needed - use --tls-cname to override: 10.116.131.47
INFO[2017-03-05T01:56:56+01:00] Loaded server certificate VCH-Development/server-cert.pem
INFO[2017-03-05T01:56:56+01:00] Loaded CA with default name from certificate path VCH-Development
INFO[2017-03-05T01:56:56+01:00] Loaded client certificate with default name from certificate path VCH-Development
ERRO[2017-03-05T01:56:56+01:00] Failed to verify certificate for target=10.116.131.11 (thumbprint=C7:48:9F:5D:43:19:47:9F:E0:56:5A:D9:8F:6F:8C:EC:E8:E7:D0:F5)
ERRO[2017-03-05T01:56:56+01:00] Create cannot continue: failed to create validator
ERRO[2017-03-05T01:56:56+01:00] --------------------
ERRO[2017-03-05T01:56:56+01:00] vic-machine-linux failed: x509: cannot validate certificate for 10.116.131.11 because it doesn't contain any IP SANs
</pre>

**Comment by andrewtchin** [comment] 2017-03-06 16:35
@tschwaller I believe the error message `common name: vcsa.vmware-sddc.test-CUSTOMERNAME.com (does not match '10.116.131.11')` is expected because the certificate presented on https://10.116.131.11/sdk/vim.wsdl is not signed for the IP address and is instead signed for the hostname, which is why the second curl command successfully validates the certificate. 
Could you paste the output of the original command you showed us in Slack, excluding `--force`, using the DNS name and thumbprint, and including `--debug 1`? Thanks!

**Comment by corrieb** [comment] 2017-03-06 18:36
Whatever we learn from this, let's make sure it's well-documented. @tschwaller is a smart guy!

**Comment by stuclem** [comment] 2017-03-07 14:23
Here's a highly uninformative proposal for the 0.9 release notes:

----


- <b>VCH deployment fails with certificate validation error even when using the `--thumbprint` option. [#4112](https://github.com/vmware/vic/issues/4112)</b><br> VCH deployment fails with the following error, even if you correctly specify the `--thumbprint` option:<pre>Failed to verify certificate for target=<i>target</i> (thumbprint=<i>thumbprint</i>)
Create cannot continue: failed to create validator
vic-machine-linux failed: x509: cannot validate certificate for 
<i>target</i> because it doesn't contain any IP SANs</pre>

----

@andrewtchin can you please provide a couple of lines that summarize the issue? Thanks!

**Comment by dougm** [comment] 2017-03-07 15:37
@stuclem let's wait to document this until we know what is causing the issue.

In the curl output we can see there is a proxy server, it is possible the proxy connection will bypass our thumbprint check.  This is something we should try to reproduce.

**Comment by stuclem** [comment] 2017-03-07 16:36
@dougm OK, duly removed from the RNs for the time being.

**Comment by hickeng** [comment] 2017-03-07 21:12
@tschwaller If the vcenter certificate doesn't have any IP SANs then we would _need_ to use the FQDN for it to match. Please can you provide the vic-machine debug output for that scenario.
As @dougm noted, `curl` reported that this was going via a proxy and that's a very configuration dependent setup - the other environments that you say work... do they also have a proxy involved?
Does this error occur if vic-machine is run from a system on the same network as the VC?

**Comment by tschwaller** [comment] 2017-03-08 12:03
`vic-machine` is run from the same network as the VC and FQDN & IP produced the same result. Had a debugging session yesterday with GSS and we tried a lot of things without success. But the good news is: After that session I downloaded VIC engine build 8471 and 8508 and suddenly it worked. So it seems this has been fixed in the meanwhile.

P.S.: When I used  `--tls-cname` with `vic-machine` I got as output to use an IP address with `docker -H ` which did not work (certificate error). When I did NOT use  `--tls-cname` then the output of  `vic-machine` told me to use the FQDN and it worked!

**Comment by hickeng** [comment] 2017-03-08 15:59
@tschwaller I don't know of any changes that would have gone in that would have addressed the VC cert issue.

@andrewtchin added some code recently that improved our inspection of certificates for reporting the appropriate name.
@andrewtchin I don't recall if the changes you made also apply to `vic-machine inspect`? I'd hope so, but ...

**Comment by andrewtchin** [comment] 2017-03-08 19:35
@hickeng The only thing I can see that affected `vic-machine inspect` was allowing wildcards in `viableHostAddress` https://github.com/vmware/vic/pull/4068/files#diff-ab6c58c594b80369f767fa321a81c06eR386
I could see there being a different warning/error if `vic-machine create` was previously failing in `DockerAPICheck` with the `doesn't contain any IP SANs` error as we now sometimes warn and proceed with install when we get `HostnameError` https://github.com/vmware/vic/pull/4068/files#diff-13cb124a8b8b2d0e7744466165fd84ffR920

In any case, @tschwaller if you're not seeing this anymore let us know if we can close this issue?

**Comment by stuclem** [comment] 2017-03-09 16:10
Dropping the kind/note tag. If you decide that this does need documenting, please put it back.

**Comment by mdubya66** [comment] 2017-03-15 18:33
closing as not reproducible.

**Closed** 2017-03-15 18:33 UTC
Labels: component/vic-machine, kind/bug, kind/customer-found, priority/high
