### ISSUE TITLE
Volume rm not removing the volume

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1720] opened 2016-07-28 15:54 UTC
Running command 'docker -H 192.168.254.172:2375 volume rm test2
${rc} = 0 	
${output} = test2

Running command 'docker -H 192.168.254.172:2375 volume ls
${rc} = 0 	
${output} = DRIVER              VOLUME NAME
vsphere             test
vsphere             test2

**Comment by fdawg4l** [comment] 2016-07-28 18:48
This is a dupe of #1511.  I'd like to close this unless you want to track the integration test separately @mhagen-vmware .

**Closed** 2016-08-08 19:43 UTC
