### ISSUE TITLE
Docker ps -l and ps -n=2 does not show containers that have been created but not started

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1545] opened 2016-07-18 15:12 UTC
docker create busybox ls
docker ps -l

Actual output:

```
anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.172:2376 --tls create busybox ls
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
9d928c7aad5547269313da1e17d92a4ccd06696566f6d22eb24020933b3d996c
anon@anon-Latitude-E7450:~/vic$ docker -H 192.168.254.172:2376 --tls ps -l
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Expected output:

```
anon@anon-Latitude-E7450:~/vic$ docker create busybox ls
115184175ef93607b77dda774445bb5cb57b0bd31ff2f33bcf97f4374c97a24d
anon@anon-Latitude-E7450:~/vic$ docker ps -l
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
115184175ef9        busybox             "ls"                5 seconds ago       Created                                 admiring_minsky
```

**Comment by mdubya66** [comment] 2016-07-19 14:11
@hickeng needs an owner

**Comment by hickeng** [comment] 2016-07-26 23:51
The same is true for `ps -n <x>` no matter what number is supplied. `ps -l` should show the last created container irrespective of state so the fact that we show STOPPED instead of CREATED for state should not be the cause.

Assigning to @jzt as this relates to the filtering. My speculation is that we're either:
a. seeing this because of a time skew between client and server that puts creation time in the future, or
b. we're not filling in a portion of the container inspect output that is needed for this operation.

**Comment by cgtexmex** [comment] 2016-07-27 14:49
I'm taking this from @jzt as it's very similar to #1676 and can be done in conjunction with it.

**Comment by matthewavery** [comment] 2016-09-07 16:29
@cgtexmex moved this to a feature from a bug, even though there is a test it is being done in conjunction with a feature implementation.

**Comment by stuclem** [comment] 2016-11-07 17:59
Already in the release notes, so removing the kind/note tag.

**Comment by mhagen-vmware** [comment] 2017-01-18 14:55
setting this to medium in the thought that we will need this for either admiral or at least one of our feature items we are working on in the release planning

**Comment by mhagen-vmware** [comment] 2017-02-03 15:58
lgtm

**Closed** 2017-02-03 16:01 UTC
Labels: kind/bug, kind/feature, priority/medium, status/has-integration-test
