### ISSUE TITLE
docker rmi behaviour changed

### ISSUE THREAD

**Issue by malikkal** [vmware/vic#7118] opened 2018-01-18 04:30 UTC
VIC Engine v1.3.0-15556-473375a

User statement: As a customer of VIC, I would like to have upgrade maintain backward compatibility (if possible) so that we could handle consistent development.

Details: In the past docker rmi <image id> used to work; but, it now returns an error as below:

```
docker rmi 6f146fe8049d
Error response from daemon: No such image: 6f146fe8049d:latest
```
However, removing the image by referencing as registry/repository:tag succeeds.

**Comment by malikkal** [comment] 2018-01-18 06:33
Tried on another VCH that was upgraded too and it works well. Looks like its inconsistent behavior. I am not sure how to reproduce. :-(

**Comment by anchal-agrawal** [comment] 2018-01-18 23:13
Looks like images that have been pulled pre-upgrade (1.2.1) cannot be deleted by image ID after upgrade (1.3.0). Images pulled after upgrading can be removed by name and ID. It would be very helpful If you could confirm this on your setup, @malikkal.

The attached log bundle is from a 1.2.1 VCH that was upgraded to 1.3.0. I pulled `busybox` and `redis:alpine` before upgrading, and `debian` and `nginx` after upgrading. I was able to `rmi` using the image IDs of `debian` and `nginx` but not `busybox` and `redis:alpine`. After upgrading, I deleted `busybox` by name and re-pulled it, and was then able to delete it by image ID. The log bundle has all these operations.

[7118-logs.zip](https://github.com/vmware/vic/files/1644779/7118-logs.zip)

**Comment by hickeng** [comment] 2018-01-18 23:37
@anchal-agrawal @malikkal I've confirmed that this error occurs with a restart, not just an upgrade. Deleting using the full ID works, just not the shortID.
```
$ docker rmi c3528103517d
Error response from daemon: No such image: c3528103517d:latest
$ docker rmi c3528103517df45826e18b195cc7688b5f101758225f02e986bd2aa43399ffd1
Deleted: a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
<snip>
Untagged: tomcat:alpine
Untagged: tomcat@sha256:55def4ece5aaf838bf626dc665274be80c749f8f31e920dc942596ea1efa97bb
```

**Comment by malikkal** [comment] 2018-01-19 09:16
> ERROR Handler for DELETE /v1.25/images/21a2450d623e returned error: No such image: 21a2450d623e:latest

Deleted all images using the full ID. However, there were two images that were adamant and refused to go even with full ID that returned the above error. I assume they were created using Docker commit; yet to confirm.

After co-relating no actual images existed in the image Datastore, I deleted the apiKV.dat, while the VCH was powered off. Subsequent docker images returned an empty image list and a later pull automatically created a new  apiKV.dat with updated image information.

**Comment by anchal-agrawal** [comment] 2018-01-19 20:11
> However, there were two images that were adamant and refused to go even with full ID that returned the above error. I assume they were created using Docker commit; yet to confirm.

@malikkal @hickeng I cannot repro this, at least with images that are created with `docker commit` - images created with `commit` before (or after) upgrade can be removed by their long ID after upgrade (and short ID before upgrade).

Having images pulled/committed before upgrade and then attempting to `rmi` them post-upgrade can be troublesome since the short ID doesn't work, and `docker inspect <image-shortID>` fails too. However, if there are containers created with those images, the containers can be inspected to find out their image ID.

**Comment by hickeng** [comment] 2018-01-19 20:17
@anchal-agrawal @malikkal noted that there were no images actually on the datastore - those images remaining could be tag entries where the association with the full ID was not correctly re-established. Speculation.

Suggest looking at why the shortID reference breaks after restart initially and coming back to @malikkal 's last issue afer you've got the root problem addressed.

**Comment by anchal-agrawal** [comment] 2018-01-19 22:22
The shortID issue after a VCH restart is because we don't populate the image cache's `iDIndex` field correctly. When we pull an image, it is added to `iDIndex` indexed by its full ID and to `cacheByID` indexed by `sha256:<fullID>`. However, when we rehydrate the image cache upon a restart of the persona, we populate `iDIndex` indexed by the keys of `cacheID` directly (that contain the `sha256:` prefix). Therefore, lookups in `iDIndex` for images pulled before a VCH restart fail after the restart.

The fix is to trim the `sha256:` prefix before adding to `iDIndex` here: https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/cache/image_cache.go#L108

**Comment by hickeng** [comment] 2018-01-22 13:01
Adding 1.3.1 label to match PR.

**Comment by anchal-agrawal** [comment] 2018-01-22 20:50
#7139 fixes the `rmi shortID` issue after VCH restart and is merged - closing this issue. We should open a new issue if we see the `rmi longID` issue you mentioned in https://github.com/vmware/vic/issues/7118#issuecomment-358909198, @malikkal.

**Closed by anchal-agrawal** 2018-01-22 20:50 UTC
Labels: component/docker-api-server, component/imagec, kind/bug, kind/customer-found, priority/high, status/needs-regression-test, team/container, triage/proposed-1.3.1
