### ISSUE TITLE
Clean up the vApp with vic-machine delete 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#5441] opened 2017-06-12 09:45 UTC
**User Statement:**

vic-machine-linux delete will delete all the containers and the VCH itself, but leaves around the vApp with the same name as VCH.  This should be cleaned up too

**Details:**
./vic-machine-linux delete -f -t administrator@vsphere.local:Admin!23@10.146.13.36/Datacenter -r Cluster/Resources --thumbprint B8:88:73:E7:07:44:C4:CD:CC:3D:B8:A2:0C:15:64:18:53:B9:D0:22 -n U-VIC-0001

deleted all the containers and the VCH but the vApp remained as shown in the screenshot.

In the subsequent create VCH fails with
Jun 12 2017 05:20:54.640-04:00 ERROR Found virtual app "/Datacenter/host/Cluster/Resources/U-VIC-0001", but it is not a VCH. Please choose a different virtual app.
Jun 12 2017 05:20:54.640-04:00 INFO  Collecting b32e55fa-beeb-45d9-bf9d-1be2c31da75a vpxd.log
Jun 12 2017 05:20:59.134-04:00 ERROR Found virtual app "/Datacenter/host/Cluster/Resources/U-VIC-0001", but it is not a VCH. Please choose a different virtual app.
Jun 12 2017 05:20:59.134-04:00 ERROR --------------------
Jun 12 2017 05:20:59.134-04:00 ERROR vic-machine-linux create failed: Found virtual app "/Datacenter/host/Cluster/Resources/U-VIC-0001", but it is not a VCH. Please choose a different virtual app.

**Acceptance Criteria:**
Either we should be able to re-purpose vApp if it is already existing or delete vApp with delete option. The later option is better. 

![vapp-remain](https://user-images.githubusercontent.com/25006749/27027717-245ab130-4f80-11e7-9c94-57600bbbca69.PNG)

Build: vic-v1.1.1-11340-4029cbe6.ova

**Comment by emlin** [comment] 2017-06-12 14:08
@lgayatri I usually run test in nimbus VC, and never see this happens. Could you please give me your vic-machine log? or let me try in your environment?

**Comment by lgayatri** [comment] 2017-06-12 14:23
@emlin, then it could be due to https://github.com/vmware/vic/issues/5156 which I hit each time I run vic-machine delete. The containers however get cleaned up but vAPP remains.

Do you also see #5156 on nimbus?

**Comment by emlin** [comment] 2017-06-12 14:25
No, if delete failed for whatever reason, this issue might happen, so the problem is still in #5156

**Comment by chengwang86** [comment] 2017-06-12 14:51
Set the estimate to 1 since it can be verified after #5156 is closed.

**Comment by mhagen-vmware** [comment] 2017-08-16 15:41
Taking this to verify with @lgayatri once #5784 is merged

**Comment by lgayatri** [comment] 2017-08-17 05:15
@mhagen-vmware DId not observe this issue in the recent builds. Can be closed as verified

**Comment by mhagen-vmware** [comment] 2017-08-17 13:47
Thanks @lgayatri

**Closed by mhagen-vmware** 2017-08-17 13:47 UTC
Labels: kind/bug, kind/customer-found, priority/high
