### ISSUE TITLE
Port layer attach

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#440] opened 2016-04-05 00:20 UTC
This is the initial call in the interaction portion of the port layer and exposes stdin/out/err for a provided session ID (session ID is the containerID from the docker personality).

**Comment by hickeng** [comment] 2016-04-10 19:29
#439 encompasses the portlayer client portion of the attach interaction, this issue is for the glue that makes use of that client.

**Comment by hickeng** [comment] 2016-04-21 17:23
Asked @fdawg4l to look into this - this covers the PL rest call through to the handling of incoming serial-over-LAN connections from the containerVMs. The basic ssh attach including client is merged, but the connection handling to deal with multiple concurrent container attaches is ommitted.

**Comment by fdawg4l** [comment] 2016-04-27 17:21
#576 addresses a portion of this.  It implements the server component which accepts the tcp connection from the container, and sshs back to the client.  _With tests!_

**Comment by hickeng** [comment] 2016-04-28 15:42
@fdawg4l should have got to the PR before it was merged - ah well. Minor comments:
connector.go:122 (Remove) - only close the underlying client connection if the argument ID matches connection.ID - this will come up when we start handling exec

containerID - should be "container-ids" and is actually an array of ids rather than a straight string.

**Comment by fdawg4l** [comment] 2016-04-28 20:47
@hickeng -  took care of the first comment.  RE: "container-ids" isn't implemented yet on the tether side.  Lets cross that bridge when we get to it.

**Comment by fdawg4l** [comment] 2016-05-02 15:42
Took care of @hickeng's comments in db7be35b7ae0498f3d06e7b3ef5efd34e1e7e779 as well as fixed broken functionality.  I didn't realize b'ville had diverged from the current tether work so my understanding of ssh session handling with respect to container ids and their processes was wrong.  This has been taken care of now and we should have parity.

**Comment by fdawg4l** [comment] 2016-05-02 15:48
The only thing left is to implement the port layer REST API handler for attaching to container sessions by their (unique) IDs and to start the session server somewhere.  A shim in between the session server and the REST API would be preferable in case we want to migrate a way from swagger at some point and not lose the API semantics, but this isn't necessary.

IIRC @sflxn volundrafted to add the swagger REST work with the session handler.  

@sflxn we simply need to call the server start (once) when then port layer starts, then call `connector.Get()` to retrieve the session for a given container ID.  The `Get()` will block until the process is running on the container side.  The result of the `Get()` is exported in the interface (I believe that includes things like STDIN, STDOUT, STDERR).  If you can the `Get()` to a REST handler and use the reader writer interfaces for the request and the response from the http handler, we should be golden.

**Comment by fdawg4l** [comment] 2016-05-04 20:30
I'm implementing the PL side REST API to attach.  I'll integrate with the docker work thereafter and close this issue once I have the PL REST working.

**Comment by fdawg4l** [comment] 2016-05-06 00:25
@hickeng and I have stumbled into serial -> IP connectivity issues from the tether to the PL.  What should have been a trivial copying of code/functionality from b'ville uncovered some bugs after the recent tether massaging to add tests and other things.  We're looking into it but progress is slow.

We so far have the tether handshaking with the PL, but the ssh connection fails because of a "short read" on the PL (ssh client) side.  We're working to figure out what is different between this code and b'ville.

**Comment by sflxn** [comment] 2016-05-06 17:06
Hey, @fdawg4l and I talked yesterday.  I went ahead and implemented the API portion of the port layer.  It's the same code pattern used in the docker personality server and I needed it to test out making an attach call to the port layer.  It's still a work in progress.

The handler for attach will not be a standard Swagger call.  We need to write some HTTP middleware to hijack the connection.  Once it's hijacked, we need a way to give the Swagger attach handler the streams.  Docker does this by passing a closure to the handler.  Swagger does not support this.  For the initial version of attach, we're going to bypass Swagger and handle attach completely through the middleware.  After talking to Ivan, there might be some changes in the latest version of Swagger that might give us alternatives, but the latest version will also require us to make a lot of changes to existing Swagger code so I'm chalking this up to +1 technical debt till after this milestone.

**Comment by fdawg4l** [comment] 2016-05-09 18:09
@hickeng and i spent the day on Friday pair debugging.  We believed the kernel, esx, our code, or golang 1.6 to have changed in some minute way thereby making the serial to ip connection unstable.  

The symptoms were that the ssh handshake would result in a `short read` on the client (PL) side.  This was indicative of lossiness on the connection.  I added a 256b random buffer to the tether/PL handshake code that would be passed from the PL to the tether and back.  The buf was then compared and if identical, we knew the channel was not lossy.  However, regardless of this check passing, ssh handshake would fail with the above short read error.  

We upgraded ESX from 6.0 beta to 6.0.1 GA, retried, same result.  We suspected the (so-called) photon kernel, so we moved the tether binary to the same development VM, same result.  We then implemented a boilerplate test which would initiate the serial handshake over the local serial port to the configured network listener ( by way of esx), and all of our tests passed.  We then removed the random 256b buffer and replaced it with a buf full of tty exit codes, and we were able to reproduce the issue.  It seems the kernel not honoring the raw serial syscall we're making.

We have 2 solutions-  first is to find an implementation of the raw mode syscall which is being honored (a.la in bonneville), or we hex/base64 encode all of our data over the channel so as to obfuscate the escaping.  I'm going to spend time today to narrow down where the raw handling code deviated between bonneville and vic.  The assumption is something in a dependency (golang?) changed sufficiently to bork this behavior.  If that fails, we'll try the heavyweight approach of encoding all of our data.

This has been a bit of a bear.

**Comment by fdawg4l** [comment] 2016-05-09 18:11
Progress can be tracked in this PR(#644) and my branch (https://github.com/fdawg4l/vic/tree/debugCity)

**Comment by fdawg4l** [comment] 2016-05-09 18:16
This is an illustration of simply writing a unit test that doesnt test the actual boundary isn't enough to provide confidence in the functionality.  Our unit test created pipes, had a network client which would RD/WR from it (like esx would) and use these connection pairs to test our code.  This clearly is an ideal scenario which didnt exhibit the wonky tty stuff we were seeing on actual esx/vm.

**Comment by fdawg4l** [comment] 2016-05-09 20:47
@hickeng moving the conversation back to here.

Using the `crypto/ssh` terminal handling code didn't actually fix anything.  Same behavior.

However!  While the test spun checking for "lossyness", I ran the following and we got past SSH short read.  

> before
```
fahmed@nestedubs:~/home/src/vic/src/github.com/vmware/vic/bin$ sudo stty -F /dev/ttyS0
speed 9600 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel
-isig -icanon -iexten -echo -echoe -echok
```

> after (with success)
```
fahmed@nestedubs:~/home/src/vic/src/github.com/vmware/vic/bin$ sudo stty -F /dev/ttyS0 raw
fahmed@nestedubs:~/home/src/vic/src/github.com/vmware/vic/bin$ sudo stty -F /dev/ttyS0
speed 9600 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel
-opost
-isig -icanon -iexten -echo -echoe -echok
```

**Comment by fdawg4l** [comment] 2016-05-09 21:04
Looks like every iteration ends with the serial set back to `-brkint -icrnl -imaxbel`.  Verified by running `stty` before and after the `go test` run.  Looks like this is the crux of our issue.  I'll test the syscall for `MakeRaw` itself and see if the impl is messed up.  Worst case, we explicitly set `-opost` via syscall in `backchannel` or the `rawconn`.

**Comment by fdawg4l** [comment] 2016-05-09 22:45
```
# strace of stty raw
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# cat /tmp/f | grep -i post
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_STOP or SNDRV_TIMER_IOCTL_GINFO or TCSETSW, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0

# strace of tether
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# cat /tmp/v | grep -i post
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# strace -o /tmp/f stty -F /dev/ttyS0
speed 9600 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel
```

**Comment by fdawg4l** [comment] 2016-05-09 22:45
Pretty sure that should be -opost.  Looks like something is wrong with the syscall.

**Comment by fdawg4l** [comment] 2016-05-09 22:52
```
# strace of stty -F /dev/ttyS0 raw
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# grep -i opost /tmp/sttyraw 
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_STOP or SNDRV_TIMER_IOCTL_GINFO or TCSETSW, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B9600 -opost -isig -icanon -echo ...}) = 0

# strace of tether (with unmodified rawconn)
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# grep -i opost /tmp/tether
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
root@55d03f7646f1:~/home/src/vic/src/github.com/vmware/vic/bin# 
```

Looks like the `opost` flag is wrong.

**Comment by hickeng** [comment] 2016-05-09 23:08
@fdawg4l well tracked down - I'm going to leave you to find an actual fix. I'm against using stty binary in the long term, but I'm okay with a MakeRaw that execs it in the short term so long as we have an associated issue to fix it properly.

**Comment by fdawg4l** [comment] 2016-05-09 23:33
@caglar10ur pointed out the following:  https://github.com/docker/docker/commit/67629c8b52f95218c2ef4ff781b6dfdcd8e88ba9

Removing line 30 from that file in our repo did the trick.  I was mistakenly looking at the `!cgo` implementation (which looks fine, btw).  It's the `cgo` impl that's poopie.  

I'll update our repo to that version and try an end to end test again, but the unit test we have which exercises esx is passing reliably.

**Comment by fdawg4l** [comment] 2016-05-09 23:42
Looks like that commit is part of docker 1.11.  I'll cherry pick the commit for now.  When we're ready for 1.11, we won't have to worry about this anymore.

**Comment by hickeng** [comment] 2016-05-09 23:53
I'll admit I'm not happy that docker broke it in the first place - this cost significant time to track down.
I have a little more trust in the crypt package impl if we can get it working

**Comment by fdawg4l** [comment] 2016-05-09 23:55
@hickeng the crypt package isnt setting Oflag at all.

**Comment by fdawg4l** [comment] 2016-05-09 23:56
Now that i say that...  it really should work...

**Comment by fdawg4l** [comment] 2016-05-10 00:09
Ah.  The crypto pkg has a bug.  They aren't clearing the Oflag bits.  So, if we do use this pkg, then we'd need to call stty before calling the tether binary.  The term pkg will simply carry over the oflag bits.

**Comment by hickeng** [comment] 2016-05-10 00:26
That's the same bug the current docker package has though - that doesn't clear it either if I recall... oh. but it's using the C...raw call.

**Comment by fdawg4l** [comment] 2016-05-10 00:31
Right-  the non cgo impl in docker clears it explicitly.  The cgo impl in docker doesn't set it.

**Comment by fdawg4l** [comment] 2016-05-10 00:47
Can confirm unsetting the bit in the crypto term pkg gives us the same (good) behavior.  Will issue a PR to golang.

**Comment by fdawg4l** [comment] 2016-05-10 03:26
Issued a change to golang.  Lets see if they accept it (https://go-review.googlesource.com/#/c/22964/2).  

I really *really* miss gerrit.  Such an awesome tool.  Sad the louder voices won that battle.

**Comment by fdawg4l** [comment] 2016-05-10 21:09
```
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic$ docker -H 192.168.8.162:2376 --tls --tlscert='./cert.pem' --tlskey='./key.pem' create  busybox /bin/top
debab08126291f21606d1cd7a3ae46281f7ac125d8908c5ae3df91f8c9c4086b
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic$ docker -H 192.168.8.162:2376 --tls --tlscert='./cert.pem' --tlskey='./key.pem' start debab08126291f21606d1cd7a3ae46281f7ac125d8908c5ae3df91f8c9c4086b
debab08126291f21606d1cd7a3ae46281f7ac125d8908c5ae3df91f8c9c4086b
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic$ 

```

```
DEBU[1275] discarding following 4 bytes from input channel
 
DEBU[1275] [21 6 213 32]
                               
DEBU[1275] Incoming channel is purged of content        
DEBU[1275] client: writing syn                          
DEBU[1275] client: reading synack                       
ERRO[1275] HandshakeClient: failed to read expected SYN-ACK: n=1, err=read tcp 192.168.8.162:2377->192.168.8.161:31851: i/o timeout buf=[0x15] 
DEBU[1275] purging incoming channel                     
DEBU[1275] Incoming channel is purged of content        
DEBU[1275] client: writing syn                          
DEBU[1275] client: reading synack                       
INFO[1275] HandshakeClient: received synack: 0x066e == 0x066e
 
DEBU[1275] client: writing ack                          
DEBU[1275] Checking for lossiness                       
INFO[1275] lossiness check PASSED                       
DEBU[1275] New connection                               
DEBU[1275] Initiating ssh handshake with new connection attempt 
INFO[1276] Established connection with container VM: debab08126291f21606d1cd7a3ae46281f7ac125d8908c5ae3df91f8c9c4086b 
```

Closing the issue.  Bam.

**Comment by fdawg4l** [comment] 2016-05-10 21:10
Premature closification.  Still waiting for the PR (#440) to merge.

**Comment by fdawg4l** [comment] 2016-05-10 22:33
fixed.

**Closed by fdawg4l** 2016-05-10 22:33 UTC
Labels: area/apis, component/portlayer/interaction
