### ISSUE TITLE
Grant Permissions Error

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7124] opened 2018-01-18 17:53 UTC
@emeirell commented on [Thu Jan 18 2018](https://github.com/vmware/vic-ui/issues/312)

**VIC version:**
VIC 1.3.0

**Deployment details:**

When creating a VCH through the Wizard, during the Operations User step, if select "grant permission" for a user which already has been given the permission previously, it fails with an error "Failed to create VCH: Cannot init ops-user permissions, failure: ServerFaultCode: The object or item referred to cloud not be found..Exiting.."

Even though the wizard does not you to proceed the VCH has been created in the background, but stay powered off.

it's tempting to select "grant permission" every time, just to make sure you dont forget anything, or to enforce privileges, or may be you just forget if you have the required privileges.

**Steps to reproduce:**
- Give a user read-only privilege on vCenter
- Create a VCH through the Wizard and select "grant permission" for the user
- This time the VCH is create successfully
- Create a second VCH through the Wizard and select "grant permission" for the same user as before.
- VCH creation fails.

**Expected behavior:**

The Wizard should check if the user has the required privileges and just apply the missing ones, if the operations user has all the required privileges it can proceed VCH creation without touching any privileges

---

@mdubya66 commented on [Thu Jan 18 2018](https://github.com/vmware/vic-ui/issues/312#issuecomment-358680845)

PM would like to see this in 1.3.1. We need to get it merged today and cherry picked for inclusion in RC1 on 1/19

@lcastellano can you also take a look at this.

---

@jak-atx commented on [Thu Jan 18 2018](https://github.com/vmware/vic-ui/issues/312#issuecomment-358716201)

This issue cannot be fixed on UI side but possibly on API side. 

cc @AngieCris @zjs 

---

@lcastellano commented on [Thu Jan 18 2018](https://github.com/vmware/vic-ui/issues/312#issuecomment-358720517)

This could be the same issue we have seen in Patrick's environment. In that scenario a local Active Directory had been added to the Identity Sources. If that is the case the problem appears to be in vSphere. We could mitigate the problem by skipping the check that is causing the failure in vic-machine (and the wizard). The check is in place to prevent the use of an Administrator as the ops-user. If the check is removed and the user selects Administrator as ops-user, vic-machine will restrict privileges for Administrator which may result in serious consequences for the whole VC instance.

**Comment by zjs** [comment] 2018-01-18 17:55
> If the check is removed and the user selects Administrator as ops-user, vic-machine will restrict privileges ...

Is there a way to make this operation additive-only? In that case, it seems like removing this check could be safe.

**Comment by lcastellano** [comment] 2018-01-18 20:45
I need to rectify my diagnosis, after Patrick pointed out the reproduction sequence I am not sure this is the same problem we were seeing on Patrick setup. I tried to reproduce it using vic-machine but so far it looks like it is working ok. I am going to install a 1.3.0 ova and try the wizard.

**Comment by lcastellano** [comment] 2018-01-19 18:00
It turns out this is the same problem seen in Patrick's setup. The API works only the very first time it is called. After that it fails no matter what the parameters are. This is only seen when an Active Directory is added as an identity source. I am going to explore the ability to bypass that check in case the API fails.

**Comment by mdubya66** [comment] 2018-01-19 19:30
is this a dupe of #7054

**Closed** 2018-01-22 21:40 UTC
Labels: area/apis, area/cli, component/vic-machine, kind/bug, priority/high, team/lifecycle
