### ISSUE TITLE
docker stop results in an RPC error returned from portlayer

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic#2021] opened 2016-08-17 14:39 UTC
**VIC Version:**

0.5.0

**Code**
```
(mwilliamson) dubs:~/Downloads/vic_0.5.0 $ docker -H 172.16.127.182:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
f2b5bcb68d3e        busybox             "/bin/top"          18 hours ago        Created                                 serene_mccarthy
(mwilliamson) dubs:~/Downloads/vic_0.5.0 $ docker -H 172.16.127.182:2376 --tls start f
f
(mwilliamson) dubs:~/Downloads/vic_0.5.0 $ docker -H 172.16.127.182:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
f2b5bcb68d3e        busybox             "/bin/top"          18 hours ago        Running                                 serene_mccarthy
(mwilliamson) dubs:~/Downloads/vic_0.5.0 $ docker -H 172.16.127.182:2376 --tls stop f
Error response from daemon: server error from portlayer : Operation failed: An RPC send operation failed. - (&{{} %!s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.transport.rpc.send.fail [] An RPC send operation failed.}]}}} An RPC send operation failed.}) An RPC send operation failed.})
(mwilliamson) dubs:~/Downloads/vic_0.5.0 $ docker -H 172.16.127.182:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
f2b5bcb68d3e        busybox             "/bin/top"          18 hours ago        Stopped                                 serene_mccarthy
```

**Expected behavior:**
The container to stop without error

**Actual behavior:**
Error response from daemon: server error from portlayer : Operation failed: An RPC send operation failed. - (&{{} %!s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.transport.rpc.send.fail [] An RPC send operation failed.}]}}} An RPC send operation failed.}) An RPC send operation failed.})

[container-logs.zip](https://github.com/vmware/vic/files/422810/container-logs.zip)

**Comment by mhagen-vmware** [comment] 2016-09-16 15:26
Saw this on the CI run:
https://ci.vmware.run/vmware/vic/4845

[integration_logs_4845_68929b28bc77259ee13d5c93b24b47875d24f268_1473983208.zip](https://github.com/vmware/vic/files/477155/integration_logs_4845_68929b28bc77259ee13d5c93b24b47875d24f268_1473983208.zip)

**Comment by jzt** [comment] 2016-09-16 19:10
Hmm, there are no references to the container involved in either the portlayer or persona logs. Additionally, the archive that's supposed to contain relevant info (VCH-4845-3336-container-logs.zip) is 0 bytes.

Not sure where to go from here for investigation/troubleshooting.

**Comment by jzt** [comment] 2016-09-16 19:11
Using @mdubya66 's logs.

**Comment by jzt** [comment] 2016-09-16 20:39
So digging through logs, I've got this feeling that the RPC error happened because the VM shutdown prematurely (not sure why, because it looks like an intentional and graceful shutdown). Perhaps there is a race condition somewhere that prevents the VigorTransportClient from disconnecting cleanly?  Here's what I've seen:

at 10:17.354, hostd gets request for state transition

hostd.log:
```
2016-08-16T20:10:17.354Z info hostd[33F81B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb0d user=root] State Transition (VM_STATE_ON -> VM_STATE_GUEST_OPERATION)
```
vmware.log:
```
2016-08-16T20:10:17.354Z| vmx| I120: VigorTransportProcessClientPayload: opID=d97ccb0d seq=651: Receiving GuestOps.StartProgram request.
```
from here VMX proceeds to power off smoothly:

vmware.log:
```
2016-08-16T20:10:17.416Z| vcpu-1| I120: VigorTransport_ServerSendResponse opID=d97ccb0d seq=651: Completed GuestOps request.
2016-08-16T20:10:17.462Z| vcpu-1| A115: ConfigDB: Setting guestinfo..sessions|f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.status = "-1"
2016-08-16T20:10:17.512Z| vcpu-1| I120: GuestRpc: Reinitializing Channel 0(toolbox)
2016-08-16T20:10:17.577Z| vcpu-0| I120: PIIX4: PM Soft Off.  Good-bye.
2016-08-16T20:10:17.577Z| vcpu-0| I120: Chipset: Issuing power-off request...
2016-08-16T20:10:17.577Z| vcpu-0| A115: ConfigDB: Setting softPowerOff = "TRUE"
2016-08-16T20:10:17.578Z| vmx| I120: Stopping VCPU threads...
…
```
at 10:17.421, a guest operation for Start Program is performed on the vm.

hostd.log:
```
6-08-16T20:10:17.421Z info hostd[34148B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 140 : Guest operation Start Program performed on Virtual machine serene_mccarthy-f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.
2016-08-16T20:10:17.443Z info hostd[34148B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] State Transition (VM_STATE_GUEST_OPERATION -> VM_STATE_ON)
2016-08-16T20:10:17.444Z info hostd[34044B70] [Originator@6876 sub=Guestsvc.GuestFileTransferImpl] Entered VmPowerStateListener
2016-08-16T20:10:17.444Z info hostd[34044B70] [Originator@6876 sub=Guestsvc.GuestFileTransferImpl] VmPowerStateListener succeeded
2016-08-16T20:10:17.444Z info hostd[34044B70] [Originator@6876 sub=Hbrsvc] Replicator: powerstate change VM: 243 Old: 1 New: 1
```
Send config update invoked:
```
2016-08-16T20:10:17.478Z info hostd[34148B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] Send config update invoked
```
As the VM is shutting down, it closes the connection to hostd and finishes poweroff:

vmware.log:
```
016-08-16T20:10:17.698Z| vmx| I120: VigorTransport_ServerCloseClient: Closing transport 322635A0 (err = 0)
2016-08-16T20:10:17.698Z| vmx| I120: VigorTransport_ServerDestroy: server destroyed.
2016-08-16T20:10:17.701Z| vmx| I120: VMX exit (0).
2016-08-16T20:10:17.701Z| vmx| I120: AIOMGR-S : stat o=5 r=15 w=0 i=0 br=245760 bw=0
2016-08-16T20:10:17.701Z| vmx| I120: OBJLIB-LIB: ObjLib cleanup done.
2016-08-16T20:10:17.701Z| vmx| W110: VMX has left the building: 0.
 ```

It looks like this is what caused the GenericVmConfigFault? (Note the timestamps)
The VigorTransportClient cleans up and closes the connection.

hostd.log:
```
2016-08-16T20:10:17.702Z info hostd[34148B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] Error encountered while retrieving configuration. Marking configuration as invalid: N3Vim5Fault20GenericVmConfigFault9ExceptionE(vim.fault.GenericVmConfigFault)
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] SOCKET 3 (37)
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] recv detected client closed connection
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] VigorTransportClientProcessError: Remote connection failure
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] VigorTransportClientDrainRecv: draining read.
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] SOCKET 3 (37)
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] recv detected client closed connection
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] VigorTransportClientProcessError: closing connection.
2016-08-16T20:10:17.703Z info hostd[32281B70] [Originator@6876 sub=Libs] VigorTransportClientManageConnection: connection closed.
```

It then tries to reconnect to the VM, but can't since it's shut down:

hostd.log:
```
2016-08-16T20:10:17.709Z info hostd[33940B70] [Originator@6876 sub=Vimsvc.TaskManager opID=d97ccb14 user=root] Task Created : haTask-243-vim.VirtualMachine.reconfigure-478
2016-08-16T20:10:17.710Z info hostd[33940B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] State Transition (VM_STATE_ON -> VM_STATE_RECONFIGURING)
2016-08-16T20:10:17.736Z info hostd[32281B70] [Originator@6876 sub=Libs] CnxAuthdProtoSecureConnect: Unencrypted connection, skipping thumbprint exchange.
2016-08-16T20:10:17.739Z info hostd[32281B70] [Originator@6876 sub=Libs] CnxConnectAuthd: Returning false because CnxAuthdProtoConnect failed
2016-08-16T20:10:17.739Z info hostd[32281B70] [Originator@6876 sub=Libs] Cnx_Connect: Returning false because CnxConnectAuthd failed
2016-08-16T20:10:17.739Z info hostd[32281B70] [Originator@6876 sub=vm:Cnx_Connect: Error message: There is no VMware process running for config file /vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx]
2016-08-16T20:10:17.739Z warning hostd[32281B70] [Originator@6876 sub=vm:VigorTransportClientManageConnection: Failed to re-connect to VM /vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx]
2016-08-16T20:10:17.739Z error hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Could not fetch Vigor vmx state: N3Vim5Fault20GenericVmConfigFault9ExceptionE(vim.fault.GenericVmConfigFault)
2016-08-16T20:10:17.739Z warning hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Unstable power state, assuming off
2016-08-16T20:10:17.740Z info hostd[34044B70] [Originator@6876 sub=Libs opID=d97ccb14 user=root] VigorOnlineRPCNewConfigParamsSetVolatileEntry RPC Send Failed
2016-08-16T20:10:17.741Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Reconfigure failed: vim.fault.GenericVmConfigFault
```

At this point it dumps the `ConfigSpec`, and follows up by marking the VM as invalid:

```
[ ConfigSpec snipped ]

2016-08-16T20:10:17.743Z error hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Could not fetch Vigor vmx state: N3Vim5Fault20GenericVmConfigFault9ExceptionE(vim.fault.GenericVmConfigFault)
2016-08-16T20:10:17.743Z warning hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Unstable power state, assuming off
2016-08-16T20:10:17.743Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] State Transition (VM_STATE_RECONFIGURING -> VM_STATE_OFF)
2016-08-16T20:10:17.743Z info hostd[32281B70] [Originator@6876 sub=Libs] VigorOnlineDisconnectCb: connection closed (is final).
2016-08-16T20:10:17.743Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Marking VirtualMachine invalid
2016-08-16T20:10:17.743Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] State Transition (VM_STATE_OFF -> VM_STATE_INVALID_CONFIG)
```

I'm a little shady on what happens next, but it looks like another attempt is made to power off the VM. It catches the `InvalidState` fault, turns off the heartbeat checker and that's the last we see of this VM.

hostd.log:
```
2016-08-16T20:10:17.743Z info hostd[34003B70] [Originator@6876 sub=Guestsvc.GuestFileTransferImpl] Entered VmPowerStateListener
2016-08-16T20:10:17.743Z info hostd[34003B70] [Originator@6876 sub=Guestsvc.GuestFileTransferImpl] VmPowerStateListener succeeded
2016-08-16T20:10:17.743Z info hostd[34003B70] [Originator@6876 sub=Hbrsvc] Replicator: powerstate change VM: 243 Old: 1 New: 0
2016-08-16T20:10:17.743Z info hostd[34003B70] [Originator@6876 sub=Hbrsvc] Replicator: Poweroff for VM: (id=243)
2016-08-16T20:10:17.744Z info hostd[34044B70] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=d97ccb14 user=root] Event 141 : Reconfigured serene_mccarthy-f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c on localhost.localdomain in ha-datacenter
2016-08-16T20:10:17.744Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Send config update invoked
2016-08-16T20:10:17.771Z info hostd[34044B70] [Originator@6876 sub=Vimsvc.TaskManager opID=d97ccb14 user=root] Task Completed : haTask-243-vim.VirtualMachine.reconfigure-478 Status error
2016-08-16T20:10:17.771Z warning hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx opID=d97ccb14 user=root] Reconfigure worker thread failed
2016-08-16T20:10:17.779Z error hostd[34148B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] Invalid transition requested (VM_STATE_INVALID_CONFIG -> VM_STATE_OFF): Invalid state
2016-08-16T20:10:17.779Z warning hostd[34148B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] Caught exception vim.fault.InvalidState while on power state change.
2016-08-16T20:10:26.170Z info hostd[34044B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/5764a09c-f236fdca-c4d3-000c2934f28b/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c/f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c.vmx] Turning off heartbeat checker
```

@hickeng does this interpretation seem accurate? If so, would you have any idea what triggered the VM shutdown (assuming it was abnormal or out of band somehow)?

**Comment by dougm** [comment] 2016-09-19 23:57
You can see the stop (kill -TERM) received in the container tether log (f2b5bcb68d3e...debug), as expected:

```
"sending signal TERM (15) to f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c"
```

And the tether shutting down, also as expected.

Seems like things went as expected according to the port-layer.log too:
```
time="2016-08-16T20:10:16Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop] Container.stop" 
time="2016-08-16T20:10:16Z" level=info msg="sending kill -TERM f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c" 
time="2016-08-16T20:10:17Z" level=info msg="waiting 10s for f2b5bcb68d3e4f706bbc2a6d7b56741d5289683e35d14f6dc0f0fbbbbfc7da3c to power off" 
time="2016-08-16T20:10:17Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop] [358.889204ms] Container.stop" 
```

If Container.shutdown had failed, Container.stop would have logged this message:
https://github.com/vmware/vic/blob/529c07e817941da151f93eec3873b87d15552754/lib/portlayer/exec/container.go#L333

So I can't see where this message is coming from on the port layer side.  Is anyone able to reproduce this with 0.6.0/master?

I believe it was possible to get this message pre-0.5.0, in this call:
https://github.com/vmware/vic/blob/529c07e817941da151f93eec3873b87d15552754/lib/portlayer/exec/container.go#L293

But commit a39f7d9 should have fixed that.  And if it didn't, we should see the Container.stop Warnf mentioned above.

**Comment by hickeng** [comment] 2016-10-12 18:36
@emlin This issue is also presenting the InvalidStatus problem that's happening in the upgrade tests. We added a check in the containerVM deletion path for this state in order to fall back to vsphere Unregister followed by datastore delete.

To repair InvalidState without deleting you have to Unregister and Reregister the VM.

**Comment by jzt** [comment] 2016-10-24 16:29
Closing as not reproducible.

**Closed by jzt** 2016-10-24 16:29 UTC
Labels: component/portlayer, kind/bug, kind/bug/no-repro, kind/bug/p0
