### ISSUE TITLE
vic-machine: validate resource exists with user specified dvSwitch, cluster, and datastores

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1014] opened 2016-06-08 20:47 UTC
First target is to validate dvSwitch, VC cluster and image datastore.
Next target is to validate dvSwitch, VC cluster and all datastores specified, including image datastore, volume datastore and container datastore.

**Comment by andrewtchin** [comment] 2016-08-03 14:32
duplicate of #1166

**Closed by andrewtchin** 2016-08-03 14:32 UTC
Labels: component/vic-machine
