### ISSUE TITLE
Nightly 5-5: Failed to create container

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5917] opened 2017-08-04 01:34 UTC
8/2, Build build 12824, vSphere 6.5
[5-5-Heterogeneous-ESXi.zip](https://github.com/vmware/vic/files/1199007/5-5-Heterogeneous-ESXi.zip)

First container create failed.  Operation, 'docker -H 10.162.46.238:2376 --tls create busybox /bin/top 2>&1'.  Error:

```
Error response from daemon: Server error from portlayer: Cannot complete file creation operation.
```

Portlayer log at point of failure:

```
Aug  3 2017 02:34:21.644Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:216] handle(ad920bb22c22ed9211dc5d45f2ef1d94)
Aug  3 2017 02:34:21.644Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:36] 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56
Aug  3 2017 02:34:21.644Z DEBUG op=287.17 (delta:4.037µs): [NewOperation] op=287.17 (delta:1.978µs) [github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult:65]
Aug  3 2017 02:34:22.160Z ERROR op=287.17 (delta:515.950632ms): unexpected fault on task retry : &types.CannotCreateFile{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:"/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"}}
Aug  3 2017 02:34:22.160Z ERROR An error occurred while waiting for a creation operation to complete. Spec was {DynamicData:{} ChangeVersion: Name:hardcore_sammet-82910d905fee Version: Uuid:4cccab93-a026-55f7-8ecf-48ee978ebfb3 InstanceUuid: NpivNodeWorldWideName:[] NpivPortWorldWideName:[] NpivWorldWideNameType: NpivDesiredNodeWwns:0 NpivDesiredPortWwns:0 NpivTemporaryDisabled:<nil> NpivOnNonRdmDisks:<nil> NpivWorldWideNameOp: LocationId: GuestId:otherGuest64 AlternateGuestName:Photon - Container v1.1.0-rc3, 12824, a85701d Annotation: Files:0xc4206c3e50 Tools:<nil> Flags:<nil> ConsolePreferences:<nil> PowerOpInfo:<nil> NumCPUs:2 NumCoresPerSocket:0 MemoryMB:2048 MemoryHotAddEnabled:0xc420087710 CpuHotAddEnabled:0xc420087710 CpuHotRemoveEnabled:<nil> VirtualICH7MPresent:<nil> VirtualSMCPresent:<nil> DeviceChange:[0xc4207362d0 0xc420736b40 0xc420736eb0 0xc420737310 0xc42069a870 0xc42069ac30 0xc42069b3b0 0xc42069b4a0] CpuAllocation:<nil> MemoryAllocation:<nil> LatencySensitivity:<nil> CpuAffinity:<nil> MemoryAffinity:<nil> NetworkShaper:<nil> CpuFeatureMask:[] ExtraConfig:[0xc4208bb480 0xc4208bb4a0 0xc4208bb4c0 0xc4208bb4e0 0xc4208bb500 0xc4208bb520 0xc4208bb540 0xc4208bb560 0xc4208bb580 0xc4208bb5a0 0xc420996040 0xc420996060 0xc420996080 0xc4209960c0 0xc420996100 0xc420996120 0xc420996140 0xc420996180 0xc4209961a0 0xc4209961c0 0xc420996200 0xc420996220 0xc420996240 0xc420996260 0xc4209962a0 0xc4209962c0 0xc4209962e0 0xc420996300 0xc4209764e0 0xc420976520 0xc420976540 0xc420976560 0xc4209765a0 0xc4209765c0 0xc4209765e0 0xc420976600 0xc420976640 0xc420976660 0xc420976680 0xc4209766a0 0xc4209766c0 0xc420976700 0xc420976720 0xc420976740 0xc420976760 0xc420976780 0xc4209767a0 0xc4209767c0 0xc4209767e0 0xc420976800 0xc420976820 0xc420976840 0xc420976860 0xc420976880 0xc4209768a0 0xc4209768c0 0xc4209768e0 0xc420976900 0xc420976940 0xc420976960 0xc420976980 0xc4209769a0 0xc4209769c0 0xc420976a00 0xc420976a20 0xc420976a60 0xc420976a80 0xc420976aa0 0xc420976ae0 0xc420976b00 0xc420976b40 0xc420976b60 0xc420976b80 0xc420976ba0 0xc420976be0 0xc420976c00 0xc420976c20 0xc420976c40 0xc420976c60 0xc420976c80 0xc420976cc0 0xc420976ce0 0xc420976d00 0xc420976d20 0xc420976d60 0xc420976da0 0xc420976f40 0xc420977080 0xc420977100] SwapPlacement: BootOptions:<nil> VAppConfig:<nil> FtInfo:<nil> RepConfig:<nil> VAppConfigRemoved:<nil> VAssertsEnabled:<nil> ChangeTrackingEnabled:<nil> Firmware: MaxMksConnections:0 GuestAutoLockEnabled:<nil> ManagedBy:<nil> MemoryReservationLockedToMax:<nil> NestedHVEnabled:<nil> VPMCEnabled:<nil> ScheduledHardwareUpgradeInfo:<nil> VmProfile:[] MessageBusTunnelEnabled:<nil> Crypto:<nil> MigrateEncryption:}
Aug  3 2017 02:34:22.160Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:36] [516.304271ms] 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56
Aug  3 2017 02:34:22.160Z ERROR CommitHandler error on handle(ad920bb22c22ed9211dc5d45f2ef1d94) for 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56: task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc420966480)}
Aug  3 2017 02:34:22.160Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:216] [516.77029ms] handle(ad920bb22c22ed9211dc5d45f2ef1d94)
Aug  3 2017 02:34:22.181Z DEBUG vSphere Event Task: Create virtual machine for eventID(584) ignored by the event collector
Aug  3 2017 02:34:22.363Z DEBUG vSphere Event Creating hardcore_sammet-82910d905fee on host 10.162.35.255 in ha-datacenter for eventID(585) ignored by the event collector
Aug  3 2017 02:34:22.363Z DEBUG vSphere Event Assign a new instance UUID (500114bb-a832-7414-5a61-fc9a88c15a08) to hardcore_sammet-82910d905fee for eventID(586) ignored by the event collector
Aug  3 2017 02:34:22.363Z DEBUG vSphere Event New MAC address (00:50:56:81:e0:29) assigned to adapter 50 01 0b 68 14 0e f6 24-db fc 52 b6 27 3d ae ae for hardcore_sammet-82910d905fee for eventID(587) ignored by the event collector
Aug  3 2017 02:34:22.364Z DEBUG Found 2 subscribers to id: 588 - vsphere.VMEvent: Removed hardcore_sammet-82910d905fee on 10.162.35.255 from ha-datacenter
Aug  3 2017 02:34:22.364Z DEBUG Event manager calling back to exec
Aug  3 2017 02:34:22.364Z DEBUG Event manager calling back to logging
Aug  3 2017 02:34:22.364Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52]
Aug  3 2017 02:34:22.364Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52] [6.34µs] 
```

Error from vpxd.log:
```
2017-08-03T02:34:22.757Z info vpxd[7F03B951C700] [Originator@6876 sub=Default opID=2efb7a93] [VpxLRO] -- ERROR task-121 -- resgroup-v31 -- vim.ResourcePool.createVm: vim.fault.CannotCreateFile:
--> Result:
--> (vim.fault.CannotCreateFile) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>, 
-->    file = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"
-->    msg = "Received SOAP response fault from [<cs p:0000557f99a59400, TCP:10.162.35.255:443>]: createEntry
--> Received SOAP response fault from [<cs p:064cbc10, TCP:localhost:8307>]: createEntry
--> Cannot complete file creation operation."
```

**Comment by mdubya66** [comment] 2017-08-10 15:49
may be test infrastructure issue but needs further eval before closing or working around

**Comment by sflxn** [comment] 2017-08-10 23:41
Same occurred 8/9, build 13080, vSphere 6.5

[Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-1809-container-logs.zip](https://github.com/vmware/vic/files/1216621/Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-1809-container-logs.zip)

**Comment by sflxn** [comment] 2017-08-14 17:46
Occurred 8/10, build 13104, vSphere 6.5

[Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-7564-container-logs.zip](https://github.com/vmware/vic/files/1222981/Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-7564-container-logs.zip)

**Comment by sflxn** [comment] 2017-08-14 19:51
8/12, build 13153, vSphere 6.5
[Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-1528-container-logs.zip](https://github.com/vmware/vic/files/1223277/Manual-Test-Cases.Group5-Functional-Tests.5-5-Heterogeneous-ESXi-VCH-0-1528-container-logs.zip)

**Comment by mhagen-vmware** [comment] 2017-08-15 17:00
Manual run:
[5-5-Heterogeneous-ESXi-VCH-0-1955-container-logs.zip](https://github.com/vmware/vic/files/1225764/5-5-Heterogeneous-ESXi-VCH-0-1955-container-logs.zip)

**Comment by chengwang86** [comment] 2017-08-17 19:14
PL log
```
Aug  3 2017 02:34:21.644Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:36] 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56
Aug  3 2017 02:34:21.644Z DEBUG op=287.17 (delta:4.037µs): [NewOperation] op=287.17 (delta:1.978µs) [github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult:65]
Aug  3 2017 02:34:22.160Z ERROR op=287.17 (delta:515.950632ms): unexpected fault on task retry : &types.CannotCreateFile{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:"/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"}}
Aug  3 2017 02:34:22.160Z ERROR An error occurred while waiting for a creation operation to complete. Spec was {DynamicData:{} ChangeVersion: Name:hardcore_sammet-82910d905fee Version: Uuid:4cccab93-a026-55f7-8ecf-48ee978ebfb3 InstanceUuid: NpivNodeWorldWideName:[] NpivPortWorldWideName:[] NpivWorldWideNameType: NpivDesiredNodeWwns:0 NpivDesiredPortWwns:0 NpivTemporaryDisabled:<nil> NpivOnNonRdmDisks:<nil> NpivWorldWideNameOp: LocationId: GuestId:otherGuest64 AlternateGuestName:Photon - Container v1.1.0-rc3, 12824, a85701d Annotation: Files:0xc4206c3e50 Tools:<nil> Flags:<nil> ConsolePreferences:<nil> PowerOpInfo:<nil> NumCPUs:2 NumCoresPerSocket:0 MemoryMB:2048 MemoryHotAddEnabled:0xc420087710 CpuHotAddEnabled:0xc420087710 CpuHotRemoveEnabled:<nil> VirtualICH7MPresent:<nil> VirtualSMCPresent:<nil> DeviceChange:[0xc4207362d0 0xc420736b40 0xc420736eb0 0xc420737310 0xc42069a870 0xc42069ac30 0xc42069b3b0 0xc42069b4a0] CpuAllocation:<nil> MemoryAllocation:<nil> LatencySensitivity:<nil> CpuAffinity:<nil> MemoryAffinity:<nil> NetworkShaper:<nil> CpuFeatureMask:[] ExtraConfig:[0xc4208bb480 0xc4208bb4a0 0xc4208bb4c0 0xc4208bb4e0 0xc4208bb500 0xc4208bb520 0xc4208bb540 0xc4208bb560 0xc4208bb580 0xc4208bb5a0 0xc420996040 0xc420996060 0xc420996080 0xc4209960c0 0xc420996100 0xc420996120 0xc420996140 0xc420996180 0xc4209961a0 0xc4209961c0 0xc420996200 0xc420996220 0xc420996240 0xc420996260 0xc4209962a0 0xc4209962c0 0xc4209962e0 0xc420996300 0xc4209764e0 0xc420976520 0xc420976540 0xc420976560 0xc4209765a0 0xc4209765c0 0xc4209765e0 0xc420976600 0xc420976640 0xc420976660 0xc420976680 0xc4209766a0 0xc4209766c0 0xc420976700 0xc420976720 0xc420976740 0xc420976760 0xc420976780 0xc4209767a0 0xc4209767c0 0xc4209767e0 0xc420976800 0xc420976820 0xc420976840 0xc420976860 0xc420976880 0xc4209768a0 0xc4209768c0 0xc4209768e0 0xc420976900 0xc420976940 0xc420976960 0xc420976980 0xc4209769a0 0xc4209769c0 0xc420976a00 0xc420976a20 0xc420976a60 0xc420976a80 0xc420976aa0 0xc420976ae0 0xc420976b00 0xc420976b40 0xc420976b60 0xc420976b80 0xc420976ba0 0xc420976be0 0xc420976c00 0xc420976c20 0xc420976c40 0xc420976c60 0xc420976c80 0xc420976cc0 0xc420976ce0 0xc420976d00 0xc420976d20 0xc420976d60 0xc420976da0 0xc420976f40 0xc420977080 0xc420977100] SwapPlacement: BootOptions:<nil> VAppConfig:<nil> FtInfo:<nil> RepConfig:<nil> VAppConfigRemoved:<nil> VAssertsEnabled:<nil> ChangeTrackingEnabled:<nil> Firmware: MaxMksConnections:0 GuestAutoLockEnabled:<nil> ManagedBy:<nil> MemoryReservationLockedToMax:<nil> NestedHVEnabled:<nil> VPMCEnabled:<nil> ScheduledHardwareUpgradeInfo:<nil> VmProfile:[] MessageBusTunnelEnabled:<nil> Crypto:<nil> MigrateEncryption:}
Aug  3 2017 02:34:22.160Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:36] [516.304271ms] 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56
Aug  3 2017 02:34:22.160Z ERROR CommitHandler error on handle(ad920bb22c22ed9211dc5d45f2ef1d94) for 82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56: task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc420966480)}
```

**Comment by chengwang86** [comment] 2017-08-18 15:54
Related error msg from hostd.log
```
2017-08-03T02:34:22.817Z warning hostd[C5C5B70] [Originator@6876 sub=Libs opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Hostlog_Flush: Failed to open hostlog /vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog for wrditing: No such file or directory
2017-08-03T02:34:22.817Z warning hostd[C5C5B70] [Originator@6876 sub=Vcsvc.OCM opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] PersistToDisk: failed to persist entry /vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog to disk, operation state may not be correctly reflected.
2017-08-03T02:34:22.817Z info hostd[C5C5B70] [Originator@6876 sub=Default opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] AdapterServer caught exception: vim.fault.CannotCreateFile
2017-08-03T02:34:22.817Z info hostd[C5C5B70] [Originator@6876 sub=Vimsvc.TaskManager opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Task Completed : haTask--vim.host.OperationCleanupManager.createEntry-180271596 Status error
2017-08-03T02:34:22.817Z verbose hostd[C5C5B70] [Originator@6876 sub=PropertyProvider opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] RecordOp ASSIGN: info, haTask--vim.host.OperationCleanupManager.createEntry-180271596. Applied change to temp map.
2017-08-03T02:34:22.817Z info hostd[C5C5B70] [Originator@6876 sub=Solo.Vmomi opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Activation [N5Vmomi10ActivationE:0x11b28270] : Invoke done [createEntry] on [vim.host.OperationCleanupManager:ha-op-cleanup-mgr]
2017-08-03T02:34:22.817Z verbose hostd[C5C5B70] [Originator@6876 sub=Solo.Vmomi opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Arg entry:
--> (vim.host.OperationCleanupManager.OperationEntry) {
-->    hlogFile = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog",
-->    opId = 5687669327487397919,
-->    opState = "running",
-->    opActivity = "create",
-->    curHostUuid = "42233321-5be8-e39e-9151-dda7ca9cef20",
-->    itemList = (vim.host.OperationCleanupManager.CleanupItemEntry) [
-->       (vim.host.OperationCleanupManager.CleanupItemEntry) {
-->          path = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/",
-->          type = "dir",
-->          removeUpon = "failure"
-->       },
-->       (vim.host.OperationCleanupManager.CleanupItemEntry) {
-->          path = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56.vmx",
-->          type = "vm",
-->          removeUpon = "failure"
-->       }
-->    ]
--> }
2017-08-03T02:34:22.817Z info hostd[C5C5B70] [Originator@6876 sub=Solo.Vmomi opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Throw vim.fault.CannotCreateFile
2017-08-03T02:34:22.817Z info hostd[C5C5B70] [Originator@6876 sub=Solo.Vmomi opID=2efb7a93-01-75-caa9 user=vpxuser:vpxuser] Result:
--> (vim.fault.CannotCreateFile) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>,
-->    file = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"
-->    msg = ""
--> }
```
From vpxd_vpxd.log
```
2017-08-03T02:34:22.695Z warning vpxd[7F03B951C700] [Originator@6876 sub=pbm opID=2efb7a93-01] PBMCallback: ShouldSkipPostCreateCallback: post create callback is skipped - VM creation failed
2017-08-03T02:34:22.695Z info vpxd[7F03B951C700] [Originator@6876 sub=VmProv opID=2efb7a93-01] Invoking callback type 2 on ResManager
2017-08-03T02:34:22.695Z info vpxd[7F03B951C700] [Originator@6876 sub=VmProv opID=2efb7a93-01] Invoking callback type 2 on SDRS
2017-08-03T02:34:22.695Z info vpxd[7F03B951C700] [Originator@6876 sub=VmProv opID=2efb7a93-01] Invoking callback type 2 on VApp
2017-08-03T02:34:22.700Z error vpxd[7F03B951C700] [Originator@6876 sub=VmProv opID=2efb7a93-01] Get exception while executing action vpx.vmprov.InvokeCallbacks: N3Vim5Fault16CannotCreateFile9ExceptionE(vim.fault.CannotCreateFile)
-->  ... ...
2017-08-03T02:34:22.750Z error vpxd[7F03B951C700] [Originator@6876 sub=vpxLro opID=2efb7a93-01] [VpxLRO] Unexpected Exception: N3Vim5Fault16CannotCreateFile9ExceptionE(vim.fault.CannotCreateFile)
--> [context]zKq7AVECAAAAANs6RgAsdnB4ZAAAkJ4rbGlidm1hY29yZS5zbwAAhE8bAOqXGIFq2gABbGlidmltLXR5cGVzLnNvAIElmhgBgV/9GAGBAgcZAQJAIBFsaWJ2bW9taS5zbwACGyIRA9lZYnZweGQAA314YgN1GmIDh1NiAqRYEgJRURKBuXYyAQM8SNADX3XQA0560AP0qcwDC7TMAz/czgOnfdADurbNA3DZzQO93s0DM49zA6iEcwM3qHMDim9zA1VfyQNeYMkDJ/legcUHBQED5JZ0AzOPcwOohHMDN6hzA2j7cwBv7SMAVvAjAHv2KwRUdABsaWJwdGhyZWFkLnNvLjAABS2ODmxpYmMuc28uNgA=[/context]
2017-08-03T02:34:22.757Z info vpxd[7F03B951C700] [Originator@6876 sub=vpxLro opID=2efb7a93-01] [VpxLRO] -- FINISH lro-1700
2017-08-03T02:34:22.757Z info vpxd[7F03B951C700] [Originator@6876 sub=Default opID=2efb7a93-01] [VpxLRO] -- ERROR lro-1700 --  -- VmprovWorkflow: vim.fault.CannotCreateFile:
--> Result:
--> (vim.fault.CannotCreateFile) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>, 
-->    file = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"
-->    msg = "Received SOAP response fault from [<cs p:0000557f99a59400, TCP:10.162.35.255:443>]: createEntry
--> Received SOAP response fault from [<cs p:064cbc10, TCP:localhost:8307>]: createEntry
--> Cannot complete file creation operation."
--> }
--> Args:
--> 
2017-08-03T02:34:22.757Z info vpxd[7F03B951C700] [Originator@6876 sub=vpxLro opID=2efb7a93] [VpxLRO] -- FINISH task-121
2017-08-03T02:34:22.757Z info vpxd[7F03B951C700] [Originator@6876 sub=Default opID=2efb7a93] [VpxLRO] -- ERROR task-121 -- resgroup-v31 -- vim.ResourcePool.createVm: vim.fault.CannotCreateFile:
--> Result:
--> (vim.fault.CannotCreateFile) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>, 
-->    file = "/vmfs/volumes/f333bddc-9eaefc1b/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56/82910d905feee345fb306b0d17fee05786ba94b97b39791791e6becc5ef04d56-5ede4a24.hlog"
-->    msg = "Received SOAP response fault from [<cs p:0000557f99a59400, TCP:10.162.35.255:443>]: createEntry
--> Received SOAP response fault from [<cs p:064cbc10, TCP:localhost:8307>]: createEntry
--> Cannot complete file creation operation."
```

**Comment by chengwang86** [comment] 2017-08-18 16:57
This failure is reproducible.

**Comment by chengwang86** [comment] 2017-08-18 16:57
This failure is reproducible.

**Comment by dougm** [comment] 2017-08-18 17:21
@chengwang86 can you reproduce without NFS?  Or when ensuring NFS in the same nimbus pod?

See: https://github.com/vmware/vic/issues/4666#issuecomment-302449065

"One suspect: nimbus-nfsdeploy doesn't specify the nimbus POD to use. The cluster and NFS server in different nimbus PODs could be the cause of these intermittent datastore issues. We should either specify the POD or use a testbed (such as iscsi) that lands everything on the same POD."

Looks like this test has the same issue via use of `Deploy Nimbus NFS Datastore`.

I wouldn't waste another second on this issue before fixing the test to use iscsi instead of NFS or at least ensure the nfs server is on the same nimbus POD.

**Comment by chengwang86** [comment] 2017-08-21 17:10
I have tried deploying a nimbus-iscsitestbed and add hosts of different esx versions to the vc cluster. However, the iscsi datastore does not automatically expand to the newly added hosts, and govc couldn't achieve it either.

Next, I will try to deploy everything (vcva, esxi hosts and nfs server) on the same Nimbus POD.

**Comment by chengwang86** [comment] 2017-08-21 19:59
@mhagen-vmware @dougm @mdubya66 

I have deployed everything on the same nimbus POD and I don't see the `Cannot complete file creation operation` in `docker create`. I can make a PR and update this test slightly following this strategy. 

However, there are two issues:

- Since we deploy one vcva, three ESXi hosts and one NFS server on the same POD, it is possible that we might see `nimbus out-of-resource` in this nightly test in the future. But so far I haven't see it in my test.
- After creating a container, starting &stopping it, then running `docker ps -a`, the container's status is shown as `stopped` but we expect `exited`. The log msgs are the same with those reported in #5803 

So even if my fix for this issue is merged, this particular test will still fail due to #5803

**Comment by chengwang86** [comment] 2017-08-23 03:42
@dougm I deployed a vc cluster and the nfs server on the same nimbus POD using my script in PR #6078 . However, I still observed the same error in one out of two test runs.

There might be certain reason other than the nimbus pod which resulted in this failure.

**Comment by chengwang86** [comment] 2017-08-23 14:29
I will (1) create a bugzilla ticket (2) try vmfs datastore and (3) check out the PRs merged before 8/2 (this first time this failure occurred).

**Comment by chengwang86** [comment] 2017-08-23 15:43
@mhagen-vmware Seems like we start to have this failure since PR https://github.com/vmware/vic/pull/5898 where the nfs datastore is introduced. This PR was merged on Aug 2nd, which is the date when the reported failure occurred for the first time. 

Do you think if we should revert it?

**Comment by chengwang86** [comment] 2017-08-23 16:42
Discussed with @mhagen-vmware just now. The goal of PR #5898 is (1) to eliminate the warning in vic-machine as we want all hosts to have access to a shared datastore and (2) we need a shared storage otherwise we get containers that are placed on hosts that cannot access the volume store.

To achieve this goal, we could use vsan, nfs, iscsi or fc datastore. Mikkel is working on writing an iscsi testbed to replace this one.

As a side note, this failure never occurs on vsphere 6.0 wherein the ESXi host with version `4240417` is not added to the cluster. So probably ESXi version `4240417` does not support nfs datastore well.

**Closed** 2017-08-23 19:19 UTC
Labels: component/portlayer, kind/bug, priority/high, status/needs-attention
