### ISSUE TITLE
Containers not stopping after command completes

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#999] opened 2016-06-07 23:02 UTC
@mhagen-vmware Please can you recreate the containers not stopping after command completion - I've been unable to do so locally.

Please add the container *.debug log to the issue, and grab the stack traces from the container (example url):
```
172.16.0.2:6060/debug/pprof/goroutine?debug=2
```

**Comment by caglar10ur** [comment] 2016-06-08 16:52
```
goroutine 328 [running]:
runtime/pprof.writeGoroutineStacks(0x7f5a9e404068, 0xc8200585b0, 0x0, 0x0)
	/usr/local/go/src/runtime/pprof/pprof.go:516 +0x84
runtime/pprof.writeGoroutine(0x7f5a9e404068, 0xc8200585b0, 0x2, 0x0, 0x0)
	/usr/local/go/src/runtime/pprof/pprof.go:505 +0x46
runtime/pprof.(*Profile).WriteTo(0x1c4b540, 0x7f5a9e404068, 0xc8200585b0, 0x2, 0x0, 0x0)
	/usr/local/go/src/runtime/pprof/pprof.go:236 +0xd4
net/http/pprof.handler.ServeHTTP(0xc820056a91, 0x9, 0x7f5a9e404008, 0xc8200585b0, 0xc8202720e0)
	/usr/local/go/src/net/http/pprof/pprof.go:210 +0x37e
net/http/pprof.Index(0x7f5a9e404008, 0xc8200585b0, 0xc8202720e0)
	/usr/local/go/src/net/http/pprof/pprof.go:222 +0x200
net/http.HandlerFunc.ServeHTTP(0x14c88c0, 0x7f5a9e404008, 0xc8200585b0, 0xc8202720e0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820057200, 0x7f5a9e404008, 0xc8200585b0, 0xc8202720e0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82007c400, 0x7f5a9e404008, 0xc8200585b0, 0xc8202720e0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8201df100)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [chan receive, 4 minutes]:
github.com/vmware/vic/lib/tether.(*tether).Start(0xc8201d2100, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/lib/tether/tether.go:151 +0x1b0
main.main()
	/opt/go/src/github.com/vmware/vic/cmd/tether/main_linux.go:73 +0x596

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0x7f5a9e3fa078)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 43 [select, 2 minutes]:
github.com/vmware/vic/pkg/serial.(*RawConn).Read(0xc8201e02a0, 0xc820252000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/pkg/serial/rawconn.go:102 +0x41a
bufio.(*Reader).fill(0xc8200544e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8200544e0, 0xc82007cca0, 0x5, 0x5, 0x20, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f5a9e3fe800, 0xc8200544e0, 0xc82007cca0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f5a9e3fe800, 0xc8200544e0, 0xc82007cca0, 0x5, 0x5, 0x70, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*streamPacketCipher).readPacket(0xc82007cc80, 0xc800000264, 0x7f5a9e3fe800, 0xc8200544e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/cipher.go:149 +0xc1
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc820090500, 0xc8200544e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/transport.go:93 +0xce
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*transport).readPacket(0xc820090500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/transport.go:89 +0x55
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc8201c4480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/handshake.go:157 +0xec
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc8201c4480)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/handshake.go:129 +0x25
created by github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.newServerTransport
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/handshake.go:104 +0x2e6

goroutine 18 [select, 4 minutes, locked to thread]:
runtime.gopark(0x14c8d08, 0xc820014728, 0x11d5070, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820014728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820014728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive, 2 minutes]:
github.com/vmware/vic/lib/tether.(*tether).childReaper.func1(0xc8201d2100)
	/opt/go/src/github.com/vmware/vic/lib/tether/tether_linux.go:49 +0x51
created by github.com/vmware/vic/lib/tether.(*tether).childReaper
	/opt/go/src/github.com/vmware/vic/lib/tether/tether_linux.go:88 +0x20f

goroutine 20 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f5a9e3ff8b0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200531e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200531e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820053180, 0x0, 0x7f5a9e3ff9a8, 0xc8202660a0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82001c060, 0x45e370, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82001c060, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc82007c400, 0x7f5a9e3ff970, 0xc82001c060, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc82007c400, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0x11d9d00, 0xc, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
main.(*operations).Setup.func1()
	/opt/go/src/github.com/vmware/vic/cmd/tether/ops.go:32 +0x3c
created by main.(*operations).Setup
	/opt/go/src/github.com/vmware/vic/cmd/tether/ops.go:33 +0xf6

goroutine 23 [chan receive, 4 minutes]:
main.(*attachServerSSH).run(0xc8201d80e0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:194 +0x7bb
created by main.(*attachServerSSH).start
	/opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:133 +0x68e

goroutine 29 [chan receive, 4 minutes]:
main.(*attachServerSSH).globalMux(0xc8201d80e0, 0xc820205500)
	/opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:276 +0x150
created by main.(*attachServerSSH).run
	/opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:190 +0x689

goroutine 28 [chan receive, 2 minutes]:
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readPacket(0xc8201c4480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/handshake.go:120 +0x6d
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*mux).onePacket(0xc820203ea0, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/mux.go:215 +0x5e
github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.(*mux).loop(0xc820203ea0)
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/mux.go:190 +0x42
created by github.com/vmware/vic/vendor/golang.org/x/crypto/ssh.newMux
	/opt/go/src/github.com/vmware/vic/vendor/golang.org/x/crypto/ssh/mux.go:128 +0x20e

goroutine 477 [IO wait]:
net.runtime_pollWait(0x7f5a9e3ff7f0, 0x72, 0xc820249000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820270220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820270220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202701c0, 0xc820249000, 0x1000, 0x1000, 0x0, 0x7f5a9e3fa050, 0xc82000a028)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201dc008, 0xc820249000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.(*connReader).Read(0xc820266120, 0xc820249000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:526 +0x196
bufio.(*Reader).fill(0xc8201e0360)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8201e0360, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8201e0360, 0x0, 0x0, 0x0, 0x11a4b00, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820056780, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820056780, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x40
net/http.readRequest(0xc8201e0360, 0x0, 0xc8202721c0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:721 +0xb6
net/http.(*conn).readRequest(0xc82007c280, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:705 +0x359
net/http.(*conn).serve(0xc82007c280)
	/usr/local/go/src/net/http/server.go:1425 +0x947
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 397 [syscall, 2 minutes]:
syscall.Syscall(0x0, 0xa, 0xc820252000, 0x1000, 0x4, 0x40e4b3, 0xc820001800)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xa, 0xc820252000, 0x1000, 0x1000, 0xc820048a00, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0xa, 0xc820252000, 0x1000, 0x1000, 0x30, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc8201dc048, 0xc820252000, 0x1000, 0x1000, 0xcf1cc0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x53
os.(*File).Read(0xc8201dc048, 0xc820252000, 0x1000, 0x1000, 0x30, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
github.com/vmware/vic/pkg/serial.(*RawConn).Read.func1(0xc82026c020, 0xc82026c040, 0xc8201e02a0, 0xc820252000, 0x1000, 0x1000, 0xc82025aa80)
	/opt/go/src/github.com/vmware/vic/pkg/serial/rawconn.go:95 +0x68
created by github.com/vmware/vic/pkg/serial.(*RawConn).Read
	/opt/go/src/github.com/vmware/vic/pkg/serial/rawconn.go:100 +0xfc
```

**Comment by caglar10ur** [comment] 2016-06-08 16:53
```ISOLINUX 4.05 0x4f92e181  Copyright (C) 1994-2011 H. Peter Anvin et al
Setting IP addr to  10.143.2.228/24
Setting route to 10.143.2.253
INFO[0000] Started reaping child processes
INFO[0000] Launching pprof server on port 6060
INFO[0000] Starting extension Attach
INFO[0000] opening ttyS0 for backchannel
INFO[0000] s = &terminal.State{termios:syscall.Termios{Iflag:0x500, Oflag:0x5, Cflag:0xcbd, Lflag:0x8a3b, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4, 0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}}
INFO[0000] creating raw connection from ttyS0 (fd=10)

INFO[0000] Loaded executor config
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] setting hostname to
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] [95.794µs] setting hostname to
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] applying endpoint configuration for bridge
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] [566.228µs] applying endpoint configuration for bridge
INFO[0000] Launching process for session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).launch] launching session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] [BEGIN] [main.(*operations).SessionLog] configure session log writer
INFO[0000] opening ttyS2 for session logging
INFO[0000] [ END ] [main.(*operations).SessionLog] [1.685742ms] configure session log writer
INFO[0000] Launching command []string{"/bin/bash"}
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.establishPty] initializing pty handling for session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.establishPty] [14.05416ms] initializing pty handling for session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*tether).launch] [40.512107ms] launching session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] Passing config to Attach
INFO[0000] [BEGIN] [main.(*attachServerSSH).Reload] attach reload
INFO[0000] Processing config for session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] Session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577 is configured for attach
INFO[0000] [BEGIN] [main.(*attachServerSSH).start] start attach server
INFO[0000] [ END ] [main.(*attachServerSSH).start] [433.098µs] start attach server
INFO[0000] [ END ] [main.(*attachServerSSH).Reload] [29.475881ms] attach reload
INFO[0000] [BEGIN] [main.(*attachServerSSH).run] main attach server loop
INFO[0000] [BEGIN] [main.backchannel] establish tether backchannel
INFO[0000] server: received ack: 0x0678 == 0x0678

INFO[0000] lossiness check PASSED
INFO[0000] [ END ] [main.backchannel] [173.459998ms] establish tether backchannel
INFO[0000] ready to service attach requests
INFO[0000] [BEGIN] [main.(*attachServerSSH).globalMux] start attach server global request handler
INFO[0000] received global request type container-ids
INFO[0000] accepting incoming channel for 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[0000] [BEGIN] [main.(*attachServerSSH).channelMux] start attach server channel request handler
INFO[0992] [BEGIN] [main.resizePty] resize pty
INFO[0992] [ END ] [main.resizePty] [111.995µs] resize pty
INFO[0992] [BEGIN] [main.resizePty] resize pty
INFO[0992] [ END ] [main.resizePty] [33.604µs] resize pty
INFO[1929] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).handleSessionExit] handling exit of session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[1929] 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577 exit code: 0
INFO[1929] [ END ] [github.com/vmware/vic/lib/tether.(*tether).handleSessionExit] [10.417402ms] handling exit of session 577241ca93ef86713eed0de95273f53bae5e853daab8f921bda6befeb0365577
INFO[1929] [ END ] [main.(*attachServerSSH).channelMux] [32m8.698941152s] start attach server channel request handler
```

**Comment by hickeng** [comment] 2016-06-21 18:23
Needs triage in time for TP3 fix

**Comment by corrieb** [comment] 2016-07-14 19:10
@mhagen-vmware this has been festering for a while now. I have not seen this issue in any of the testing I've done. This should be picked up by the integration test that does an rm after a stop. @caglar10ur do we need to investigate this PANIC further, or has that been fixed.

If there's no remaining work to do, we should close

**Comment by caglar10ur** [comment] 2016-07-14 19:15
I don't remember seeing this for a while so I suggest closing this (we can always re-open if we observe again)

**Comment by mhagen-vmware** [comment] 2016-07-25 14:04
Unable to reproduce this anymore

**Closed by mhagen-vmware** 2016-07-25 14:04 UTC
Labels: kind/bug
