### ISSUE TITLE
Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1109] opened 2016-06-15 19:55 UTC
Seeing this error periodically, not sure how to reliably cause this problem.  It seems transitory and immediately after seeing this error, I can run the docker command again and not see this error.

Might be a race condition with how quickly my scripts make a docker request after deploying a new VCH?

**Comment by mhagen-vmware** [comment] 2016-06-16 12:44
This does seem to be a race condition, as it looks like every build now has this issue on the first pull image after a new deploy.  So I think either vic-machine should have an additional check when it reports the system is up or maybe VCH should not give back it's IP to vic-machine until it is fully up?

**Comment by hickeng** [comment] 2016-06-16 19:44
There is working code in vic-machine in the #746 fix that blocks until the individual components are up and running. Still a hole until we have an "initialized" mechanism, but that's much more involved than just ensuring the process has launched.

**Comment by hickeng** [comment] 2016-06-19 21:57
This could also be released to cache change in #1111 - please check with @jzt  for correct issue number to track fix if that's the case.

**Comment by hickeng** [comment] 2016-06-21 17:10
@mhagen-vmware I believe you said this was fixed by the recent merge from @jzt. Please can you close this if confirmed.

**Comment by mhagen-vmware** [comment] 2016-06-28 19:17
Still seeing this issue.

**Comment by darrylcauldwell** [comment] 2016-07-14 11:50
I just installed using vic_2868.tar.gz and found it installed without error.

I can get docker info,

    docker -H 192.168.1.218:2375 info
    Containers: 0
     Running: 0
     Paused: 0
     Stopped: 0
     Images: 0
    Storage Driver: vSphere Integrated Containers Backend Engine
    vSphere Integrated Containers Backend Engine: STOPPED
    Execution Driver: vSphere Integrated Containers Backend Engine
    Plugins: 
     Volume: 
     Network: bridge
    Kernel Version: 4.4.8-esx
    Operating System: VMware Photon/Linux
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 1.958 GiB
    Name: vch
    ID: vSphere Integrated Containers
    Docker Root Dir: 
    Debug mode (client): false
    Debug mode (server): false
    Registry: registry-1.docker.io
    WARNING: No memory limit support
    WARNING: No swap limit support
    WARNING: No kernel memory limit support
    WARNING: No cpu cfs quota support
    WARNING: No cpu cfs period support
    WARNING: No cpu shares support
    WARNING: No cpuset support
    WARNING: IPv4 forwarding is disabled
    WARNING: bridge-nf-call-iptables is disabled
    WARNING: bridge-nf-call-ip6tables is disabled

But whenever I try to pull something like the example busybox I get,

    docker -H 192.168.1.218:2375 pull busybox:latest
    Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused

I noticed VCH VM runs high CPU and on checking ps aux

    root       205 43.6  1.1 434204 22884 ?        Ssl  11:03  15:11 /sbin/vic-init
    root       371  0.0  0.8 290096 18228 ?        Sl   11:03   0:00 /sbin/vicadmin -docker-host=unix:///var/run/docker.sock -insecure -sdk=https://Administrator%40vsphere.local@vcenter.darrylcauldwell.local -ds=vsanDatastore -cluster=/EvilWorkshop/host/ElectricChair -pool=/EvilWorkshop/host/ElectricChair/Resources -vm-path=/EvilWorkshop/vm/vch
    root       376  0.0  1.4 306592 29972 ?        Sl   11:03   0:00 /sbin/docker-engine-server -serveraddr=0.0.0.0 -port=2375 -port-layer-port=8080

Could this be related to same issue?
Does 'vSphere Integrated Containers Backend Engine: STOPPED' look correct or should this be running?

**Comment by mhagen-vmware** [comment] 2016-07-26 18:38
Assigning back to @hickeng as I have answered the question.

**Comment by hickeng** [comment] 2016-07-27 18:41
There are a couple of approaches here:
1. block docker api operations until the port layer has finished initializing.
2. block the installer from returning until the port-layer is initialized (it currently blocks until the portlayer is launched)

**Comment by mdubya66** [comment] 2016-08-10 14:51
This is a blocker to CI functioning correctly. Raising it's priority. @hmahmood will you take point on this and the other issues in this list?

#1878, #1870, #1822, #1823, #1109

**Comment by anchal-agrawal** [comment] 2016-08-11 15:18
As per the discussion with @hmahmood yesterday, vic-machine can't ping the engine server and the portlayer to check if they're up since they listen on localhost.

The installer currently waits on the key `"guestinfo..init.sessions|port-layer.started"` but that seems to be set when the portlayer process has been spawned, not when it has started serving. A solution would be to add two keys in [`VirtualContainerHostConfigSpec`](https://github.com/vmware/vic/blob/master/lib/config/virtual_container_host.go#L51), set them in the engine server and the portlayer once they've started serving, and check the keys in the installer before it exits. This follows the second approach suggested by @hickeng.

If we don't resolve this issue, we'd have to add a `sleep` before every integration test suite to give the portlayer enough time to start serving. This would add a lot of time to our integration test runs.

**Comment by mhagen-vmware** [comment] 2016-08-11 15:38
We currently have a sleep before each integration test it probably adds several minutes to each build, which is why it would be great if we could fix this and get rid of that sleep :)

**Comment by anchal-agrawal** [comment] 2016-08-11 20:25
There's no other way to determine exactly when the portlayer has started serving other than pinging it. Since the portlayer isn't exposed, we can use the following dependency to ensure that the portlayer is serving before the installer exits.

`vic-machine waits until it can connect to the personality -> personality waits until it can connect to the portlayer`

@hmahmood @emlin

This approach may have side-effects if the portlayer crashes during initialization, but that remains to be explored.

**Closed** 2016-08-18 20:34 UTC
Labels: component/docker-api-server, component/portlayer, component/vic-machine, kind/bug, kind/bug/p0, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:41
This is fixed. Removing kind/note.
