### ISSUE TITLE
Performance regression in remove containers operation

### ISSUE THREAD

**Issue by gopakumarr** [vmware/vic#6627] opened 2017-10-25 10:27 UTC
Remove container operations slow down with VIC build **13678**. All the values below are in seconds

Benchmark name |   13676  |  13678   |  Delta % |
------------------- | --------- | --------  | ----------|
rm_vic_0075_median | 2.884 | 4.089   |  41% |
rm_vic_0075_total      | 3.534 | 4.607  |  30% |
rm_vic_0050_median |  1.981 | 2.597  |  31% |
rm_vic_0050_total      |  2..396 | 3.020 |  26% |
rm_vic_0025_median |  0.990 | 1.417  |  43% |
rm_vic_0025_total      |  1.281 | 1.508 |  17% |

Above operations are removing N number of containers (25, 50, 75) parallelly. I performed this experiment with constant ESX build L1-18

**VIC version:**

From https://console.cloud.google.com/storage/browser/vic-engine-builds

vic_13676.tar.gz (fast)
vic_13678.tar.gz (slow)

**Deployment details:**

vic-machine-linux create --target myesxhost.com --image-store datastore1 --name vic_13678 --compute-resource /ha-datacenter/host/*/Resources --no-tls --force --timeout 10m0s --user root --password mypassword

**Logs:**

* [container-logs-13676.zip](https://github.com/vmware/vic/files/1414164/container-logs-13676.zip) (fast)

* [container-logs-13678.zip](https://github.com/vmware/vic/files/1414165/container-logs-13678.zip) (slow)

**Comment by mdubya66** [comment] 2017-10-25 15:48
Build https://ci.vcna.io/vmware/vic/13678
PR https://github.com/vmware/vic/pull/6284

**Comment by hickeng** [comment] 2017-10-25 19:23
I suspect this relates to the following change and not the next commit if this is removing powered on containers:
https://github.com/vmware/vic/pull/6254/files#diff-6e989557b980355774bd4187364245fbR1255

The linked change waits for up to 2 minutes to retry a stop if there is a conflict error.
We were seeing ConflictErrors in parallel operations when deployed as a vApp that never present when deployed as a resource pool, particularly with `rm -f` ( @caglar10ur can confirm from his concurrency investigation)

As such we need to confirm with @gopakumarr whether these builds were deployed with `--use-rp=true` (assuming the necessary fixes are in the code by that build).

Regarding the timeout interval I don't see any comments about why 2 minutes was chosen, so unless @chengwang86 can expand on the choice I suggest we reduce that figure as 2 minutes is a very long time to wait for something that could occur for a single operation.

**Comment by chengwang86** [comment] 2017-10-25 20:40
@hickeng The reason we increased the timeout to 2min is: Originally the timeout value was 1min.  However, we found in our nightly tests that sometimes it took more than 1 min for the first attempt of `hard poweroff` to finish, and the `retry logic` in `docker stop` didn't take effect. Thus we increased the timeout to 2min which seemed to work. Without this code change, the `docker stop` via `hard poweroff` would simply fail (after exceeding the default 1min `maxElapseTime`) without retrying.

In the performance test, if `docker stop` takes longer time than before, it may be the case that the first attempt of `hard poweroff` didn't succeed and retries were carried out.

**Comment by mhagen-vmware** [comment] 2017-10-25 21:13
Which makes sense, powering off 25/50/75 containers all at once is going to have problems and many of them are going to hit that hard power off timeout.

**Comment by gopakumarr** [comment] 2017-10-26 11:13
@hickeng Builds are not deployed with --use-rp=true. Here is how we deploy `vic-machine-linux create --target myesxhost.com --image-store datastore1 --name vic_13678 --compute-resource /ha-datacenter/host/*/Resources --no-tls --force --timeout 10m0s --user root --password mypassword`

**Comment by sflxn** [comment] 2017-11-02 22:58
I perused the logs for the fast and slow path looking for signatures of the 2 min max backoff time (from the persona).  Unfortunately, we do not have enough logging to positively identify the change.  What I ended up doing is take a random sampling of container stops from the portlayer logs to see if there were retries (indicating retry from the persona).  I saw no evidence of this.  It was only a random sampling, but so far, there is no evidence of the 2 min max backoff causing this regression.  That max time could still potentially be the cause.

**Comment by sflxn** [comment] 2017-11-03 23:18
Until #6572 is merged, @gopakumarr you can try doing a performance run with --use-rp=true.

**Comment by gopakumarr** [comment] 2017-11-04 04:05
@sflxn Sure I will have this option `--use-rp=true` for the deployment

**Comment by mdubya66** [comment] 2017-11-06 16:28
Please note that --use-rp flag will be deprecated since we are making it the only way to deploy a VCH in 1.3. See https://github.com/vmware/vic/issues/6471

**Comment by mdubya66** [comment] 2017-11-06 16:30
question though. our baseline is vApp, is comparing a vch delpoy using --use-rp against one that was deployed as a vApp a valid performance comparison?  @hickeng @sflxn

**Comment by sflxn** [comment] 2017-11-06 19:08
@mdubya66 @gopakumarr You're right about that.  Running this test with resource pool is a completely different set of performance numbers.  The numbers can go up or down.  The only way to determine if it fixes the regression is if we rerun build 13676 using resource pool to set as a baseline.  Then we can either rerun build 13678 (using resource pool) or one of the current 1.3 builds (using resource pool) to see if there are no regression.

**Comment by mdubya66** [comment] 2017-11-06 19:24
ok, for 1.3 should we redo the baselines using 1.2.1 and the --use-rp flag to vic-machine? @mlh78750 @mhagen-vmware @hickeng

**Comment by gopakumarr** [comment] 2017-11-07 14:37
@sflxn I tried build 13676 and 13678, both deployed using resource pool. Still there is regression

Benchmark name | 13676 | 13678
-------------------|--|--
rm_vic_0075_median|3.122|4.159
rm_vic_0075_total|3.804|4.715
rm_vic_0050_median|2.073|2.678 
rm_vic_0050_total|2.47|3.042
rm_vic_0025_median|1.031|1.293
rm_vic_0025_total |1.27|1.516

**Comment by hickeng** [comment] 2017-11-07 20:08
Given the lack of effect of `--use-rp` and the continued note that it's 13678 I'm withdrawing my previous hypothesis for now. I have no new hypothesis given there's literally no code changed in ca11294aec that is involved in the remove path.

I suggest running this with `debug=1` to get operation deltas recorded in the logs - that will give a reasonable indication of where time increases have occurred between the builds.

A follow up issue should also be made to determine why the following appears in the 13676 personality log:
```
Oct 25 2017 07:29:30.987Z WARN  error locating Admiral, returning last known config: Login failed: body: , status: 400 Bad Request
```

**Comment by sflxn** [comment] 2017-11-07 21:58
@gopakumarr Can you rerun it using George's suggestion.  It may affect the run times, but without the debug logs, I can't guess at what the cause.  Also, can you provide us with the script that you actually run?  It maybe informative for me to run this locally.

**Comment by gopakumarr** [comment] 2017-11-08 11:13
@hickeng @sflxn I reran 13676 and 13678 builds with flag debug=1 and collected container logs

fast case : [container-logs-13676-debug.zip](https://github.com/vmware/vic/files/1453479/container-logs-13676-debug.zip)
slow case : [container-logs-13678-debug.zip](https://github.com/vmware/vic/files/1453487/container-logs-13678-debug.zip)

Performance numbers while collecting container logs were

Benchmark name | 13676 | 13678
--------------------|--------|---------
rm_vic_0075_median|14.293|21.29 
rm_vic_0075_total|17.749|24.497
rm_vic_0050_median|10.232 |15.767 
rm_vic_0050_total|12.314 |17.01
rm_vic_0025_median|5.172|8.0
rm_vic_0025_total|6.768|9.521

**Comment by gopakumarr** [comment] 2017-11-08 14:47
@sflxn I have emailed you the scripts. Fyi, I have removed flag --use-rp from automation scripts since it is deprecated. I have started to see failures while deploying in our automation runs with this option set

**Comment by gopakumarr** [comment] 2017-11-20 09:44
We switched our baseline to VIC 1.2.1 with --use-rp flag set to true, now when comparing to 1.2.1 performance numbers there is no regression in latest VIC builds

Test | vic 1.2.1 | 14750 |
-----|----------|--------|
rm_vic_0075_median| 3.996| 3.99|
rm_vic_0075_total|4.603|4.683|
rm_vic_0050_median|2.628|2.537|
rm_vic_0050_total|3.1|3.128|
rm_vic_0025_median|1.308|1.252|
rm_vic_0025_total|1.551|1.541|

**Comment by sflxn** [comment] 2017-11-27 23:19
Using the debug logs files that @gopakumarr uploaded, I process the times for

ContainerCreate
ContainerStart
Containers
ContainerStop
ContainerRm

Eyeballing the numbers for the fast and slow path, I can see the regression is in ContainerRm.  Here's a sample:

Fast | Slow
-- | --
  |  
635.269451ms | 684.758022ms
620.895972ms | 749.538852ms
275.424824ms | 389.402429ms
298.264851ms | 370.124633ms
372.587159ms | 350.509591ms
282.209803ms | 384.662689ms
303.638164ms | 354.968844ms
270.8082ms | 360.289765ms
315.035374ms | 366.431523ms
271.221215ms | 381.857503ms
1.321620863s | 3.099847748s
1.740766767s | 3.099777679s
1.856457315s | 3.127731846s
1.815146499s | 3.533875338s
2.125443161s | 3.605110556s
2.12723368s | 3.605059208s
2.132652584s | 3.586763121s
2.120138416s | 3.616649669s

**Comment by sflxn** [comment] 2017-11-27 23:24
To process the file, run the following commands on the docker-personality.log file for each log bundles:

```
grep "END .*\*Container).Container" docker-personality.log > container-ops.log
grep "ContainerCreate" container-ops.log | grep -Po '\d+\.\d+(ms|s|µs)' > create-time.log
grep "ContainerStart" container-ops.log | grep -Po '\d+\.\d+(ms|s|µs)' > start-time.log
grep "Containers" container-ops.log | grep -Po '\d+\.\d+(ms|s|µs)' > ps-time.log
grep "ContainerStop" container-ops.log | grep -Po '\d+\.\d+(ms|s|µs)' > stop-time.log
grep "ContainerRm" container-ops.log | grep -Po '\d+\.\d+(ms|s|µs)' > remove-time.log
```

Then import them into a spreadsheet to do a comparison.

**Comment by sflxn** [comment] 2017-11-27 23:38
Running the following command on the portlayer logs seems to indicate the removeHandler on the portlayer is not at fault,

```
grep "END .*\.RemoveContainerHandler" port-layer.log | grep -Po '\d+\.\d+(ms|s|µs)' > pl-remove-time.log
```

**Comment by sflxn** [comment] 2017-11-27 23:59
Since the portlayer operation to remove container did not regress, I looked in the persona logs again.  Here's the root cause,

**UnbindContainerFromNetwork**

Run the following command on the persona logs:

```
grep "END .*UnbindContainerFromNetwork" docker-personality.log | grep -Po '\d+\.\d+(ms|s|µs)' > unbind-from-network.log
```

The call exist in the slow case but not in the fast case.

**Comment by sflxn** [comment] 2017-11-28 00:07
I don't think this is a regression.  The following was added to fix a bug,

https://github.com/vmware/vic/pull/6209
https://github.com/vmware/vic/issues/5948

The reason why the "fast" build was faster was because it did not unbind the container in ContainerRm.  That was a bug.

**Comment by sflxn** [comment] 2017-11-28 00:12
I added "resolution/not-a-bug" label to indicate this isn't a bug.

**Comment by mdubya66** [comment] 2017-11-28 14:25
Great team work and analysis. Closing.

**Closed by mdubya66** 2017-11-28 14:25 UTC
Labels: component/test, kind/bug, priority/high, resolution/not-a-bug, team/container
