### ISSUE TITLE
`vic-machine ls` is doubling output

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#3975] opened 2017-02-16 17:47 UTC
**VIC version:** 
bd30cd68cd883f209e542bab20f5af0f5f1b8598

**Deployment details:**
Deployed to a local ESX 6.0

**Steps to reproduce:**
vic-machine ls

**Actual behavior:**
```
ID         PATH                                                                 NAME                VERSION                 UPGRADE STATUS
723        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        localtls            v0.8.0-0-54921dd        Up to date
726        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        ghicken-test        v0.8.0-0-bd30cd6        Up to date
723        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        localtls            v0.8.0-0-54921dd        Up to date
726        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        ghicken-test        v0.8.0-0-bd30cd6        Up to date
```

**Expected behavior:**
```
ID         PATH                                                                 NAME                VERSION                 UPGRADE STATUS
723        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        localtls            v0.8.0-0-54921dd        Up to date
726        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        ghicken-test        v0.8.0-0-bd30cd6        Up to date
```

Please add a test to confirm we're listing each VCH only once - should confirm that we're not hitting the same duplication for networks, datastores, etc now that govmomi finder recurses.

**Logs:**
```
vagrant@devbox:~/vic$ vic-ls --debug=1
Feb 16 2017 17:36:53.367Z INFO  ### Listing VCHs ####
Feb 16 2017 17:36:53.369Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.NewValidator:78]
Feb 16 2017 17:36:53.458Z DEBUG Session Environment Info:
Feb 16 2017 17:36:53.458Z DEBUG vSphere resource cache populating...
Feb 16 2017 17:36:53.469Z DEBUG Cached dc:
Feb 16 2017 17:36:53.483Z DEBUG Cached cluster:
Feb 16 2017 17:36:53.494Z DEBUG Cached ds:
Feb 16 2017 17:36:53.511Z DEBUG Cached host:
Feb 16 2017 17:36:53.523Z DEBUG Cached pool:
Feb 16 2017 17:36:53.523Z DEBUG vSphere resource cache populated...
Feb 16 2017 17:36:53.524Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.NewValidator:78] [155.182446ms]
Feb 16 2017 17:36:53.527Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateTarget:279]
Feb 16 2017 17:36:53.527Z INFO  Validating target
Feb 16 2017 17:36:53.528Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).target:335]
Feb 16 2017 17:36:53.530Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:342]
Feb 16 2017 17:36:53.555Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:342] [24.8418ms]
Feb 16 2017 17:36:53.555Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).target:335] [27.14859ms]
Feb 16 2017 17:36:53.555Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:221]
Feb 16 2017 17:36:53.555Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:221] [172.89µs]
Feb 16 2017 17:36:53.556Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateTarget:279] [28.507837ms]
Feb 16 2017 17:36:53.556Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateCompute:251]
Feb 16 2017 17:36:53.556Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateCompute:251] [155.5µs]
Feb 16 2017 17:36:53.557Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.NewDispatcher:79]
Feb 16 2017 17:36:53.557Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.NewDispatcher:79] [423.332µs]
Feb 16 2017 17:36:53.559Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).SearchVCHs:160]
Feb 16 2017 17:36:53.561Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerDC:196] /ha-datacenter
Feb 16 2017 17:36:53.606Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:53.607Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:53.633Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:53.655Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:53.681Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:53.720Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [39.183369ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:53.721Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [65.848669ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:53.721Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [88.638976ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:53.721Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:53.757Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [35.774527ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:53.758Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:53.789Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [31.441927ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:53.790Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [182.814853ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:53.790Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:53.869Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [79.248164ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:53.870Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:53.905Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [35.37223ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:53.905Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:53.914Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls
Feb 16 2017 17:36:53.915Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:723
Feb 16 2017 17:36:53.915Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:53.942Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] [28.014344ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls
Feb 16 2017 17:36:53.944Z DEBUG "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls" is VCH
Feb 16 2017 17:36:53.972Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [67.059128ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:53.973Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:53.980Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
Feb 16 2017 17:36:53.981Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:726
Feb 16 2017 17:36:53.981Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.001Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] [20.59321ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
Feb 16 2017 17:36:54.001Z DEBUG "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test" is VCH
Feb 16 2017 17:36:54.049Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [76.52219ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.050Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.081Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [31.168523ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.081Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.121Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [39.798772ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.122Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [515.361305ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources
Feb 16 2017 17:36:54.122Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.122Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.158Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.193Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.230Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [36.799815ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.231Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [72.823087ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.231Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [108.765163ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.231Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.265Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [34.191057ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.266Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.345Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [78.922055ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.345Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.375Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [29.911108ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.376Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [253.871038ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool
Feb 16 2017 17:36:54.376Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.376Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.408Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.447Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [38.640561ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.447Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [71.184693ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.448Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.486Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [38.888231ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.487Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.537Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [50.080653ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.537Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [161.440706ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other
Feb 16 2017 17:36:54.538Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.538Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.590Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [52.377165ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.591Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.633Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [42.221975ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.634Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [95.73384ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/pool/other/there
Feb 16 2017 17:36:54.634Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.634Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.656Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [22.303451ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.657Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.673Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls
Feb 16 2017 17:36:54.673Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:723
Feb 16 2017 17:36:54.673Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.699Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] [26.491645ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls
Feb 16 2017 17:36:54.700Z DEBUG "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls/localtls" is VCH
Feb 16 2017 17:36:54.737Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [80.443918ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.737Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [103.587266ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/localtls
Feb 16 2017 17:36:54.737Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.738Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.765Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).listChildrenPools:290] [27.672009ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.766Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.770Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
Feb 16 2017 17:36:54.771Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:726
Feb 16 2017 17:36:54.771Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.788Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:72] [17.174509ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
Feb 16 2017 17:36:54.788Z DEBUG "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test" is VCH
Feb 16 2017 17:36:54.834Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).getChildVCHs:249] [68.134233ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.835Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerRP:224] [97.091319ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test
Feb 16 2017 17:36:54.835Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).searchVCHsPerDC:196] [1.274419251s] /ha-datacenter
Feb 16 2017 17:36:54.835Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).SearchVCHs:160] [1.276474565s]
Feb 16 2017 17:36:54.836Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136]
Feb 16 2017 17:36:54.837Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:723
Feb 16 2017 17:36:54.837Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.867Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136] [31.406961ms]
Feb 16 2017 17:36:54.867Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136]
Feb 16 2017 17:36:54.867Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:726
Feb 16 2017 17:36:54.868Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.883Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136] [16.082677ms]
Feb 16 2017 17:36:54.884Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136]
Feb 16 2017 17:36:54.884Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:723
Feb 16 2017 17:36:54.884Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.912Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136] [28.711404ms]
Feb 16 2017 17:36:54.914Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136]
Feb 16 2017 17:36:54.914Z DEBUG get vm properties [config.extraConfig] of vm VirtualMachine:726
Feb 16 2017 17:36:54.915Z DEBUG properties: [config.extraConfig summary.runtime.connectionState]
Feb 16 2017 17:36:54.928Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136] [14.737909ms]

ID         PATH                                                                 NAME                VERSION                 UPGRADE STATUS
723        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        localtls            v0.8.0-0-54921dd        Up to date
726        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        ghicken-test        v0.8.0-0-bd30cd6        Up to date
723        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        localtls            v0.8.0-0-54921dd        Up to date
726        /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources        ghicken-test        v0.8.0-0-bd30cd6        Up to date
vagrant@devbox:~/vic$
```

**Comment by dougm** [comment] 2017-02-16 20:54
Likely triggered by #3620 .  Quick fix is to change finder List calls from "*" to "./*" or squash duplicates.

But along the lines of #3817 , the proper fix is to take advantage of the finder enhancements to find VCHs within nested inventory folders.  Should also simplify the Dispatcher.SearchVCHs code.

**Comment by anchal-agrawal** [comment] 2017-02-24 20:50
This is reproducible when `--compute-resource` is not specified with the command. With it, the command works as expected.

**Comment by stuclem** [comment] 2017-03-13 16:22
Added the following to the release notes:

----

- <b>`vic-machine ls` doubles output. [#3975](https://github.com/vmware/vic/issues/3975)</b><br> When you run `vic-machine ls`, VCHs are listed twice in the output.

   Workaround: Specify the `--compute-resource` option when you run `vic-machine ls`.

-----

@anchal-agrawal does this cover it?

**Comment by anchal-agrawal** [comment] 2017-03-13 22:25
LGTM, thanks Stuart!

Side-note: I couldn't repro this issue (with/without `--compute-resource`) on a VC with 1 ESX. On a standalone ESX, the workaround we have is valid.

**Comment by stuclem** [comment] 2017-03-16 12:00
Thanks @anchal-agrawal. Removing kind/note.

**Comment by emlin** [comment] 2017-03-21 16:26
Talked with Doug offline. Looks like a better option is to use new containerview wrapper in govmomi to fix this issue, so assign to Doug as he will take care of this issue after the change in govmomi.
thanks Doug

**Comment by dougm** [comment] 2017-03-22 18:58
@emlin opted to hold off on integrating with ContainerView as it would just be an optimization in this case and would need a vcsim impl to test.

Sticking with the original plan for now: vmware/govmomi#689

**Comment by dougm** [comment] 2017-03-22 20:34
The Finder enhancement cures the double ls issue: https://github.com/vmware/vic/compare/master...dougm:issue-3975

I'm going to work on simulator based tests before opening a PR.

**Closed** 2017-03-24 17:58 UTC
Labels: component/vic-machine, kind/bug, priority/high, status/needs-regression-test
