### ISSUE TITLE
Find a work around to ContainerStatPath

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5570] opened 2017-06-22 20:50 UTC
As a user of VIC, I expect to be able to copy files/folders into a container.

Acceptance Criteria:

backend.ContainerExtractToDir() gets called!

---
Basic research for docker cp.  We need containerstatpath for docker cp to work.  Docker assumes local file system or volume with lightweight mounting.  We need a way for the daemon to convince the CLI to continue onto ContainerExtractToDir() after calling ContainerStatPath().

**Comment by morris-jason** [comment] 2017-06-23 21:14
#### Tracing
Writing to a container, ie copyToContainer, is shown here - https://github.com/docker/cli/blob/master/cli/command/container/cp.go#L180-L274 

Per @sflxn's suggestion to mock the path stat as a directory all the time, dstInfo is always going to be marked as existing and a directory, shown on line 217.

The issue is with line 258, where the cli prepares the tar header file paths for transfer to a container, using method PrepareArchiveCopy shown here: https://github.com/moby/moby/blob/master/pkg/archive/copy.go#L244

Because we are saying the dst esixts and is a directory at all times, we will always end up in the first case here: https://github.com/moby/moby/blob/master/pkg/archive/copy.go#L255

#### Concern
Something like `docker cp log.html f5d5d3a4:/usr/share/nginx/name2.html` should be caught by case 3, which would rename the tar headers in the source content from log.html to name2.html. 

Since we get caught in case 1 at all times, that renaming isn’t going to happen.

#### Conclusion
We’d have to find some way to handle the other 3 cases ourselves, during the tar extraction inside the portlayer. Using the example above, we'd need to find someway to rename the tar file path headers from src to dst using only dst path, as that is all that ContainerExtractToDir provides. 

How to solve that? By implementing the stat logic anyways in the port layer as some untarring step way deep in the call chain.

Or, we can implement it for ContainerStatPath, and inherit a lot of the logic for the other 3 cases in PrepareArchiveCopy that the cli already handles for us.

**Comment by morris-jason** [comment] 2017-06-28 14:14
Partial implementation complete on my branch docker-cp for online copy.

**Comment by hickeng** [comment] 2017-07-25 16:37
@morris-jason I think this issue is no longer needed - it's been superseded by functional stat implemented. If that's correct, can you close this.

**Comment by morris-jason** [comment] 2017-07-26 15:57
Closing.

**Closed** 2017-07-26 15:57 UTC
Labels: area/docker, component/docker-api-server, kind/investigation, priority/medium
