### ISSUE TITLE
Subset of DVS and PortGroups listed in VCH Wizard

### ISSUE THREAD

**Issue by jhedman2** [vmware/vic#7127] opened 2018-01-18 20:59 UTC
New deployment leveraging VIC v1.3.0.533, VCSA 6.5U1, ESXi 6.5U1.  Having troubles during the VCH deployment wizard via WebUI.  Everything works fine until the network configuration dialog, specifically the drop downs for Bridge and Public only show two port-groups, out of say 10 in my lab environment.  All DPG's are configured identically, the user connected to vCenter has Administrator privileges, and have even tested creation of completely new DPG's.  Oddly enough, the two DPG's in the drop down are part of a single DVS, the other primary DVS doesn't show up at all.

Both DVS's are also operating at 6.5 level.  Any ideas on why only one DVS out of two and two out of 10+ DPG's are listed?

Will attempt a manual deployment without wizard, but hoping to figure out the root cause of this.

**Comment by AngieCris** [comment] 2018-01-18 22:18
@jooskim @jak-atx Is this addressed by this PR https://github.com/vmware/vic-ui/pull/310 too?

**Comment by jooskim** [comment] 2018-01-18 22:40
@AngieCris yes. This is a dupe of the existing issue and will be addressed by 310

**Comment by jooskim** [comment] 2018-01-18 22:43
Dupe of https://github.com/vmware/vic-ui/issues/307

**Closed by jooskim** 2018-01-18 22:43 UTC
Labels: area/ui, kind/bug, kind/customer-found, team/lifecycle
