### ISSUE TITLE
Sharing image store folders not supported

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#2995] opened 2016-11-03 13:18 UTC
I am using build 6507 (0.7.0 candidate). 

I am playing around with image store configurations. 

I have deployed two VCHs both with `--image-store sharedstorage/test` (where `sharedstorage` is my datastore and `test` is the directory I want to specify).

When the two VCHs are deployed each of them land on the root of the DS (directories `VCH1` and `VCH2`). A third directory `test` is also created which contains the image directory (with `scratch` etc). 

If I pull busybox from VCH1 the layers land in the `test` directory. If I run `docker images` on VCH2 I see that I have the busybox image available (this makes sense because I am sharing the repository). 

However if I try to delete (`docker rmi`) the image from VCH2 it claims the busybox image doesn't exist (albeit I can see it with `docker images`. If I delete the busybox image from VCH1 it gets deleted but VCH2 it's still caching it somewhere:
```
user1@ubuntu:~/vic$ docker -H 192.168.8.53:2375 pull busybox
Using default tag: latest
Pulling from library/busybox
56bec22e3559: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Image is up to date for library/busybox:latest

user1@ubuntu:~/vic$ docker -H 192.168.8.53:2375 images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              e292aa76ad3b        3 weeks ago         1.093 MB
```
The image doesn't exist in reality, in fact if I try to use it from VCH2 .. it shoots an error:

```
user1@ubuntu:~/vic$ docker -H 192.168.8.53:2375 run -it busybox
docker: Error response from daemon: Server error from portlayer: Invalid configuration for device '1'..
See 'docker run --help'.
```

I am unsure if the desired behaviour is to have 2+ VCHs share docker images (in which case there are big issues in how they work on that shared space) or if there is a bug in vic-machine that lets you create different VCHs pointing to the same directory when this would NOT be supported.

**Comment by mlh78750** [comment] 2016-11-03 14:30
My initial thoughts on this is to document that this is not supported and wait until post .8 to fix.

**Comment by stuclem** [comment] 2016-11-03 14:39
In the current docs I state that you can share an image store between VCHs, as that is how (I think) things used to be. But I noticed the other day that the `VIC/.../images` folder is now created in the folder for the VCH. Previously, it was created at the top level of the specified datastore. As @mreferre  states above, if you specify the same DS folder as the image store for two VCHs then they do end up sharing that folder. 

I have a suspicion that ages ago, in the old folder structure (whereby the image store was always at the root of the DS, or in a specified folder, but never under the VCH folder), I tested sharing the image store and it did work. So this is possibly a bug that has come in since the folder structure changed.

Either way, the doc for `image-store` needs updating...

**Comment by mlh78750** [comment] 2016-11-03 14:49
cc @jzt What's supposed to be working here?

**Comment by fdawg4l** [comment] 2016-11-03 16:46
@mreferre 

> am unsure if the desired behaviour is to have 2+ VCHs share docker images 

They are not meant to be shared. They *can* live in the same datastore or directory structure, but they will be namespaced to keep from conflicting.  The `image-store` parameter you passed also looks malformed, which is why you're seeing the racy behavior you're seeing.

**Comment by fdawg4l** [comment] 2016-11-03 16:47
@mdubya66  Would like to close this.  We have no plans on sharing of image stores in the near future without some offline prep by the vi/container admin via a tool or out of band call to the PL.

ping @hickeng

**Comment by fdawg4l** [comment] 2016-11-03 16:51
@mreferre 

Some things are puzzling in your report.  Even with malformed `image-store` parameters provided on the `vic-admin` CLI, you shouldn't see the weirdness you're seeing.  Can you provide the full console output as well as log bundles from both VCH's?

**Comment by mreferre** [comment] 2016-11-03 16:52
@fdawg4l thanks. What would have been a properly formatted parameter? I thought the format was <datastore_name>/<directory_name>. 

Regardless, I am wondering if there is something we can do (e.g. a check in vic-machine?) to avoid users to do that other than writing in docs "don't do it".

**Comment by mreferre** [comment] 2016-11-03 17:07
@fdawg4l not sure what happened here. I teared down everything and recreated the two VCHs using the same parameter `--image-store sharedstorage/test`. 

This time they are behaving properly:
```
user1@ubuntu:~/vic$ docker -H 192.168.8.57:2375 pull busybox
Using default tag: latest
Pulling from library/busybox
56bec22e3559: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for library/busybox:latest

user1@ubuntu:~/vic$ docker -H 192.168.8.57:2375 images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              e292aa76ad3b        3 weeks ago         1.093 MB

user1@ubuntu:~/vic$ docker -H 192.168.8.56:2375 images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```
From what I can tell I was doing the same thing before. 

If I look at the directory structure it makes slightly more sense now as it has one VIC directory under test but there are two different branches that seem to refer to the two distinct VCHs. See picture.

While I can't see why one would want to do this (Vs creating two separate directories)... at least it doesn't seem to be breaking. Not sure what happened before. 

![vicstorage](https://cloud.githubusercontent.com/assets/4123965/19976520/519b7064-a1f0-11e6-8c50-ed3f697a29dc.png)

**Comment by fdawg4l** [comment] 2016-11-03 17:09
> What would have been a properly formatted parameter

Woops!!  You are right.  That format is totally correct provided the first param before the slash is a datastore.  Apologies.  I thought we used a colon separator between datastore and path, but clearly we do not.  Sorry about that!

**Comment by fdawg4l** [comment] 2016-11-03 17:12
> While I can't see why one would want to do this (Vs creating two separate directories)... at least it doesn't seem to be breaking.

We do this to avoid racing.  If a user create's 2 vchs pass the same image store path (like you did), we want to be able to identify them uniquely on the datastore and prevent racing on one another.  Docker gets away with being able to do bind mounts of image layers to containers because Linux allows 1 to many bind mounts on a given path.  We, however, are binding a block device;  we cannot attach the same block device to many VMs.  It may be possible, but we certainly haven't explored it.

**Comment by fdawg4l** [comment] 2016-11-03 17:14
> This time they are behaving properly:

I'll try your configuration here and see if I can reproduce this.  We have a test that mimicks this but if you saw this issue, it's likely to happen again due to a bug somewhere.  If you can repro, please grab logs from the VCHs and copy the full terminal output so we get more details as to what's happening.

**Comment by fdawg4l** [comment] 2016-11-03 18:25
```
$ ./vic-machine-linux create -f -p "" -t 192.168.8.128 --user root --no-tlsverify --image-store=datastore1/test -name vchone                              

$ ./vic-machine-linux create -f -p "" -t 192.168.8.128 --user root --no-tlsverify --image-store=datastore1/test -name vchtwo
```

```
[root@localhost:/vmfs/volumes/57ffbf41-3f1631b6-6b63-000c29b55dbc/test] find .
.
./kvStores
./VIC
./VIC/564d1630-dabf-0750-4597-68fca2daead1
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images/scratch
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images/scratch/imageMetadata
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images/scratch/scratch-flat.vmdk
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images/scratch/scratch.vmdk
./VIC/564d1630-dabf-0750-4597-68fca2daead1/images/scratch/manifest
./VIC/564dc379-e827-460a-4436-07638769cee8
./VIC/564dc379-e827-460a-4436-07638769cee8/images
./VIC/564dc379-e827-460a-4436-07638769cee8/images/scratch
./VIC/564dc379-e827-460a-4436-07638769cee8/images/scratch/imageMetadata
./VIC/564dc379-e827-460a-4436-07638769cee8/images/scratch/scratch-flat.vmdk
./VIC/564dc379-e827-460a-4436-07638769cee8/images/scratch/scratch.vmdk
./VIC/564dc379-e827-460a-4436-07638769cee8/images/scratch/manifest
```

@jzt looks like the `kvStores` file is not namespaced in this case.  This is likely related to @mreferre's issue since the kvstore will now race.

**Comment by fdawg4l** [comment] 2016-11-03 18:33
Also cc @cgtexmex.

**Comment by mlh78750** [comment] 2016-11-03 18:41
@fdawg4l: good work root causing this. Opened a new issue #3003 to track the race and closing this one. 

Looks like using the same image store is allowed and supported, but that sharing the actual images is not. Can someone confirm that is the case so that we update the documentation correctly?

**Closed by mlh78750** 2016-11-03 18:41 UTC
Labels: area/storage, component/imagec, component/portlayer/storage, kind/bug, kind/user-doc

**Comment by fdawg4l** [comment] 2016-11-03 20:30
@mlh78750 I can confirm that 2 VCHs that use the same image store path are racing on images.  `pull` busybox on both,  rmi on `vchone`, create on `vchtwo`, and suddenly `images` on `vchone` includes the image we removed.

The image cache in the personality is racing due to the kvstore issue (in #3003).  If we fix this, then we'll have the namespaced behavior we want where nothing is shared despite > 1 VCHs sharing image paths.

**Comment by fdawg4l** [comment] 2016-11-03 20:32
@mlh78750 we can discuss it in #3003, but i think we need to get this in `0.7.0`

**Comment by mreferre** [comment] 2016-11-03 20:33
@fdawg4l ah that may explain why I wasn't seeing this when I tried to reproduce? The racing condition may depend on what you are actually doing (and in my attempt I wasn't doing much, my bad). 

@mlh78750 I am not sure we want to rush this into 0.7.0. I am going to call this a corner case. No?

**Comment by mlh78750** [comment] 2016-11-03 20:37
@mreferre Agreed. See discussion in #3003.
