### ISSUE TITLE
docker ps -l did not report the last container created

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6676] opened 2017-11-02 15:47 UTC
From build:  https://ci.vcna.io/vmware/vic/14383

Logs:
[Test-Cases.Group1-Docker-Commands.1-10-Docker-PS-VCH-14383-6860-container-logs.zip](https://github.com/vmware/vic/files/1438382/Test-Cases.Group1-Docker-Commands.1-10-Docker-PS-VCH-14383-6860-container-logs.zip)

The docker ps -l reported the nginx container as being the last one up, but that container clearly started after the redis container:
```
Nov  1 2017 19:59:41.683Z DEBUG Container create - name(adoring_lumiere), containerID(208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670), config(&container.Config{Hostname:"77fbea4a3f5b", Domainname:"", User:"", AttachStdin:false, AttachStdout:true, AttachStderr:true, ExposedPorts:nat.PortSet{"80/tcp":struct {}{}}, Tty:false, OpenStdin:false, StdinOnce:false, Env:[]string{"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.13.0-1~stretch", "NJS_VERSION=1.13.0.0.1.10-1~stretch"}, Cmd:strslice.StrSlice{"nginx", "-g", "daemon off;"}, Healthcheck:(*container.HealthConfig)(nil), ArgsEscaped:true, Image:"sha256:2d6bc6ab898e27956758f13e390eb3076d215d12c920213b94a3eddac1ceaf66", Volumes:map[string]struct {}{}, WorkingDir:"",
```

```
Nov  1 2017 19:59:43.483Z DEBUG Container create - name(cocky_beaver), containerID(cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c), config(&container.Config{Hostname:"", Domainname:"", User:"", AttachStdin:false, AttachStdout:false, AttachStderr:false, ExposedPorts:nat.PortSet{"6379/tcp":struct {}{}}, Tty:false, OpenStdin:false, StdinOnce:false, Env:[]string{"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "REDIS_VERSION=4.0.2", "REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-4.0.2.tar.gz",
```

And according to all the logs I can see, the redis container did not die, so for some reason docker ps -l just reported it inaccurately...

**Comment by anchal-agrawal** [comment] 2017-11-07 04:36
Also seen in https://ci.vcna.io/vmware/vic/14533.

**Comment by mhagen-vmware** [comment] 2017-11-08 15:19
Here too:
https://ci.vcna.io/vmware/vic/14560

**Comment by anchal-agrawal** [comment] 2017-11-09 22:38
This comment refers to the logs from the build in the parent comment.

redis container (expected output): `cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c`
nginx container (actual output): `208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670`

For the `ps -l` call:

**Personality**
```
Nov  1 2017 19:59:56.975Z DEBUG Calling GET /v1.25/containers/json?limit=1
Nov  1 2017 19:59:56.975Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).Containers:1503] ListOptions &types.ContainerListOptions{Quiet:false, Size:false, All:false, Latest:false, Since:"", Before:"", Limit:1, Filters:filters.Args{fields:map[string]map[string]bool{}}}
Nov  1 2017 19:59:57.095Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/convert.State:32]
Nov  1 2017 19:59:57.095Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/convert.State:32] [17.948µs] 
Nov  1 2017 19:59:57.096Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:330]
Nov  1 2017 19:59:57.096Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:330] [12.166µs] 
Nov  1 2017 19:59:57.096Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/convert.State:32]
Nov  1 2017 19:59:57.096Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/convert.State:32] [6.448µs] 
Nov  1 2017 19:59:57.096Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).Containers:1503] [120.464769ms] ListOptions &types.ContainerListOptions{Quiet:false, Size:false, All:false, Latest:false, Since:"", Before:"", Limit:1, Filters:filters.Args{fields:map[string]map[string]bool{}}}
```

The containers aren't logged, so there's no insight as to which container(s) were processed and/or sent back to the docker client. We do see though that since `limit=1` in the GET request, only two containers are processed from the payload returned by the portlayer (there are two calls to `convert.State`, and `filter.IncludeContainer()` returns when called on the second container here): https://github.com/vmware/vic/blob/9981ccb228775cbab754995d2c1a60b518044fa7/lib/apiservers/engine/backends/filter/container.go#L63

So only one container was sent back to the docker client, but not sure which one.


**Portlayer**

The logs show that both the nginx and redis containers were found and sent back to the persona.
```
Nov  1 2017 19:59:56.976Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:300]
...
# nginx container 
Nov  1 2017 19:59:57.012Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:515] 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670
Nov  1 2017 19:59:57.012Z DEBUG op=300.1456 (delta:2.485µs): [NewOperation] op=300.1456 (delta:1.245µs) [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:521]
Nov  1 2017 19:59:57.012Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:121] 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670
Nov  1 2017 19:59:57.012Z DEBUG Update: for 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670, refreshing from change version 2017-11-01T19:59:41.864847Z
Nov  1 2017 19:59:57.012Z DEBUG get vm properties [config runtime] of vm VirtualMachine:32766
Nov  1 2017 19:59:57.012Z DEBUG properties: [config runtime summary.runtime.connectionState]
Nov  1 2017 19:59:57.034Z DEBUG Update: for 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670, change version 2017-11-01T19:59:41.864847Z, extraconfig id: 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670
Nov  1 2017 19:59:57.034Z DEBUG [BEGIN] [github.com/vmware/vic/lib/migration.migrateConfig:77] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Nov  1 2017 19:59:57.034Z DEBUG [ END ] [github.com/vmware/vic/lib/migration.migrateConfig:77] [41.687µs] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Nov  1 2017 19:59:57.034Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:121] [22.137962ms] 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670
Nov  1 2017 19:59:57.034Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:515] [22.181647ms] 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670
...
# redis container
Nov  1 2017 19:59:57.056Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:515] cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c
Nov  1 2017 19:59:57.056Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo:515] [7.399µs] cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c
...
Nov  1 2017 19:59:57.095Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerListHandler:300] [119.102281ms] 
```

The container payload returned to the persona is reverse-sorted on the container create time: https://github.com/vmware/vic/blob/9981ccb228775cbab754995d2c1a60b518044fa7/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go#L320

The container create time is set in the portlayer right before the `Handle.Create` log statement:

```
# nginx container
Nov  1 2017 19:59:41.030Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Create:292] Handle.Create
Nov  1 2017 19:59:41.049Z DEBUG id: 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670, name: adoring_lumiere, cpu: 2, mem: 2048, parent: 9d4eb1cbfcf841b83a8ef9c5d6bbef3b3255c34346153d6b669341e7ff028bc3, os: [datastore1] VCH-14383-6860/V1.2.0-RC1-14383-A3D7A5F-bootstrap.iso, path: [datastore1] 208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670/208dcc9b7e61183b71f4e07200944e1f80356bace0a30968d5a375ba79721670.vmx
```

```
# redis container
Nov  1 2017 19:59:41.835Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Create:292] Handle.Create
Nov  1 2017 19:59:41.854Z DEBUG id: cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c, name: cocky_beaver, cpu: 2, mem: 2048, parent: b5f46bdcac82c42dbcd21d148d51f2e65f23acea5455fcb972cde59eabfe0f88, os: [datastore1] VCH-14383-6860/V1.2.0-RC1-14383-A3D7A5F-bootstrap.iso, path: [datastore1] cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c/cc30ab177810265b26871e8152a2795557f4632b047c190194410206222bdd6c.vmx
```

Based on these timestamps, the redis container should have been returned by the `ps -l` call.

**Comment by anchal-agrawal** [comment] 2017-11-10 19:25
Follow-up of the above comment:

I suspect this is because we store the create time in seconds:

https://github.com/vmware/vic/blob/9981ccb228775cbab754995d2c1a60b518044fa7/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go#L108

* The `(t Time) Unix()` func uses only the seconds field in the `Time` object and ignores the nanoseconds field. As seen in the above comment, the create timestamps for both containers (set in the portlayer) are the same second (`19:59:41.030Z` and `19:59:41.835Z`). Note: those aren't the exact timestamps saved in the config since we don't log the timestamps when they are stored, but those are from the closest log statements.
* The built-in `Sort` function isn't stable w.r.t. the original order of equal elements (see https://golang.org/pkg/sort/#Sort and https://golang.org/src/sort/sort.go#L365).

This also explains why, in build https://ci.vcna.io/vmware/vic/14418, one of the tests that invoke `ps -l` (`Docker ps last container`) passed, and the other (`Docker ps last container with size`) failed.

The fix for this would be to store timestamps with nanoseconds (swap the `Unix()` call with `UnixNano()` above) and make other changes to ensure that time translation works as intended in other places `docker ps`, `docker inspect`, etc.

**Comment by hickeng** [comment] 2017-11-14 03:18
https://ci.vcna.io/vmware/vic/14664

**Comment by mhagen-vmware** [comment] 2017-11-14 15:21
https://ci.vcna.io/vmware/vic/14666

**Comment by anchal-agrawal** [comment] 2017-11-15 03:07
https://ci.vcna.io/vmware/vic/14672

**Closed** 2017-11-20 19:25 UTC
Labels: kind/bug, priority/high, team/container
