### ISSUE TITLE
VCH delete fails leaving vApps around which cannot be deleted at all

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#6218] opened 2017-09-06 11:32 UTC
Build: vic-v1.2.0-rc2-b53a69aa.ova

![image](https://user-images.githubusercontent.com/25006749/30109270-63b6848a-9323-11e7-8142-37cf2ba9bc2c.png)

Screen shot uploaded

Live testbed available: VCSA : 10.197.37.191 - root/Admin!23

Attempt to delete VCH failed leaving vApps. These vApps cannot be deleted through UI.

**Comment by lgayatri** [comment] 2017-09-06 11:32
OVA : 10.197.37.132 - root/Admin!23

**Comment by emlin** [comment] 2017-09-06 15:09
Had a basic search for vpxd log, there are VM reconfiguration log, but no information about vm destroy.
Could you please attach the vic-machine delete log? It would be nicer if you still have the vic-machine log for all other operations.

**Comment by lgayatri** [comment] 2017-09-06 16:43
[vic-machine.zip](https://github.com/vmware/vic/files/1281908/vic-machine.zip)
vic-machine log attached.

Any workaround to get rid of these?

**Comment by lgayatri** [comment] 2017-09-06 17:22
Found the workaround. The containers should be unregistered and then the vApp should be deleted from Web Client.

**Comment by dougm** [comment] 2017-09-06 17:38
Sounds like we need to also disable Destroy_Task for the vApp itself.  Delete via UI removed the vApp/ResourcePool, but not the VMs (since Destroy is disabled).  Followed by an attempt to removing using `vic-machine delete`, which fails because the vApp/ResourcePool has been removed.

**Comment by emlin** [comment] 2017-09-06 18:20
@lgayatri the attached log file just contains the log after the first time you delete VCH failed.
So the log only shows that left over vApp without VCH cannot be deleted, but shows nothing about why there is container vm left in the vApp, but without VCH VM available. In theory, VCH VM should be deleted in the last step before vApp removal.

@dougm Cause the left over VM is container VM, not VCH VM. vic-machine cannot remove that vApp anymore. So basically, disable vApp destroy does not help this situation.

The error like this `Sep  6 2017 07:18:43.100-04:00 ERROR Failed to get VCH resource pool "/Datacenter/host/Cluster/Resources/U-VIC-00017": resource pool '/Datacenter/host/Cluster/Resources/U-VIC-00017' not found`, should just because script is trying to remove non-exist VCH, is that right? @lgayatri 

@lgayatri do you still have the old vic-machine log, with first time vic-machine delete failure? If not, please attach that next time you reproduced this issue.
One more question is that, are you still running docker commands to create new container while you're running vic-machine delete?

**Comment by dougm** [comment] 2017-09-06 20:37
@emlin ok I was guessing since the steps to reproduce were not included.  Subject says "VCH delete fails", but doesn't say if it was done via vic-machine or the UI.

**Comment by emlin** [comment] 2017-09-06 21:50
I see your point. But as we already disabled VM destroy from UI, user should not be able to delete VCH VM from UI.
I'm curious what happens before this

**Comment by matthewavery** [comment] 2017-10-27 16:05
I am marking this as a 5 as it seems investigative.

**Comment by cgtexmex** [comment] 2017-11-08 20:53
Closing this as vApp deployments have been problematic from a concurrency perspective and the ability to deploy via vApp is going to be removed.

**Closed by cgtexmex** 2017-11-08 20:53 UTC
Labels: priority/low, team/foundation
