### ISSUE TITLE
Container that's not fully started cannot be stopped

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1541] opened 2016-07-17 00:35 UTC
This environment had a misconfiguration (a mapped network that did not have DHCP and cat was connect to it) which meant that the container couldn't start cleanly because the network configuration couldn't be applied. This means that the container process has not been launched and seems to inhibit us from stopping the container despite ps showing it running.

```
vagrant@devbox:~/vic$ docker -H 192.168.78.216:2376 --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cdb29a811639        busybox             "sh"                7 days ago          Running                                 cat
vagrant@devbox:~/vic$ docker -H 192.168.78.216:2376 --tls stop cat
Error response from daemon: container cdb29a811639fd5061f55cd66412573cd929ef9504b3a4333b7ee4360ed8bf07 not found
vagrant@devbox:~/vic$ docker -H 192.168.78.216:2376 --tls stop cat
```

**Comment by mdubya66** [comment] 2016-07-19 14:10
@hickeng needs a clear owner. marking for GA for now

**Comment by cgtexmex** [comment] 2016-09-15 16:05
dupe of #2271

**Closed by cgtexmex** 2016-09-15 16:05 UTC
Labels: kind/bug, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:33
This is fixed. Removing kind/note.
