### ISSUE TITLE
Nightly 21-1: Default registry name changed

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#5902] opened 2017-08-02 22:55 UTC
8/1, build 12824

The Whitelist test fails because the PR to add dynamic config changed the default docker hub registry name in the code but not in the robot scripts.

Formerly, it looked for registry-1.docker.io.
The PR changed the code to look for registry.hub.docker.com.

This is a simple fix, but I do not know why the hub value was changed.  I have never seen registry.hub.docker.com in any of vanilla docker's info output.  Is this change needed for Admiral or was it needed for the dynamic config?
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1195496/21-1-Whitelist.zip)

**Comment by sflxn** [comment] 2017-08-02 22:58
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1195495/21-1-Whitelist.zip)

**Comment by sflxn** [comment] 2017-08-09 18:58
Still occurring 8/7, build 12978

**Comment by mdharamadas1** [comment] 2017-08-09 21:13
@gigawhitlocks this looks dupe of #5982

**Comment by sgairo** [comment] 2017-08-09 21:16
@mdharamadas1 you are right, they are connected. 5982 is the PR to fix this issue.

**Comment by gigawhitlocks** [comment] 2017-08-11 16:37
I fixed dis

**Comment by gigawhitlocks** [comment] 2017-08-11 16:37
aww yee

**Closed** 2017-08-11 16:37 UTC
Labels: component/test/nightly, priority/high, status/has-integration-test, status/needs-attention
