### ISSUE TITLE
Vic-machine create fails, but VCH is still created

### ISSUE THREAD

**Issue by kjplatz** [vmware/vic#1452] opened 2016-07-12 20:59 UTC
While attempting to deploy to skinner.eng.vmware.com, I received the following error sequence:

**Expected behavior:**
Expect the command to either succeed or fail in the same manner, since the VCH should not have been created since the first execution of the command failed.

**Actual behavior**
$ sudo ./vic-machine-linux create --target skinner.eng.vmware.com --user root --image-datastore Datastore --password _<omitted>_ --bridge-network vch-test --name mavery-vch-1 --compute-resource /Datacenter/host/Austin/Resources/mavery --volume-store=test-store:Datastore/test-volumestore --volume-store=default:Datastore/default-store-matt

INFO[2016-07-12T15:45:55-05:00] ### Installing VCH ####                      
INFO[2016-07-12T15:45:55-05:00] Generating certificate/key pair - private key in ./mavery-vch-1-key.pem 
INFO[2016-07-12T15:45:56-05:00] Validating supplied configuration            
INFO[2016-07-12T15:45:56-05:00] Firewall status: DISABLED on /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:45:56-05:00] Firewall configuration OK on hosts:          
INFO[2016-07-12T15:45:56-05:00]   /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:45:56-05:00] License check OK on hosts:                   
INFO[2016-07-12T15:45:56-05:00]   /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:45:56-05:00] DRS check OK on:                             
INFO[2016-07-12T15:45:56-05:00]   /Datacenter/host/Austin/Resources/mavery   
INFO[2016-07-12T15:45:57-05:00] Creating Resource Pool mavery-vch-1          
INFO[2016-07-12T15:45:57-05:00] Datastore path is [Datastore] test-volumestore 
INFO[2016-07-12T15:45:57-05:00] Datastore path is [Datastore] default-store-matt 
INFO[2016-07-12T15:45:57-05:00] Creating appliance on target                 
INFO[2016-07-12T15:45:57-05:00] Network role client is sharing NIC with external 
INFO[2016-07-12T15:45:57-05:00] Network role management is sharing NIC with external 
INFO[2016-07-12T15:45:59-05:00] Uploading images for container               
INFO[2016-07-12T15:45:59-05:00]         bootstrap.iso                               
INFO[2016-07-12T15:45:59-05:00]         appliance.iso                               
ERRO[2016-07-12T15:45:59-05:00]                 Upload failed for bootstrap.iso, 401 Unauthorized 
ERRO[2016-07-12T15:45:59-05:00]                 Upload failed for appliance.iso, Put https://patty.eng.vmware.com/folder/mavery-vch-1/appliance.iso?dsName=Datastore: write tcp 127.0.0.1:50296->127.0.1.2:443: write: broken pipe 
INFO[2016-07-12T15:45:59-05:00] Collecting 57d35220-06d2-4004-8aba-0e7f8b52eef7 vpxd.log 
--------------------
vic-machine-linux failed: Uploading images failed with 401 Unauthorized. Exiting...

$ sudo ./vic-machine-linux create --target skinner.eng.vmware.com --user root --image-datastore Datastore --password _<omitted>_ --bridge-network vch-test --name mavery-vch-1 --compute-resource /Datacenter/host/Austin/Resources/mavery --volume-store=test-store:Datastore/test-volumestore --volume-store=default:Datastore/default-store-matt
INFO[2016-07-12T15:46:20-05:00] ### Installing VCH ####                      
INFO[2016-07-12T15:46:20-05:00] Generating certificate/key pair - private key in ./mavery-vch-1-key.pem 
INFO[2016-07-12T15:46:21-05:00] Validating supplied configuration            
INFO[2016-07-12T15:46:21-05:00] Firewall status: DISABLED on /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:46:21-05:00] Firewall configuration OK on hosts:          
INFO[2016-07-12T15:46:21-05:00]   /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:46:21-05:00] License check OK on hosts:                   
INFO[2016-07-12T15:46:21-05:00]   /Datacenter/host/Austin/patty.eng.vmware.com 
INFO[2016-07-12T15:46:21-05:00] DRS check OK on:                             
INFO[2016-07-12T15:46:21-05:00]   /Datacenter/host/Austin/Resources/mavery   
INFO[2016-07-12T15:46:22-05:00] Collecting 57d35220-06d2-4004-8aba-0e7f8b52eef7 vpxd.log 
--------------------

**Comment by mdubya66** [comment] 2016-07-19 14:22
Assigning to @emlin for triage. Please move to backlog if you don't feel this is an issue for Onsite and put it in the GA Milestone.

**Comment by emlin** [comment] 2016-07-19 20:51
@kjplatz Our approach is to keep the existing result there, instead of clean up anything we created for a failed operation.
I think there might have different issues happen during vch deployment, and lots of them are vSphere env related, for example, no enough permission in your case, network mis-configuration, network is unreachable, or wrong resource usage, etc.
Even after the appliance VM is successfully created, the services inside might not work correctly.
To help user or our support better triage issue, leaving the failed env is a key point. So we can touch it instead of rely on the left error message only.
But if user doesn't care about this failure, or after the error triage, user doesn't need this env anymore, it can be easily deleted by vic-machine delete.
Btw, if vic-machine delete works here?

**Comment by emlin** [comment] 2016-07-20 21:04
tried to install VCH failed, and then run vic-machine delete, everything is removed clearly. So close bug as work by design.

**Closed** 2016-07-20 21:05 UTC
Labels: component/vic-machine, kind/bug
