### ISSUE TITLE
Server error from portlayer: unable to wait for process launch status: context deadline exceeded

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2472] opened 2016-09-26 20:29 UTC
Seen in:
https://ci.vmware.run/vmware/vic/5139

[integration_logs_5139_6ee9c6b83d2fe921fc6f0eaa72310b3a53414f1b.zip](https://github.com/vmware/vic/files/494051/integration_logs_5139_6ee9c6b83d2fe921fc6f0eaa72310b3a53414f1b.zip)

**Comment by mhagen-vmware** [comment] 2016-09-27 13:54
https://ci.vmware.run/vmware/vic/5167

[integration_logs_5167_edd92e5e44bd4870bb6c5e031e9164f17803c09a.zip](https://github.com/vmware/vic/files/495678/integration_logs_5167_edd92e5e44bd4870bb6c5e031e9164f17803c09a.zip)

**Comment by hmahmood** [comment] 2016-09-27 14:41
Seems to be stuck in tether [MountLabel](https://github.com/vmware/vic/blob/master/lib/tether/ops_linux.go#L584) call, and port layer times out waiting for "started" property to change in guestinfo.
```
...
time="2016-09-26T19:19:04Z" level=debug msg="&{lines:[nameserver 172.16.0.1 options timeout:15 options attempts:5] i:0}" 
time="2016-09-26T19:19:04Z" level=debug msg="writing \"nameserver 172.16.0.1\\n\" to /etc/resolv.conf" 
time="2016-09-26T19:19:04Z" level=debug msg="writing \"options timeout:15\\n\" to /etc/resolv.conf" 
time="2016-09-26T19:19:04Z" level=debug msg="writing \"options attempts:5\\n\" to /etc/resolv.conf" 
time="2016-09-26T19:19:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply:411] [94.103093ms] applying endpoint configuration for bridge" 
time="2016-09-26T19:19:04Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).MountLabel:585] Mounting 1a4beb04b7f42d3d on /var/log" ```

**Comment by mhagen-vmware** [comment] 2016-09-27 16:38
Also,
https://ci.vmware.run/vmware/vic/5175

This time it was embedded in our volume create verification step.

[integration_logs_5175_5cf377667b750afd432d79ad40abd95ea2c5506f.zip](https://github.com/vmware/vic/files/496124/integration_logs_5175_5cf377667b750afd432d79ad40abd95ea2c5506f.zip)

```
time="2016-09-27T15:26:09Z" level=error msg="Handler for POST /v1.21/containers/207a1ad56a8dc64d5755b5f1fce36509b7740fb9fc4df175ceb9326921d53438/start returned error: Server error from portlayer: unable to wait for process launch status: context deadline exceeded" 
```

**Comment by hickeng** [comment] 2016-10-09 15:55
Confirmed that 5175 has the same output in tether:
```
time="2016-09-27T15:21:36Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply:411] [83.79946ms] applying endpoint configuration for bridge" 
time="2016-09-27T15:21:36Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).MountLabel:585] Mounting 098f6bcd4621d373 on /mydata" 
```

Closing as dup of #2485 as that's got some fix approach discussion in it.

**Closed by hickeng** 2016-10-09 15:55 UTC
Labels: kind/bug, kind/bug/p0
