### ISSUE TITLE
Nightly 6.5 - 5-6-1-VSAN-Simple - 2018-03-16 - Datastore not empty after cleanup

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#7540] opened 2018-03-19 14:14 UTC
**VIC version:**

V1.4.0-DEV-17572-42375AA

**Deployment details:**

Nightly 6.5

**Logs:**

```
Running command 'govc datastore.vsan.dom.ls -ds vsanDatastore -l -o 2>&1'.
${out} = 24bbab5a-7481-2f8a-f783-02004ed4e2fe 
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-02-36-47.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-19 17:03
**VIC version:**

v1.4.0-dev-17605-6144b31

**Deployment details:**

Nightly 6.5

**Logs:**

```
Running command 'govc datastore.vsan.dom.ls -ds vsanDatastore -l -o 2>&1'.
${out} = f93eae5a-89f7-2e7c-f262-02002e6d2036 
```
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-18-00-55-35.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-27 15:28
**VIC version:**

1.4.0-dev-17719-9326347

**Deployment details:**

Nightly 6.5 2018-03-27
5-6-2-VSAN-Complex

**Logs:**

```
Running command 'govc datastore.vsan.dom.ls -ds "vsanDatastore" -l -o 2>&1'.
${out} = 2d1cba5a-c6c6-ab70-5c79-020003cafcc3 
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-27-01-22-38.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-27 20:52
Also seen in 6.7 run https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-27-07-01-44.zip?authuser=1

**Comment by anchal-agrawal** [comment] 2018-03-28 19:44
Looks like this issue needs some investigation as to what the root cause is. I recall some issues regarding leaking DOM objects (https://github.com/vmware/vic/issues?q=is%3Aissue+dom+objects+is%3Aclosed). It's not clear here whether these objects are related to the VCH.

**Comment by rajanashok** [comment] 2018-03-28 23:52
Seen again on 6.7
 https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-28-04-59-58.zip?authuser=1

**Comment by rajanashok** [comment] 2018-04-02 18:55
Seen again on 03/30 04/02, 6.5 run
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-02-00-34-14.zip?authuser=1
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-30-23-53-59.zip?authuser=1

**Comment by AngieCris** [comment] 2018-04-02 19:07
@hickeng 
I remember seeing this log message `Image store parent directory not empty, leaving in place` in vic-machine processes that successfully removed all datastore files as well. The `deleteImages` function empties `/VIC` and `/kvStores` directory, and the top level datastore folder still contains the vmx file, tether debug and all that.
One of my test run of listing leftover children files gives:
```
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Image store parent directory not empty, leaving in place.
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Listing all children...
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039-17becdc4.vswp
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.vmx
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/vmx-VCH-0-7039-398380484-1.vswp
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.vmxf
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.vmx~
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/vic-machine_2018-02-28T22:03:25Z_create_91.1.log
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.vmsd
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.nvram
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/tether.debug
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039.vmx.lck
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/VCH-0-7039-7e17aae2.hlog
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/vmware.log
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/V1.4.0-DEV-0-C6D5F72-appliance.iso
Feb 28 2018 22:06:12.341Z DEBUG op=163.1: Child: [datastore1] VCH-0-7039/V1.4.0-DEV-0-C6D5F72-bootstrap.iso
Feb 28 2018 22:06:12.341Z DEBUG [ END ] op=163.1 [vic/lib/install/management.(*Dispatcher).deleteImages:40] [10.618861383s] 
```
And those files are subsequently cleaned up by the last `deleteDatastoreFiles` function after VM cleanup. It doesn't look like that those files block imagestore delete since top level directory delete happens at a later step?

**Comment by mhagen-vmware** [comment] 2018-04-10 23:14
Not a component/test issue, the only way that this leaks is if vic-machine delete fails to clean up the VSAN datastore as expected. I took this issue 2 weeks ago in order to triage it a bit further, but not to necessarily change anything in the test.

**Comment by mhagen-vmware** [comment] 2018-04-11 14:06
I started going down this from the top unfortunately and basically did the work that @hickeng already had done at the bottom, I am not sure why this was assigned to me to triage further. He has already clearly gone through it and identified that we are leaking the root VCH folder (because apparently it is not empty) and he has added more logging to help us triage. We now need to wait for a repro.

**Comment by rajanashok** [comment] 2018-04-11 16:12
Seen again on 6.7 Nightlies 4/10.
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-10-14-42-27.zip?authuser=1

**Comment by hickeng** [comment] 2018-04-17 20:11
Can we add a `Wait For Keyword To Succeed` to the check so we can determine if this is a VSAN eventual consistency quirk.

**Comment by rogeliosanchez** [comment] 2018-04-19 19:36
Seen in Nightly 6.7 2018-04-17

VIC version
v1.4.0-rc1-0-86968ff

5-6-1-VSAN-Simple
govc datastore.vsan.dom.ls -ds vsanDatastore -l -o should be empty

![screen shot 2018-04-19 at 2 36 08 pm](https://user-images.githubusercontent.com/26554503/39014118-0bf5fd3a-43df-11e8-8884-b619f63e24f4.png)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-17-08-04-42.zip?authuser=1

**Comment by rogeliosanchez** [comment] 2018-04-19 22:55
Seen in Nightly 6.5 - 2018-040-17

VIC version:
v1.5.0-dev-18481-023de08

5-6-1-VSAN-Simple
govc datastore.vsan.dom.ls -ds vsanDatastore -l -o should be empty

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-17-23-47-16.zip?authuser=1

**Closed** 2018-04-20 18:25 UTC
Labels: kind/bug, kind/nightly-blocker, priority/p0, team/foundation
