### ISSUE TITLE
port layer crash during attach error path

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1130] opened 2016-06-17 08:26 UTC
[container-logs.tar.gz](https://github.com/vmware/vic/files/320044/container-logs.tar.gz)

The port layer crashed during the workflow described in #1129 - the error message about deadline exceeded is the last thing we see from it.

**Comment by hickeng** [comment] 2016-06-21 17:02
This must be triaged and assessed in sufficient time to fix for TP3 if critical.

**Comment by mdubya66** [comment] 2016-06-30 14:31
re-assigning to @fdawg4l for initial investigation.

**Comment by fdawg4l** [comment] 2016-07-06 21:54
```
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:48Z" level=debug msg="Found connection for 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b: 0xc82051eb00" 
time="2016-06-17T07:57:53Z" level=info msg="Attempting to get ssh session for container 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b stdin" 
time="2016-06-17T07:59:15Z" level=info msg="Finished copying stdout stream for container 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b" 
time="2016-06-17T07:59:15Z" level=info msg="Finished copying stderr stream for container 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b" 
time="2016-06-17T07:59:15Z" level=info msg="Error copying stdin for container 0111ffa9d711542ef5a146b6adc8dd4e49a097d4b63f934dc372d02df453094b" 
time="2016-06-17T07:59:15Z" level=info msg="Done copying stdin" 
time="2016-06-17T08:03:29Z" level=error msg="id:4dbf6a9527ad0e771179dae0b65f4d5fd9b37f0989a57a577b53041a4ebe6672: context deadline exceeded"
```

**Comment by fdawg4l** [comment] 2016-07-06 21:56
We likely didn't see the cause of the crash due to #1237

**Comment by fdawg4l** [comment] 2016-07-06 22:01
The last message is due to the connection no longer being available.  This likely isnt the routine that PANICked since 4s have elapsed since the error was reported.

```
 68 // Returns a connection corresponding to the specified ID. If the connection doesn't exist
 69 // the method will wait for the specified timeout, returning when the connection is created
 70 // or the timeout expires, whichever occurs first
 71 func (c *Connector) Get(ctx context.Context, id string, timeout time.Duration) (SessionInteraction, error) {
...
107 »···select {
108 »···case client := <-result:
109 »···»···log.Debugf("Found connection for %s: %p", id, client)
110 »···»···return client.spty, nil
111 »···case <-ctx.Done():
112 »···»···err := fmt.Errorf("id:%s: %s", id, ctx.Err())
113 »···»···log.Error(err)                                                         // <---  printed here
114 »···»···// wake up the result gofunc before returning
115 »···»···c.cond.Broadcast()
116 »···»···return nil, err
117 »···}
118 }
```

**Comment by fdawg4l** [comment] 2016-07-06 22:40
Welp, I found *a* crash.  I don't know if it's the one we're looking for :smiley:.

**Comment by fdawg4l** [comment] 2016-07-06 22:43
```
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/spec.(*VirtualMachineConfigSpec).ID] [208ns] 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/spec.(*VirtualMachineConfigSpec).AddVirtualFileSerialPort] [39.233µs] 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Handle).Create] [9.006763ms] Handle.Create" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CreateHandler] [22.595084ms] Containers.CreateHandler" 
time="2016-07-06T21:18:23Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer] ScopesAddContainer" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer] [885.705µs] ScopesAddContainer" 
time="2016-07-06T21:18:23Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler] Containers.CommitHandler" 
time="2016-07-06T21:18:23Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] Committing handle" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] [177.818597ms] Committing handle" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler] [180.078747ms] Containers.CommitHandler" 
time="2016-07-06T21:20:54Z" level=error msg="id:6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: context deadline exceeded" 
2016/07/06 21:20:54 http: panic serving 127.0.0.1:34874: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc820906000)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x131ce20, 0xc82000c080)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStderrNotFound).WriteResponse(0xc82001a020, 0x7f2fbd0741b0, 0xc820315ee0, 0x0, 0x0)
        /go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stderr_responses.go:82 +0xb8
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc82077f700, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0, 0xc820868ad0, 0x1, 0x1, 0xc820526a80, 0x1417240, 0xc82001a020)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x6a8
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStderr).ServeHTTP(0xc82081a900, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stderr.go:53 +0x2f0
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8202d4040, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x108
net/http.HandlerFunc.ServeHTTP(0xc8209f3480, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x1d7
net/http.HandlerFunc.ServeHTTP(0xc82023ff20, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820a45580, 0x7f2fbd0741b0, 0xc820315ee0, 0xc8205269a0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820906000)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
time="2016-07-06T21:20:54Z" level=error msg="id:6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: context deadline exceeded" 
2016/07/06 21:20:54 http: panic serving 127.0.0.1:34906: runtime error: invalid memory address or nil pointer dereference
goroutine 136 [running]:
net/http.(*conn).serve.func1(0xc820943f00)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x131ce20, 0xc82000c080)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStdoutNotFound).WriteResponse(0xc82001a028, 0x7f2fbd0741b0, 0xc8201828f0, 0x0, 0x0)
        /go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stdout_responses.go:82 +0xb8
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc82077f700, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40, 0xc820869e70, 0x1, 0x1, 0xc820526d20, 0x1417340, 0xc82001a028)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x6a8
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction.(*ContainerGetStdout).ServeHTTP(0xc82081a920, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/interaction/container_get_stdout.go:53 +0x2f0
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc8202d4040, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x108
net/http.HandlerFunc.ServeHTTP(0xc8209f3480, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x1d7
net/http.HandlerFunc.ServeHTTP(0xc82023ff20, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820a45580, 0x7f2fbd0741b0, 0xc8201828f0, 0xc820526c40)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820943f00)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
```

Steps to repro

```
fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker -H 192.168.8.196:2376 --tls create -i -t busybox /bin/dmesg                                                                                      
9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker start -a 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b
Error: No such container: 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker start -a 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b
Error: No such container: 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker start -a 9c34
Error: No such container: 9c34

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ govc ls vm
/ha-datacenter/vm/docker-appliance
/ha-datacenter/vm/9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b


fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker start -a 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b                                                                        
Error: No such container: 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b

fahmed@hasselhoff: ~/src/vic/src/github.com/vmware/vic/bin$ docker start 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b                                                                           
Error response from daemon: No such container: 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b
Error: failed to start containers: 9c3406740257900dcfe8b7fb55812d3b5e22580792d67a275097595e3d8c746b
```

**Comment by fdawg4l** [comment] 2016-07-06 22:46
It was after the last invocation of `start` that the PLS went belly up.

**Comment by fdawg4l** [comment] 2016-07-06 23:22
```
time="2016-07-06T21:10:53Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-07-06T21:10:54Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [178.908965ms] ContainerCreate" 
time="2016-07-06T21:10:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] ContainerAttach" 
time="2016-07-06T21:10:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] ContainerStart" 
time="2016-07-06T21:11:09Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart] [15.345628368s] ContainerStart" 
time="2016-07-06T21:13:34Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:34Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:34Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:35Z" level=error msg="Attach stream has stdinOnce set.  VIC does not yet support this." 
time="2016-07-06T21:13:39Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:39Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:39Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:39Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:39Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:13:40Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:16:43Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/kill returned error: Cannot kill container 6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77: vSphere Integrated Containers does not implement container.ContainerKill" 
time="2016-07-06T21:18:23Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] ContainerCreate" 
time="2016-07-06T21:18:23Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate] [215.027953ms] ContainerCreate" 
time="2016-07-06T21:20:54Z" level=info msg="Detected EOF from swagger, detaching all streams..." 
time="2016-07-06T21:20:54Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach] [10m0.011856901s] ContainerAttach" 
time="2016-07-06T21:20:54Z" level=error msg="Handler for POST /v1.23/containers/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/attach returned error: Unknown error from the interaction port layer: Get http://127.0.0.1:8080/interaction/6e6af6cdada4bc4dd223e48d4e35746b0f5c0f337cdd7269857c3ac8afa44a77/stderr: EOF" 
```

**Comment by fdawg4l** [comment] 2016-07-07 17:08
cc @sflxn

**Comment by fdawg4l** [comment] 2016-07-07 23:39
Very weird.  After pulling and rebasing from Master, I can't repro.  Very very strange.

**Comment by fdawg4l** [comment] 2016-07-08 00:06
ah. Panic just takes a while to appear in the log file.  It's very much still there.

**Comment by corrieb** [comment] 2016-07-11 17:57
Review with George. This is a must-have for TP3

**Closed** 2016-07-12 05:15 UTC
Labels: component/portlayer/interaction, kind/bug, status/needs-attention
