### ISSUE TITLE
image id incorrect for image pulled from private registry

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#3163] opened 2016-11-14 18:15 UTC
The image id that is persisted to a private registry is not calculated correctly via vic.

1. build a docker image via standard docker
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
192.168.175.142:5000/test   latest              818ab186abf8        7 days ago          1.093 MB
```
2. push custom image to registry: `docker push 192.168.175.142:5000/test`
3. pull custom image via another standard docker client: `docker pull 192.168.175.142:5000/test`
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
192.168.175.142:5000/test   latest              818ab186abf8        7 days ago          1.093 MB
```
4. pull custom image via vic: `docker pull 192.168.175.142:5000/test`
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
192.168.175.142:5000/test   latest              8e49b5ac53be        7 days ago          1.093 MB
```

Notice the image ids are the same for the docker host that created as well as the docker host who pulled, yet the vic image id is different.  I would expect these to be the same.

The registry used was a local insecure registry (image: registry:2) hosted via a standard docker host.

**Comment by jzt** [comment] 2016-11-14 19:41
FYI, this is true for all images, not just ones tagged for private registries. This is because docker >= 1.12 omits the diff ID from the image metadata (although it keeps the corresponding history), resulting in a different image ID.

**Comment by cgtexmex** [comment] 2016-11-14 19:47
@jzt yeah...after I created the issue I realized that....do we have a general issue open for that? or should we use this issue to track?

**Comment by jzt** [comment] 2016-11-14 20:03
@cgtexmex I searched but couldn't find one. Closest one I found was the one being caused by removing and re-pulling an image, that was fixed here:  https://github.com/vmware/vic/pull/2834

**Comment by mdubya66** [comment] 2016-11-14 22:19
i'm gonna backlog this.

**Comment by jzt** [comment] 2017-01-17 17:53
Closing in favor of the encompassing general issue #3602

**Closed by jzt** 2017-01-17 17:53 UTC
Labels: area/docker, component/imagec, kind/bug
