### ISSUE TITLE
vicadmin panic with second panic after being relaunched

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6219] opened 2017-09-06 13:11 UTC
Observed in build https://ci.vcna.io/vmware/vic/12176

There was an issue following a vCenter restart, which is assumed to have been the proximate cause the first panic, although it didn't actually occur until attempting to access vicadmin some time later:
```
Sep  5 2017 06:42:10.512Z INFO  User with a valid auth cookie at x.x.x.x is authenticated.
Sep  5 2017 06:42:10.512Z ERROR Failed to acquire logrotate lock: open /var/run/lock/logrotate_run.lock: permission denied
Sep  5 2017 06:42:10.515Z WARN  User b396afb9-4a88-4aa1-8e4e-e6980430bbf2 session has expired
2017/09/05 06:42:10 http: panic serving x.x.x.x:53397: runtime error: invalid memory address or nil pointer dereference
goroutine 563 [running]:
net/http.(*conn).serve.func1(0xc4205adae0)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xdd48e0, 0x18dff70)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
main.listVMPaths(0x18fb700, 0xc4200141b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/vmware/vic/cmd/vicadmin/vicadm.go:323 +0x194
main.findDatastoreLogs(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/vmware/vic/cmd/vicadmin/vicadm.go:432 +0x121
main.(*server).bundleContainerLogs(0xc420312b70, 0x18fad40, 0xc420365340, 0xc42000bb00, 0x1)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:467 +0x181
main.(*server).zipContainerLogs(0xc420312b70, 0x18fad40, 0xc420365340, 0xc42000bb00)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:526 +0x52
main.(*server).(main.zipContainerLogs)-fm(0x18fad40, 0xc420365340, 0xc42000bb00)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:394 +0x48
main.(*server).Authenticated.func1(0x18fad40, 0xc420365340, 0xc42000bb00)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:262 +0xe42
net/http.HandlerFunc.ServeHTTP(0xc42030fd00, 0x18fad40, 0xc420365340, 0xc42000bb00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/vmware/vic/vendor/github.com/gorilla/context.ClearHandler.func1(0x18fad40, 0xc420365340, 0xc42000bb00)
        /go/src/github.com/vmware/vic/vendor/github.com/gorilla/context/context.go:141 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc42030fd20, 0x18fad40, 0xc420365340, 0xc42000bb00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420313530, 0x18fad40, 0xc420365340, 0xc42000bb00)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42007fa20, 0x18fad40, 0xc420365340, 0xc42000bb00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4205adae0, 0x18fb6c0, 0xc4204c5fc0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

In the course of trying to debug the issue, vicadmin binary was killed and relaunched by hand having updated `debug=1` without rebooting the applianceVM. The following was seen:
```
Sep  5 2017 10:54:42.350Z INFO  Setting debug logging
Sep  5 2017 10:54:42.350Z DEBUG [BEGIN] [main.(*server).listen:79]
Sep  5 2017 10:54:42.350Z WARN  No certificate authorities found for certificate-based authentication. This may be intentional, however, certificate-based authentication is disabled
Sep  5 2017 10:54:42.350Z DEBUG [ END ] [main.(*server).listen:79] [760.078µs]
Sep  5 2017 10:54:42.350Z INFO  listening on client.localhost:2378
Sep  5 2017 10:54:42.350Z DEBUG [BEGIN] [main.(*server).serve:381]
Sep  5 2017 10:54:42.350Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [14.985µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [5.153µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [4.232µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [4.598µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.logFiles:106]
Sep  5 2017 10:54:42.351Z DEBUG Found potential file for export: docker-personality.log
Sep  5 2017 10:54:42.351Z DEBUG Adding file for export: /var/log/vic/docker-personality.log
Sep  5 2017 10:54:42.351Z DEBUG Found potential file for export: init.log
Sep  5 2017 10:54:42.351Z DEBUG Adding file for export: /var/log/vic/init.log
Sep  5 2017 10:54:42.351Z DEBUG Found potential file for export: port-layer.log
Sep  5 2017 10:54:42.351Z DEBUG Adding file for export: /var/log/vic/port-layer.log
Sep  5 2017 10:54:42.351Z DEBUG Found potential file for export: vicadmin.log
Sep  5 2017 10:54:42.351Z DEBUG Adding file for export: /var/log/vic/vicadmin.log
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.logFiles:106] [230.175µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [43.029µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [31.015µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [37.97µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [24.438µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [25.118µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [19.585µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [14.042µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [18.629µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [17.504µs]
Sep  5 2017 10:54:42.351Z DEBUG [BEGIN] [main.(*server).Authenticated:167]
Sep  5 2017 10:54:42.351Z DEBUG [ END ] [main.(*server).Authenticated:167] [17.288µs]
Sep  5 2017 10:55:13.237Z INFO  No authentication token: map[]
Sep  5 2017 10:55:13.238Z DEBUG [BEGIN] [main.(*server).loginPage:269]
Sep  5 2017 10:55:13.238Z DEBUG [ END ] [main.(*server).loginPage:269] [82.218µs]
2017/09/05 10:55:13 http: panic serving x.x.x.x:58151: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
net/http.(*conn).serve.func1(0xc42033caa0)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xdd48e0, 0x18dff70)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xfd2b65, 0x9, 0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:141 +0x67
html/template.(*Template).ExecuteTemplate(0x0, 0x18f49c0, 0xc4203776c0, 0xfd2b65, 0x9, 0xd3f3c0, 0xc4202a38f0, 0x3, 0x0)
        /usr/local/go/src/html/template/template.go:130 +0x43
main.(*server).loginPage(0xc420322b10, 0x18fad40, 0xc4203776c0, 0xc42033ad00)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:372 +0x2aa
main.(*server).(main.loginPage)-fm(0x18fad40, 0xc4203776c0, 0xc42033ad00)
        /go/src/github.com/vmware/vic/cmd/vicadmin/server.go:386 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420325dd0, 0x18fad40, 0xc4203776c0, 0xc42033ad00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420323620, 0x18fad40, 0xc4203776c0, 0xc42033ad00)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420091760, 0x18fad40, 0xc4203776c0, 0xc42033ad00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42033caa0, 0x18fb6c0, 0xc4202a6700)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

Of note is that the configuration looked correct, and the applianceVM came up with vicadmin working fine after a reboot, yet repeated fresh runs of the processes manually prior to the reboot resulted in the same panic.

Estimate is for initial investigation and recommendation as to follow on work.

**Comment by gigawhitlocks** [comment] 2017-09-07 21:03
I have been attempting to reproduce this issue, and right now it looks like it's related to the vmx locking issue.

Failed replications:
1) Resetting the VM that vCenter is on
2) Resetting the VM vCenter is on after mangling the time on the host ESX
3) Resetting after spinning up as many containers as my vCenter had resources for
4) Mangling GuestInfo values (works through a vCenter restart but not a VCH restart, but doesn't cause the above error, everything just breaks.. not a surprising result)

**Comment by gigawhitlocks** [comment] 2017-09-11 17:15
Walked through call stack w/ @hmahmood and found a case where vicadmin is returning `nil, nil`, and should return `nil, err` and have requisite handling while getting the vSphere session after the vSphere session is expired by vSphere.

**Comment by mhagen-vmware** [comment] 2017-09-13 13:47
resolved in master already and cherry-picked to release here:
https://github.com/vmware/vic/pull/6313

**Closed by mhagen-vmware** 2017-09-13 13:47 UTC
Labels: component/vicadmin, kind/bug, kind/customer-found, priority/high
