### ISSUE TITLE
Resize thinks container doesn't exist if its powered off

### ISSUE THREAD

**Issue by jzt** [vmware/vic#2344] opened 2016-09-15 20:51 UTC
```
vagrant@devbox $ docker -H 192.168.218.235:2376 --tls run -it --rm busybox /bin/date
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
Error response from daemon: No such container: 6db5458960735b38814914c8f789ae6c186fa6ee8f174903479d3bee1b8c8d41
```

The container is still there:
```
vagrant@devbox $ docker -H 192.168.218.235:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6db545896073        busybox             "/bin/date"         3 months ago        Exited (0)                              hopeful_wozniak

```

But can't be removed because the `NotFound` error resulted in its removal from the persona cache once it bubbled up:

```
vagrant@devbox $ docker -H 192.168.218.235:2376 --tls rm 6db545896073
Error response from daemon: No such container: 6db545896073
```

The problem appears in short-lived containers (already a known issue). When a container is powered off too fast, the `ContainerResize` path ends up calling the attach server's `Get` which calls the connect server's `Get` method. Any error returned down this path will be treated as a `NotFound` error, and this bubbles up to the persona and back to the client.

```go
	connContainer, err := i.attachServer.Get(context.Background(), params.ID, interactionTimeout)
	if err != nil {
		retErr := &models.Error{Message: fmt.Sprintf("No such container: %s", params.ID)}
		return interaction.NewContainerResizeNotFound().WithPayload(retErr)
	}

```

In the short-lived container case, this results from a context timeout while waiting for a connection to a permanently powered-off container.

This can be fixed if we can differentiate between timing out waiting on a connection and actually being able to tell if the container really no longer exists.

Tagging @sflxn in case he has something to add.

**Comment by mhagen-vmware** [comment] 2016-09-20 15:20
Note: For short lived containers, it is possible to get into a state where you cannot docker rm the container.  To workaround, attempt to detach and destroy the container VM through the vSphere UI.

**Comment by jzt** [comment] 2016-09-20 15:50
@mhagen-vmware is that still possible after https://github.com/vmware/vic/pull/2230 was merged? Just curious if that's a different issue.

**Comment by mdubya66** [comment] 2016-09-20 21:30
Closed per @mhagen-vmware

**Comment by jzt** [comment] 2016-09-20 21:56
Reopening this issue as I think I caused a misunderstanding earlier today.

The state @mhagen-vmware described earlier, and the associated PR I mentioned (#2230) was for containers VMs that have been marked with an invalid state by hostd. This particular issue involves containers that are still in a valid state, but are not in the container cache on the persona side and thusly cannot be removed.

Apologies for the confusion.

**Comment by hickeng** [comment] 2016-10-10 18:46
Confirm this is fixed by recent attach logic changes

**Comment by mdubya66** [comment] 2016-10-10 18:46
need to confirm that this might be fixed @jzt

**Comment by mdubya66** [comment] 2016-10-10 20:54
I'm closing as Cannot Reproduce. 

(mwilliamson) dubs:~/Downloads $  docker -H 10.17.109.93:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: v0.6.0-5571-e9861c3
Storage Driver: vSphere Integrated Containers v0.6.0-5571-e9861c3 Backend Engine
VolumeStores:
vSphere Integrated Containers v0.6.0-5571-e9861c3 Backend Engine: RUNNING
 VCH mhz limit: 2942 Mhz
 VCH memory limit: 1.282 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
Plugins:
 Volume:
 Network: bridge
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Security Options:
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 2942
Total Memory: 1.282 GiB
Name: dubs
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io

(mwilliamson) dubs:~/Downloads $ docker -H 10.17.109.93:2376 --tls run -it --rm busybox /bin/date
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
56bec22e3559: Already exists
a3ed95caeb02: Pull complete
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for library/busybox:latest
(mwilliamson) dubs:~/Downloads $ docker -H 10.17.109.93:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
(mwilliamson) dubs:~/Downloads $do

**Closed by mdubya66** 2016-10-10 20:54 UTC
Labels: kind/bug, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:12
Not reproduced. Removing kind/note.
