### ISSUE TITLE
[6.5] vic-machine fails to remove

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#2014] opened 2016-08-16 21:21 UTC
```
INFO[2016-08-16T21:15:51Z] ### Removing VCH ####
adsf;lkINFO[2016-08-16T21:15:54Z]
INFO[2016-08-16T21:15:54Z] VCH ID: VirtualMachine:4
jINFO[2016-08-16T21:15:54Z] Removing VMs
INFO[2016-08-16T21:15:59Z] Removing volume stores...
INFO[2016-08-16T21:15:59Z] Deleting volume store "default" on Datastore "datastore1" at path "."
ERRO[2016-08-16T21:16:00Z] Operation failed: Error caused by file /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7 - (&{{} %!!(MISSING)s(*types.FileFault=&{{{<nil> []}} /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7}) Error caused by file /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7})
INFO[2016-08-16T21:16:00Z] Removing appliance VM network devices
INFO[2016-08-16T21:16:01Z] No network device attached
INFO[2016-08-16T21:16:01Z] Removing Portgroup "ZzZ"
INFO[2016-08-16T21:16:02Z] Removing VirtualSwitch "ZzZ"
ERRO[2016-08-16T21:16:02Z] Operation failed: Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'. - (&{{} %!!(MISSING)s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.offline.deleteVM [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.vigor.method.invalidConfig [] The virtual machine configuration is invalid.} {{} msg.vigor.vmx.load.error [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Unable to load configuration file '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.dictionary.load.openFailed [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx} {{} 2 2 (No such file or directory)}] Cannot open file "/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx": 2 (No such file or directory). }]}}} Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.}) Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.})
INFO[2016-08-16T21:16:02Z] Collecting ha-host hostd.log
ERRO[2016-08-16T21:16:03Z] Failed to destroy vm "VirtualMachine:4": Operation failed: Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'. - (&{{} %!s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.offline.deleteVM [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.vigor.method.invalidConfig [] The virtual machine configuration is invalid.} {{} msg.vigor.vmx.load.error [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Unable to load configuration file '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.dictionary.load.openFailed [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx} {{} 2 2 (No such file or directory)}] Cannot open file "/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx": 2 (No such file or directory). }]}}} Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.}) Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.})
ERRO[2016-08-16T21:16:03Z] --------------------
ERRO[2016-08-16T21:16:03Z] vic-machine-linux failed: delete failed
```

**Comment by caglar10ur** [comment] 2016-08-16 21:22
[hostd.log.zip](https://github.com/vmware/vic/files/421313/hostd.log.zip)

**Comment by caglar10ur** [comment] 2016-08-22 22:26
same again, just installed and removed without doing anything in between

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(revert)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -e -i
INFO[2016-08-22T22:21:04Z] ### Installing VCH ####
INFO[2016-08-22T22:21:04Z] Generating certificate/key pair - private key in ./ZzZ-key.pem
INFO[2016-08-22T22:21:06Z] Validating supplied configuration
INFO[2016-08-22T22:21:10Z] Firewall status: ENABLED on "/ha-datacenter/host/office2-sfo2-dhcp262.eng.vmware.com/office2-sfo2-dhcp262.eng.vmware.com"
INFO[2016-08-22T22:21:10Z] Firewall configuration OK on hosts:
INFO[2016-08-22T22:21:10Z]   "/ha-datacenter/host/office2-sfo2-dhcp262.eng.vmware.com/office2-sfo2-dhcp262.eng.vmware.com"
INFO[2016-08-22T22:21:10Z] License check OK
INFO[2016-08-22T22:21:10Z] DRS check SKIPPED - target is standalone host
INFO[2016-08-22T22:21:12Z] Creating VirtualSwitch
INFO[2016-08-22T22:21:13Z] Creating Portgroup
INFO[2016-08-22T22:21:13Z] Creating directory [datastore1]
INFO[2016-08-22T22:21:13Z] Datastore path is [datastore1]
INFO[2016-08-22T22:21:13Z] Creating appliance on target
INFO[2016-08-22T22:21:13Z] Network role "client" is sharing NIC with "external"
INFO[2016-08-22T22:21:13Z] Network role "management" is sharing NIC with "external"
INFO[2016-08-22T22:21:15Z] Uploading images for container
INFO[2016-08-22T22:21:15Z]      "/opt/go/src/github.com/vmware/vic/bin/bootstrap.iso"
INFO[2016-08-22T22:21:15Z]      "/opt/go/src/github.com/vmware/vic/bin/appliance.iso"
INFO[2016-08-22T22:21:32Z] Waiting for IP information
INFO[2016-08-22T22:21:43Z] Waiting for major appliance components to launch
INFO[2016-08-22T22:21:46Z] Initialization of appliance successful
INFO[2016-08-22T22:21:46Z]
INFO[2016-08-22T22:21:46Z] vic-admin portal:
INFO[2016-08-22T22:21:46Z] https://10.118.69.155:2378
INFO[2016-08-22T22:21:46Z]
INFO[2016-08-22T22:21:46Z] DOCKER_HOST=10.118.69.155:2376
INFO[2016-08-22T22:21:46Z]
INFO[2016-08-22T22:21:46Z] Connect to docker:
INFO[2016-08-22T22:21:46Z] docker -H 10.118.69.155:2376 --tls info
INFO[2016-08-22T22:21:46Z] Installer completed successfully
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(revert)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -e -u
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(revert)] /opt/go/src/github.com/vmware/vic/infra/machines/vcsa/install.sh -e -u
INFO[2016-08-22T22:23:59Z] ### Removing VCH ####
INFO[2016-08-22T22:24:02Z]
INFO[2016-08-22T22:24:02Z] VCH ID: VirtualMachine:26
INFO[2016-08-22T22:24:03Z] Removing VMs
INFO[2016-08-22T22:24:05Z] Removing volume stores...
INFO[2016-08-22T22:24:05Z] Deleting volume store "default" on Datastore "datastore1" at path "."
ERRO[2016-08-22T22:24:07Z] Operation failed: Error caused by file /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7 - (&{{} %!!(MISSING)s(*types.FileFault=&{{{<nil> []}} /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7}) Error caused by file /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7})
INFO[2016-08-22T22:24:07Z] Removing appliance VM network devices
INFO[2016-08-22T22:24:08Z] No network device attached
INFO[2016-08-22T22:24:08Z] Removing Portgroup "ZzZ"
INFO[2016-08-22T22:24:08Z] Removing VirtualSwitch "ZzZ"
ERRO[2016-08-22T22:24:09Z] Operation failed: Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'. - (&{{} %!!(MISSING)s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.offline.deleteVM [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.vigor.method.invalidConfig [] The virtual machine configuration is invalid.} {{} msg.vigor.vmx.load.error [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Unable to load configuration file '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.dictionary.load.openFailed [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx} {{} 2 2 (No such file or directory)}] Cannot open file "/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx": 2 (No such file or directory). }]}}} Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.}) Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.})
INFO[2016-08-22T22:24:09Z] Collecting ha-host hostd.log
ERRO[2016-08-22T22:24:09Z] Failed to destroy vm "VirtualMachine:26": Operation failed: Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'. - (&{{} %!s(*types.GenericVmConfigFault=&{{{{<nil> [{{} msg.vigor.offline.deleteVM [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.vigor.method.invalidConfig [] The virtual machine configuration is invalid.} {{} msg.vigor.vmx.load.error [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx}] Unable to load configuration file '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.} {{} msg.dictionary.load.openFailed [{{} 1 /vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx} {{} 2 2 (No such file or directory)}] Cannot open file "/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx": 2 (No such file or directory). }]}}} Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.}) Failed to delete the virtual machine, '/vmfs/volumes/57ae54e6-4e829e2c-8ece-000c29da2bd7/ZzZ/ZzZ.vmx'.})
ERRO[2016-08-22T22:24:09Z] --------------------
ERRO[2016-08-22T22:24:09Z] vic-machine-linux failed: delete failed

[vagrant@devbox:/opt/go/src/github.com/vmware/vic(revert)]
```

**Comment by mdubya66** [comment] 2016-09-28 20:25
Working on VC is a must have for bundle beta

**Comment by mlh78750** [comment] 2016-09-28 20:31
This is possibly related to #1888. When I ran into issues there I couldn't even delete things via the VC UI. I had to dive into the host and use rm -rf. It might not be related, but there are some details in the comments for #1888 about this and reference to an internal bug as well.

**Comment by mlh78750** [comment] 2016-10-05 18:06
#1888 is now resolved and I still see this problem in 6.5.

**Comment by hickeng** [comment] 2016-10-11 15:39
I see a slightly different behaviour locally.

### Recreate steps
1. deploy VCH
2. DO NOTHING WITH IT
3. delete VCH

This ends up with a broken VCH that cannot be powered on because we're already removed the ISOS, and cannot be deleted by vic-machine even with --force.

### Expected
Once we start actually deleting components of a VCH, we're committed. The validation that we can continue should all occur up front and then we make a go/no-go decision.

### Outputs:

First a repetition (this is with --force) to show the VCH isn't deleted at all
```
vagrant@devbox:~/vic$ vic-rm
INFO[2016-10-11T15:25:02Z] ### Removing VCH ####
INFO[2016-10-11T15:25:02Z]
INFO[2016-10-11T15:25:02Z] VCH ID: VirtualMachine:93
INFO[2016-10-11T15:25:03Z] Removing VMs
INFO[2016-10-11T15:25:03Z] Removing volume stores...
INFO[2016-10-11T15:25:03Z] Deleting volume store "default" on Datastore "datastore1" at path "volumes"
INFO[2016-10-11T15:25:03Z] Removing appliance VM network devices
INFO[2016-10-11T15:25:03Z] No network device attached
INFO[2016-10-11T15:25:03Z] Bridge network was not created during VCH deployment, leaving it there
INFO[2016-10-11T15:25:03Z] Collecting ha-host hostd.log
ERRO[2016-10-11T15:25:03Z] File [datastore1] localesx/images was not found
ERRO[2016-10-11T15:25:03Z] --------------------
ERRO[2016-10-11T15:25:03Z] vic-machine-linux failed: delete failed

vagrant@devbox:~/vic$ vic-rm
INFO[2016-10-11T15:25:08Z] ### Removing VCH ####
INFO[2016-10-11T15:25:09Z]
INFO[2016-10-11T15:25:09Z] VCH ID: VirtualMachine:93
INFO[2016-10-11T15:25:09Z] Removing VMs
INFO[2016-10-11T15:25:09Z] Removing volume stores...
INFO[2016-10-11T15:25:09Z] Deleting volume store "default" on Datastore "datastore1" at path "volumes"
INFO[2016-10-11T15:25:09Z] Removing appliance VM network devices
INFO[2016-10-11T15:25:09Z] No network device attached
INFO[2016-10-11T15:25:09Z] Bridge network was not created during VCH deployment, leaving it there
INFO[2016-10-11T15:25:09Z] Collecting ha-host hostd.log
ERRO[2016-10-11T15:25:09Z] File [datastore1] localesx/images was not found
ERRO[2016-10-11T15:25:09Z] --------------------
ERRO[2016-10-11T15:25:09Z] vic-machine-linux failed: delete failed
```

Then with debug, which honestly doesn't give any more useful data:
```
INFO[2016-10-11T15:27:08Z] ### Removing VCH ####
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:80]
DEBU[2016-10-11T15:27:08Z] Trying to log in with username/password in lieu of cert
DEBU[2016-10-11T15:27:08Z] Session Environment Info:                     API Type=HostAgent API Version=6.0 Build=3380124 Name=VMware ESXi OS Type=vmnix-x86 Product ID=embeddedEsx UUID= Vendor=VMware, Inc. Version=6.0.0
DEBU[2016-10-11T15:27:08Z] vSphere resource cache populating...
DEBU[2016-10-11T15:27:08Z] Cached dc:
DEBU[2016-10-11T15:27:08Z] Cached cluster:
DEBU[2016-10-11T15:27:08Z] Cached ds:
DEBU[2016-10-11T15:27:08Z] Cached host:
DEBU[2016-10-11T15:27:08Z] Cached pool:
DEBU[2016-10-11T15:27:08Z] vSphere resource cache populated...
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:80] [129.299832ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.NewDispatcher:76]
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.NewDispatcher:76] [108.876µs]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:80] path "/", name "ghicken-test"
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:78] /
DEBU[2016-10-11T15:27:08Z] Using default resource pool for compute resource: "/ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources"
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:78] [105.648µs] /
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:64] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).isVCH:64] [21.20497ms] /ha-datacenter/host/office1-sfo2-dhcp51.localdomain/Resources/ghicken-test/ghicken-test
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:80] [43.768867ms] path "/", name "ghicken-test"
INFO[2016-10-11T15:27:08Z]
INFO[2016-10-11T15:27:08Z] VCH ID: VirtualMachine:93
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136]
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).GetVCHConfig:136] [13.774011ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).InitDiagnosticLogs:93]
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).InitDiagnosticLogs:93] [69.600734ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).DeleteVCH:34] ghicken-test
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findApplianceByID:323]
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findApplianceByID:323] [3.336945ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).DeleteVCHInstances:93] ghicken-test
INFO[2016-10-11T15:27:08Z] Removing VMs
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).DeleteVCHInstances:93] [20.711567ms] ghicken-test
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteImages:42]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:101] path "localesx/images/VIC", force true
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsFolder:238] [datastore1] localesx/images/VIC
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsFolder:238] [31.057906ms] [datastore1] localesx/images/VIC
DEBU[2016-10-11T15:27:08Z] Folder "[datastore1] localesx/images/VIC" is not found
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:101] [32.644549ms] path "localesx/images/VIC", force true
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsSubFolder:212] [datastore1] localesx/images
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsSubFolder:212] [18.503544ms] [datastore1] localesx/images
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteImages:42] [60.404576ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteVolumeStoreIfForced:287]
INFO[2016-10-11T15:27:08Z] Removing volume stores...
DEBU[2016-10-11T15:27:08Z] Provided datastore URL: "[datastore1] volumes"
Parsed volume store path: "volumes"
INFO[2016-10-11T15:27:08Z] Deleting volume store "default" on Datastore "datastore1" at path "volumes"
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:101] path "volumes", force true
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsFolder:238] [datastore1] volumes
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).lsFolder:238] [23.337737ms] [datastore1] volumes
DEBU[2016-10-11T15:27:08Z] Folder "[datastore1] volumes" is not found
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:101] [24.109194ms] path "volumes", force true
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteVolumeStoreIfForced:287] [33.192195ms]
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteNetworkDevices:157] ghicken-test
INFO[2016-10-11T15:27:08Z] Removing appliance VM network devices
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).networkDevices:191]
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).networkDevices:191] [5.404401ms]
INFO[2016-10-11T15:27:08Z] No network device attached
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).deleteNetworkDevices:157] [10.963995ms] ghicken-test
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).removeNetwork:87] ghicken-test
INFO[2016-10-11T15:27:08Z] Bridge network was not created during VCH deployment, leaving it there
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).removeNetwork:87] [306.807µs] ghicken-test
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).DeleteVCH:34] [130.838203ms] ghicken-test
DEBU[0000] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:163]
INFO[2016-10-11T15:27:08Z] Collecting ha-host hostd.log
DEBU[0000] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:163] [25.550775ms]
ERRO[2016-10-11T15:27:08Z] File [datastore1] localesx/images was not found
ERRO[2016-10-11T15:27:08Z] --------------------
ERRO[2016-10-11T15:27:08Z] vic-machine-linux failed: delete failed
```

**Comment by emlin** [comment] 2016-10-11 17:25
Is this vc 6.5, or it actually happens in vc 6.0?

**Comment by emlin** [comment] 2016-10-11 17:26
If that is in vc6.0, I highly suspect that's still related to image store deletion, which deleted the parent dir, as known as vch vm directory.

**Comment by emlin** [comment] 2016-10-11 18:53
@hickeng how do you delete before the image store is initialized? Are you trying vic-machine delete hit into that time slot, or you stop the appliance VM immediately after it's powered on?
In another word, in which status of a vch appliance vm, while you start to run vic-machine delete?

**Comment by emlin** [comment] 2016-10-11 19:27
@hickeng I tried to reproduce what you said, but turns to be caused by custom image path not found.
It's not related to vc 6.5 with this issue, so created another issue for your new issue: #2662
Please comment on that issue, if you have any other observations.

**Closed** 2016-10-18 21:23 UTC
Labels: component/vic-machine, kind/bug
