### ISSUE TITLE
HA nightly: "host is temporarily disconnected" - fails to delete container, then fails to delete image in use by container.

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#6667] opened 2017-11-01 15:31 UTC
Seen: 11/1/2017
Engine Build: 14321
On: VC 6.5 during High-availability nightlies
Tests: All HA tests failed.

relevant logs:
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1434640/5-4-High-Availability.zip)

@hickeng edit: additional symptom match in this test:
```
ESX host is temporarily disconnected
```

**Comment by matthewavery** [comment] 2017-11-06 17:42
Seen during a nightly VC 6.5 High-Availability failure on 11/5/2017:
Engine Build 14432

[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1447232/5-4-High-Availability.zip)

**Comment by matthewavery** [comment] 2017-11-08 16:46
Seen during a nightly VC 6.0 High-Availability failure on 11/7/2017:
Engine Build 14432

[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1454675/5-4-High-Availability.zip)

**Comment by sflxn** [comment] 2017-11-08 19:32
May be related to #4858.  Please determine whether to keep both or close one as dupe.

**Comment by sflxn** [comment] 2017-11-08 21:45
After looking at #4858, it might not be related to this issue.  This issue is around rmi failing because VIC believes the image is still in use.  4858 is around inability to find a parent image.  A dive into the logs is needed.

**Comment by sgairo** [comment] 2017-11-17 01:21
`DEBUG vSphere Event Relocating xenodochial_goldberg-d8523c178be3 in ha-datacenter from 10.192.246.212, nfsDatastore to 10.160.114.21, nfsDatastore for eventID(910) ignored by the event collector` just out of curiosity, why does the happen to only this particular container?

**Comment by sgairo** [comment] 2017-11-17 01:56
In fact, I dont even see a container create for xenodochial_goldberg-d8523c178be3

**Comment by sgairo** [comment] 2017-11-17 01:59
Okay, looks like a host failed which is causing this problem:

`Nov  7 2017 09:50:32.961Z DEBUG vSphere Event The vSphere HA availability state of the host 10.192.246.212 in cluster in cls in ha-datacenter has changed to Unreachable for eventID(907) ignored by the event collector
Nov  7 2017 09:50:32.961Z DEBUG vSphere Event The vSphere HA availability state of the host 10.192.246.212 in cluster in cls in ha-datacenter has changed to Host Failed for eventID(908) ignored by the event collector
Nov  7 2017 09:50:32.961Z DEBUG vSphere Event vSphere HA detected a possible host failure of host 10.192.246.212 in cluster cls in datacenter ha-datacenter for eventID(909) ignored by the event collector
Nov  7 2017 09:50:32.961Z DEBUG vSphere Event Relocating xenodochial_goldberg-d8523c178be3 in ha-datacenter from 10.192.246.212, nfsDatastore to 10.160.114.21, nfsDatastore for eventID(910) ignored by the event collector
Nov  7 2017 09:50:32.961Z DEBUG vSphere Event Alarm 'vSphere HA host status' on 10.192.246.212 changed from Green to Red for eventID(911) ignored by the event collector
Nov  7 2017 09:52:04.826Z DEBUG vSphere Event Host 10.192.246.212 in ha-datacenter is not responding for eventID(941) ignored by the event collector
Nov  7 2017 09:52:05.824Z DEBUG vSphere Event Alarm 'Host connection and power state' on 10.192.246.212 changed from Green to Red for eventID(942) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host CPU usage' on 10.192.246.212 changed from Green to Gray for eventID(943) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host memory usage' on 10.192.246.212 changed from Green to Gray for eventID(944) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host service console swap rates' on 10.192.246.212 changed from Green to Gray for eventID(945) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host connection failure' on 10.192.246.212 triggered by event 941 'Host 10.192.246.212 in ha-datacenter is not responding' for eventID(946) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host connection failure' on 10.192.246.212 triggered an action for eventID(947) ignored by the event collector
Nov  7 2017 09:52:05.831Z DEBUG vSphere Event Alarm 'Host connection failure': an SNMP trap for entity 10.192.246.212 was sent for eventID(948) ignored by the event collector
Nov  7 2017 09:54:22.845Z DEBUG vSphere Event The vSphere HA agent on the host 10.160.114.21 in cluster cls in ha-datacenter cannot reach some of the management network addresses of other hosts, and thus HA may not be able to restart VMs if a host failure occurs:  10.192.246.212:10.192.246.212 10.192.246.212:fd01:1:2:2917:0:3aff:fe58:c177 for eventID(970) ignored by the event collector`

**Comment by sflxn** [comment] 2017-11-17 22:30
@sgairo You might want to look at https://github.com/vmware/vic/commit/bdf8f7f29281f52a1fe2da8fe97bdc93bca56ef4

Ian added a message back to the CLI indicating the host had disconnected.  If the host did disconnect as your log snippet above indicates, you should send a similar message back.

**Comment by sgairo** [comment] 2017-11-19 17:38
Seen in 6.0 on 11/19 report:
[5-4-High-Availability.zip](https://github.com/vmware/vic/files/1485786/5-4-High-Availability.zip)

**Comment by sgairo** [comment] 2017-11-19 18:05
This latest log set shows no sign of a host connection failure, so the underlying problem must be something different than the host connection.

**Comment by sgairo** [comment] 2017-11-21 15:42
The failures from the 11/20 report were posted in #6263 as the underlying cause of seeing the error message in this issue. Another issue that results in this error message is the logs posted above when we see a host connection failure. I also suspect the fix to #6263 would catch this case as well. Another case we see is `ERROR CommitHandler error on handle(3487c0ee5c39c5f12bdbdaadf139a2d7) for eaeb57361728956b10fee6994050e14ef1be3b9ffe77d63d48a8aae06b372307: unable to wait for process launch status: container VM has unexpectedly powered off` which is behaviorally different from the host connection failures seen above.

**Comment by sgairo** [comment] 2018-02-06 15:41
Seen in 2/5 6.0 nightly HA test run:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-3334-container-logs.zip](https://github.com/vmware/vic/files/1699706/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-3334-container-logs.zip)

**Comment by sgairo** [comment] 2018-02-12 17:09
Seen in 2/10 nightly 6.0 and 6.5  run: 
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-5075-container-logs.zip](https://github.com/vmware/vic/files/1717111/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-5075-container-logs.zip)

**Comment by hickeng** [comment] 2018-02-12 19:48
There are two failures seen in the HA test from @sgairo's last comment:
1. Failure to delete [reference container after HA restart](https://github.com/vmware/vic/blob/326eed4c217ffb49a8f8d9030089dffc311ef551/tests/manual-test-cases/Group5-Functional-Tests/5-4-High-Availability.robot#L221)
2. Failure to delete busybox image at the end of subsequent regression tests

(1) is easily found from the personality logs and #7005:
```
Feb 11 2018 05:57:05.385Z DEBUG Calling DELETE /v1.25/containers/04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462
Feb 11 2018 05:57:05.385Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*Container).ContainerRm:788] 04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462
Feb 11 2018 05:57:05.385Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).State:852]
Feb 11 2018 05:57:05.448Z INFO  Specified Volumes : []string{"named-volume:/mnt/named:rw", "fb48d4d1-0eef-11e8-91f1-005056a41364:/mnt/test:rw"}
Feb 11 2018 05:57:05.448Z INFO  Processed volume arguments: backends.volumeFields{ID:"named-volume", Dest:"/mnt/named", Flags:"rw"}
Feb 11 2018 05:57:05.448Z INFO  Processed volume arguments: backends.volumeFields{ID:"fb48d4d1-0eef-11e8-91f1-005056a41364", Dest:"/mnt/test", Flags:"rw"}
Feb 11 2018 05:57:05.448Z INFO  anonymous Volumes : []string{"named-volume:/mnt/named:rw", "fb48d4d1-0eef-11e8-91f1-005056a41364:/mnt/test:rw"}
Feb 11 2018 05:57:05.448Z INFO  Processed volume arguments: backends.volumeFields{ID:"named-volume", Dest:"/mnt/named", Flags:"rw"}
Feb 11 2018 05:57:05.448Z INFO  Processed volume arguments: backends.volumeFields{ID:"fb48d4d1-0eef-11e8-91f1-005056a41364", Dest:"/mnt/test", Flags:"rw"}
Feb 11 2018 05:57:05.448Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends/cache.(*ICache).Get:153] 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884
Feb 11 2018 05:57:05.448Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:193] sha256:96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884
Feb 11 2018 05:57:05.448Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:193] [4.918µs] sha256:96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884
Feb 11 2018 05:57:05.448Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends/cache.(*ICache).Get:153] [34.581µs] 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884
Feb 11 2018 05:57:05.448Z DEBUG Docker inspect - network settings = &types.NetworkSettings{NetworkSettingsBase:types.NetworkSettingsBase{Bridge:"", SandboxID:"", HairpinMode:false, LinkLocalIPv6Address:"", LinkLocalIPv6PrefixLen:0, Ports:nat.PortMap{}, SandboxKey:"", SecondaryIPAddresses:[]network.Address(nil), SecondaryIPv6Addresses:[]network.Address(nil)}, DefaultNetworkSettings:types.DefaultNetworkSettings{EndpointID:"", Gateway:"", GlobalIPv6Address:"", GlobalIPv6PrefixLen:0, IPAddress:"", IPPrefixLen:0, IPv6Gateway:"", MacAddress:""}, Networks:map[string]*network.EndpointSettings{"bridge":(*network.EndpointSettings)(0xc4200c5800)}}
Feb 11 2018 05:57:05.448Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).State:852] [63.398747ms] 
Feb 11 2018 05:57:05.505Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).UnbindContainerFromNetwork:831] 04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462
Feb 11 2018 05:57:05.505Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).UnbindContainerFromNetwork:831] [522.213µs] 04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462
Feb 11 2018 05:57:05.505Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Feb 11 2018 05:57:05.886Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc420343980), statusCode:500}
Feb 11 2018 05:57:05.886Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [381.2864ms] 
Feb 11 2018 05:57:05.886Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*Container).ContainerRm:788] [501.703738ms] 04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462
Feb 11 2018 05:57:05.886Z ERROR Handler for DELETE /v1.25/containers/04374877d6785b78aca834717ee95e7d63f6d46371e73e5689b290c9ce7ae462 returned error: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.
```

(2) is failing to delete an image that is in use. The container in question is `vigilant_wescoff-b2f38a12a165` and is created [here](https://github.com/vmware/vic/blob/326eed4c217ffb49a8f8d9030089dffc311ef551/tests/manual-test-cases/Group5-Functional-Tests/5-4-High-Availability.robot#L174).
Because we fail with #7005 in (1) we never follow through and delete the containers that are expected to be running after the restart. This means that the image is still in use, legitimately.

Unless other logs show different failure patterns for this test, this should be resolved by #7005.

**Comment by sgairo** [comment] 2018-02-13 22:10
Seen in 6.5 nightly run on 2/12:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-8639-container-logs.zip](https://github.com/vmware/vic/files/1721907/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-8639-container-logs.zip)

**Comment by AngieCris** [comment] 2018-02-16 18:02
seen again on 02/16/18
VC version: 6.5
Suite: 5-4-High-Availability

docker rm fails with:
```Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.```

From portlayer log, the image is in use:
```
Feb 16 2018 09:30:09.447Z ERROR op=293.95: ImageStore: delete image error: image 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884 in use by 3a7d279bc192da4684fe67fc8e4ec04cb96c17f4d1245d7e5e8a6d60fe164e0c
Feb 16 2018 09:30:09.447Z ERROR op=293.95: image 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884 in use by 3a7d279bc192da4684fe67fc8e4ec04cb96c17f4d1245d7e5e8a6d60fe164e0c
Feb 16 2018 09:30:09.447Z DEBUG op=293.95: image 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884 in use by 3a7d279bc192da4684fe67fc8e4ec04cb96c17f4d1245d7e5e8a6d60fe164e0c
Feb 16 2018 09:30:09.447Z ERROR DeleteImage: error image 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884 in use by 3a7d279bc192da4684fe67fc8e4ec04cb96c17f4d1245d7e5e8a6d60fe164e0c
```

Also from portlayer log:
```
Feb 16 2018 09:30:07.414Z DEBUG op=293.93: Could not get container 715eee930f6ecc58d8179bf978cefb84 by handle c8fcd16bb496044244663d8ccd22054b2e1372055af33c072167616d15791061: container c8fcd16bb496044244663d8ccd22054b2e1372055af33c072167616d15791061 not found
```
Not sure if it means the container can't be referenced after HA restart.


Container logs:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-7462-container-logs.zip](https://github.com/vmware/vic/files/1732321/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-7462-container-logs.zip)

**Comment by AngieCris** [comment] 2018-02-26 21:25
Nightly 02/26/18
VC version: 6.5
Test suite: 5-4-High-Availability

Two failures:

docker command:
`docker -H 10.193.14.185:2376 --tls rm -f cb7820559ac5b07721e956e530d776366ea219cfe40b412e16a1e59d9328021e`
failed with:
`Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.`

Later in regression test:
docker command: 
`docker -H 10.193.14.185:2376 --tls rmi busybox 2>&1`
failed with: 
`image 96838c2bec69fdd9c20d524f13e69beb090f09f118cae4cbdeb622c69dc15884 in use by cb7820559ac5b0772...`

container logs:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-5756-container-logs.zip](https://github.com/vmware/vic/files/1760325/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-5756-container-logs.zip)
appliance logs:
[VCH-0-5756.zip](https://github.com/vmware/vic/files/1760330/VCH-0-5756.zip)

**Comment by sgairo** [comment] 2018-03-05 16:42
Seen in 6.5 nightly on 3/1: 
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-2643-container-logs.zip](https://github.com/vmware/vic/files/1781759/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-2643-container-logs.zip)
[vic-machine.log](https://github.com/vmware/vic/files/1781760/vic-machine.log)
[VCH-0-2643-vmware.log](https://github.com/vmware/vic/files/1781762/VCH-0-2643-vmware.log)

**Comment by sgairo** [comment] 2018-03-09 18:38
Seen in 6.0 nightly run on 3/7:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-3367-container-logs.zip](https://github.com/vmware/vic/files/1797988/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-3367-container-logs.zip)
[VCH-0-3367-vmware.log](https://github.com/vmware/vic/files/1797989/VCH-0-3367-vmware.log)
[VCH-0-3367-tether.debug.zip](https://github.com/vmware/vic/files/1797990/VCH-0-3367-tether.debug.zip)
[vic-machine.log](https://github.com/vmware/vic/files/1797991/vic-machine.log)

**Comment by sgairo** [comment] 2018-03-14 15:08
Seen in 6.0 nightly run on 3/13/18:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-9109-container-logs.zip](https://github.com/vmware/vic/files/1811697/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-9109-container-logs.zip)
[VCH-0-9109-vmware.log](https://github.com/vmware/vic/files/1811700/VCH-0-9109-vmware.log)
[vic-machine.log](https://github.com/vmware/vic/files/1811701/vic-machine.log)
[VCH-0-9109-tether.debug.zip](https://github.com/vmware/vic/files/1811705/VCH-0-9109-tether.debug.zip)

**Comment by andrewtchin** [comment] 2018-03-19 15:27
**VIC version:**

v1.4.0-dev-17605-6144b31

**Deployment details:**

Nightly 6.0
5-4-High-Availability Test

**Logs:**

```
${output} = Error response from daemon: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-17-20-32-56.zip?authuser=1

**Comment by vburenin** [comment] 2018-03-19 17:44
I have successfully reproduced this bug on my test environment, however, it took a few days to actually hit the bug after 72 successful runs. The code version I was running had a retry logic in case if of "ESX host is temporarily disconnected" error. After 12 retry attempts retry logic has failed to succeed. It took around 3 minutes. I had hopes that eventually this error goes away as VC recovers from failed ESXi, however, it didn't happen withing 3 minutes.
[5-4-High-Availability-VCH-0-9171-container-logs.zip](https://github.com/vmware/vic/files/1826209/5-4-High-Availability-VCH-0-9171-container-logs.zip)
[VCH-0-9171-vmware.log](https://github.com/vmware/vic/files/1826211/VCH-0-9171-vmware.log)
[VCH-0-9171-tether.log](https://github.com/vmware/vic/files/1826214/VCH-0-9171-tether.log)

**Comment by vburenin** [comment] 2018-03-19 17:45
Work is continued, I am adding extra logs to get a better view for the failure. Reproduction of this issue can take awhile again.

**Comment by sgairo** [comment] 2018-03-27 19:41
Moving this out of container ops:
"I am transferring my 6667 to @rogelios it seems like due to the test environment setup." -vlad

@rogeliosanchez

**Comment by rajanashok** [comment] 2018-04-02 18:42
Seen again on 03/31 6.7 
nightlyhttps://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-31-05-28-31.zip?authuser=1

**Comment by hickeng** [comment] 2018-04-09 21:46
Seen again in 2018-04-08 6.0 nightly
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-08-20-32-56.zip?authuser=1

Updated bug2057397 with vcsupport bundle and commentary

@rajanashok FYI

**Comment by andrewtchin** [comment] 2018-04-11 16:43
moved to backlog pending response from vsphere team

**Comment by rogeliosanchez** [comment] 2018-04-20 23:36
Seen in Nightly 6.5 - 2018-040-20

VIC version:
v1.5.0-dev-18481-023de08

5-4-High-Availability
Error response from daemon: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.

![screen shot 2018-04-20 at 6 27 37 pm](https://user-images.githubusercontent.com/26554503/39077709-870d01fe-44c9-11e8-8e87-b2e0086cc888.png)

Vic machine
[vic-machine.log](https://github.com/vmware/vic/files/1933918/vic-machine.log)

VCH logs
[vch-0-4101.zip](https://github.com/vmware/vic/files/1933920/vch-0-4101.zip)

Nightly summary
[65.zip](https://github.com/vmware/vic/files/1933922/65.zip)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-20-01-04-51.zip?authuser=1

More logs
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-4101-container-logs.zip](https://github.com/vmware/vic/files/1933924/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-4101-container-logs.zip)

**Comment by AngieCris** [comment] 2018-04-30 16:54
Seen again on nightly 04/29/18
5-4-High-Availability

command:
`docker -H 10.192.210.157:2376 --tls rm 134052f82390d17700685de6c9c6895c2363991907cbb6068b9eb5927221f279 2>&1`

output:
`Error response from daemon: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.`

link: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-29-00-41-08.zip?authuser=1
container logs:
[Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-4737-container-logs.zip](https://github.com/vmware/vic/files/1961474/Suites.Group5-Functional-Tests.5-4-High-Availability-VCH-0-4737-container-logs.zip)
appliance logs:
[VCH-0-4737.zip](https://github.com/vmware/vic/files/1961481/VCH-0-4737.zip)

**Comment by luwang-vmware** [comment] 2018-11-05 10:53
See it again on scenario testing on 04/11/2018 
5-4-High-Availability.robot

docker -H 10.161.72.172:2376 --tls rm 347e71e01051282dcbcf689089b9a949520f390175a26365f2cf7122fb7cae62 2>&1'.
 Error response from daemon: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.

logs:  https://vic-jenkins.eng.vmware.com/view/Scenario/job/vic-master-scenario/53/

**Comment by luwang-vmware** [comment] 2018-11-16 05:58
The case is randomly failure. After check the latest failure log https://vic-jenkins.eng.vmware.com/job/vic-master-scenario/62/robot/report/log.html#s1-s4-s20, we could see that the issue is occured when case is trying to remove the container which is in power off state and registered in the power off ESXi.

The scripts creates a container which id is ba5ce4a01217a0405636cb5ae8e41f6101a262a47630fb58a04ea3ed61b4213c
```
02:52:59.647 | INFO | Running command 'docker -H 10.192.148.9:2376 --tls create --name=mount-data-test -v /mnt/test -v named-volume:/mnt/named busybox 2>&1'. |  
02:53:05.119 | INFO | ${rc} = 0
02:53:05.119 | INFO | ${containerMountDataTestID} = ba5ce4a01217a0405636cb5ae8e41f6101a262a47630fb58a04ea3ed61b4213c
```
Before power off ESXi(10.192.128.52), we could see that the container vm mount-data-test-ba5ce4a01217 and VCH is register on that ESXi
```
Name:           mount-data-test-ba5ce4a01217
  Path:         /ha-datacenter/vm/VCH-0-9696/mount-data-test-ba5ce4a01217
  UUID:         7fb82305-3b6b-5ac1-a2ca-90d0024fbb16
  Guest name:   Photon - Container v1.5.0-dev, 20370, cda51428
  Memory:       2048MB
  CPU:          2 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:   
  Host:         10.192.128.52
.....
  Name:           VCH-0-9696
  Path:         /ha-datacenter/vm/VCH-0-9696/VCH-0-9696
  UUID:         4228aca8-84dd-141d-2813-b1a04d57155b
  Guest name:   Photon - VCH v1.5.0-dev, 20370, cda51428
  Memory:       2048MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2018-11-14 18:46:44.379409 +0000 UTC
  IP address:   10.192.148.9
  Host:         10.192.128.52
```
Scripts is checking whether VCH has succesfully re-registered on other available hosts, from the info below, we could see that the container vm mount-data-test-ba5ce4a01217 is still in that power off ESXi.
```
Name:           mount-data-test-ba5ce4a01217
  Path:         /ha-datacenter/vm/VCH-0-9696/mount-data-test-ba5ce4a01217
  UUID:         7fb82305-3b6b-5ac1-a2ca-90d0024fbb16
  Guest name:   Photon - Container v1.5.0-dev, 20370, cda51428
  Memory:       2048MB
  CPU:          2 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:   
  Host:         10.192.128.52
...
Name:           VCH-0-9696
  Path:         /ha-datacenter/vm/VCH-0-9696/VCH-0-9696
  UUID:         4228aca8-84dd-141d-2813-b1a04d57155b
  Guest name:   Photon - VCH v1.5.0-dev, 20370, cda51428
  Memory:       2048MB
  CPU:          1 vCPU(s)
  Power state:  poweredOn
  Boot time:    2018-11-14 18:53:52.100137 +0000 UTC
  IP address:   
  Host:         10.192.57.16
```
When the scripts know that VCH has successfully re-registered on other host, scripts are calling docker rm ** to remove the tested container(mount-data-test-ba5ce4a01217). However at that time, the mount-data-test-ba5ce4a01217 container is still in power-off state host, then hit the issue of 'Error response from daemon: Server error from portlayer: Couldn't remove container. The ESX host is temporarily disconnected. Please try again later.'

**Closed** 2018-12-11 01:04 UTC
Labels: area/vsphere, component/portlayer/storage, component/test, priority/p1, source/scenario, team/foundation, team/lifecycle
