### ISSUE TITLE
Docker pull behaviour for different versions of the same image

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#2590] opened 2016-10-06 09:16 UTC
I am running 0.6.0 and I am seeing the following behavior:

I have no images

```
Massimos-MacBook-Pro:vic-product-machine mreferre$ docker -H 192.168.1.239:2375 images

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

I am pulling nginx (latest)
```
Massimos-MacBook-Pro:vic-product-machine mreferre$ docker -H 192.168.1.239:2375 pull nginx

Using default tag: latest
Pulling from library/nginx
a3ed95caeb02: Pull complete 
6a5a5368e0c2: Pull complete 
4aceccff346f: Pull complete 
c8967f302193: Pull complete 
Digest: sha256:0d4dac4abf4f5217f878974a6cffea83b9102ed49b1f9f4c5216db0fd6b0af99
Status: Downloaded newer image for library/nginx:latest
```

I am pulling nginx:1.9.0 (which seems to be downloading fine)  
```
Massimos-MacBook-Pro:vic-product-machine mreferre$ docker -H 192.168.1.239:2375 pull nginx:1.9.0 

Pulling from library/nginx
a3ed95caeb02: Pull complete 
e5ad7970bc69: Pull complete 
2767943aa23d: Pull complete 
5a40bd63d577: Pull complete 
90ba96f0c53d: Pull complete 
d83ac9507937: Pull complete 
1512e0f1740f: Pull complete 
Digest: sha256:4157ed7179858886f21024583247a875bafd8e8966e1cf68b4c8916963b20b62
Status: Downloaded newer image for library/nginx:1.9.0
```

nginx:1.9.0 doesn't show up in the list of available images.
```
Massimos-MacBook-Pro:vic-product-machine mreferre$ docker -H 192.168.1.239:2375 images

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               latest              f7df00cd0f62        12 days ago         181.3 MB 
```

And a subsequent run of `nginx:1.9.0` results in an `image not found error`. 

Is this expected behavior for 0.6.0?

**Comment by mdubya66** [comment] 2016-10-06 19:59
It is not expected. Marking as must fix for GA. Could it be related to #1941 and #2064?

**Comment by anchal-agrawal** [comment] 2016-10-06 22:06
I can repro this on latest master as well. I believe @jzt's imagec PR #2587 resolves this since we couldn't repro on his branch.

**Comment by mreferre** [comment] 2016-10-07 07:07
thanks @mdubya66 @anchal-agrawal. 

So does this mean that this issue is: 
1) reproducible with selected images (e.g. nginx) but not with others (e.g. ubuntu) with VIC 0.6.0
2) it's (likely) solved in the latest fixes 
?
 
If so it should be noted in the "known issues / limitations" for beta. If we had a way to find out what images would be affected (eg nginx) and which not (i.e. ubuntu) that would be a good bonus.

**Comment by mdubya66** [comment] 2016-10-07 14:01
I reproduced it with nginx and nginx:1.9.0.

**Comment by anchal-agrawal** [comment] 2016-10-12 17:47
Closing as resolved on the latest master build with @jzt's changes in #2587.

**Closed by anchal-agrawal** 2016-10-12 17:47 UTC
Labels: component/imagec, kind/bug, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:08
This is fixed. Removing kind/note tag.
