### ISSUE TITLE
Image Store Pathing is not space character friendly

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#3555] opened 2017-01-03 17:35 UTC
Support issue that is tracked in bugzilla ticket #1788767

The VCH deployment fails due to a space character in the datastore name used for the image store. It is highly likely that the paths for datastores used for volume stores and other storage mechanisms suffer from this issue as well. 

The proposed solution is to change the way that we treat paths so that it is compliant with the actual "acceptance language" of vsphere itself. This will allow exisiting production deployments to avoid this kind of issue altogether in the future. 

Vic-machine already contains information on compliance with vsphere naming conventions. These functions should be moved to another package if not already done and used within the portlayer as well. There will be additional functionality needed(maybe?) since some of the paths are parsed within the portlayer in certain ways, due to expected pathing. 

estimated: 3

**Comment by fdawg4l** [comment] 2017-01-03 18:13
```
./vic-machine-linux create --target '#####@#####:#####' --compute-resource Cluster --bridge-network BridgePG --public-network InternalPG --image-store "Storage3 Test" --volume-store "Storage3 Test:default" --name VCH_test --no-tlsverify --registry-ca /etc/docker/certs.d/harbor1.vmware.lab/ca.crt --force
INFO[2016-12-30T09:42:19Z] ### Installing VCH ####
WARN[2016-12-30T09:42:19Z] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2016-12-30T09:42:19Z] Loaded server certificate VCH_test/server-cert.pem
WARN[2016-12-30T09:42:19Z] Configuring without TLS verify - certificate-based authentication disabled
INFO[2016-12-30T09:42:19Z] Loaded registry CA from /etc/docker/certs.d/harbor1.vmware.lab/ca.crt
INFO[2016-12-30T09:42:19Z] Validating supplied configuration
INFO[2016-12-30T09:42:20Z] vDS configuration OK on "BridgePG"
INFO[2016-12-30T09:42:20Z] Firewall status: ENABLED on "/Lab/host/Cluster/192.168.2.101"
INFO[2016-12-30T09:42:20Z] Firewall status: ENABLED on "/Lab/host/Cluster/192.168.2.102"
INFO[2016-12-30T09:42:20Z] Firewall configuration OK on hosts:
INFO[2016-12-30T09:42:20Z]      "/Lab/host/Cluster/192.168.2.101"
INFO[2016-12-30T09:42:20Z]      "/Lab/host/Cluster/192.168.2.102"
INFO[2016-12-30T09:42:21Z] License check OK on hosts:
INFO[2016-12-30T09:42:21Z]   "/Lab/host/Cluster/192.168.2.101"
INFO[2016-12-30T09:42:21Z]   "/Lab/host/Cluster/192.168.2.102"
INFO[2016-12-30T09:42:21Z] DRS check OK on:
INFO[2016-12-30T09:42:21Z]   "/Lab/host/Cluster/Resources"
INFO[2016-12-30T09:42:21Z]
INFO[2016-12-30T09:42:22Z] Creating virtual app "VCH_test"
INFO[2016-12-30T09:42:22Z] Creating directory [Storage3 Test] VIC
INFO[2016-12-30T09:42:22Z] Datastore path is [Storage3 Test] VIC
INFO[2016-12-30T09:42:22Z] Creating appliance on target
INFO[2016-12-30T09:42:22Z] Network role "management" is sharing NIC with "client"
INFO[2016-12-30T09:42:22Z] Network role "public" is sharing NIC with "client"
INFO[2016-12-30T09:42:38Z] Uploading images for container
INFO[2016-12-30T09:42:38Z]      "bootstrap.iso"
INFO[2016-12-30T09:42:38Z]      "appliance.iso"
ERRO[2016-12-30T09:42:39Z]              Upload failed for "appliance.iso": 500 Internal Server Error
WARN[2016-12-30T09:42:39Z]              Continuing despite failures (due to --force option)
WARN[2016-12-30T09:42:39Z]              Note: The VCH will not function without "appliance.iso"...
ERRO[2016-12-30T09:42:39Z]              Upload failed for "bootstrap.iso": Put https://192.168.3.200/folder/VCH_test_2/V0.8.0-7315-C8AC999-bootstrap.iso?dcPath=%2FLab&dsName=Storage3+Test: EOF
WARN[2016-12-30T09:42:39Z]              Continuing despite failures (due to --force option)
WARN[2016-12-30T09:42:39Z]              Note: The VCH will not function without "bootstrap.iso"...

```

**Comment by stuclem** [comment] 2017-01-05 14:11
@matthewavery do we need to update https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/vch_installer_options.html#datastore to state that spaces are not supported in 0.8?

**Comment by mdubya66** [comment] 2017-01-06 15:49
"After more testing in my lab, I was able to reproduce this issue with a perl script I did.
This issue is not an issue with VIC, but an issue with the vCenter 6.0 U2 API.

Thanks a lot for your help, you can close this case."

Closing as not a bug

**Closed by mdubya66** 2017-01-06 15:49 UTC
Labels: kind/bug, kind/customer-found
