### ISSUE TITLE
Login to VCH admin UI results in "failed to authenticate"

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic#5703] opened 2017-07-13 01:39 UTC
Unable to login using administrator@vsphere.local to VCH UI https://VCH-IP:2378 
	Result "Authentication failed due to incorrect credentials(s)"

Bug-Ref 1914783

**Comment by corrieb** [comment] 2017-07-13 06:18
This is going to be hard to diagnose without more context. 

To be clear, you were unable to log in to the VIC admin console? Is that something you can reproduce? Were there other issues that VCH experienced such as network connectivity, configuration issues etc?

**Comment by corrieb** [comment] 2017-07-14 19:45
This is due to a self-signed certificate. Discussion in the vic-dev channel posted here:

@here should the vch admin be validating the entire SSL chain for authentication to the vCenter? Trying to login the VCH UI at 2378 and logs report as follows.
```2017/07/06 20:15:31 http: TLS handshake error from 10.157.149.164:52956: EOF
Jul  6 2017 20:15:31.358Z INFO  No authentication token: map[]
Jul  6 2017 20:15:31.376Z DEBUG [BEGIN] [main.(*server).loginPage:268]
Jul  6 2017 20:15:31.377Z DEBUG [ END ] [main.(*server).loginPage:268] [589.268µs]
Jul  6 2017 20:15:31.573Z INFO  No authentication token: map[]
Jul  6 2017 20:15:47.701Z DEBUG [BEGIN] [main.(*server).loginPage:268]
Jul  6 2017 20:15:47.826Z WARN  Unable to connect: Failed to connect to BNALABDA.labcorp.com: Post https://BNALABDA.labcorp.com/sdk: x509: certificate signed by unknown authority
Jul  6 2017 20:15:47.827Z WARN  10.157.149.164:52960 failed to authenticate```

The vCenter cert is signed by a self signed VMCA.
```Signature Algorithm: sha256WithRSAEncryption
            Issuer: CN=CA, DC=vsphere, DC=local, C=US, ST=California, O=BNALABDA.labcorp.com, OU=VMware Engineering
            Validity
                Not Before: Jan 13 18:18:38 2017 GMT
                Not After : Jan  8 18:18:37 2027 GMT
        Subject: CN=BNALABDA.labcorp.com, C=US```


[2:32] 
If the whole chain needs to be trusted. What is the best way to add the CA chain for the vch admin UI?

@gigawhitlocks 

I’m surprised to see this because I tested that connection thoroughly and never install a root-signed certificate on my test boxes, especially back when I wrote a lot of that stuff, was doing a lot of testing in Fusion, so maybe it’s changed, and there are a few ways we can address this in a patch, but I don’t know an easy workaround. There might be a way to inject the certificate authority into the pool on the appliance VM

**Comment by corrieb** [comment] 2017-07-14 19:48
Summary is we ned to figure out how to trust the self-signed certificate so that customers using one can get access to vic-admin.

**Comment by gigawhitlocks** [comment] 2017-07-19 16:20
```.\vic-machine-windows.exe create --target https://vc1.vcloud.local/"Test DC" --user administrator@vsphere.local --password "***" --compute-resource "Test Cluster" --bridge-network="VIC-Bridge-DVS-01" --management-network=mgmt-DVS --management-network-ip=192.168.1.50/20 --management-network-gateway 192.168.0.0/20:192.168.0.1 --client-network=mgmt-DVS --public-network=public-DVS --public-network-ip=192.168.100.50/24 --public-network-gateway 192.168.100.1 --dns-server=192.168.1.2 --volume-store=iSCSI-1/VCH0000vol:default --image-store iSCSI-1/VCH0000img  --https-proxy=https://proxy.eng.vmware.com:3128 --http-proxy=http://proxy.eng.vmware.com:3128 --no-tlsverify --thumbprint *** --name VCH00-00```

**Comment by gigawhitlocks** [comment] 2017-07-19 19:01
Moving to backlog, needs priority and to be scheduled in a sprint. I've also already tried to reproduce this, ensured that ESX/vCenter had a self-signed cert, and I was not able to reproduce this issue, so I still suspect there's something going on with DNS (re: `vc1.vcloud.local`) but that's just speculation. In any case, it's not as simple as *just* toggling TLSverify.. more investigation will be required when this story is picked up

**Comment by gigawhitlocks** [comment] 2017-08-09 19:10
Had call with customer. Proxy is performing cert offloading such that vic-admin is presented with the proxy's certificate instead of the vSphere certificate. TLS verify causes this to fail (correctly). Customer needs to add certificate to his ca chain on the VCH in order to permit vic-admin to trust and communicate with vSphere. Closing this issue as not a bug.

**Closed by gigawhitlocks** 2017-08-09 19:10 UTC
Labels: component/vicadmin, kind/bug, kind/customer-found, priority/high
