### ISSUE TITLE
docker pull after VC restart fails:  WriteImage of 00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6 failed with: ServerFaultCode: The session is not authenticated.

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#6673] opened 2017-11-01 21:16 UTC
```
Nov  1 2017 21:02:21.484Z DEBUG URLFetcher.fetch() - &http.bodyEOFSignal{body:(*http.body)(0xc4206147c0), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:error(nil), fn:(func(error) error)(0x6ff190), earlyCloseFn:(func() error)(0x6ff120)}, http.Header{"Etag":[]string{"\"54a01009f17bdb7ec1dd1cb427244304\""}, "X-Cache":[]string{"Hit from cloudfront"}, "Date":[]string{"Wed, 29 Mar 2017 14:11:04 GMT"}, "X-Amz-Cf-Id":[]string{"feq3CjY-maRXffSBONgrpT7IoF11bKT95C7z7g0JKHQeZtgHHBwGtQ=="}, "Content-Type":[]string{"application/octet-stream"}, "Connection":[]string{"keep-alive"}, "Server":[]string{"AmazonS3"}, "Age":[]string{"79528"}, "Content-Length":[]string{"32"}, "Last-Modified":[]string{"Sat, 14 Nov 2015 09:09:44 GMT"}, "X-Amz-Version-Id":[]string{"mSZnulvkQ2rnXHxnyn7ciahEgq419bja"}, "Accept-Ranges":[]string{"bytes"}, "Via":[]string{"1.1 68e4011ca1c00bec92bb202e1ddce131.cloudfront.net (CloudFront)"}}
Nov  1 2017 21:02:21.525Z DEBUG URLFetcher.fetch() - &http.bodyEOFSignal{body:(*http.body)(0xc4206140c0), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:error(nil), fn:(func(error) error)(0x6ff190), earlyCloseFn:(func() error)(0x6ff120)}, http.Header{"Connection":[]string{"keep-alive"}, "Age":[]string{"56377"}, "Via":[]string{"1.1 02192a27c967e955f8c815efa939bfc8.cloudfront.net (CloudFront)"}, "Content-Type":[]string{"application/octet-stream"}, "Date":[]string{"Fri, 13 Oct 2017 05:20:12 GMT"}, "Last-Modified":[]string{"Thu, 24 Aug 2017 13:15:57 GMT"}, "Accept-Ranges":[]string{"bytes"}, "Content-Length":[]string{"715181"}, "Etag":[]string{"\"c22489d51c88b6e2bfd61cae985a5200\""}, "X-Cache":[]string{"Hit from cloudfront"}, "X-Amz-Cf-Id":[]string{"GpCuQfF4m0VxQUkqQM3wwUdqMtUitu9qr7TYVEn_JtTbvG2j-tLJag=="}, "X-Amz-Version-Id":[]string{"QpBaAx81KXsfPoTa.9tpAu5VYLmAzDj9"}, "Server":[]string{"AmazonS3"}}
Nov  1 2017 21:02:21.526Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:135] [882.925664ms] https://registry.hub.docker.com/v2/library/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Nov  1 2017 21:02:21.526Z INFO  diffID for layer c33a7c3535692e8ca015bebc3a01f7a72b14cc013918c09c40d808efe1505c62: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Nov  1 2017 21:02:21.526Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageBlob:168] [883.530547ms] library/busybox/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Nov  1 2017 21:02:21.687Z WARN  session keepalive error: ServerFaultCode: The session is not authenticated.
Nov  1 2017 21:02:21.726Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:135] [1.083984285s] https://registry.hub.docker.com/v2/library/busybox/blobs/sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e
Nov  1 2017 21:02:21.796Z INFO  diffID for layer 00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6: sha256:6a749002dd6a65988a6696ca4d0c4cbe87145df74e3bf6feae4025ab28f420f2
Nov  1 2017 21:02:21.803Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageBlob:168] [1.16119182s] library/busybox/sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e
Nov  1 2017 21:02:21.803Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*ImageC).WriteImageBlob:324] 00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6
Nov  1 2017 21:02:21.803Z INFO  Path: /tmp/https/registry.hub.docker.com/v2/library/busybox/latest/00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6/00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6.tar
Nov  1 2017 21:02:21.803Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.WriteImage:82] 00e34fc12d885133ebb172d49a70fb5f6df2f3207a58a3b761e70692ec3727d6
Nov  1 2017 21:02:21.842Z DEBUG Creating an image failed: [POST /storage/{store_name}][500] WriteImage default  &{Code:500 Message:ServerFaultCode: The session is not authenticated.}
```

[22-2-vCenter-Restart-VCH-0-8926-container-logs.zip](https://github.com/vmware/vic/files/1435733/22-2-vCenter-Restart-VCH-0-8926-container-logs.zip)

From https://github.com/vmware/vic/pull/6222

**Comment by anchal-agrawal** [comment] 2017-11-20 19:19
@mhagen-vmware Is this a new test under development? Is there a branch where I can view the test steps?

**Comment by anchal-agrawal** [comment] 2017-11-20 21:18
The personality logs end with:

```
Nov  1 2017 21:02:22.190Z INFO  session keepalive re-authenticated
```

@mhagen-vmware Did a retry of the pull operation resolve the issue?

**Comment by anchal-agrawal** [comment] 2017-11-27 22:43
session keepalive messages in personality logs:

```
Nov  1 2017 21:00:01.467Z WARN  session keepalive error: Post https://10.161.179.146/sdk: read tcp 10.192.74.211:39664->10.161.179.146:443: read: connection reset by peer
Nov  1 2017 21:00:21.481Z WARN  session keepalive error: Post https://10.161.179.146/sdk: dial tcp 10.161.179.146:443: getsockopt: connection refused
Nov  1 2017 21:00:41.498Z WARN  session keepalive error: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x000055a7acf59320] _serverNamespace = /sdk action = Allow _port = 8085)
Nov  1 2017 21:01:01.515Z WARN  session keepalive error: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x000055a7acf59320] _serverNamespace = /sdk action = Allow _port = 8085)
Nov  1 2017 21:01:21.533Z WARN  session keepalive error: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x000055a7acf59320] _serverNamespace = /sdk action = Allow _port = 8085)
Nov  1 2017 21:01:41.550Z WARN  session keepalive error: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x000055a7acf59320] _serverNamespace = /sdk action = Allow _port = 8085)
Nov  1 2017 21:02:01.570Z WARN  session keepalive error: 503 Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http16LocalServiceSpecE:0x000055a7acf59320] _serverNamespace = /sdk action = Allow _port = 8085)
...
<docker info succeeds>
...
<docker pull starts>
Nov  1 2017 21:02:21.687Z WARN  session keepalive error: ServerFaultCode: The session is not authenticated.
...
<docker pull fails with session error>
...
Nov  1 2017 21:02:22.190Z INFO  session keepalive re-authenticated
```

The keepalive duration is set to 20 seconds: https://github.com/vmware/vic/blob/6a956c04c528b5437741e43a91efe5f35b339515/lib/apiservers/portlayer/restapi/options/options.go#L24

It was changed from 5m to 20s in https://github.com/vmware/vic/pull/5350. As seen in the snippet above, the session is refreshed every 20s and finally re-authenticated. As annotated in the snippet, the test performs a `docker info` (which succeeds), followed by a `docker pull` which fails due to the session error. There are a few approaches to resolve this:
1. reduce the keepalive from 20s to a smaller value
2. pause the test for a minute or two after the VC is restarted and the VCH is up - this should allow time for the session to re-authenticate before running the `docker pull` operation

Assuming 1. is implemented with a new value (say 5s), 2. will still be needed to ensure that the session is re-authenticated. I'll see if there are other solutions and if there are performance implications to reducing the keepalive duration.

**Comment by hickeng** [comment] 2017-11-28 01:30
(1) is still not ideal, nor is reauthenticating via the keepalive handler. @dougm may recall other reasons, but iirc the keepalive handler was used because it was an existing mechanism.

I was advocating for a conditional trigger style mechanism in govmomi similar to what we ended up implementing in the `tasks` and `retry` packages but that applies to all operations on a session instead of wrapping specific operations.

I'd prefer:
1. trigger in govmomi to reauth, or
2. handling in tasks/retry package to reauth when needed

**Comment by dougm** [comment] 2017-11-28 18:04
I don't recall exactly why either, but the session package could make use of vim25.Retry, just do something like this: https://github.com/vmware/govmomi/blob/master/vim25/retry.go#L30-L33

But checking for the auth error and calling Login within the RetryFunc impl.

**Comment by anchal-agrawal** [comment] 2017-11-29 22:10
I have a WIP for adding a retry mechanism in the session pkg here: https://github.com/anchal-agrawal/vic/commit/3e27716e9b7a5c9541057851907d6fbf93a4b52a. To test it, I did the following:

1. Create VCH on VC, pull image, create containerVM
2. Reboot VC
3. When VC and VCH are up again, pull another image

3 fails with the same "session not authenticated" error, and I don't see any log messages from the session retry logic I wrote. Upon retrying 3, it succeeds - although I still didn't see any logs from the logic I added. I'm guessing the session was re-established _temporarily_ via some other mechanism, because eventually the VCH got into a state where a container create operation would fail with
```
Error response from daemon: Server error from portlayer: [POST /scopes/{scope}/containers][500] addContainerInternalServerError  &{Code:0 Message:NotAuthenticated}
```
and this was unrecoverable.

I think I'm missing a retry trigger somewhere, or this retry needs to be placed in the actual operations themselves. Or if we wish to keep the keepalive mechanism (cc @hickeng) and reduce the duration, I can do that.

**Comment by mdubya66** [comment] 2017-12-06 19:27
@mlh78750 says "Not critical, but if we could do better here we should."

**Comment by anchal-agrawal** [comment] 2017-12-08 21:13
Release note entry if this is not included in 1.3:

---
After a vCenter or ESXi restart, a docker operation may fail due to a "NotAuthenticated" or "session not authenticated" error.

This is because the session authentication keepalive duration is 20 seconds and the session may not have re-authenticated yet. Workaround: retry the operation after a few seconds.

**Comment by mlh78750** [comment] 2017-12-08 22:02
Let's release note this and defer from 1.3.

**Comment by anchal-agrawal** [comment] 2017-12-08 22:03
cc @stuclem for the release note - thanks!

**Comment by stuclem** [comment] 2018-01-09 19:28
Attempt at release note:

- <b>Docker operations fail with the `NotAuthenticated` or `session not authenticated` errors. [#6673](https://github.com/vmware/vic/issues/6673)</b><br>This issue occurs after restarting vCenter or ESXi hosts  because the keepalive duration for the authentication of the session is 20 seconds and the session might not have re-authenticated yet.

   Workaround: retry the operation after a few seconds.

@anchal-agrawal does this cover it?

**Comment by anchal-agrawal** [comment] 2018-01-10 03:36
Looks good!

**Comment by stuclem** [comment] 2018-01-10 11:00
Thanks @anchal-agrawal !

**Comment by vburenin** [comment] 2018-02-12 20:41
@anchal-agrawal I have difficulties reproducing this bug. Immediately after VC becomes active docker pull succeeds with no errors. Can you provide more details for these steps?
```
Create VCH on VC, pull image, create containerVM
Reboot VC
When VC and VCH are up again, pull another image
```

I wonder about placement of components and how you reboot VC. (I basically press reset button).

**Comment by anchal-agrawal** [comment] 2018-02-13 17:01
@vburenin This bug was initially seen in this test: https://github.com/vmware/vic/pull/6222/files#diff-1cf7982f0fa928cde29963fd3ce8f435 (not merged yet). We can attempt to repro by running that test locally (with a pre-deployed vCenter to save time).

I was able to repro in https://github.com/vmware/vic/issues/6673#issuecomment-350373337 because my session re-auth logic was not entirely correct, causing the session to not get re-authenticated at all after a VC restart.

**Comment by vburenin** [comment] 2018-02-21 17:19
Hm, I have not been able to reproduce this issue for a while with ESXi or VC. I see the re-authentication happens and everything keeps working as expected. I unassigned  myself and have put this issue into TODO list for now.

**Comment by vburenin** [comment] 2018-02-27 20:55
Closing as can't repro. However, let's still keep eyes on it.

**Closed** 2018-02-27 20:55 UTC
Labels: component/vmomi-gateway, kind/bug, priority/p0, team/container
