### ISSUE TITLE
Need to split tests into tiers

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1488] opened 2016-07-13 20:13 UTC
Please comment with opinions and ideas on what makes sense. 

I'll start and throw this out:

Add different test profiles:
1) lightweight subset of test that exercise core functions that runs for every commit.
2) medium size subset that runs every X amount of time (propose 1 hour)
3) full suite that runs every night.

We may choose to move over to med or full tests per commit as we get closer to a release. But for normal commits we could go with something lightweight.

**Comment by corrieb** [comment] 2016-07-13 20:26
Assigning to Mike. This is high priority, because for onsite we need to significantly increase the scope of our integration tests and it will be unsustainable to do that without this split

**Comment by sflxn** [comment] 2016-07-13 20:38
Which one does our current CI run for PR today?  It currently runs > 1hr.  Given the proposal that profile 2 to run every hour, it might clog up the CI during periods of large numbers of PRs (e.g. close to release time).

**Comment by corrieb** [comment] 2016-07-13 20:39
@sflxn part of the goal of this is to reduce the load on the CI system. the hourly/nightly tests don't have to run on the same hardware

**Comment by corrieb** [comment] 2016-07-13 20:44
In terms of tests we need to add to our nightly suite:
- Regression tests (we badly need to catch up on that and get into the habit of doing it)
- Medium-level stress tests (single client within the bounds of what we think is reasonable)
- Expand functional testing to meet the test plan we already have drawn up
- Negative testing (fat fingering dumb stuff) how do we react?
- Demo workflows (when we get more demo focussed, we should encode them into our tests)
- Pulling, running and testing popular images (etcd, nginx etc)
- Testing some of the application topologies we claim to support

**Comment by mlh78750** [comment] 2016-07-13 20:44
@sflxn: Our CI runs everything now. But we are way under-testing. We need to be doing a better job writing tests. If we make a big push to improve automated testing right now and it takes 3x longer after we add a bunch of tests, then we are going to need a priority and tiering to the tests to make this work.

**Comment by mhagen-vmware** [comment] 2016-07-19 19:42
Please see https://github.com/vmware/vic/pull/1549

This is the start of what I would like to do, you can see I have implemented a bit more tagging, cleaned up the drone file, and introduced a really fast regression test.  I think we need to expand the regression test some more - not too much, but it is very basic right now.  With the conditional statement in the integration.sh now though we can manage the tiering however we want including if we ultimately introduce a new branch (staging or dev), we can run a different set of tests based on the branch as well.  Time based will be a whole different beast, as drone is not setup to do time based scheduling.

**Comment by mhagen-vmware** [comment] 2016-08-16 17:00
Calling this done now, based on our meetings in SF and the agreement on the QA presentation I gave to the leads then the entire team.

**Closed by mhagen-vmware** 2016-08-16 17:00 UTC
Labels: area/infra
