### ISSUE TITLE
VCH Install Stress failure: Failed to power on appliance A specified parameter was not correct: path

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3345] opened 2016-11-28 21:04 UTC
```
[34mINFO[0m[2016-11-28T07:00:16-06:00] Uploading images for container               
[34mINFO[0m[2016-11-28T07:00:16-06:00] 	"bin/bootstrap.iso"                         
[34mINFO[0m[2016-11-28T07:00:16-06:00] 	"bin/appliance.iso"                         
[37mDEBU[0m[2016-11-28T07:00:44-06:00] unexpected fault on task retry : &types.InvalidArgument{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, InvalidProperty:"path"} 
[37mDEBU[0m[2016-11-28T07:00:44-06:00] Do not fix non invalid state error           
[34mINFO[0m[2016-11-28T07:00:44-06:00] Collecting dc112ee5-1570-4c87-8d33-60c3fd66f00c vpxd.log 
[31mERRO[0m[2016-11-28T07:00:44-06:00] Failed to power on appliance A specified parameter was not correct: path. Exiting... 
```

**Comment by mhagen-vmware** [comment] 2016-11-28 21:25
[vmware-logs.zip](https://github.com/vmware/vic/files/617505/vmware-logs.zip)

**Comment by mhagen-vmware** [comment] 2016-11-28 21:28
This was on the 15th iteration of install stress test.

**Comment by hickeng** [comment] 2016-11-28 22:16
This is almost certainly the same as #3022 but I cannot confirm as I've been unable to find the equivalent log in the support bundle.

**Comment by jzt** [comment] 2016-11-28 22:24
@hickeng I have grabbed all logs from bart.eng.vmware.com. I can supply you with whichever you need (I assumed it was vpxd.log).

**Comment by jzt** [comment] 2016-11-28 22:29
I believe this is the log containing references to this vm (I searched on `dc112ee5-1570-4c87-8d33-60c3fd66f00c`):

[vpxd-25.log.zip](https://github.com/vmware/vic/files/617657/vpxd-25.log.zip)

**Comment by hickeng** [comment] 2016-11-28 22:43
Confirmed that this is the same as 3022.

**Comment by mdubya66** [comment] 2016-11-28 22:58
Closing as a duplicate of #3022

**Closed** 2016-11-28 22:57 UTC
Labels: kind/bug
