### ISSUE TITLE
vic-machine validation: check if datastore is connected to all hosts in VC cluster

### ISSUE THREAD

**Issue by emlin** [vmware/vic#1166] opened 2016-06-21 19:19 UTC
vic-machine validation should verify if there is common hosts exist, with user specified parameters, VC cluster, image datastore, volume datastore, and dvSwitch.
If not fail the creation gracefully.

**Comment by emlin** [comment] 2016-08-01 18:40
Network checking is tracked in #802, so I would like to have this track the datastore connection only.

**Comment by emlin** [comment] 2016-08-01 18:43
@hickeng for the datastore connection checking, if we had this checking, user will have to use shared datastore in VC env. Is that a common scenario?
Anddo we need to enforce this requirement to all datastore configured? Image store, volume store and container stores?

**Comment by emlin** [comment] 2016-08-12 17:01
@hickeng Please help to confirm on this issue. thanks

**Comment by hickeng** [comment] 2016-08-15 17:09
@emlin The currently model absolutely requires a shared datastore for images.

With work we could allow more flexibility here at the expense of constrained placement of VMs on hosts, but for the moment we don't have that capability.

If there is only one host that is attached to all the datastores specified for the various stores then we should absolutely warn the customer as it impacts ability to do high availability and maintenance. I think that should require --force to deploy.

**Comment by emlin** [comment] 2016-08-15 17:38
ok, fair enough.

**Comment by emlin** [comment] 2016-08-29 15:44
@gigawhitlocks as we discussed last week, #1974 is duplicate with this issue, so reassign this one to you.

**Comment by gigawhitlocks** [comment] 2016-09-08 00:27
This is a duplicate of #1974 and was fixed in  #2126

**Closed by gigawhitlocks** 2016-09-08 00:27 UTC
Labels: area/vsphere, component/vic-machine
