### ISSUE TITLE
vic api

### ISSUE THREAD

**Issue by nickcooper-zhangtonghao** [vmware/vic#5786] opened 2017-07-21 03:13 UTC
if we do not use the vic-machine-xxx to create/delete VCH, there is api we can use ?
if so, where i can find the api doc ? thanks.

**Comment by mdubya66** [comment] 2017-07-21 14:11
There is no API today. We have an open issue that we will be taking on soon. https://github.com/vmware/vic/issues/5721. Closing this as a duplicate of that issue.

**Closed by mdubya66** 2017-07-21 14:11 UTC
Labels: duplicate, kind/question
