### ISSUE TITLE
Nightly failure: 'Check for the proper log files' failed

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4389] opened 2017-03-24 20:23 UTC
Keyword 'Check For The Proper Log Files' failed after retrying 5 times. The last error was: '-rw-r----- 0/0             265 2017-03-24 01:12 proc-self-fd
-rw-r----- 0/0          379395 2017-03-24 01:12 portlayer/heap
-rw-r----- 0/0            1711 2017-03-24 01:12 proc-mounts
-rw-r----- 0/0             180 2017-03-24 01:12 ip-route
-rw-r----- 0/0            2088 2017-03-24 01:12 iptables
-rw-r----- 0/0               6 2017-03-24 01:12 VERSION
-rw-r----- 0/0           10079 2017-03-24 01:12 vicadm/concise
-rw-r----- 0/0          278232 2017-03-24 01:12 vicadm/heap
-rw-r----- 0/0            3836 2017-03-24 01:12 vic-init/heap
-rw-r----- 0/0              62 2017-03-24 01:12 uptime
-rw-r----- 0/0             204 2017-03-24 01:12 free
-rw-r----- 0/0              68 2017-03-24 01:12 disk-by-label
-rw-r----- 0/0            3788 2017-03-24 01:12 ps
-rw-r----- 0/0          228183 2017-03-24 01:12 journalctl
-rw-r----- 0/0          220111 2017-03-24 01:12 dmesg
-rw-r----- 0/0             129 2017-03-24 01:12 sys-block
-rw-r----- 0/0             517 2017-03-24 01:12 ip-link
-rw-r----- 0/0              82 2017-03-24 01:12 disk-by-uuid
-rw-r----- 0/0            1259 2017-03-24 01:12 ip-addr
-rw-r----- 0/0           25559 2017-03-24 01:12 portlayer/verbose
    [ Message content over the limit has been removed. ]
-rw-r----- 0/0            1241 2017-03-24 01:12 lsmod
-rw-r----- 0/0             113 2017-03-24 01:12 lsblk
-rw-r----- 0/0          158455 2017-03-24 01:12 var/log/vic/vicadmin.log
-rw-r----- 0/0          890333 2017-03-24 01:12 hostd/HostSystem:host-10 @ /ha-datacenter/host/cls/10.192.206.193
-rw-r----- 0/0              41 2017-03-24 01:12 vicadm/block
-rw-r----- 0/0          373365 2017-03-24 01:12 appliance/tether.debug
-rw-r----- 0/0          212991 2017-03-24 01:12 inspiring_barde-3f091f1cd70a760bd92278acdf243251c902f37549771c43ea4dd6c2ee6d9c3c/vmware.log
-rw-r----- 0/0           26707 2017-03-24 01:12 inspiring_barde-3f091f1cd70a760bd92278acdf243251c902f37549771c43ea4dd6c2ee6d9c3c/tether.debug
-rw-r----- 0/0              82 2017-03-24 01:12 disk-by-path
-rw-r----- 0/0            1195 2017-03-24 01:12 meminfo
-rw-r----- 0/0           17776 2017-03-24 01:12 portlayer/concise
-rw-r----- 0/0           94663 2017-03-24 01:12 var/log/vic/port-layer.log
-rw-r----- 0/0            7177 2017-03-24 01:12 inspiring_barde-3f091f1cd70a760bd92278acdf243251c902f37549771c43ea4dd6c2ee6d9c3c/output.log
-rw-r----- 0/0           35655 2017-03-24 01:12 docker/verbose
-rw-r----- 0/0           11294 2017-03-24 01:12 docker/concise' does not contain 'inspiring_bardeen-3f091f1cd70a/output.log'
[log.html.zip](https://github.com/vmware/vic/files/869099/log.html.zip)

**Comment by rajanashok** [comment] 2017-03-24 20:50
This is apparently caused due to the timing of the test code that the nightlies pulled in. We should not see this for the future builds, but in any case we need to fetch the commit the bintray build is tied to so we don't see this happening again.

**Comment by rogeliosanchez** [comment] 2018-04-20 20:05
Seen in Nightly 6.5 - 2018-04-19

5-3-Enhanced-Linked-Mode: Check For The Proper Log Files

VIC version:
v1.5.0-dev-18481-023de08

![screen shot 2018-04-20 at 2 58 55 pm](https://user-images.githubusercontent.com/26554503/39071142-95ada2cc-44ab-11e8-9cbc-1dcfeb38c47a.png)

Vic machine
[vic-machine.log](https://github.com/vmware/vic/files/1933493/vic-machine.log)

VCH logs
[vch-0-8702.zip](https://github.com/vmware/vic/files/1933502/vch-0-8702.zip)

Nightly Summary
[65.zip](https://github.com/vmware/vic/files/1933504/65.zip)

Link to logs
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-19-00-26-56.zip?authuser=1

More logs
[Suites.Group5-Functional-Tests.5-3-Enhanced-Linked-Mode-VCH-0-8702-container-logs.zip](https://github.com/vmware/vic/files/1933507/Suites.Group5-Functional-Tests.5-3-Enhanced-Linked-Mode-VCH-0-8702-container-logs.zip)

**Comment by AngieCris** [comment] 2018-04-27 22:46
Nightly 04/27/18
VC 6.0
Test suite: 5-22-OPS-User-Grant
Test step: Regression test

command:
```
tar tvzf container-logs.tar.gz 2>&1
```

output:
```
-rw-r----- 0/0             204 2018-04-27 04:33 free
-rw-r----- 0/0             517 2018-04-27 04:33 ip-link
-rw-r----- 0/0            1261 2018-04-27 04:33 ip-addr
-rw-r----- 0/0              68 2018-04-27 04:33 disk-by-label
-rw-r----- 0/0           36241 2018-04-27 04:33 docker/verbose
-rw-r----- 0/0          484584 2018-04-27 04:33 portlayer/heap
-rw-r----- 0/0           38992 2018-04-27 04:33 vicadm/verbose
-rw-r----- 0/0            1922 2018-04-27 04:33 proc-mounts
-rw-r----- 0/0             113 2018-04-27 04:33 lsblk
-rw-r----- 0/0             265 2018-04-27 04:33 proc-self-fd
-rw-r----- 0/0          174531 2018-04-27 04:33 journalctl
-rw-r----- 0/0          166994 2018-04-27 04:33 dmesg
-rw-r----- 0/0          262766 2018-04-27 04:33 vicadm/heap
-rw-r----- 0/0          117027 2018-04-27 04:33 docker/heap
-rw-r----- 0/0            1569 2018-04-27 04:33 lsmod
-rw-r----- 0/0              82 2018-04-27 04:33 disk-by-path
-rw-r----- 0/0           12521 2018-04-27 04:33 docker/concise
-rw-r----- 0/0              41 2018-04-27 04:33 vicadm/block
-rw-r----- 0/0             177 2018-04-27 04:33 ip-route
-rw-r----- 0/0            1195 2018-04-27 04:33 meminfo
-rw-r----- 0/0           19830 2018-04-27 04:33 portlayer/concise
tar: Skipping to next header

gzip: stdin: invalid compressed data--format violated
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Link to logs: https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-04-26-20-32-56.zip?authuser=1

**Comment by anchal-agrawal** [comment] 2018-04-27 23:02
The failure in the issue description is different from the ones in the comments. Since the original issue is no longer present, we should either

* update the issue title and description with the failures mentioned in the comments, or
* close this issue and open another with the failures mentioned in the comments

**Closed** 2018-05-08 21:12 UTC
Labels: component/test, kind/nightly-blocker, priority/p0, team/lifecycle
