### ISSUE TITLE
Error response from daemon: vSphere Integrated Containers does not implement image.LoadImage

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1028] opened 2016-06-09 16:50 UTC
This is a failure in the docker integration tests. Not really anymore details than the subject. Lots of instances of this, we need to implement this seemingly if we want to be able to run the tests at all.

**Comment by hickeng** [comment] 2016-06-19 20:43
This is a subtask of #373 that is not yet broken out into a separate task. This is not in scope for GA. @mhagen-vmware we need to know what % of the docker integration tests are impacted by the lack of this function.
This is not one that'd be hard to do as it's basically the same workflow that imagec already performs, however it's not currently in scope.

**Comment by mdubya66** [comment] 2017-01-31 17:33
running docker integration tests are not a priority. making this low.

**Comment by anchal-agrawal** [comment] 2017-06-05 01:08
Closing as duplicate of https://github.com/vmware/vic/issues/2128.

**Closed by anchal-agrawal** 2017-06-05 01:08 UTC
Labels: component/docker-api-server, priority/low
