### ISSUE TITLE
5-14-Remove-Container-OOB nightly fails in vic-machine create: upload image isos EOF and waiting for IP info exceeded context deadline

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#6933] opened 2017-12-08 17:28 UTC
vSphere 6.5, nightly on 12/06/17, test 5-14-Remove-Container-OOB

vic-machine.log:
```
Dec  6 2017 03:25:28.380-06:00 WARN  op=12606.1: failed an attempt to upload isos with err (Put https://10.161.101.215/folder/VCH-0-2914/V1.3.0-RC1-15228-0013443-appliance.iso?dcPath=%2Fha-datacenter&dsName=datastore1: EOF), 4 retries remain
Dec  6 2017 03:25:28.380-06:00 WARN  Will try again in 11.04660288s. Operation failed with detected error
Dec  6 2017 03:25:46.231-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1m9.935285523s] 
Dec  6 2017 03:25:46.231-06:00 DEBUG [ END ] op=12606.1 [vic/lib/install/management.(*Dispatcher).uploadImages:115] [1m9.936221061s] 
Dec  6 2017 03:25:46.231-06:00 DEBUG [BEGIN] op=12606.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100]
Dec  6 2017 03:25:47.357-06:00 DEBUG [ END ] op=12606.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100] [1.126537269s] 
Dec  6 2017 03:25:47.357-06:00 DEBUG [ END ] op=12606.1 [vic/lib/install/management.(*Dispatcher).CreateVCH:42] [1m15.611957729s] VCH-0-2914
Dec  6 2017 03:25:47.357-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes:1066]
Dec  6 2017 03:25:47.357-06:00 INFO  op=12606.1: Waiting for IP information
Dec  6 2017 03:25:47.358-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.networks|client.assigned.IP
Dec  6 2017 03:55:47.358-06:00 ERROR op=12606.1: vic/pkg/trace.(*Operation).Err: Create error: context deadline exceeded
```
log shows two errors during VCH install: failed to upload image isos to datastore (EOF), and context deadline exceeded in waiting for IP information.

(Possible similar failures in 13-1-vMotion-VCH-Appliance and 5-6 VSAN tests: https://github.com/vmware/vic/issues/5447, https://github.com/vmware/vic/issues/5042
But we can't confirm about waiting for IP exceeded context deadline on these ones)

Log:
[5-14-Remove-Container-OOB.zip](https://github.com/vmware/vic/files/1543441/5-14-Remove-Container-OOB.zip)

**Comment by AngieCris** [comment] 2017-12-08 17:38
The step waiting for IP information exceeds context deadline in this code (https://github.com/vmware/vic/blob/master/lib/install/management/appliance.go#L1072):
```
	d.op.Info("Waiting for IP information")
	d.waitForKey(extraconfig.CalculateKeys(conf, "ExecutorConfig.Networks.client.Assigned.IP", "")[0])
	ctxerr := d.op.Err()
``
It fails in `d.waitForKey`.
Since uploading isos failed in EOF, it's probably because the VC connection somehow cuts down in the middle of the POST request, and then it can't grab IP because of it (need further investigation on this)

**Comment by AngieCris** [comment] 2017-12-08 22:11
Seen in nightly 12/07/17, VC 6.5, 5-8-DRS

vic-machine.log (looks pretty much the same):
```
Dec  7 2017 01:08:36.280-06:00 WARN  op=6825.1: failed an attempt to upload isos with err (Put https://10.160.155.91/folder/VCH-0-5410/V1.3.0-RC2-15248-5687DDD-appliance.iso?dcPath=%2Fha-datacenter&dsName=datastore1: EOF), 4 retries remain
Dec  7 2017 01:08:36.281-06:00 WARN  Will try again in 11.04660288s. Operation failed with detected error
Dec  7 2017 01:08:54.062-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1m14.709342605s] 
Dec  7 2017 01:08:54.062-06:00 DEBUG [ END ] op=6825.1 [vic/lib/install/management.(*Dispatcher).uploadImages:115] [1m14.710935249s] 
Dec  7 2017 01:08:54.062-06:00 DEBUG [BEGIN] op=6825.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100]
Dec  7 2017 01:08:55.581-06:00 DEBUG [ END ] op=6825.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100] [1.519212023s] 
Dec  7 2017 01:08:55.581-06:00 DEBUG [ END ] op=6825.1 [vic/lib/install/management.(*Dispatcher).CreateVCH:42] [1m19.704854198s] VCH-0-5410
Dec  7 2017 01:08:55.581-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes:1066]
Dec  7 2017 01:08:55.581-06:00 INFO  op=6825.1: Waiting for IP information
Dec  7 2017 01:08:55.581-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.networks|client.assigned.IP
Dec  7 2017 01:38:55.582-06:00 ERROR op=6825.1: vic/pkg/trace.(*Operation).Err: Create error: context deadline exceeded
vic/cmd/vic-machine/create.(*Create).Run:741 Create
vic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux
Dec  7 2017 01:38:55.776-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [30m0.194639251s] guestinfo.vice..init.networks|client.assigned.IP
Dec  7 2017 01:38:55.776-06:00 ERROR op=6825.1: vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes: Create error: context deadline exceeded
vic/cmd/vic-machine/create.(*Create).Run:741 Create
vic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux
Dec  7 2017 01:38:55.776-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).applianceConfiguration:755]
Dec  7 2017 01:38:55.776-06:00 DEBUG [BEGIN] op=6825.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:519] VM(VirtualMachine:vm-29) Properties([config.extraConfig])
Dec  7 2017 01:38:55.776-06:00 DEBUG op=6825.1: properties: [config.extraConfig summary.runtime.connectionState]
Dec  7 2017 01:38:55.776-06:00 ERROR op=6825.1: vic/pkg/trace.(*Operation).Err: Create error: context deadline exceeded
```

Log bundle: 
[5-8-DRS.zip](https://github.com/vmware/vic/files/1543943/5-8-DRS.zip)

**Comment by AngieCris** [comment] 2017-12-11 16:43
Seen again in nightly 12/08/17, build 15259, VC 6.5, 5-14-Remove-Container-OOB
Log bundle: [5-14-Remove-Container-OOB.zip](https://github.com/vmware/vic/files/1548577/5-14-Remove-Container-OOB.zip)

**Comment by AngieCris** [comment] 2017-12-17 05:02
Seen again in nightly 12/15/17, VC 6.5, 5-12-Multiple-VLAN

Log: [5-12-Multiple-VLAN.zip](https://github.com/vmware/vic/files/1565330/5-12-Multiple-VLAN.zip)

**Comment by anchal-agrawal** [comment] 2017-12-19 09:18
Backlog items must have a priority - moving to Not Ready and assigning to reporter and/or triager.

**Comment by AngieCris** [comment] 2017-12-26 00:32
Seen again in nightly 12/21/17, VC 6.0, 5-8 DRS

vic-machine.log:
```
Dec 22 2017 13:38:17.705-06:00 WARN  op=13307.1: failed an attempt to upload isos with err (Put https://10.161.224.244/folder/VCH-0-4265/V1.3.0-RC4-15374-B5EE291-appliance.iso?dcPath=%2Fha-datacenter&dsName=datastore1: EOF), 4 retries remain
Dec 22 2017 13:38:17.705-06:00 WARN  Will try again in 11.04660288s. Operation failed with detected error
Dec 22 2017 13:39:22.709-06:00 WARN  op=13307.1: failed an attempt to upload isos with err (Put https://10.161.224.244/folder/VCH-0-4265/V1.3.0-RC4-15374-B5EE291-appliance.iso?dcPath=%2Fha-datacenter&dsName=datastore1: EOF), 3 retries remain
Dec 22 2017 13:39:22.709-06:00 WARN  Will try again in 1m26.430545283s. Operation failed with detected error
Dec 22 2017 13:41:37.714-06:00 WARN  op=13307.1: failed an attempt to upload isos with err (Put https://10.161.224.244/folder/VCH-0-4265/V1.3.0-RC4-15374-B5EE291-appliance.iso?dcPath=%2Fha-datacenter&dsName=datastore1: EOF), 2 retries remain
Dec 22 2017 13:41:37.714-06:00 WARN  Will try again in 1m9.873603193s. Operation failed with detected error
Dec 22 2017 13:42:56.747-06:00 DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [5m28.480000416s] 
Dec 22 2017 13:42:56.747-06:00 DEBUG [ END ] op=13307.1 [vic/lib/install/management.(*Dispatcher).uploadImages:115] [5m28.481169718s] 
Dec 22 2017 13:42:56.748-06:00 DEBUG [BEGIN] op=13307.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100]
Dec 22 2017 13:43:00.009-06:00 DEBUG [ END ] op=13307.1 [vic/lib/install/management.(*Dispatcher).startAppliance:100] [3.261180553s] 
Dec 22 2017 13:43:00.009-06:00 DEBUG [ END ] op=13307.1 [vic/lib/install/management.(*Dispatcher).CreateVCH:42] [5m34.996599328s] VCH-0-4265
Dec 22 2017 13:43:00.009-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes:1066]
Dec 22 2017 13:43:00.009-06:00 INFO  op=13307.1: Waiting for IP information
Dec 22 2017 13:43:00.009-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.networks|client.assigned.IP
Dec 22 2017 14:13:00.009-06:00 ERROR op=13307.1: vic/pkg/trace.(*Operation).Err: Create error: context deadline exceeded
vic/cmd/vic-machine/create.(*Create).Run:741 Create
vic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux
Dec 22 2017 14:13:00.204-06:00 DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] [30m0.195207552s] guestinfo.vice..init.networks|client.assigned.IP
Dec 22 2017 14:13:00.205-06:00 ERROR op=13307.1: vic/lib/install/management.(*Dispatcher).ensureApplianceInitializes: Create error: context deadline exceeded
```

Bundle: [5-8-DRS.zip](https://github.com/vmware/vic/files/1586273/5-8-DRS.zip)

**Comment by andrewtchin** [comment] 2018-02-13 21:09
ask mike what can be done for this and check to see if there's a place we can add more logging, otherwise close

**Comment by mhagen-vmware** [comment] 2018-02-15 19:33
From that log snippet it is unclear to me that the IP address is the actual problem... both the Waiting for IP and upload iso operations have the exact same opid... I think we really need to break that up so that we can differentiate in our logs and if we actually timeout on the waiting for ip can we not print our network info so that we could actually see what that was set to while trying to get an IP?

**Comment by hickeng** [comment] 2018-02-26 17:53
We can see clearly that the timeout applies to the `Waiting for IP` step - in all of the examples there is a 30min delay between the two messages:
```
Dec  6 2017 03:25:47.357-06:00 INFO  op=12606.1: Waiting for IP information
Dec  6 2017 03:25:47.358-06:00 DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).waitForKey:768] guestinfo.vice..init.networks|client.assigned.IP
Dec  6 2017 03:55:47.358-06:00 ERROR op=12606.1: vic/pkg/trace.(*Operation).Err: Create error: context deadline exceeded
```

However, if the appliance iso upload failed I would not expect the VM to boot correctly - in these cases it looks like we _think_ we succeeded on the 4th attempt but it's not worked correctly given the endpointVM isn't booting.

When checking to see why the endpointVM didn't boot we look at `tether.debug` (unavailable in these log bundles for some reason) and the vmware.log for the system.

vmware.log from https://github.com/vmware/vic/issues/6933#issuecomment-353897820:
```
2017-12-22T19:42:58.744Z| vcpu-0| I125: CDROM: Connecting ide0:0 to 'V1.3.0-RC4-15374-B5EE291-appliance.iso'. type=2 remote=0
2017-12-22T19:42:58.744Z| vcpu-0| I125: AIOGNRC: Failed to open 'V1.3.0-RC4-15374-B5EE291-appliance.iso' : Failed to lock the file (40003) (0x21).
2017-12-22T19:42:58.744Z| vcpu-0| I125: CDROM-IMG:  image open for 'V1.3.0-RC4-15374-B5EE291-appliance.iso' failed: Failed to lock the file (40003).
2017-12-22T19:42:58.744Z| vcpu-0| I125: CDROM-IMG: Failed to connect 'V1.3.0-RC4-15374-B5EE291-appliance.iso'.
2017-12-22T19:42:58.744Z| vcpu-0| I125: CDROM: Failed to connect CDROM device 'V1.3.0-RC4-15374-B5EE291-appliance.iso'.
2017-12-22T19:42:58.745Z| vcpu-0| I125: Msg_Post: Warning
2017-12-22T19:42:58.745Z| vcpu-0| I125: [msg.cdromImage.cantOpen] Cannot connect file "V1.3.0-RC4-15374-B5EE291-appliance.iso" as a CD-ROM image: Failed to lock the file
2017-12-22T19:42:58.745Z| vcpu-0| I125: [msg.device.startdisconnected] Virtual device ide0:0 will start disconnected.
2017-12-22T19:42:58.745Z| vcpu-0| I125: ----------------------------------------
2017-12-22T19:42:58.748Z| vcpu-0| I125: Vigor_MessageRevoke: message 'msg.device.startdisconnected' (seq 18685) is revoked
<snip>
2017-12-22T19:43:58.986Z| vcpu-0| I125: [msg.Backdoor.OsNotFound] No operating system was found. If you have an operating system installation disc, you can insert the disc into the system's CD-ROM drive and restart the virtual machine.
2017-12-22T19:43:58.986Z| vcpu-0| I125: ----------------------------------------
```

It's very clear that the problem is the ISO file cannot be locked. This _may_ mean that it's still held open,. but if this is vSAN _could_ relate to #6701 which shows the same error after a vMotion during power on for the tether.debug file.

A quick search of the issues also shows #7050 with exactly the same symptoms after a vMotion but for bootstrap.iso.

Was this VM vMotioning? I do not see any `migration` messages or `Restoring checkpoint` which are my normal indicators so I assume not.

**Hypthoeses**
a. vSAN DOM ownership has not transitioned from the host used for the datastore upload ticket (possible correlation with #6701)
b. the file is actively held open, presumably by the upload in some manner.

a. Not sure how to pursue this. Is it even vSAN? If so can check (or add logging for) the host used for the upload ticket and see if it's the same host as the one used for power on (from vmware.log - don't know if this is the VC or the host sc-rdops-vm08-dhcp-253-3.eng.vmware.com?).
b. Find a way to determine from the vSphere logs what is holding the file lock. Purely speculative; check whether we explicitly call cancel on the context for the filed operation to ensure that we shut everything down.

**Comment by andrewtchin** [comment] 2018-02-26 21:44
this is not on vsan and i don't think it was vmotioning. I think this is the cancel? https://github.com/vmware/vic/blob/master/cmd/vic-machine/create/create.go#L742

**Comment by hickeng** [comment] 2018-02-27 05:10
@andrewtchin Clarification - I'm talking about a cancel just for the failed image upload that we then retry. We want to _ensure_ that the underlying connection is torn down.

That would require a child context here: https://github.com/vmware/vic/blob/master/lib/install/management/create.go#L137 that was cancelled on exit from that `operation` function. That way we'd get a new context created for each attempt.

**Closed** 2018-03-15 14:11 UTC
Labels: component/test, kind/nightly-blocker, priority/p0, team/lifecycle
