### ISSUE TITLE
Problem with VIC Management Portal UI

### ISSUE THREAD

**Issue by shachideshpande** [vmware/vic#6115] opened 2017-08-25 20:07 UTC
[docker-personality.txt](https://github.com/vmware/vic/files/1252886/docker-personality.txt)
[init.txt](https://github.com/vmware/vic/files/1252887/init.txt)
[port-layer.txt](https://github.com/vmware/vic/files/1252888/port-layer.txt)
[vicadmin.txt](https://github.com/vmware/vic/files/1252889/vicadmin.txt)

**VIC version:**
trial version 6.5
**Deployment details:**

./vic-machine-linux create --target <target IP> --user 'Administrator@vsphere.local' --password <password> --image-store <image store name> --bridge-network <name of port group> --https-proxy <https proxy address> --http-proxy <http proxy address> --name <name of VCH>  --no-tlsverify --force --registry-ca=cert_path/ca.crt
 

**Steps to reproduce:**
I create VCH using above command, and then add this VCH as a VCH host with default-client-cert authentication on the management portal of VIC. If I have added containers to VCH from remote docker client I am able to see the containers on management portal. But I am not able to add new containers to this VCH using management portal UI to create new container. I have pushed one docker container image to the vic registry.

**Actual behavior:**
After clicking on 'Create Container', if I type in the name of container image, the search never gets completed, and I see the following warning message in the events log

Error(s) while trying to perform registry search: [not an SSL/TLS record: 3c68746d6c3e0d0a3c686561643e3c7469746c653e3430302042616420526571756573743c2f7469746c653e3c2f686561643e0d0a3c626f6479206267636f6c6f723d227768697465223e0d0a3c63656e7465723e3c68313e3430302042616420526571756573743c2f68313e3c2f63656e7465723e0d0a3c68723e3c63656e7465723e6e67696e783c2f63656e7465723e0d0a3c2f626f64793e0d0a3c2f68746d6c3e0d0a]

**Expected behavior:**
I would like to see the container getting created similar to how I can create containers from remote docker client by supplying IP address of VCH.

**Logs:**
Attached 4 log files from my VCH

**Comment by anchal-agrawal** [comment] 2017-08-25 21:45
@shachideshpande Did you deploy Admiral (Management Portal) with the VIC Product OVA or standalone?

The VCH logs show no evidence of a container create operation. This is likely an issue/question for the Admiral team: https://github.com/vmware/admiral. @sergiosagu, what could be the cause of this error?
```
Error(s) while trying to perform registry search: [not an SSL/TLS record: 3c68746d6c3e0d0a3c686561643e3c7469746c653e3430302042616420526571756573743c2f7469746c653e3c2f686561643e0d0a3c626f6479206267636f6c6f723d227768697465223e0d0a3c63656e7465723e3c68313e3430302042616420526571756573743c2f68313e3c2f63656e7465723e0d0a3c68723e3c63656e7465723e6e67696e783c2f63656e7465723e0d0a3c2f626f64793e0d0a3c2f68746d6c3e0d0a]
```

**Comment by shachideshpande** [comment] 2017-08-26 08:32
I deployed Admiral with VIC Product OVA.

**Comment by sergiosagu** [comment] 2017-08-28 07:35
@anchal-agrawal - The SSL error message seems to indicate that a particular SSL certificate to access some registry may be missing or wrongly imported in Admiral.

@shachideshpande - What container images did you try? Were they from Docker Hub, from the default Harbor registry or from any other registry that you added?

@mshipkovenski - Any quick idea?

**Comment by andrewtchin** [comment] 2017-09-11 16:55
@shachideshpande Did you deploy the OVA with TLS certificates that you provided or did you leave the fields blank so that the appliance generated self signed certs?

**Comment by shachideshpande** [comment] 2017-09-11 18:21
@andrewtchin I deployed OVA without TLS certificate (left that field blank)
@anchal-agrawal I tried the busybox container image taken from docker hub and uploaded it to the Harbor registry.

**Comment by andrewtchin** [comment] 2017-09-11 18:58
@shachideshpande Did you add the Harbor registry running on the VIC Appliance as a registry in the Admiral interface?

![screen shot 2017-09-11 at 1 57 30 pm](https://user-images.githubusercontent.com/1649165/30291677-3e34339a-96f9-11e7-857d-2869212caf95.jpg)

**Comment by shachideshpande** [comment] 2017-09-11 19:08
@andrewtchin Yes I have added the registry to admiral portal and I it is visible as in the screenshot above.

**Comment by andrewtchin** [comment] 2017-09-11 19:12
Can you SSH into the appliance and provide the output of `journalctl -u admiral` and `journalctl -u harbor`?

**Comment by andrewtchin** [comment] 2017-10-11 14:17
Closing this, please reopen if needed.
Please note an updated version of the VIC Appliance is available at https://my.vmware.com/en/web/vmware/info/slug/datacenter_cloud_infrastructure/vmware_vsphere_integrated_containers/1_2

**Closed by andrewtchin** 2017-10-11 14:17 UTC
Labels: product/admiral, product/ova, status/need-info
