### ISSUE TITLE
vic-machine delete throws error, but delete completes successfully

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#2120] opened 2016-08-24 19:13 UTC
When deleting the VCH via vic-machine via the following command:
` vic-machine-linux delete -t 'root:vagrant@192.168.175.131' -n vickie-esx" `

The following output occurs:
```
INFO[2016-08-24T18:04:57Z] ### Removing VCH ####
INFO[2016-08-24T18:04:57Z]
INFO[2016-08-24T18:04:57Z] VCH ID: VirtualMachine:10
INFO[2016-08-24T18:04:57Z] Removing VMs
ERRO[2016-08-24T18:04:57Z] Operation failed: Error caused by file /vmfs/volumes/567a44c7-67ea0133-584e-000c2956ea35/vickie-esx - (&{{} %!!(MISSING)s(*types.FileFault=&{{{<nil> []}} /vmfs/volumes/567a44c7-67ea0133-584e-000c2956ea35/vickie-esx}) Error caused by file /vmfs/volumes/567a44c7-67ea0133-584e-000c2956ea35/vickie-esx})
INFO[2016-08-24T18:04:57Z] Removing appliance VM network devices
INFO[2016-08-24T18:04:57Z] Bridge network was not created during VCH deployment, leaving it there
INFO[2016-08-24T18:04:57Z] Removing Resource Pool "vickie-esx"
INFO[2016-08-24T18:04:57Z] Completed successfully
```

The error is regarding the appliance vm, but appears to be a false error as everything is deleted and there are no items "orphaned" on the datastore.

Environment Details - Standalone ESXi:
```
Version:      6.0.0
Build:        3029758
OS type:      vmnix-x86
API type:     HostAgent
API version:  6.0
Product ID:   embeddedEsx
```

This is backed by a local datastore -- no vsan or network attached storage.  This occurs every time I delete from ESXi.

**Comment by emlin** [comment] 2016-08-25 21:44
@mdubya66 is this a p0 bug?
It's a regression, although it does not break test, it is one 100% reproducible issue.

**Comment by emlin** [comment] 2016-08-26 14:08
for closed by mistake

**Comment by emlin** [comment] 2016-08-26 15:12
@gigawhitlocks turns to be a regression cased by your change: https://github.com/vmware/vic/pull/2083
deleteImages will delete configured image datastore path. If custom image path is not configured, VCH name will be used. And for your above change, no default child directory created for image store. The image store path in guestinfo will be [datastore] virtual-container-host, which is the VCH VM folder.
So deleteImageStore method will fail cause the VCH VM is still alive. The risk is that if the VM is powered off, that might remove VCH VM files by mistake.

To fix this issue, few related things should be fixed as well:
- deleteImages failed but vic-machine delete does not.
- deleteVolumeStore does not contribute to error message as well. if we force to delete volume and also delete failed, vic-machine delete should fail before we start to delete VCH VM.
- based on this issue, it's appreciated to add integration test for vic-machine delete. There should not have unexpected error message printed.

**Comment by gigawhitlocks** [comment] 2016-08-31 16:10
Oh, yep, I know the cause of this. Augh.

**Closed** 2016-09-09 18:04 UTC
Labels: component/vic-machine, kind/bug
