### ISSUE TITLE
UI build failed for gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by emlin** [vmware/vic#2279] opened 2016-09-08 16:48 UTC
The merge build https://ci.vmware.run/vmware/vic/4671 failed. The last message is as following
```
$ tar --warning=no-unknown-keyword -xzf /tmp/$UI_INSTALLER_WIN_UTILS_ARCHIVE -C $UI_INSTALLER_WIN_PATH

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[info] build failed (exit code 2)
``` 
The change is not related to UI or UI build, and later on build passed as well. 

@mhagen-vmware for more information in case.

**Comment by jooskim** [comment] 2016-09-08 16:59
i removed the winscp binary yesterday and updated bintray. it's clearly because of the wrongly formatted tgz file. i'll correct the issue and let you know.

**Comment by jooskim** [comment] 2016-09-08 17:16
```$ wget -nv $BINTRAY_DOWNLOAD_PATH$UI_INSTALLER_WIN_UTILS_ARCHIVE -O /tmp/$UI_INSTALLER_WIN_UTILS_ARCHIVE
2016-09-07 22:15:02 URL:https://akamai.bintray.com/a4/a401786fa1d7b88d757ab2b3096c7e802d3b439f8eebb2b1d27df515bbc2e42d?__gda__=exp=1473287223~hmac=e12fed4e4691a8859c3974fda66084c9f9076f8cba5212707c3f9799929239bd&response-content-disposition=attachment;filename=%22vic_installation_utils_win.tgz%22&response-content-type=application/gzip&requestInfo=U2FsdGVkX1-7Qa8BxAFU9_YufLcQkVc95xN0LrL9ELCwxIUbnYErCWaSBOBeewjGOKGDjLV_c5oi9MsyOUwhUEbmNLUvOH2xbBWfcyfAUUPDi0WQhy3AShRO2SYJYS0DWhElGvrrxMm2Tz5doYYtQA [2269184/2269184] -> "/tmp/vic_installation_utils_win.tgz" [1]```

It seems that build 4671 used a defective `vic_installation_utils.win.tgz` which is about 2.2MB in size. I reuploaded the correct one yesterday after seeing this happen on my forked repo. The new binary has the size of about 1.2MB.

**Comment by jooskim** [comment] 2016-09-08 17:42
I'm now running a full ci on PR #2257 to see if the issue is gone. It turns out build 4671 downloaded a defective binary file which caused `tar` to throw an error. I also notice that build was created about 20 hours ago from now, when I was working on PR #2275 and this issue. So it seems that this build downloaded the defective file before I replaced it on Bintray.

**Comment by mhagen-vmware** [comment] 2016-09-08 19:02
Sounds good @jooskim , it sounds like this was a temporary issue that you have already fixed then.  Can you close this issue then please if my synopsis is correct?

**Comment by jooskim** [comment] 2016-09-08 19:40
@mhagen-vmware The latest build failed after merging the latest `vmware/master` branch. Following is the error that broke the test. That probably doesn't have to do with the issue we're talking about here though. Maybe I could rerun the test, but in other successful builds I noticed that those were picking up the right `tgz` file (size being 1326476 bytes)

**From 1-4**
```
Create linked containers that can ping                                | FAIL |
1 != 0
```

**Comment by jooskim** [comment] 2016-09-08 19:47
Closing the issue, as I've seen already in other recent successful builds that the new binary gets downloaded and expanded without an issue.

**Closed by jooskim** 2016-09-08 19:47 UTC
Labels: kind/bug/p0
