### ISSUE TITLE
vic-machine-{os} delete fails to cleanup properly if there are pulled images

### ISSUE THREAD

**Issue by isyarov** [vmware/vic#7359] opened 2018-02-22 15:35 UTC
vic-machine-{os} delete fails to cleanup properly if there are pulled images.

The container VMs and volumes are removed, but the images are not deleted and the respective folder on the datastore remains. All files related to the VCH deployment are also not cleaned up.
If the VCH is created and deleted without pulling any images, everything is cleaned up properly.
The delete commad output is normal, but running it with the  **--debug 3** option produces:
```
DEBU[0013] Failed to delete "[datastore0] virtual-container-host/VIC": Cannot delete file [datastore0] virtual-container-host/VIC
DEBU[0017] Image store parent directory not empty, leaving in place.
```

This happens if the VCH is created on a vCenter server, i have not tried it on just an ESX.
Trying to delete the folder from the vSphere web client manually fails with:
"Cannot delete file [datastore0] virtual-container-host"
All other files related to the VCH can be deleted, but the image files cannot.
SSH-ing to the ESX and deleting the folder manually succeeds

The vic-machine version is: v1.4.0-dev-0-8d92ff7

Steps to reproduce:
1. Create a VCH in a vCenter server. I used the following command:
```
./vic-machine-linux create --target {vcenter-ip} --user {username} --password {password} --bridge-network vch-bridge --image-store datastore0 --volume-store datastore0/vol
umes:default --no-tlsverify --thumbprint {vcenter-cert-thumbprint} --name virtual-container-host
```

2. With a docker client execute:
```
docker --tls -H {VCH-IP}:2376 pull alpine
```

3. Delete the VCH. I used the following command:
```
./vic-machine-linux delete --target {vcenter-ip} --user {username} --password {password} --force --name virtual-container-host
```

**Comment by AngieCris** [comment] 2018-02-22 20:01
@isyarov
> The delete commad output is normal, but running it with the --debug 3 option produces:
Does running delete with debug level less than 3 work for you?
If possible can you provide the complete log output for vic-machine delete command for debug level 3?
Thanks.

**Comment by isyarov** [comment] 2018-02-22 21:47
@AngieCris 
 
This is the output from the delete command with **--debug 3**
```
./vic-machine-linux delete --target {vcenter-ip} --user {username} --password {password} --force --debug 3 --name virtual-container-host

INFO[0000] ### Removing VCH ####
DEBU[0001] Accepting host "***" thumbprint ***
DEBU[0001] Creating VMOMI session with thumbprint ***
DEBU[0002] Session Environment Info:                     API Type=VirtualCenter API Version=6.5 Build=7092793 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=06bc6ae8-96e6-4a8b-9017-3ed1c33418d1 Vendor="VMware, Inc." Version=6.5.0
DEBU[0002] vSphere resource cache populating...
DEBU[0002] Cached dc:
DEBU[0002] Cached cluster:
DEBU[0003] Cached host:
DEBU[0004] Cached pool:
DEBU[0004] Cached folders:
DEBU[0004] Error count populating vSphere cache: (1)
DEBU[0004] new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
INFO[0004] Validating target
DEBU[0004] Using default resource pool for compute resource: "/vcqaDC/host/cls/Resources"
DEBU[0007] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0007] Cannot find image stores from configuration; attempting to find from vm datastore
DEBU[0007] properties: [datastore summary.runtime.connectionState]
INFO[0010]
INFO[0010] VCH ID: VirtualMachine:vm-126
DEBU[0010] properties: [config.extraConfig summary.runtime.connectionState]
INFO[0010] Removing VMs
DEBU[0011] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0011] No disks found attached to VM
INFO[0011] Removing image stores
DEBU[0014] Failed to delete "[datastore0] virtual-container-host/VIC": Cannot delete file [datastore0] virtual-container-host/VIC
DEBU[0017] Image store parent directory not empty, leaving in place.
INFO[0017] Removing volume stores
DEBU[0017] Provided datastore URL: "[datastore0] volumes"
DEBU[0017] Parsed volume store path: "volumes"
INFO[0017] Deleting volume store "default" on Datastore "datastore0" at path "volumes"
INFO[0020] Removing appliance VM network devices
DEBU[0022] Remove network is not supported for vCenter
DEBU[0022] properties: [config.files.vmPathName summary.runtime.connectionState]
DEBU[0024] unexpected soap fault on task retry: {{{%!s(*types.LocalizedMethodFault=<nil>) []}} VIC}
INFO[0024] Unregistered VM to cleanup after failed destroy: "VirtualMachine:vm-126"
DEBU[0027] Failed to delete "[datastore0] virtual-container-host": Cannot delete file [datastore0] virtual-container-host
INFO[0027] Removing Resource Pool "virtual-container-host"
INFO[0028] ----------
INFO[0028] If firewall changes were made for VIC during install, they were not reverted during delete
INFO[0028] To modify firewall rules see vic-machine update firewall --help
INFO[0028] ----------
INFO[0028] Completed successfully
```

**Comment by AngieCris** [comment] 2018-02-22 23:46
@isyarov 
As far as I know the whole delete VCH process goes like this:
1. Destroy the VCH VM
2. If step 1 fails, unregister the VM instead
3. If step 2 succeeds, manually cleanup all the datastore files (since unregister doesn't delete datastore files)
And in your case, step 1 fails because of a MethodDisabledError from vSphere, and it goes to step 2, and then step 3 fails.

This process is probably not what it should be - there's a bug on our side that we disable destroy operation on VM at some point but we never re-enable it, so step 1 fails every time, and we end up doing unregister every time, and that's error prone since there're cases like yours where deleting datastore files fails....
I'm working on fixing the bug to avoid unnecessary VM unregister and datastore file cleanup. Hopefully that will fix things in the future.

But I'm not sure as for the underlying root cause of why deleting datastore files failed. 
The error message `Cannot delete file [datastore0] virtual-container-host` in the log isn't very informational (and that should probably be improved). 

It fails when deleting VMFS files. Code where the function fails:
https://github.com/vmware/vic/blob/master/lib/install/management/store_files.go#L184

Pinging relevant people for better input:
@matthewavery do you happen to know the potential reasons why deleting datastore files fail?

**Comment by AngieCris** [comment] 2018-02-23 23:20
I have reproduced the same behavior on my VC.
```
DEBU[0012] Failed to delete "[datastore1] test_2": Cannot delete file [datastore1] test_2
```
Investigating into the root cause. Will keep any progress posted here

**Comment by AngieCris** [comment] 2018-02-28 20:15
Root cause identified. It's a bug in the logic of deleting datastore files.

**Details**
During `vic-machine-linux delete`, it cleans up all the datastore files in the VCH's datastore folder. If the VCH's datastore folder has image files for the pulled image layers in it, then under the `VIC` directory in the datastore folder, there will be nonempty directories with child images. Attempt to destroy the directory will result in an error from vSphere.

**Why do we have this problem**
This is related to a change made recently to master: https://github.com/vmware/vic/pull/6951
It was thought that deleting nonempty directories would only complain for vSAN type datastores, but we didn't expect that it's a problem for non-vSAN type datastores as well.

**Fix**
The original approach was to recursively search for all children and delete them explicitly.  And then we made a change to do that only for vSAN type datastores. We need to do the recursive deletion for all datastore types. 

PR coming up.

**Comment by isyarov** [comment] 2018-03-19 14:26
@AngieCris after the change the delete command fails for me, leaving the VM and resource pool in place. The steps i use are the same as above and the delete command output with **--debug 3** is as follows:
```
INFO[0000] ### Removing VCH ####
DEBU[0000] Accepting host "###" thumbprint ###
DEBU[0000] Creating VMOMI session with thumbprint ###
DEBU[0000] Session Environment Info:                     API Type=VirtualCenter API Version=6.5 Build=7092793 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=d7548279-cca9-4d40-859b-177c379cce90 Vendor="VMware, Inc." Version=6.5.0
DEBU[0000] vSphere resource cache populating...
DEBU[0000] Cached dc:
DEBU[0000] Cached cluster:
DEBU[0000] Cached host:
DEBU[0000] Cached pool:
DEBU[0000] Cached folders:
DEBU[0000] Error count populating vSphere cache: (1)
DEBU[0000] new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
INFO[0000] Validating target
DEBU[0000] Using default resource pool for compute resource: "/vcqaDC/host/cls/Resources"
DEBU[0000] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0000] Cannot find image stores from configuration; attempting to find from vm datastore
DEBU[0000] properties: [datastore summary.runtime.connectionState]
INFO[0001]
INFO[0001] VCH ID: VirtualMachine:vm-34
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
INFO[0001] Removing VMs
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0001] No disks found attached to VM
INFO[0001] Removing image stores
DEBU[0001] Failed to delete "[datastore0] virtual-container-host/VIC": Cannot delete file [datastore0] virtual-container-host/VIC
DEBU[0001] Attempt to delete top level folder [datastore0] virtual-container-host/VIC failed. Remove the children files instead.
DEBU[0006] Failed to delete "[datastore0] virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk": File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
DEBU[0006] Image store parent directory not empty, leaving in place.
INFO[0006] Removing volume stores
DEBU[0006] Provided datastore URL: "[datastore0] volumes"
DEBU[0006] Parsed volume store path: "volumes"
INFO[0006] Deleting volume store "default" on Datastore "datastore0" at path "volumes"
INFO[0006] Removing appliance VM network devices
DEBU[0007] Remove network is not supported for vCenter
INFO[0007] Collecting d7548279-cca9-4d40-859b-177c379cce90 vpxd.log
ERRO[0007] File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
ERRO[0007] --------------------
ERRO[0007] vic-machine-linux delete failed: delete failed
```

**Comment by AngieCris** [comment] 2018-03-20 17:02
@isyarov Thanks for reporting it.

From the log I noticed that the file that was failed to delete is a `-sesparse.vmdk` file, which is the format for delta disk of large size. Actually when vic-machine delete removes the original `.vmdk` disk file, the `-sesparse.vmdk` file (also any other kinds of `-flat.vmdk`, `-delta.vmdk` snapshot files) will be automatically removed altogether too by vSphere, so we never have to delete `-sesparse.vmdk` file explicitly. However, it's indeed a bug in our code that we never skip the `-sesparse.vmdk` file. When this file is already removed when deleting the original vmdk disk, the operation failed with an `not found` error.

For other kinds of snapshot files like `-flat.vmdk` and `-delta.vmdk`, vic-machine delete will skip them and let the vSphere `DeleteVirtualDisk_Task` handle the deletion of all. This should be done with `-sesparse.vmdk` file as well.

I'll put up a fix for it. PR coming up.

**Comment by AngieCris** [comment] 2018-03-20 18:21
The new bug of vic-machine delete failed to clean up `-sesparse.vmdk` file is tracked in ticket https://github.com/vmware/vic/issues/7549. Closing this one.

**Closed by AngieCris** 2018-03-20 18:21 UTC
Labels: component/vic-machine, kind/bug, kind/customer-found, priority/p1, team/lifecycle
