### ISSUE TITLE
Add support for docker import

### ISSUE THREAD

**Issue by pkhodaveissi** [vmware/vic#4272] opened 2017-03-16 07:07 UTC
Hi there
I am trying to integrate gitlab-runner with VICE instead of local docker server, but getting this error that it seems VIC api does not implement one of the functions:
`
Running with gitlab-ci-multi-runner 1.11.1 (a67a225)
  on vm-docker-runner (a6e17466)
Using Docker executor with image maven:3-jdk-8 ...
ERROR: Failed to create container volume for /builds/cmts API error (500): vSphere Integrated Containers does not implement image.ImportImage

ERROR: Preparation failed: API error (500): vSphere Integrated Containers does not implement image.ImportImage
` 
any help or clue is highly appreciated you folks

**Comment by anchal-agrawal** [comment] 2017-03-16 15:14
@pkhodaveissi, thanks for reporting. What is the command/script you're running? We haven't implemented `docker import` yet, which is what seems like the command is trying to do.

I'll update the issue title so we can use this to track `docker import` work.

**Comment by pkhodaveissi** [comment] 2017-03-18 07:32
@anchal-agrawal I'm not the one who's running the scripts, I'm afraid. It's gitlab's CI doing the job via gitlab-runner. 
I'll be glad to provide any information you ask for.
cheers

**Comment by anchal-agrawal** [comment] 2017-03-20 15:03
@pkhodaveissi I took a quick look at gitlab-runner and looks like you're using the Docker executor with VIC. Does your `.gitlab-ci.yml` include a `docker build` command as shown [here](https://docs.gitlab.com/runner/executors/docker.html#use-docker-in-docker-with-privileged-mode)? Would it be possible to show your `.gitlab-ci.yml` or just the Docker commands in it?

**Comment by anchal-agrawal** [comment] 2017-03-27 16:38
Thanks @pkhodaveissi. I can't gather much else other than the fact that gitlab-runner with the Docker executor requires `docker import` to work, which we don't yet support.

Please watch this issue since we'll use it to track `docker import` work. Thanks for your patience!

**Comment by anchal-agrawal** [comment] 2017-08-30 22:08
Closing as duplicate of https://github.com/vmware/vic/issues/5408.

**Closed by anchal-agrawal** 2017-08-30 22:08 UTC
Labels: component/docker-api-server, kind/feature, priority/medium
