### ISSUE TITLE
New docker client is not working with VIC [v1.13]

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#3734] opened 2017-01-26 19:02 UTC
New docker client is not working with VIC [version 1.13] and that needs to be documented somewhere.
- [ ] determine source of hang (but not fix)
- [ ] document as known issue for current VIC release.

The original issue is tracked at https://github.com/vmware/vic/issues/3720

**Comment by mdubya66** [comment] 2017-01-26 19:46
works for me

**Comment by mdubya66** [comment] 2017-01-26 19:47
Closing this. Added kind/note to the original issue #3720

**Comment by hickeng** [comment] 2017-01-26 20:45
I'd like to determine what the problem is so we can document it appropriately as a high priority in the near term.

This is separated from the original issue as the two hypothesis raised both imply potentially long and involved fixes:
a. client is now using event stream (unsupported) to determine container exit
b. parameters have been switched in the API update (tied to outcome of #3415)

**Comment by caglar10ur** [comment] 2017-01-26 20:45
This is what I'm observing but this is a build from my branch. Will try switching back to master

```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(3605)] docker version
Client:
 Version:      1.13.0
 API version:  1.23
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      0.8.0
 API version:  1.23 (minimum version )
 Go version:   go1.7.4
 Git commit:   dcff4f6
 Built:        Thu Jan 26 18:43:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(3605)] docker ^Cllo-world
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(3605)] docker run ubuntu uname
Unable to find image 'ubuntu:latest' locally
Pulling from library/ubuntu
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:0c01b5105fc57b5eb8b7bb1d697b9dc5602022f69a0a33bf282b117e7a754a91
Status: Downloaded newer image for library/ubuntu:latest

Linux



^C^C^C
```

**Comment by caglar10ur** [comment] 2017-01-27 17:30
Same problem with master so not sure what are you doing differently @mdubya66. Can you try running "docker run ubuntu uname"?

**Comment by mdubya66** [comment] 2017-02-01 17:35
This hang on mac as well. Control-C does nothing. kill -9 <pid> was required. The container still reports as being running after the kill.

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
2cd453dede6e        ubuntu              "uname"             5 days ago          Up About a minute                       backstabbing_liskov

**Comment by stuclem** [comment] 2017-02-08 11:25
Apologies for getting to this so late (have had a huge backlog that I have only just cleared). Proposed text for the release notes:

- <b>vSphere Integrated Containers Engine 0.8 does not support Docker Client 1.13. [#3734](https://github.com/vmware/vic/issues/3734), [#3734](https://github.com/vmware/vic/issues/3720)</b><br>If you attempt to connect version 1.13 of the Docker Client to a virtual container host, the Docker client stops working.<br>**Workaround**: Use version 1.12 of the Docker Client to connect to virtual container hosts.

**Comment by sflxn** [comment] 2017-02-08 20:22
@stuclem this is only a temporary situation.  It will get fixed.

**Comment by sflxn** [comment] 2017-02-08 20:25
I'm going to comment in the original issue for all technical discussions from here on out.

**Comment by stuclem** [comment] 2017-02-09 10:14
No problem, @sflxn. Here's an updated version of the release note entry for 0.8:

- <b>vSphere Integrated Containers Engine 0.8 does not support Docker Client 1.13. [#3734](https://github.com/vmware/vic/issues/3734), [#3734](https://github.com/vmware/vic/issues/3720)</b><br>If you attempt to connect version 1.13 of the Docker Client to a virtual container host, the Docker client stops working. This happens because Docker 1.13 uses Docker Events, which vSphere Integrated Containers 0.8 does not support.<br>**Workaround**: Use version 1.12 of the Docker Client to connect to virtual container hosts. 

Is this OK? Thanks!

**Comment by stuclem** [comment] 2017-02-10 09:57
Incidentally, @caglar10ur @mdubya66 @mhagen-vmware, the main docs for 0.8 currently state support for Docker 1.11.2. Should we update this to state "versions up to 1.12, but not 1.13"?

**Comment by sflxn** [comment] 2017-02-10 23:52
@stuclem I would say "which vSphere Integrated Containers Engine 0.8 does not yet support."  We're going to get docker events implemented.  It's not just for docker 1.13 run but also for docker stats.

**Comment by stuclem** [comment] 2017-02-13 10:24
Done. Thanks @sflxn. Since this issue is just for doc, closing.

**Closed by stuclem** 2017-02-13 10:24 UTC
Labels: kind/note, priority/high
