### ISSUE TITLE
Harbor cannot be installed on a VCH using docker compose

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#4336] opened 2017-03-22 18:46 UTC
**VIC version:**

0.80/master/7269eff

**Steps to reproduce:**

Use a VCH to deploy Harbor using docker-compose.

**Actual behavior:**

Deployment fails due to LoadImage not being supported

**Expected behavior:**

Deployment should work, need to implement load image

**Comment by mdubya66** [comment] 2017-03-22 19:10
probably a dupe of #1028

**Comment by mdubya66** [comment] 2017-03-25 14:08
closing as a duplicate of the loadimage issue, #1028

**Closed** 2017-03-25 14:08 UTC
