### ISSUE TITLE
Intermittent failure in CI: Connectivity Bridge to Public (6-07-Create-Network)

### ISSUE THREAD

**Issue by zjs** [vmware/vic#6811] opened 2017-11-20 23:21 UTC
In [build 14880](https://ci.vcna.io/vmware/vic/14880) and [build 14882](https://ci.vcna.io/vmware/vic/14882) (but not [build 14881](https://ci.vcna.io/vmware/vic/14881) or [build 14883](https://ci.vcna.io/vmware/vic/14883), which were of the same commit), the "Connectivity Bridge to Public" test in the `6-07-Create-Network` robot suite failed with a connection timeout:

#### 14880:
```
Running command 'docker -H 192.168.31.113:2376 --tls run --net bridge harbor.ci.drone.local/library/busybox nc 192.168.31.188 8000 2>&1'.`
${rc} = 1
${output} = nc: can't connect to remote host (192.168.31.188): Connection timed out
```

#### 14882:
```
Running command 'docker -H 192.168.31.166:2376 --tls run --net bridge harbor.ci.drone.local/library/busybox nc 192.168.31.204 8000 2>&1'.
${rc} = 1
${output} = nc: can't connect to remote host (192.168.31.204): Connection timed out
```

This was also seen in earlier builds, such as [build 14809](https://ci.vcna.io/vmware/vic/14809).

#### 14809:
```
Running command 'docker -H 192.168.31.120:2376 --tls run --net bridge harbor.ci.drone.local/library/busybox nc 192.168.31.136 8000 2>&1'.
${rc} = 1
${output} = nc: can't connect to remote host (192.168.31.136): Connection timed out
```

**Comment by zjs** [comment] 2017-11-21 00:43
It appears that this can also happen in other tests within the same suite, such as `Container Firewalls`:
```
Running command 'docker -H 192.168.31.196:2376 --tls run --net bridge harbor.ci.drone.local/library/busybox nc 192.168.31.240 1234 2>&1'.
${rc} = 1
${output} = nc: can't connect to remote host (192.168.31.240): Connection timed out
```

**Comment by anchal-agrawal** [comment] 2017-11-21 02:00
https://ci.vcna.io/vmware/vic/14897

**Comment by hickeng** [comment] 2017-11-22 19:25
Noted this failure in #2932 as well.
If this was due to invalid arpcache in the public network gateway then #6819 likely addressed this specific behaviour.
If this was due to invalid arpcache in the endpoint then it will not be fixed until #2932 is addressed.

If it's not related to arp then I've no idea and we'll need to add gratuitous packet capture to the test environment so we can actually track what's occurring at a network level.

**Comment by vburenin** [comment] 2017-11-28 16:46
As @hickeng mentioned, it could happen due to the invalid ARP cache. I have been trying to reproduce this issue for several days with no luck.
I think we can keep this issue open for a while and close it if there are no more such errors appear.

**Comment by sgairo** [comment] 2017-12-06 18:14
Will be taking this issue for sprint 23 to try and reproduce it consistently. Will assign myself when I get to a computer.

**Comment by anchal-agrawal** [comment] 2018-01-03 05:45
We haven't seen this in CI recently AFAIK. We could move this to medium priority.

**Comment by vburenin** [comment] 2018-02-14 16:52
Haven't seen also for a long time. Closing.

**Closed by vburenin** 2018-02-14 16:52 UTC
Labels: area/docker, kind/investigation, priority/p0, team/container
