### ISSUE TITLE
Image ID is not persistent.

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#2756] opened 2016-10-17 03:43 UTC
Repo steps:
1. Pull tomcat
2. check image id
3. rmi tomcat
4. pull tomcat
5. check image id - it is different from step 2.

**Comment by anchal-agrawal** [comment] 2016-10-17 04:12
Related/dup of #2530.

**Comment by mdubya66** [comment] 2016-10-17 17:47
Closing as dupe of 2530

**Closed** 2016-10-17 17:47 UTC
