### ISSUE TITLE
Container start after network connect gets EOF in portlayer

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1316] opened 2016-07-01 14:11 UTC
**VIC Version:**

0.1 / master / 2488

I was running through some network tests as created by @mhagen-vmware 

I was able to successfully deploy busybox container with a shell:

```
docker -H 10.27.33.243:2376 --tls run -it busybox
```

However I ran into an issue after attaching a new network to an existing busybox container, and trying to start said container:

```ts
// A self-contained demonstration of the problem follows...

root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.33.243:2376 --tls network create cor-network
05d1d93a142ce44db0db02ce02dc461d
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.33.243:2376 --tls create busybox ifconfig
06def68bdee38e782337b5ae0168863b95afc2d312c5180109b28cacb5eadc04
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.33.243:2376 --tls network connect cor-network 06def68bdee38e782337b5ae0168863b95afc2d312c5180109b28cacb5eadc04
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.33.243:2376 --tls start 06def68bdee38e782337b5ae0168863b95afc2d312c5180109b28cacb5eadc04
Error response from daemon: server error from portlayer
Error: failed to start containers: 06def68bdee38e782337b5ae0168863b95afc2d312c5180109b28cacb5eadc04
root@photon-NaTv5i8IA [ /workspace/vic ]#
```

I looked at the portlayer logs and this is what I see:

```
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=error msg="HandshakeClient: failed to read expected SYN-ACK: n=1, err=read tcp 10.27.33.243:8080->10.27.51.8:31864: i/o timeout buf=[0xa8]"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="HandshakeClient: did not receive synack: 0x06d4 != 0x5e08"
time="2016-07-01T11:32:36Z" level=debug msg="discarding following 118 bytes from input channel\n"
time="2016-07-01T11:32:36Z" level=debug msg="[94 8 254 94 8 126 94 8 140 94 8 156 94 8 213 94 8 122 94 8 85 94 8 110 94 8 115 94 8 94 92 94 8 188 94 8 123 94 8 68 94 8 177 94 8 94 71 94 8 177 94 8 135 94 8 86 94 8 233 94 8 94 66 94 8 94 77 94 8 219 94 8 91 94 8 34 94 8 94 65 94 8 236 94 8 193 94 8 78 94 8 170 94 8 40 94 8 144 94 8 250 94 8 240 94 8 240 94 8 94 94 94 8 147 94 8 94 81]\n"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="Incoming channel is purged of content"
time="2016-07-01T11:32:36Z" level=debug msg="caught EOF"
time="2016-07-01T11:32:55Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesUnbindContainer] ScopesUnbindContainer"
time="2016-07-01T11:32:55Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesUnbindContainer] [92.319µs] ScopesUnbindContainer"
```

**Expected behavior:**

Container should start

**Actual behavior:**

Container fails to start with "Error response from daemon: server error from portlayer"

I have seen some discussions regarding swagger and EOF but I saw that is was supposed to be fixed in #2483. Since this is #2488, I am filing this issue (apologies if it is a dupe)

**Comment by mdubya66** [comment] 2016-07-01 14:25
Assigning to @hmahmood for validation as this is the workflow he is currently completing

**Comment by mhagen-vmware** [comment] 2016-07-01 14:43
Might be related to this:
https://github.com/vmware/vic/issues/1235

**Comment by hmahmood** [comment] 2016-07-01 22:45
Maybe related to #1214

**Comment by cormachogan** [comment] 2016-07-04 08:47
I just retried with the latest VIC Version from bintray this morning. Adding this update as an FYI.:

0.1 / master / 2513

```
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.32.234:2376 --tls network ls -f name=test
NETWORK ID          NAME                DRIVER
b230c0a58c71        test-network        bridge
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.32.234:2376 --tls create busybox ifconfig
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
b7847276aa5beb20acbaeb686bd058275b6e587b6e885b11d631a11990a2666e
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.32.234:2376 --tls network connect test-network b7847276aa5beb20acbaeb686bd058275b6e587b6e885b11d631a11990a2666e
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.32.234:2376 --tls start b7847276aa5beb20acbaeb686bd058275b6e587b6e885b11d631a11990a2666e

Error response from daemon: server error from portlayer
Error: failed to start containers: b7847276aa5beb20acbaeb686bd058275b6e587b6e885b11d631a11990a2666e
root@photon-NaTv5i8IA [ /workspace/vic ]#
root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.32.234:2376 --tls logs b7847276aa5beb20acbaeb686bd058275b6e587b6e885b11d631a11990a2666e
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x62d1d9]

goroutine 1 [running]:
github.com/docker/docker/api/client.(*DockerCli).CmdLogs(0xc8201e3d80, 0xc82000a170, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/logs.go:40 +0xb69
reflect.callMethod(0xc8203749c0, 0xc820183c28)
        /usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a170, 0x1, 0x1, 0x1, 0xc8203749c0, 0x0, 0x0, 0xc8203749c0, 0x0, 0x4758c4, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc8203744e0, 0xc82000a160, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:63 +0x43c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f8d9ce091f0, 0x72, 0xc82000e1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203764c0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203764c0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820376460, 0xc820382800, 0x800, 0x800, 0x0, 0x7f8d9cdfa050, 0xc82000e1a0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c5e0, 0xc820382800, 0x800, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820374d50, 0x7f8d9ce09c40, 0xc82002c5e0, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200ad8c0, 0x1adb817, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200ad8c0, 0xc820317000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f8d9ce0a090, 0xc8200ad8c0, 0xc8200d3658, 0xc820317000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820379a40, 0xc820317000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820372d80)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820372d80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200d3600)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 14 [runnable]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f8d9ce031b8, 0xc82000f0d0, 0xc8203863a0, 0xc820372f00)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:77
created by github.com/docker/engine-api/client/transport/cancellable.Do
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x335

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc8200d3600)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d
root@photon-NaTv5i8IA [ /workspace/vic ]#

```

**Comment by hmahmood** [comment] 2016-07-05 15:35
@cormachogan I think that is the `logs` command crashing.

**Comment by cormachogan** [comment] 2016-07-06 09:09
Thanks @hmahmood - should I open a new issue for that, or is it already a known issue?

**Comment by hickeng** [comment] 2016-07-08 16:24
@cormachogan new issue please and we can assign it to @jzt. Logs isn't supported currently so it _should_ be a quick fix.

**Comment by corrieb** [comment] 2016-07-11 17:25
Let's get the issue raised on this crash. We shouldn't have any known panics in TP3

**Comment by hmahmood** [comment] 2016-07-11 18:29
I cannot reproduce this in master. Moving to "Done". @cormachogan could you validate please?

**Comment by cormachogan** [comment] 2016-07-12 12:05
I just tested with #2801 - docker start after network attach now works.

**Closed** 2016-07-12 15:46 UTC
