### ISSUE TITLE
Port not available after removing a container with the same port that had been attached and exited

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#2519] opened 2016-09-29 16:52 UTC
Here is my action sequence:

1. docker -H 192.168.60.130:2375 create -it -p 1234:1234 busybox
2. docker -H 192.168.60.130:2375 start container_id
3. docker -H 192.168.60.130:2375 attach container_id
4. exit from container
5. docker -H 192.168.60.130:2375 stop container_id
6. docker -H 192.168.60.130:2375 rm container_id
7. docker -H 192.168.60.130:2375 create -it -p 1234:1234 busybox
8. docker -H 192.168.60.130:2375 start new_container_id

**Expected behavior:**
A new container with new_container_id should be started.

**Actual behavior:** (this is reproducible)

> > Error response from daemon: Server error from portlayer: error mapping ports: port 1234 is not available
Error: failed to start containers: new_container_id

[container-logs (1).zip](https://github.com/vmware/vic/files/501238/container-logs.1.zip)

**Note:**
This issue does not occur if I do not attach to and then exit from the first container.

**Comment by mdubya66** [comment] 2016-09-29 17:37
I reproduced as well on 6.5.

```
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls stop 0
0
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls rm 0
0
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls create -it -p 1234:1234 busybox
1fad13b337fba031622c397faa4f737b1ec2396531600337d7399e4da0a3b04b
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls start 1
Error response from daemon: Server error from portlayer: error mapping ports: port 1234 is not available
Error: failed to start containers: 1
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
1fad13b337fb        busybox             "sh"                About a minute ago   Created                                 distracted_jennings
(mwilliamson) dubs:~/Downloads/vic_0.6.0 $  docker -H 10.17.109.160:2376 --tls inspect 1
[
    {
        "Id": "1fad13b337fba031622c397faa4f737b1ec2396531600337d7399e4da0a3b04b",
        "Created": "2016-09-29T17:35:46Z",
        "Path": "sh",
        "Args": [],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "",
            "FinishedAt": ""
        },
        "Image": "b05baf071fd542c3146f08e5f20ad63e76fa4b4bd91f274c4838ddc41f3409f8",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "distracted_jennings",
        "RestartCount": 0,
        "Driver": "vSphere Integrated Containers v0.6.0-4890-4f98611 Backend Engine",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "1234/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "1234"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "vSphere Integrated Containers v0.6.0-4890-4f98611 Backend Engine",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "vSphere Integrated Containers v0.6.0-4890-4f98611 Backend Engine",
            "Data": null
        },
        "Mounts": null,
        "Config": {
            "Hostname": "1fad13b337fb",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm"
            ],
            "Cmd": [
                "sh"
            ],
            "Image": "busybox",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "NetworkDisabled": true,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1234/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1234"
                    }
                ]
            },
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]
```

**Comment by hmahmood** [comment] 2016-09-29 17:39
This is because the container stops out of band, and the docker persona does not know that it did. Port mappings are only stored/executed by the persona, not the port layer. 

The proper fix for this would be to use events on the persona side to monitor vm state changes.

**Comment by mdubya66** [comment] 2016-09-29 17:41
Basic use case. Flagging for 0.7.0 by putting in the ToDo list.

**Comment by mdubya66** [comment] 2016-09-29 17:43
Is this a duplicate of #2042

**Comment by hmahmood** [comment] 2016-09-29 17:57
#2042 is a different issue

**Comment by mdubya66** [comment] 2016-09-29 18:02
Similar though, right? @hmahmood 

Moving it to backlog. If VCH restart doesn't provide a workaround we can address it in 0.7.0

**Comment by mreferre** [comment] 2016-10-05 12:03
I am hitting the same issue:

**Closed** 2016-10-21 22:59 UTC
Labels: kind/bug
