### ISSUE TITLE
Status of newly created container is "exited" 

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#6372] opened 2017-09-15 21:11 UTC
This has proved to be an issue in my experimentations with SwarmKit - SwarmKit creates a container and then looks at the status to decide how to proceed. When it sees "exited" and not "created", it goes down a wrong code path and loops trying to recreate the container.

Steps to reproduce:

```
docker create --name=foo busybox
docker inspect foo
```

You'll see the State.Status as "exited", when it should be "created".

I debugged the reason this is happening.
- The container is created and its state is set to "created".
- The inspect call causes Refresh() to be called in lib/portlayer/exec/container.go#L331 and this looks at the power state of the VM. It slams the state from "created" to "stopped" because the VM is powered off.
- The personality then turns the "stopped" status into an "exited" status here: lib/apiservers/engine/backends/container_proxy.go#L1491.

The simplest fix would be to add a clause to Refresh() so that if the state is "created", it doesn't make the modification. Arguably the Port Layer should only care about stopped or started, but the "created" state needs to be preserved and passed back to the persona for the inspect result.

**Comment by cgtexmex** [comment] 2017-09-15 21:18
This will impact `docker ps` as well -- specifically the following interaction:

```
docker create --name jojo ubuntu sh

docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cc3fa099cc1f        ubuntu              "sh"                25 seconds ago      Created                                 jojo

docker inspect jojo
"State": {
      "Status": "exited"

docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cc3fa099cc1f        ubuntu              "sh"                3 minutes ago       Stopped                                 jojo
```

**Comment by cgtexmex** [comment] 2017-09-15 21:40
bumped estimate up because I think we need to look at the overall state machine in the PL.  The quick fix for this issue would be a clause on the code mentioned above, but that _could_ introduce issues in other areas.  

Additionally, tests need to be modified to ensure we catch this type of regression in the future.

**Comment by sflxn** [comment] 2017-09-15 22:46
As an additional guard around this, we can add a condition in the persona's backends/convert/state.go file to check start time.  If start time or end time is empty, then we can assume the state value is incorrect.

**Comment by hickeng** [comment] 2017-09-16 02:26
This is mostly a problem because of a very long standing issue where instead of a somewhat flexible but predictable state/status tuple we have exitStatus/started and have to infer the actual state.
Completely agree with @sflxn  - for fast patch and checking StartTime - had thought that was in there, but only looked at the exit paths.
Completely agree with @cgtexmex that we need to revisit the recording of state.

Some additional complexity comes on the exit paths because we try to emulate bash logic for noting signal based exit (128 + signnum), so exit from SIGKILL becomes 137, and SIGTERM becomes 143.
However we don't have a record of the last signal dispatched to the process so we have to guess at it based on other fields.

**Comment by corrieb** [comment] 2017-09-18 13:31
Thanks for looking at this in detail, guys. I can make progress on #6293 with my hacked build, but we should consider this a blocker for Swarmkit

**Comment by cgtexmex** [comment] 2017-09-18 22:39
I'm inclined to fix this on the portLayer in the code @corrieb mentions in the original comments.  I've added come logic to both poweredOn and poweredOff case -- I'll create a test and then provide for review.

I do believe we need to rework the state machine in the portLayer -- but think that's a much bigger change that shouldn't block #6293...also I'd like that change to have some actual design discussion around longer term outcomes, goals, etc..

**Closed** 2017-10-18 23:41 UTC
Labels: component/portlayer/execution, kind/bug, priority/medium, team/foundation
