### ISSUE TITLE
The "Container Firewalls" test in 6-07-Create-Network fails with a server error from portlayer

### ISSUE THREAD

**Issue by zjs** [vmware/vic#7067] opened 2018-01-10 18:35 UTC
**VIC version:**

`v1.3.0-rc1-15605-89bc7c9` (not actually RC1)

**Deployment details:**

https://ci.vcna.io/vmware/vic/15605

**Actual behavior:**

The command `docker -H 192.168.31.236:2376 --tls run -d --net=outbound-net --name p3 harbor.ci.drone.local/library/busybox nc -l -p 1234 2>&1` returned code `125` with an error message of:

```
7067abe25db4c67e67deaf1919c7140702dde1d1d65196434fa24d734fae280a
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://192.168.31.52/s...
```

**Expected behavior:**

The test passes.

**Logs:**

[Test-Cases.Group6-VIC-Machine.6-07-Create-Network-VCH-15605-9509-container-logs.zip](https://github.com/vmware/vic/files/1620018/Test-Cases.Group6-VIC-Machine.6-07-Create-Network-VCH-15605-9509-container-logs.zip)

**Additional details as necessary:**

![image](https://user-images.githubusercontent.com/408880/34789105-c91d1cc2-f5f1-11e7-8629-11b982c7b500.png)

**Comment by jzt** [comment] 2018-01-11 22:54
Seeing the following in the hostd log:

Evidently the core files are unable to be retrieved?:
```
2018-01-10T02:19:12.892Z warning hostd[40E01B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/59976bc0-5b86fee7-acff-0cc47a9f99e0/7067abe25db4c67e67deaf1919c7140702dde1d1d65196434fa24d734fae280a/7067abe25db4c67e67deaf1919c7140702dde1d1d65196434fa24d734fae280a.vmx opID=301.99-b5f6 user=droneci] CannotRetrieveCorefiles: VM is in an invalid state
2018-01-10T02:19:12.919Z info hostd[40E01B70] [Originator@6876 sub=Libs opID=301.99-b5f6 user=droneci] Error getting extended config name from config file.
2018-01-10T02:19:12.919Z info hostd[40E01B70] [Originator@6876 sub=Libs opID=301.99-b5f6 user=droneci] Error getting extended config file path.
```
[snip]

```
2018-01-10T02:19:20.002Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.002Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.003Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.004Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.004Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.004Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
2018-01-10T02:19:20.004Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4000': vim.fault.InvalidState
2018-01-10T02:19:20.004Z error hostd[FFD26B70] [Originator@6876 sub=Statssvc.vim.PerformanceManager] Reconfigured: For VM(MoID:'2088',WID:2655817): Unexpected VIM fault while obtaining virtual ethernet card '4001': vim.fault.InvalidState
```
I believe the following behavior was also seen in #7066 also:
```
2018-01-10T02:19:20.489Z error hostd[421C1B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x436a3e94, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:19:26.488Z info hostd[421C1B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 48244 : User droneci@192.168.31.132 logged out (login time: Wednesday, 10 January, 2018 01:48:36, number of API invocations: 0, user agent: vic-engine/1.3.0-rc1)
2018-01-10T02:19:30.493Z error hostd[45440B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x40951edc, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:19:30.493Z error hostd[421C1B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x410e1d7c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:19:32.474Z info hostd[421C1B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/59976bc0-5b86fee7-acff-0cc47a9f99e0/720816af6a882f04c33d9672829266154d3e5a913371c573cada71e489aa2208/720816af6a882f04c33d9672829266154d3e5a913371c573cada71e489aa2208.vmx] Turning off heartbeat checker
2018-01-10T02:19:40.434Z info hostd[421C1B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/59976bc0-5b86fee7-acff-0cc47a9f99e0/67e2d27281c18a7f5fca78a81053450f8d49fed0ec68752bc555840e3eb2c302/67e2d27281c18a7f5fca78a81053450f8d49fed0ec68752bc555840e3eb2c302.vmx] Turning off heartbeat checker
[LikewiseGetDomainJoinInfo:355] QueryInformation(): ERROR_FILE_NOT_FOUND (2/0):
2018-01-10T02:19:55.507Z error hostd[421C1B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x4304e0e4, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:19:55.507Z error hostd[45440B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x43b31a4c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:20:05.512Z error hostd[FFD26B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x418ee53c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:20:05.512Z error hostd[40EC4B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x42aaba0c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
[LikewiseGetDomainJoinInfo:355] QueryInformation(): ERROR_FILE_NOT_FOUND (2/0):
2018-01-10T02:21:15.545Z error hostd[40E83B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x4256179c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:15.545Z error hostd[421C1B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x44a1a00c, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:15.545Z error hostd[FFD26B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x423c0e34, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:15.545Z error hostd[40EC4B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x42a364e4, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:20.547Z error hostd[FFD26B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x44914dcc, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:24.130Z info hostd[FFD26B70] [Originator@6876 sub=Vimsvc.ha-eventmgr] Event 48245 : User droneci@192.168.31.250 logged out (login time: Wednesday, 10 January, 2018 01:51:24, number of API invocations: 0, user agent: vic-machine/1.3.0-rc1)
2018-01-10T02:21:25.550Z error hostd[42140B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x4307d234, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
2018-01-10T02:21:25.551Z error hostd[40EC4B70] [Originator@6876 sub=SoapAdapter.HTTPService] Failed to read request; stream: <io_obj p:0x429a83ec, h:-1, <TCP '0.0.0.0:0'>, <TCP '0.0.0.0:0'>>, error: N7Vmacore16TimeoutExceptionE(Operation timed out)
[LikewiseGetDomainJoinInfo:355] QueryInformation(): ERROR_FILE_NOT_FOUND (2/0):
2018-01-10T02:22:13.697Z info hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Activation [N5Vmomi10ActivationE:0x4185ac88] : Invoke done [waitForUpdatesEx] on [vmodl.query.PropertyCollector:session[522dbca3-9749-e6c5-83c2-cd37667c5e64]5215050a-f604-47e3-471e-28db8e182abf]
2018-01-10T02:22:13.697Z verbose hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Arg version:
--> "1"
2018-01-10T02:22:13.697Z verbose hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Arg options:
--> (null)
2018-01-10T02:22:13.697Z info hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Throw vmodl.fault.RequestCanceled
2018-01-10T02:22:13.697Z info hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Result:
--> (vmodl.fault.RequestCanceled) {
-->    faultCause = (vmodl.MethodFault) null,
-->    msg = ""
--> }
```

Might be worth adding the vmx file to the vicadmin log bundle so we can verify one way or the other if there is anything wrong with it.

**Comment by jzt** [comment] 2018-01-12 23:23
Upon further investigation, I don't think anything we were seeing regarding the vmx/vmsd files were out of the ordinary. Nevertheless, I have a PR that includes them in the log bundle anyway, just for future reference:  https://github.com/vmware/vic/pull/7089/files

It appears to hang while waiting on the virtual nic until the property collector finally times out:
```
2018-01-10T02:22:13.697Z info hostd[FFD26B70] [Originator@6876 sub=Solo.Vmomi opID=301.102-b621 user=droneci] Activation [N5Vmomi10ActivationE:0x4185ac88] : Invoke done [waitForUpdatesEx] on [vmodl.query.PropertyCollector:session[522dbca3-9749-e6c5-83c2-cd37667c5e64]5215050a-f604-47e3-471e-28db8e182abf]
```
As also seen in the portlayer log:
```
Jan 10 2018 02:22:13.031Z ERROR op=301.102: CommitHandler error on handle(c114c19dc61c49ac0a5c63bd8b73bdf3) for 7067abe25db4c67e67deaf1919c7140702dde1d1d65196434fa24d734fae280a: unable to wait for process launch status: Post https://192.168.31.52/sdk: context deadline exceeded
```

**Comment by jzt** [comment] 2018-01-16 18:23
After further triage and conversation with George, I'm closing this as a dupe of #6379.

**Closed by jzt** 2018-01-16 18:23 UTC
Labels: kind/bug, priority/high, status/needs-triage, team/foundation
