### ISSUE TITLE
Deploying a multi-container wordpress application on VCH via Admiral fails

### ISSUE THREAD

**Issue by bhravich** [vmware/vic#3439] opened 2016-12-02 23:57 UTC
**VIC version:** 

v0.8.0-rc2-7257-9553959

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
```
./vic-machine-linux create --target host/Cluster --image-store vsanDatastore --name bhu-vic-host-3 --user Administrator@vsphere.local --password 'password' --no-tlsverify --thumbprint '5B:C9:9B:D8:C3:D7:73:83:00:21:0A:06:B9:F8:CB:61:2A:C6:3A:9B' --public-network 'NSXScalePerf-VMPG01' --volume-store=vsanDatastore/vic-volume:default --insecure-registry 10.197.9.235:80 --force

[[34mINFO[[0m[2016-12-02T21:39:58Z] ### Installing VCH ####
[[33mWARN[[0m[2016-12-02T21:39:58Z] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
[[34mINFO[[0m[2016-12-02T21:39:58Z] Loaded server certificate bhu-vic-host-3/server-cert.pem
[[33mWARN[[0m[2016-12-02T21:39:58Z] Configuring without TLS verify - certificate-based authentication disabled
[[34mINFO[[0m[2016-12-02T21:39:59Z] Validating supplied configuration
[[34mINFO[[0m[2016-12-02T21:40:00Z] vDS configuration OK on "bhu-vic-host-3"
[[34mINFO[[0m[2016-12-02T21:40:00Z] Firewall status: DISABLED on "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1801.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:00Z] Firewall status: DISABLED on "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1802.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z] Firewall status: DISABLED on "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1803.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z] Firewall status: DISABLED on "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1804.eng.vmware.com"
[[33mWARN[[0m[2016-12-02T21:40:01Z] Firewall configuration will be incorrect if firewall is reenabled on hosts:
[[33mWARN[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1801.eng.vmware.com"
[[33mWARN[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1802.eng.vmware.com"
[[33mWARN[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1803.eng.vmware.com"
[[33mWARN[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1804.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
[[34mINFO[[0m[2016-12-02T21:40:01Z] License check OK on hosts:
[[34mINFO[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1801.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1802.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1803.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/w2-hs2-e1804.eng.vmware.com"
[[34mINFO[[0m[2016-12-02T21:40:01Z] DRS check OK on:
[[34mINFO[[0m[2016-12-02T21:40:01Z]   "/VRANSX-PREPROD/host/NSX-SCALE-PERF/Resources"
[[34mINFO[[0m[2016-12-02T21:40:02Z]
[[34mINFO[[0m[2016-12-02T21:40:04Z] Creating virtual app "bhu-vic-host-3"
[[34mINFO[[0m[2016-12-02T21:40:04Z] Creating directory [vsanDatastore] vic-volume
[[34mINFO[[0m[2016-12-02T21:40:04Z] Datastore path is [vsanDatastore] vic-volume
[[34mINFO[[0m[2016-12-02T21:40:04Z] Creating appliance on target
[[34mINFO[[0m[2016-12-02T21:40:04Z] Network role "client" is sharing NIC with "public"
[[34mINFO[[0m[2016-12-02T21:40:04Z] Network role "management" is sharing NIC with "public"
[[34mINFO[[0m[2016-12-02T21:40:09Z] Uploading images for container
[[34mINFO[[0m[2016-12-02T21:40:09Z]   "bootstrap.iso"
[[34mINFO[[0m[2016-12-02T21:40:09Z]   "appliance.iso"
[[34mINFO[[0m[2016-12-02T21:41:47Z] Waiting for IP information
[[34mINFO[[0m[2016-12-02T21:41:59Z] Waiting for major appliance components to launch
[[34mINFO[[0m[2016-12-02T21:41:59Z] Checking VCH connectivity with vSphere target
[[33mWARN[[0m[2016-12-02T21:42:00Z] Could not run VCH vSphere API target check due to ServerFaultCode: The operation is not allowed in the current state.
[[34mINFO[[0m[2016-12-02T21:42:02Z] Initialization of appliance successful
[[34mINFO[[0m[2016-12-02T21:42:02Z]
[[34mINFO[[0m[2016-12-02T21:42:02Z] VCH Admin Portal:
[[34mINFO[[0m[2016-12-02T21:42:02Z] https://10.197.9.234:2378
[[34mINFO[[0m[2016-12-02T21:42:02Z]
[[34mINFO[[0m[2016-12-02T21:42:02Z] Published ports can be reached at:
[[34mINFO[[0m[2016-12-02T21:42:02Z] 10.197.9.234

```

**Steps to reproduce:**
1. Deploy the VCH using the above mentioned command.
2. Register the host on admiral.
3. Upload an application template with the following specification:
```
---
version: "2"
services:
  wordpress:
    image: "wordpress:4.3.1"
    environment:
    - "WORDPRESS_DB_PASSWORD=pass@word01"
    - "WORDPRESS_DB_NAME=wordpress"
    - "WORDPRESS_DB_HOST=mysql:3306"
    ports:
    - "80"
    links:
    - "mysql"
    depends_on:
    - "mysql"
  mysql:
    image: "mariadb:10.0.26"
    environment:
    - "MYSQL_ROOT_PASSWORD=pass@word01"
    ports:
    - "3306"
```
4. Deploy the application.

**Actual behavior:**
The mysql container is sucessfully deployed however, the wordpress container goes offline after reporting the following error in the console:
![wordpress-error](https://cloud.githubusercontent.com/assets/1731572/20854307/99e3371c-b8a7-11e6-8047-8e6e430964f2.png)

**Expected behavior:**
The application should have successfully deployed.

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/628547/container-logs.zip)

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by mdubya66** [comment] 2016-12-03 20:42
@sflxn please continue to triage this.

**Comment by chengwang86** [comment] 2016-12-05 22:43
I tried it manually on my local ESXi host (only vic engine; no admiral) and it worked.

```
bin/vic-machine-linux create  --name=... --volume-store=datastore1/test:default --target=root:pwd@192.168.60.162 --thumbprint=... --no-tlsverify
docker -H 192.168.60.250:2376 --tls run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass@word01 --name=mysql mariadb:10.0.26
docker -H 192.168.60.250:2376 --tls run -d -p 80:80 --link mysql -e WORDPRESS_DB_PASSWORD=pass@word01 -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_HOST=mysql:3306 --name=wordpress wordpress:4.3.1
```

**Comment by bhravich** [comment] 2016-12-05 23:22
**#1.**
I tried the following:
```
docker -H vch-host-ip:2376 --tls run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass@word01 --name=mysql mariadb:10.0.26
docker -H vch-host-ip:2376 --tls run -d -p 80:80 --link mysql -e WORDPRESS_DB_PASSWORD=pass@word01 -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_HOST=mysql:3306 --name=wordpress wordpress:4.3.1
```
Faced the same issue as reported in the defect.

**#2.**
Then I slightly modified the command as follows:
```
docker -H vch-host-ip:2376 --tls run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass@word01 --name=mysql mariadb:10.0.26
docker -H vch-host-ip:2376 --tls run -d -p 80:80 --link mysql -e WORDPRESS_DB_PASSWORD=pass@word01 -e WORDPRESS_DB_NAME=wordpress -e WORDPRESS_DB_HOST=vch-host-ip:3306 --name=wordpress wordpress:4.3.1
```
This time the application launched successfully.

The issue is that the wordpress container is not able to resolve the IP based on name 'mysql'. Am I missing any configuration for this name lookup.

**Comment by bhravich** [comment] 2016-12-05 23:55
@chengwang86 I changed the application template as follows and it worked:

```
---
version: "2"
services:
  wordpress:
    image: "wordpress:4.3.1"
    environment:
    - "WORDPRESS_DB_PASSWORD=pass@word01"
    - "WORDPRESS_DB_NAME=wordpress"
    - "WORDPRESS_DB_HOST=mysql:3306"
    ports:
    - "80"
    links:
    - "mysql:mysql"
    depends_on:
    - "mysql"
  mysql:
    image: "mariadb:10.0.26"
    environment:
    - "MYSQL_ROOT_PASSWORD=pass@word01"
    ports:
    - "3306"
```

The links section was changed from 'mysql' to 'mysql:mysql'.

**Comment by chengwang86** [comment] 2016-12-05 23:56
@bhravich I agree.

In the portlayer log, I found the following (can't find the container mysql):
```
time=2016-12-02T23:06:54.626684757Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).ContainersByAlias:1140] 
time=2016-12-02T23:06:54.626718080Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).ContainersByAlias:1140] [30.194µs]  
time="2016-12-02T23:06:54Z" level=debug msg="Can't find the container: \"mysql\"" 
time=2016-12-02T23:06:54.626763125Z level=debug msg=[ END ] [github.com/vmware/vic/lib/dns.(*Server).HandleVIC:325] [281.1µs] ;; opcode: QUERY, status: NOERROR, id: 45156
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mysql.	IN	 A
```


In "#1", if you do "docker -H ... network ls", you would find all the networks. If there is one named "bridge", could you pls do "docker -H ... network inspect bridge" and post the output? Also post the output of "docker -H ... inspect mysql".

The reason is that when you do "#1", the two containers would be connected by the default network "bridge". And "network inspect ..." should show both containers. If not, there is a problem.

**Comment by chengwang86** [comment] 2016-12-06 00:06
@bhravich This is weird. According to https://github.com/vmware/admiral/wiki/User-Guide#service-discovery

> Example: If we take for example 2 services that are represented by 2 containers, one named serviceA and the other serviceB.

> If they are connected to one user defined network, then serviceA can reach serviceB, using its name i.e. serviceB.

So I thought it was not necessary to specify alias for mysql.

**Comment by bhravich** [comment] 2016-12-07 00:04
@chengwang86 I guess, last test run was a random success. And the network details doesn't look right to me.

Both the containers got the same IP "172.16.0.2" only then the networking between them works.

```
docker -H 10.197.9.234:2376 --tls ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                          NAMES
e4866e9b4449        mariadb:10.0.26              "docker-entrypoint.sh"   2 hours ago         Up 2 hours          10.197.9.234:32786->3306/tcp   mysql-mcm324_29452858683
8254a0a6694d        wordpress:4.3.1              "/entrypoint.sh apach"   2 hours ago         Up 2 hours          10.197.9.234:32785->80/tcp     wordpress-mcm323_29451579038
d5552cf00e34        victest/vote-worker:latest   "/bin/sh -c dotnet Wo"   28 hours ago        Up 28 hours                                        worker-mcm289_29358723909
```

```
docker -H 10.197.9.234:2376 --tls network ls
NETWORK ID          NAME                DRIVER
925bf4a5e568        bridge              bridge  
```

```
docker -H 10.197.9.234:2376 --tls network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "925bf4a5e5689360be0e9ecfe33a97586641d04d974011029ba8e67643a8ae30",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.16.0.0/16",
                    "Gateway": "172.16.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "e4866e9b4449262cd9664ba66185de5008a14ba7d2021b71489bceba11747156": {
                "Name": "mysql-mcm324_29452858683",
                "EndpointID": "e4866e9b4449262cd9664ba66185de5008a14ba7d2021b71489bceba11747156",
                "MacAddress": "",
                "IPv4Address": "172.16.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```


```
docker -H 10.197.9.234:2376 --tls inspect mysql-mcm324_29452858683
[
    {
        "Id": "e4866e9b4449262cd9664ba66185de5008a14ba7d2021b71489bceba11747156",
        "Created": "2016-12-06T21:21:04Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "mysqld"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-12-06T21:21:11Z",
            "FinishedAt": ""
        },
       ....................
       ....................
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32786"
                    }
                ]
            },
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "",
                    "EndpointID": "192",
                    "Gateway": "172.16.0.1/16",
                    "IPAddress": "172.16.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```

```
docker -H 10.197.9.234:2376 --tls inspect wordpress-mcm323_29451579038
[
    {
        "Id": "8254a0a6694d70718f66a1e747e1bb5a949410bb228f0f70b443fe3fee3df16c",
        "Created": "2016-12-06T21:00:06Z",
        "Path": "/entrypoint.sh",
        "Args": [
            "apache2-foreground"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-12-06T21:15:30Z",
            "FinishedAt": "2016-12-06T21:00:47Z"
        },
       ....................
       ....................
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32785"
                    }
                ]
            },
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "",
                    "EndpointID": "192",
                    "Gateway": "172.16.0.1/16",
                    "IPAddress": "172.16.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```
Logs for the above mentioned host : 
[container-logs-host-3.zip](https://github.com/vmware/vic/files/635338/container-logs-host-3.zip)

Also, I deployed another host and just tried to deploy the two containers separately. Noticed the same behavior. The wordpress application goes offline due to network error.

```
docker -H 10.197.9.251:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                         NAMES
a75fff751631        wordpress:4.3.1     "/entrypoint.sh apach"   17 minutes ago      Exited (1) 4 minutes ago   10.197.9.251:80->80/tcp       wordpress
8672d120c914        mariadb:10.0.26     "docker-entrypoint.sh"   34 minutes ago      Up 34 minutes              10.197.9.251:3306->3306/tcp   mysql
```

```
docker -H 10.197.9.251:2376 --tls network ls
NETWORK ID          NAME                DRIVER
24812c006a89        bridge              bridge 
```

```
docker -H 10.197.9.251:2376 --tls network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "24812c006a89470897003c663f06ee6e26969ecada40c1171e0485e719e1e531",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.16.0.0/16",
                    "Gateway": "172.16.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "8672d120c914cd14a70d38d58f7c256dfa32b63ff244d36d914a2f2409f13912": {
                "Name": "mysql",
                "EndpointID": "8672d120c914cd14a70d38d58f7c256dfa32b63ff244d36d914a2f2409f13912",
                "MacAddress": "",
                "IPv4Address": "172.16.0.2/16",
                "IPv6Address": ""
            },
            "a75fff7516319c2947e2848b2053e70cc8d6ce65f5b71529b904c28be7345c01": {
                "Name": "wordpress",
                "EndpointID": "a75fff7516319c2947e2848b2053e70cc8d6ce65f5b71529b904c28be7345c01",
                "MacAddress": "",
                "IPv4Address": "172.16.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
Logs can be located here: 
[container-logs-host-5.zip](https://github.com/vmware/vic/files/635352/container-logs-host-5.zip)

**Comment by lazarin** [comment] 2016-12-07 06:57
Tested with rc2.
I think the issue here is with the container name, link and link alias.

Manually it succeeds because the container is named 'mysql' as the link and the link alias.
With admiral the container has some unique suffix - 'mysql-xxx-xxxx' and the link alias is 'mysql'. From wordpress container I am able to ping 'mysql-xxx-xxxx' but not 'mysql' although that's the alias used in the template. The name resolution should honor the link alias if such is present, and then it will be fine.

**Comment by mlh78750** [comment] 2016-12-07 16:22
cc @hmahmood Can you take a look at why the container's IP's were the same. 

Also, you should not need to specify --link for the container to be found by others. However @lazarin is right that by default it will resolve the container name so if it has -xxx-xxxx added you'll need to use that name as well.

**Comment by chengwang86** [comment] 2016-12-07 16:30
@mlh78750 Here the goal is to get the wordpress application run using admiral template (similar to docker-compose I suppose), not running it manually. When we create the template file, we couldn't know what the suffix "-xxx-xxxx" would be. So we cannot simply use the name "mysql-xxx-xxxx" before the container is created.

**Comment by mlh78750** [comment] 2016-12-07 16:36
@chengwang86 Correct. `--link` is also deprecated. But if admiral is changing the name, then we need to make sure aliases are working correctly and admiral should set the alias to the name that the other containers will look for the service on.

**Comment by hmahmood** [comment] 2016-12-07 18:06
@mlh78750 @bhravich the second of those logs, the ps output seems to not match what's in the logs. The wordpress container shows up as running in the logs, and that would explain why it shows up in the output of network inspect. This might just be a race; maybe a docker ps after the inspect command would have shown the container as running.

As for the duplicate IP in the docker info output, again looking through the logs, it does not seem to match the IP that is actually assigned. Plus wordpress does not show up in the network inspect command output, but does seem to have an IP according to docker info. I see this container starting and stopping several times in the logs; could this be just another race between the commands while the container state is in flux? I will investigate if the docker info output with regards to the IP is correct.

**Comment by sflxn** [comment] 2016-12-14 21:28
Not so sure it's an Admiral issue.  I just tried using Admiral to provision to a regular docker host.  It works fine.  When I inspect the resulting wordpress container, it had the following,

```
            "Links": [
                "/mysql-mcm480_29388469985:/wordpress-mcm481_29388473927/mysql"
            ],
```

I was able to load the wordpress page in a browser.  Regular docker is mapping the links correctly.  I'll have to dig in some more to find out where the problem is.

BTW, in your yml file, you must specify 80:80 in your port.

**Comment by hmahmood** [comment] 2016-12-14 22:19
There may be a bug in how we process `--link` where only the alias is specified (e.g. `--link mysql` as opposed to `--link mysql:mysql`). 

@sflxn the links section above looks like the [legacy docker link](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) mechanism. We don't support it, and I think docker is deprecating it as well. However, `--link` should work, although of course the underlying mechanics are entirely different.

**Comment by chengwang86** [comment] 2016-12-14 22:32
@hmahmood Even after I removed --link and depends_on, it still didn't work with vic+admiral. And I observed exactly the same error msg; however, it is expected to work according to https://github.com/vmware/admiral/wiki/Docker-Compose-Support#wordpress-template

So I think maybe there are other reasons why the example in the original post didn't work other than --link.

**Comment by sflxn** [comment] 2016-12-14 23:53
These are the logs from wordpress after a successful docker-compose bring up:

```
Complete! WordPress has been successfully copied to /var/www/html
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Dec 06 05:19:34.083246 2016] [mpm_prefork:notice] [pid 227] AH00163: Apache/2.4.10 (Debian) PHP/5.6.28 configured -- resuming normal operations
```

This is what happens after provisioning with Admiral:

```
Complete! WordPress has been successfully copied to /var/www/html

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19
```

Eventually, the Wordpress container gives up and exits.

**Comment by sflxn** [comment] 2016-12-15 00:27
This is a snippet from the portlayer logs after a successful docker-compose:

```
time="2016-12-06T05:50:33Z" level=debug msg="adding alias wordpress_default:wordpress_mysql_1 -> wordpress_mysql_1" 
time="2016-12-06T05:50:33Z" level=debug msg="adding alias wordpress_default:b177ce112a6e -> wordpress_mysql_1" 
time="2016-12-06T05:50:33Z" level=debug msg="adding alias wordpress_default:mysql -> wordpress_mysql_1" 
```

This is the snippet after provisioning from Admiral:

```
time="2016-12-06T05:58:25Z" level=debug msg="adding alias bridge:mysql-mcm193_29397495692 -> mysql-mcm193_29397495692" 
time="2016-12-06T05:58:25Z" level=debug msg="adding alias bridge:858b90deffb5 -> mysql-mcm193_29397495692" 
```

It's missing the 3rd operation.  @hmahmood will be in a better position to interpret this.

**Comment by sflxn** [comment] 2016-12-15 00:35
One difference between the way docker-compose and admiral provision is that docker-compose creates a new network for the services.  Admiral just uses the bridge network.

**Comment by hmahmood** [comment] 2016-12-15 00:36
@sflxn that would explain your previous comment. We are ignoring links for containers that are only on the bridge networks. I am fixing that right now.

**Comment by sflxn** [comment] 2016-12-15 00:51
I was looking in the Admiral docs for info on creating a new network, and I actually came across this, 
https://github.com/vmware/admiral/wiki/Docker-Compose-Support#docker-compose-file-modifications-in-examples

**Comment by sflxn** [comment] 2016-12-15 01:19
When I followed Admiral's docs for updating the compose file to simulate what docker-compose does, it still doesn't work, and I get the following portlayer log snippet:

```
time="2016-12-06T06:54:48Z" level=debug msg="adding alias wpnet-mcm781_29400830972:mysql -> mysql-mcm782_29400833722" 
time="2016-12-06T06:54:48Z" level=debug msg="adding alias bridge:mysql-mcm782_29400833722 -> mysql-mcm782_29400833722" 
time="2016-12-06T06:54:48Z" level=debug msg="adding alias bridge:6e38f1da37bb -> mysql-mcm782_29400833722" 
time="2016-12-06T06:54:48Z" level=debug msg="adding alias wpnet-mcm781_29400830972:mysql-mcm782_29400833722 -> mysql-mcm782_29400833722" 
time="2016-12-06T06:54:48Z" level=debug msg="adding alias wpnet-mcm781_29400830972:6e38f1da37bb -> mysql-mcm782_29400833722" 
```

**Closed** 2016-12-15 21:19 UTC
Labels: product/admiral, status/needs-triage
