### ISSUE TITLE
Docker-personality not restarted during VCH installation

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3380] opened 2016-11-29 18:01 UTC
**VIC version:**

0.8 (based on the code checked out on 11/28; maybe the same with rc3)

**Deployment details:**

Mimicking the stress test by installing/deleting VCHes 100 times on a local ESXi host. 
```
#!/bin/bash

for i in {1..100}
do
        bin/vic-machine-linux create --debug 3 --name=cheng-1 --target=root:pwd@192.168.60.162 --image-store=datastore1 --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso  --no-tlsverify --timeout=60m --thumbprint=...

        bin/vic-machine-linux delete --force --target=root:pwd@192.168.60.162 --name=cheng-1 --thumbprint=...
done
```

**Steps to reproduce:**
See above. This is the first time I see the error. Not sure yet whether it is reproducible.

**Actual behavior:**
From vic-machine.log
```
^[[34mINFO^[[0m[2016-11-28T09:17:56-08:00] Uploading images for container
^[[34mINFO^[[0m[2016-11-28T09:17:56-08:00]      "bin/bootstrap.iso"
^[[34mINFO^[[0m[2016-11-28T09:17:56-08:00]      "bin/appliance.iso"
^[[34mINFO^[[0m[2016-11-28T09:18:05-08:00] Waiting for IP information
^[[34mINFO^[[0m[2016-11-28T09:18:25-08:00] Waiting for major appliance components to launch
^[[37mDEBU^[[0m[2016-11-28T09:18:28-08:00] get vm properties [config.extraConfig] of vm VirtualMachine:1503
^[[37mDEBU^[[0m[2016-11-28T09:18:28-08:00] properties: [config.extraConfig summary.runtime.connectionState]
^[[37mDEBU^[[0m[2016-11-28T09:18:28-08:00] Obtained IP address for client interface: "192.168.60.150"
^[[34mINFO^[[0m[2016-11-28T09:18:28-08:00] Checking VCH connectivity with vSphere target
^[[37mDEBU^[[0m[2016-11-28T09:18:28-08:00] Using default resource pool for compute resource: "/ha-datacenter/host/localhost.localdomain/Resources"
^[[37mDEBU^[[0m[2016-11-28T09:18:29-08:00] get vm properties [config.extraConfig] of vm VirtualMachine:1503
^[[37mDEBU^[[0m[2016-11-28T09:18:29-08:00] properties: [config.extraConfig summary.runtime.connectionState]
^[[34mINFO^[[0m[2016-11-28T09:18:29-08:00] vSphere API Test: https://192.168.60.162 vSphere API target responds as expected
^[[37mDEBU^[[0m[2016-11-28T09:18:29-08:00] connection refused
^[[37mDEBU^[[0m[2016-11-28T09:18:30-08:00] Components not yet initialized, retrying
^[[37mDEBU^[[0m[2016-11-28T09:18:30-08:00] connection refused
^[[37mDEBU^[[0m[2016-11-28T09:18:31-08:00] Components not yet initialized, retrying
^[[37mDEBU^[[0m[2016-11-28T09:18:31-08:00] connection refused
```
tether.debug
```
time=2016-11-23T09:50:01.572669356Z level=info msg=op=255.4 (delta:823.156733ms): Creating image scratch ([datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk) 
time=2016-11-23T09:50:01.572695279Z level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk 
time=2016-11-23T09:50:01.572704273Z level=info msg=op=255.4 (delta:823.242625ms): Create/attach vmdk [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk from parent  
time=2016-11-23T09:50:01.603642612Z level=debug msg=op=255.4 (delta:854.174957ms): Attach reconfigure task=Task:haTask-1503-vim.VirtualMachine.reconfigure-463371 
time="2016-11-23T09:50:01Z" level=debug msg="unexpected fault on task retry : &types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}" 
time="2016-11-23T09:50:01Z" level=debug msg="Do not fix non invalid state error" 
time=2016-11-23T09:50:01.671723759Z level=error msg=op=255.4 (delta:922.26055ms): vmdk storage driver failed to attach disk: The operation is not allowed in the current state. 
time=2016-11-23T09:50:01.671731979Z level=debug msg=[ END ] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [99.036619ms] [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk 
time=2016-11-23T09:50:01.671741405Z level=error msg=op=255.4 (delta:922.275994ms): CreateAndAttach([datastore1] 
```
docker-personality
```
time="2016-11-23T09:50:00Z" level=info msg="Container cache updated successfully" 
time="2016-11-23T09:50:00Z" level=info msg="Creating image store" 
time="2016-11-23T09:50:01Z" level=error msg="Failed to create image store" 
time="2016-11-23T09:50:01Z" level=fatal msg="failed to initialize backend: [POST /storage][500] CreateImageStore default  &{Code:0xc4204635e8 Message:The operation is not allowed in the current state.}" 
```
hostd
```
2016-11-23T09:50:01.753Z error hostd[578C8B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/58239ae6-46466bb6-a754-000c293a3617/cheng-1/cheng-1.vmx opID=613fbeaa user=root] Invalid transition requested (VM_STATE_GUEST_OPERATION -> VM_STATE_RECONFIGURING): Invalid state
2016-11-23T09:50:01.754Z warning hostd[578C8B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/58239ae6-46466bb6-a754-000c293a3617/cheng-1/cheng-1.vmx opID=613fbeaa user=root] Failed to start Reconfiguring: vim.fault.InvalidState
2016-11-23T09:50:01.755Z info hostd[578C8B70] [Originator@6876 sub=Default opID=613fbeaa user=root] AdapterServer caught exception: vim.fault.InvalidState
```
PL
```
time=2016-11-23T09:50:01.572669356Z level=info msg=op=255.4 (delta:823.156733ms): Creating image scratch ([datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk) 
time=2016-11-23T09:50:01.572695279Z level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk 
time=2016-11-23T09:50:01.572704273Z level=info msg=op=255.4 (delta:823.242625ms): Create/attach vmdk [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk from parent  
time=2016-11-23T09:50:01.603642612Z level=debug msg=op=255.4 (delta:854.174957ms): Attach reconfigure task=Task:haTask-1503-vim.VirtualMachine.reconfigure-463371 
time="2016-11-23T09:50:01Z" level=debug msg="unexpected fault on task retry : &types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}" 
time="2016-11-23T09:50:01Z" level=debug msg="Do not fix non invalid state error" 
time=2016-11-23T09:50:01.671723759Z level=error msg=op=255.4 (delta:922.26055ms): vmdk storage driver failed to attach disk: The operation is not allowed in the current state. 
time=2016-11-23T09:50:01.671731979Z level=debug msg=[ END ] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [99.036619ms] [datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk 
time=2016-11-23T09:50:01.671741405Z level=error msg=op=255.4 (delta:922.275994ms): CreateAndAttach([datastore1] cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk) error: The operation is not allowed in the current state. 
time=2016-11-23T09:50:01.671746476Z level=error msg=op=255.4 (delta:922.285576ms): Cleaning up failed image scratch 
time="2016-11-23T09:50:01Z" level=info msg="Removing 564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/manifest" 
time="2016-11-23T09:50:01Z" level=debug msg="unexpected fault on task retry : &types.FileNotFound{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:\"/vmfs/volumes/58239ae6-46466bb6-a754-000c293a3617/cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/manifest\"}}" 
time="2016-11-23T09:50:01Z" level=info msg="Removing 564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk" 
time="2016-11-23T09:50:01Z" level=debug msg="unexpected fault on task retry : &types.FileNotFound{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:\"/vmfs/volumes/58239ae6-46466bb6-a754-000c293a3617/cheng-1/VIC/564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch/scratch.vmdk\"}}" 
time="2016-11-23T09:50:01Z" level=info msg="Removing 564df1cc-9cae-fe28-19b4-9bb27180d541/images/scratch" 
time=2016-11-23T09:50:01.807329295Z level=info msg=op=255.4 (delta:1.057863507s): Removing failed image store 564df1cc-9cae-fe28-19b4-9bb27180d541 
time=2016-11-23T09:50:01.807347142Z level=info msg=op=255.4 (delta:1.057884569s): Cleaning up image store 564df1cc-9cae-fe28-19b4-9bb27180d541 
time="2016-11-23T09:50:01Z" level=info msg="Removing 564df1cc-9cae-fe28-19b4-9bb27180d541/images" 
```

**Expected behavior:**
The VCH should be started successfully.

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/619757/container-logs.zip)

P.S. 
Initial discussion with @fdawg4l is [here](https://github.com/vmware/vic/issues/3273#issuecomment-263392888)

**Comment by fdawg4l** [comment] 2016-11-29 20:51
From the bundle.

ps
```
vicadmin   247   193  0 09:49 ?        00:00:00 /sbin/vicadmin --dc=ha-datacenter --pool=/ha-datacenter/host/localhost.localdomain/Resources --cluster=/ha-datacenter/host/localhost.localdomain
root       255   193  0 09:49 ?        00:00:00 /sbin/port-layer-server --host=localhost --port=2377
```

It doesn't look like the docker daemon is running from the ps output.

docker-personality.log
```
 23 time="2016-11-23T09:50:00Z" level=debug msg="Found 0 containers"·
 24 time="2016-11-23T09:50:00Z" level=info msg="Container cache updated successfully"·
 25 time="2016-11-23T09:50:00Z" level=info msg="Creating image store"·
 26 time="2016-11-23T09:50:01Z" level=error msg="Failed to create image store"·
 27 time="2016-11-23T09:50:01Z" level=fatal msg="failed to initialize backend: [POST /storage][500] CreateImageStore default  &{Code:0xc4204635e8 Message:The operation is not allowed in the current state.}"·
                                                                                                                                                                                                                        
```

`cmd/docker/main.go`
```
 75 »···if err := vicbackends.Init(cli.portLayerAddr, productName, &vchConfig, vchConfig.InsecureRegistries); err != nil {
 76 »···»···log.Fatalf("failed to initialize backend: %s", err)
 77 »···}
```

I'm not sure if this is related, but `systemd` doesn't necessarily like the vic-init unit.

`journalctl`

```
 993 Nov 23 09:49:54 Photon systemd[1]: [/etc/systemd/system/vic-init.service:15] Unknown lvalue 'Wants' in section 'Install'
 994 Nov 23 09:49:54 Photon systemd[1]: [/etc/systemd/system/vic-init.service:16] Unknown lvalue 'Wants' in section 'Install'
```

Anyway, the crux of the problem is we waited 3 seconds before giving up.  And the docker daemon didn't look to have come up in that time.  I can't tell if it was going to come up or if it was bouncing.  The log only has the failure once (where there's the `Fatalf`) so I'm guessing we either needed to wait longer or something else is going on.

**Comment by chengwang86** [comment] 2016-11-30 18:41
Hit this again using the same script.

[container-logs.zip](https://github.com/vmware/vic/files/622658/container-logs.zip)

**Comment by fdawg4l** [comment] 2016-11-30 19:14
`init.og`

648 time="2016-11-23T09:50:02Z" level=warning msg="Wait returned waitid: no child processes"·
649 time="2016-11-23T09:50:02Z" level=warning msg="Debug is set to 3 so squashing relaunch of exited process"·

**Comment by fdawg4l** [comment] 2016-11-30 19:15
@chengwang86 

Since the vch was deployed with debug enabled, we don't restart the docker personality daemon.  Can you retry your test with debug disabled?

**Comment by chengwang86** [comment] 2016-11-30 20:21
@fdawg4l After I disabled the "debug" option, the whole test (100 times of installing/deleting VCHs) succeeded. However, I cannot confirm whether "restart the docker personality daemon" happened or not during the test.

**Comment by fdawg4l** [comment] 2016-11-30 21:01
@chengwang86 I think it's fine.  If we see the issue again we can reopen this bug.  But, for reference, testing with debug enabled changes the behavior so I suggest removing debug from all the tests.

I'm closing the issue.  Thanks.

**Closed by fdawg4l** 2016-11-30 21:01 UTC
Labels: kind/bug, status/needs-triage

**Comment by thiagocorredor** [comment] 2017-05-15 21:37
Hello ! I am having this issue also. I am running the VIC 1.1.0 version.
Messagem from test:

docker -H 172.27.1.245:2376 --tls info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by fdawg4l** [comment] 2017-05-15 21:54
@thiagocorredor this issue is from quite a long time ago.  Can you create a new issue and attach a log bundle?  See here for details for getting the bundle (https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/log_bundles.html)
