### ISSUE TITLE
[tether] should use a default and sane PATH

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#1032] opened 2016-06-09 18:27 UTC
**VIC Version:**

master

**Code**

```ts
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] $Z create -it busybox
148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] $Z start 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
Error response from daemon: server error from portlayer
Error: failed to start containers: 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] $Z create -it busybox /bin/sh
5ea8e1f9ab808677221759a9505878689c71683a8bfcac7952bf9a49fffe7979
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)] $Z start 5ea8e1f9ab808677221759a9505878689c71683a8bfcac7952bf9a49fffe7979
5ea8e1f9ab808677221759a9505878689c71683a8bfcac7952bf9a49fffe7979
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(master)]
```

**Expected behavior:**

Both should work

**Actual behavior:**

First one fails with 
```
INFO[0000] Loaded executor config
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] setting hostname to
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] [91.116µs] setting hostname to
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] applying endpoint configuration for bridge
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] [555.819µs] applying endpoint configuration for bridge
INFO[0000] Launching process for session 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).launch] launching session 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
INFO[0000] [BEGIN] [main.(*operations).SessionLog] configure session log writer
INFO[0000] opening ttyS2 for session logging
INFO[0000] [ END ] [main.(*operations).SessionLog] [1.703722ms] configure session log writer
ERRO[0000] Path lookup failed for sh: sh: no such executable in PATH
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*tether).launch] [19.808292ms] launching session 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b
ERRO[0000] failed to launch sh for 148e86e8327c9e4c3a21f98074a1ec53d2bc79547340877b8f349259aca1475b: sh: no such executable in PATH
INFO[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).stopReaper] Shutting down child reaping
INFO[0000] Shutting down reaper
INFO[0000] [ END ] [github.com/vmware/vic/lib/tether.(*tether).stopReaper] [2.023356ms] Shutting down child reaping
INFO[0000] Stopping extension Attach
INFO[0000] [BEGIN] [main.(*attachServerSSH).stop] stop attach server
INFO[0000] [ END ] [main.(*attachServerSSH).stop] [1.583µs] stop attach server
```

**Comment by hickeng** [comment] 2016-06-19 19:43
@jzt Docker has a default path - I don't want to hard code that into the tether as it's a personality thing - the path actually includes directories that don't necessarily exist in the image. Either the personality needs to add this default path, or the path from the image metadata is not getting passed to the port layer correctly during create. I'm assigning to you because you were the last person looking at the metadata - if it should be someone else, please pass it on. This should be an easy fix and significantly improves usability so relatively high priority.

**Comment by jzt** [comment] 2016-06-21 02:04
@hickeng I'll move to this after #1155.

**Comment by hickeng** [comment] 2016-06-27 14:00
@jzt can you pick this up asap - it should be a relatively small item if the image metadata is available (either it's rolled into the base layer or it's added during container create)

**Comment by jzt** [comment] 2016-06-27 23:06
@hickeng yep, looking into it now.

**Comment by jzt** [comment] 2016-06-27 23:26
@hickeng: I'm familiarizing myself with the container create code, but just FYI I'm having problems reproducing:

```
$ docker -H 192.168.218.135:2376 --tls create -it busybox
46c1a3f4aa7d464d080099a2c3388d063a82a8e3bfaf2d360a5b26d46ae1120b
$ docker -H 192.168.218.135:2376 --tls start 46c1a3f4aa7d464d080099a2c3388d063a82a8e3bfaf2d360a5b26d46ae1120b
46c1a3f4aa7d464d080099a2c3388d063a82a8e3bfaf2d360a5b26d46ae1120b
```

**Comment by caglar10ur** [comment] 2016-06-28 00:03
https://github.com/docker/docker/blob/3f6fa8af4522ba9b5ce2e4a52f959970ae4ccb8a/container/container_unix.go#L51

https://github.com/docker/docker/blob/b3a1ae02a91d93efdface95ce7ed131dc397dedd/pkg/system/path_unix.go

**Comment by jzt** [comment] 2016-06-28 01:23
I see now.. @caglar10ur thanks for the links. @hickeng when you say you don't want to hardcode it into the tether, do you mean to say that you don't want to use the tether to make any changes on the appliance in this regard?

I ask because I assume we will always be using Photon as the OS for our container VMs, and I'm trying to think of the best way to couple (or decouple?) our code with/from Photon and any potential future filesystem layout changes.

Side note: The image ID is generated from metadata that contains this default path, so we probably should be wary about altering it in there - which means we would need some shim code somewhere to modify the path on the way into a container. Just thinking out loud.

**Comment by hickeng** [comment] 2016-07-06 19:33
works for me.

**Closed by hickeng** 2016-07-06 19:33 UTC
Labels: component/tether, kind/bug, status/needs-attention
