### ISSUE TITLE
root password for the virtual container host

### ISSUE THREAD

**Issue by mbenachour** [vmware/vic#2952] opened 2016-10-29 20:30 UTC
what is the password for root user in the VCH (photon os)  created with vic-machine ?
root/changeme is not working

**Comment by mdubya66** [comment] 2016-10-29 22:34
This as changed with https://github.com/vmware/vic/issues/1218

The issue to document how to enable ssh and the root password can be found here https://github.com/vmware/vic/issues/2678

**Comment by mdubya66** [comment] 2016-10-29 22:34
Closing as duplicate of #2678

**Closed by mdubya66** 2016-10-29 22:34 UTC
