### ISSUE TITLE
"No such image error" on docker run with an image in harbor registry

### ISSUE THREAD

**Issue by mobla** [vmware/vic#2913] opened 2016-10-26 23:03 UTC
Not sure it is similar to issue: https://github.com/vmware/vic/issues/1821
Steps:
1. Create VCH - with insecure-registry - harbor registry (with no default volume store)
root@photon-yhNySW7sg [ ~/vic ]# ./vic-machine-linux create --name VCH2 --target 10.139.23.227 --compute-resource cls --user administrator@vsphere.local --password 'Admin!23' --bridge-network vicDVPG --image-store sharedVmfs-0 --no-tls --insecure-registry 10.139.23.226:80
2. Pull an image to local registry
3. Do docker login (admin user in Harbor)
4. Tag and Push that image to Harbor registry
5. Now, Pull it back from Harbor
6. Do docker images cmd to ensure images are listed in VCH
root@photon-yhNySW7sg [ ~/vic ]# docker -H 10.139.23.221:2375 images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
10.139.23.226:80/heimdall/busybox   latest              e292aa76ad3b        2 weeks ago         1.093 MB
10.139.23.226:80/heimdall/nginx     1.9.0               7e156d496c9f        17 months ago       132.8 MB
7. Run the application
root@photon-yhNySW7sg [ ~/vic ]# docker -H 10.139.23.221:2375 run -it 10.139.23.226:80/heimdall/busybox:latest
Unable to find image '10.139.23.226:80/heimdall/busybox:latest' locally
Pulling from heimdall/busybox
56bec22e3559: Already exists
a3ed95caeb02: Already exists
Digest: sha256:f6a678ca67d75465a1bfd3e9b1e93ba124e92bb2829553b121e08b21767f0c6c
Status: Image is up to date for heimdall/busybox:latest
docker: Error: No such image: 10.139.23.226:80/heimdall/busybox:latest.
See 'docker run --help'.

**VIC Version:**
root@photon-yhNySW7sg [ ~/vic ]# ./vic-machine-linux version
vic-machine-linux version v0.6.0-4890-4f98611
Server:
Version: 0.6.0
API version: 1.23

**Expected behavior:**
busybox:latest should run and tty should be accessible and interactive

**Actual behavior:**
Fails with: docker: Error: No such image: 10.139.23.226:80/heimdall/busybox:latest.

Note: the same image runs ok with local docker (client machine)
root@photon-yhNySW7sg [ ~/vic ]# docker run -it 10.139.23.226:80/heimdall/busybox:latest
/ # ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var

![invalid-config-for-device](https://cloud.githubusercontent.com/assets/3538999/19749052/affa3e44-9b9a-11e6-9e34-5b8ecb9e43ba.png)
[container-logs.tar.gz](https://github.com/vmware/vic/files/554637/container-logs.tar.gz)

**Comment by anchal-agrawal** [comment] 2016-10-27 04:34
`Invalid configuration for device 1` - looks like a dup of #2856.

**Comment by mlh78750** [comment] 2016-10-27 16:16
@mobla I'm taking a look at this. I'll be in touch if I end up with questions.

**Comment by mlh78750** [comment] 2016-10-27 18:05
@mobla did you do a snapshot on the container VM?
Also, what build of 6.5 is this?
What build of vic was this?

**Comment by mobla** [comment] 2016-10-27 18:55
Did you do a snapshot on the container VM? - Nope
Also, what build of 6.5 is this? : SB-7955641
What build of vic was this?: vic-machine-linux version v0.6.0-4890-4f98611

**Comment by mlh78750** [comment] 2016-10-27 19:01
can you reproduce with vic 6299?

**Comment by mobla** [comment] 2016-10-27 19:17
with vic 6194, it is still the same problem

root@photon-lJUA39j42 [ ~/vic ]# docker -H 10.139.23.221:2375 run -it 10.139.23.226:80/heimdall/busybox:latest
Unable to find image '10.139.23.226:80/heimdall/busybox:latest' locally
Pulling from heimdall/busybox
56bec22e3559: Already exists
a3ed95caeb02: Already exists
Digest: sha256:f6a678ca67d75465a1bfd3e9b1e93ba124e92bb2829553b121e08b21767f0c6c
Status: Image is up to date for heimdall/busybox:latest
docker: Error: No such image: 10.139.23.226:80/heimdall/busybox:latest.
See 'docker run --help'.

**Comment by mlh78750** [comment] 2016-10-27 19:30
after talking to @mobla offline found out that he was removing the container VM in the vSphere UI and then this issue would occur. This is a dup of #2856. We'll close this as a dup.

**Comment by mobla** [comment] 2016-10-27 19:35
Sure accepted it as a dup of 2856! will follow up on 2856. Thanks for your time Mike!

**Comment by mlh78750** [comment] 2016-10-27 20:05
@mobla: I understand from offline discussion that the steps included deleting the container VM from the VC UI and then you could no longer run containers using the same image. Is that correct? if so, can you please reproduce and file a new issue with that information for tracking. Please include the VC/ESX versions/builds as well.

**Comment by mlh78750** [comment] 2016-10-27 21:33
See #2928

**Closed** 2016-10-28 23:10 UTC
Labels: duplicate
