### ISSUE TITLE
Stopped Containers appear to not actually be stopped

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic#2271] opened 2016-09-07 16:49 UTC
When attemping to reproduce another issue. I made a busybox /bin/top container. started it. then stopped it(supposedly) and tried to remove it. The removal fails with a "power of the container first" type error, this is after a reportedly successful stop call. 

```
matthewavery@ubuntu ~/go/src/github.com/vmware/vic
 % docker -H 10.160.60.105:2376 --tls stop dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a    
dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a
matthewavery@ubuntu ~/go/src/github.com/vmware/vic
 % docker -H 10.160.60.105:2376 --tls rm dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a
Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f
matthewavery@ubuntu ~/go/src/github.com/vmware/vic
 % docker -H 10.160.60.105:2376 --tls stop dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a
dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a
matthewavery@ubuntu ~/go/src/github.com/vmware/vic
 % docker -H 10.160.60.105:2376 --tls rm dced210b3c98596bb03447f7cd1cd50661528004ef2d7c6f359f8e69e8faa53a
Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f
```

**Comment by mdubya66** [comment] 2016-09-07 20:45
possible dupe of or related to #1541

**Comment by mdubya66** [comment] 2016-09-07 20:47
see also #378 and #2230

**Comment by mdubya66** [comment] 2016-09-07 21:02
I'll move this back to p0.

**Comment by anchal-agrawal** [comment] 2016-09-08 19:03
I can repro this on a VC setup but not on a single ESX.

**Comment by gigawhitlocks** [comment] 2016-09-12 20:51
Further investigation reveals that `stop` does work, but the state of the machine is not reported properly back to the VCH. `ps`'s output is therefore erroneous, and anything that relies on the internal state reporting to be correct is also broken

**Closed** 2016-09-13 19:06 UTC
Labels: kind/bug, kind/bug/p0
