### ISSUE TITLE
Timeout while deleting VCH with large numbers of container VMs

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#7739] opened 2018-04-13 21:32 UTC
I had a few thousands containers in stopped mode. I decided to delete VIC, while this operation was happening, it seems like I have hit allowed timeout to delete VIC, so I started seeing many such errors in vic-machine output:
```
Apr 13 2018 16:30:43.708-05:00 WARN  Will try again in 22.490796035s. Operation failed with detected error
ERRO[0193] net.dialSerial: vic-machine-linux error: context deadline exceeded
vic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux
vic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux 
DEBU[0194] Getting list of the devices for VM "kind_booth-853cef88f1f4" 
ERRO[0194] net/http.(*Transport).getConn: vic-machine-linux error: context deadline exceeded
vic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux
vic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux 
```

**Comment by vburenin** [comment] 2018-04-13 21:34
Repro step:
1. Create at least 500 not running containers.
2. run vic-machine delete

**Comment by hickeng** [comment] 2018-04-13 21:59
@vburenin The operations should be dispatched in parllel - can you confirm that that at least is occurring?
Also, edited title for clarity.

**Comment by zjs** [comment] 2018-04-13 22:14
Also, does specifying a larger `--timeout` value than the default (3m0s) avoid this issue?

**Comment by vburenin** [comment] 2018-04-16 17:00
@zjs It may work. But it is not what user would expect. Process of deleting my setup was intense producing a lot of logging. At some point it just started printing all those timeout errors not interrupting the process of removing VCH successfully failing on each API call operation since timeout has expired.

**Comment by rogeliosanchez** [comment] 2018-04-18 00:25
Pinging @anchal-agrawal for further triage/labeling.

**Comment by anchal-agrawal** [comment] 2018-04-18 18:41
Assigning issue owner for further triage - since this is a `vic-machine` issue, please work with the lifecycle team to triage this issue further. Thanks!

**Comment by zjs** [comment] 2018-04-24 22:37
Duplicate of #7020

**Closed by zjs** 2018-04-24 22:37 UTC
Labels: component/vic-machine, priority/p3, status/needs-estimation, team/lifecycle
