### ISSUE TITLE
vic-machine-windows.exe failed: Failed to power on appliance Module 'MonitorLoop' power on failed. . Exiting...

### ISSUE THREAD

**Issue by mobla** [vmware/vic#3183] opened 2016-11-15 20:23 UTC
**VIC Version:**

vSphere/vCenter 6.5 RTM build #
VC: ob-4584207
ESX: ob-4564106
Harbor build: 0.4.5 re-spin

Steps:
1. Use windows client machine (may be doesn't matter)
2. Create a VCH using No TLS insecure registry configured to http harbor
3. Docker login to http and https harbor done in client machine
3. Pull an image from docker hub and tag/push it to harbor using local docker (windows)
4. Run the image from (https - public CA) harbor 
5. Noticed this "Failed to power on appliance Module 'MonitorLoop' power on failed. . Exiting..." issue
6. Later tried creating another VCH on the same vCenter, got the same error
Not sure if this issue 'MonitorLoop' had happened due specific steps mentioned above! 
7. After a day, this error is gone. Now we are able to remove, create VCH's fine..

Just filing it for records..

Logs attached..
[vic-machine.log.txt](https://github.com/vmware/vic/files/593027/vic-machine.log.txt)
[container-logs.tar.gz](https://github.com/vmware/vic/files/593028/container-logs.tar.gz)

Snippet
--------
[34mINFO[0m[2016-11-11T09:07:07-08:00] Creating virtual app "VCH1"                  
[34mINFO[0m[2016-11-11T09:07:07-08:00] Creating appliance on target                 
[34mINFO[0m[2016-11-11T09:07:07-08:00] Network role "external" is sharing NIC with "management" 
[34mINFO[0m[2016-11-11T09:07:07-08:00] Network role "client" is sharing NIC with "management" 
[34mINFO[0m[2016-11-11T09:07:10-08:00] Uploading images for container               
[34mINFO[0m[2016-11-11T09:07:10-08:00] 	"appliance.iso"                             
[34mINFO[0m[2016-11-11T09:07:10-08:00] 	"bootstrap.iso"                             
[34mINFO[0m[2016-11-11T09:07:26-08:00] Registering VCH as a vSphere extension       
[34mINFO[0m[2016-11-11T09:07:32-08:00] Waiting for IP information                   
[34mINFO[0m[2016-11-11T09:08:01-08:00] Waiting for major appliance components to launch 
[34mINFO[0m[2016-11-11T09:08:05-08:00] Initialization of appliance successful       
[34mINFO[0m[2016-11-11T09:08:05-08:00]                                              
[34mINFO[0m[2016-11-11T09:08:05-08:00] vic-admin portal:                            
[34mINFO[0m[2016-11-11T09:08:05-08:00] http://10.160.103.198:2378                   
[34mINFO[0m[2016-11-11T09:08:05-08:00]                                              
[34mINFO[0m[2016-11-11T09:08:05-08:00] Published ports can be reached at:           
[34mINFO[0m[2016-11-11T09:08:05-08:00] 10.160.103.198                               
[34mINFO[0m[2016-11-11T09:08:05-08:00]                                              
[34mINFO[0m[2016-11-11T09:08:05-08:00] Docker environment variables:                
[34mINFO[0m[2016-11-11T09:08:05-08:00] DOCKER_HOST=10.160.103.198:2375              
[34mINFO[0m[2016-11-11T09:08:05-08:00]                                              
[34mINFO[0m[2016-11-11T09:08:05-08:00] Connect to docker:                           
[34mINFO[0m[2016-11-11T09:08:05-08:00] docker -H 10.160.103.198:2375 info           
[34mINFO[0m[2016-11-11T09:08:05-08:00] Installer completed successfully             
[33mWARN[0m[2016-11-13T16:34:58-08:00] Configuring without TLS - all communications will be insecure 
[34mINFO[0m[2016-11-13T16:34:58-08:00] ### Installing VCH ####                      
[34mINFO[0m[2016-11-13T16:34:59-08:00] Validating supplied configuration            
[34mINFO[0m[2016-11-13T16:34:59-08:00] vDS configuration OK on "VICDVPG"            
[34mINFO[0m[2016-11-13T16:34:59-08:00] Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.127.179" 
[34mINFO[0m[2016-11-13T16:34:59-08:00] Firewall status: DISABLED on "/vcqaDC/host/cls/10.160.97.115" 
[33mWARN[0m[2016-11-13T16:34:59-08:00] Firewall configuration will be incorrect if firewall is reenabled on hosts: 
[33mWARN[0m[2016-11-13T16:34:59-08:00]   "/vcqaDC/host/cls/10.160.127.179"          
[33mWARN[0m[2016-11-13T16:34:59-08:00]   "/vcqaDC/host/cls/10.160.97.115"           
[33mWARN[0m[2016-11-13T16:34:59-08:00] Firewall must permit 2377/tcp outbound if firewall is reenabled 
[34mINFO[0m[2016-11-13T16:35:00-08:00] License check OK on hosts:                   
[34mINFO[0m[2016-11-13T16:35:00-08:00]   "/vcqaDC/host/cls/10.160.127.179"          
[34mINFO[0m[2016-11-13T16:35:00-08:00]   "/vcqaDC/host/cls/10.160.97.115"           
[34mINFO[0m[2016-11-13T16:35:00-08:00] DRS check OK on:                             
[34mINFO[0m[2016-11-13T16:35:00-08:00]   "/vcqaDC/host/cls/Resources"               
[34mINFO[0m[2016-11-13T16:35:00-08:00]                                              
[34mINFO[0m[2016-11-13T16:35:01-08:00] Creating virtual app "VCH2"                  
[34mINFO[0m[2016-11-13T16:35:01-08:00] Creating appliance on target                 
[34mINFO[0m[2016-11-13T16:35:01-08:00] Network role "management" is sharing NIC with "client" 
[34mINFO[0m[2016-11-13T16:35:01-08:00] Network role "external" is sharing NIC with "client" 
[34mINFO[0m[2016-11-13T16:35:02-08:00] Uploading images for container               
[34mINFO[0m[2016-11-13T16:35:02-08:00] 	"bootstrap.iso"                             
[34mINFO[0m[2016-11-13T16:35:02-08:00] 	"appliance.iso"                             
[34mINFO[0m[2016-11-13T16:35:18-08:00] Registering VCH as a vSphere extension       
[34mINFO[0m[2016-11-13T16:35:23-08:00] Collecting 5a65a80c-d6f0-4c06-8c44-bc9a6ad2cda9 vpxd.log 
[31mERRO[0m[2016-11-13T16:35:23-08:00] --------------------                         
[31mERRO[0m[2016-11-13T16:35:23-08:00] vic-machine-windows.exe failed: Failed to power on appliance Module 'MonitorLoop' power on failed. . Exiting...

**Comment by mlh78750** [comment] 2016-11-15 20:29
Adding to 0.8 for triage. Want to try and understand root cause before we decide where it needs to be fixed.

**Comment by mlh78750** [comment] 2016-11-15 20:30
cc @emlin

**Comment by andrewtchin** [comment] 2016-11-15 21:48
This looks like an out of resource error:
``` 
time="2016-11-12T19:04:19Z" level=debug msg="unexpected fault on task retry : &types.GenericVmConfigFault{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage{types.              LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"msg.moduletable.powerOnFailed\", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"1\", Value:\"MonitorLoop\"}}, Message:\"Module 'MonitorLoop' power on failed. \"}, types.LocalizableMessage{DynamicData:         types.DynamicData{}, Key:\"vob.fssvec.Lookup.file.failed\", Arg:[]types.KeyAnyValue(nil), Message:\"File system specific implementation of Lookup[file] failed\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"vob.fssvec.LookupAndOpen.file.failed\", Arg:[]types.                      KeyAnyValue(nil), Message:\"File system specific implementation of LookupAndOpen[file] failed\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"vob.swap.extend.failure.status\", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"1\", Value:\"0\"},      types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"2\", Value:\"2097152\"}}, Message:\"Failed to extend swap file from 0 KB to 2097152 KB.\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"vob.swap.extend.failure.moreinfo\", Arg:[]types.KeyAnyValue{types.                      KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"1\", Value:\"0\"}}, Message:\"Current swap file size is 0 KB.\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"vob.swap.poweron.extendfailure.status\", Arg:[]types.KeyAnyValue(nil), Message:\"Failed to extend the virtual           machine swap file\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"msg.vmmonVMK.creatVMFailed\", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"1\", Value:\"msg.vmk.status.VMK_NO_SPACE\"}}, Message:\"Could not power on virtual machine: No          space left on device.\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"msg.monitorLoop.createVMFailed.vmk\", Arg:[]types.KeyAnyValue(nil), Message:\"Failed to power on VM.\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"msg.vmx.poweron.failed\", Arg:            []types.KeyAnyValue(nil), Message:\"Failed to start the virtual machine.\"}, types.LocalizableMessage{DynamicData:types.DynamicData{}, Key:\"vpxd.vm.poweron.unexpectedfailure\", Arg:[]types.KeyAnyValue{types.KeyAnyValue{DynamicData:types.DynamicData{}, Key:\"1\", Value:\"hungry_goldstin-             0f7d51263aaa303c0186828d41bc6a487e5e6b483a7b0e270f07e6bba92c560c\"}}, Message:\"An error was received from the ESX host while powering on VM hungry_goldstin-0f7d51263aaa303c0186828d41bc6a487e5e6b483a7b0e270f07e6bba92c560c.\"}}}}}, Reason:\"Module 'MonitorLoop' power on failed. \"}"
```

**Comment by mdubya66** [comment] 2016-11-19 02:18
I'm pulling this. The error message needs to be improved but we failed properly.

**Comment by mhagen-vmware** [comment] 2017-02-01 16:35
priority low, estimate 1 under the assumption this issue is now just to improve the error logging

**Comment by mdubya66** [comment] 2017-10-30 15:15
No reports of this since 1.0. Closing as CNR.

**Closed by mdubya66** 2017-10-30 15:15 UTC
Labels: component/vic-machine, kind/bug, kind/bug/no-repro, priority/low, status/needs-attention
