### ISSUE TITLE
Consider defining a role for VCH

### ISSUE THREAD

**Issue by smaithani** [vmware/vic#2854] opened 2016-10-21 22:38 UTC
For a non-admin, to be able to deploy and operate VCHA we need a minimum set of privileges.  We should either document this minimum set or create a role in VC which has all these privileges.

**Comment by mdubya66** [comment] 2016-10-23 16:21
duplicate of https://github.com/vmware/vic/issues/1689?

**Comment by hickeng** [comment] 2016-10-24 14:06
dup of #1689

**Closed by hickeng** 2016-10-24 14:06 UTC
