### ISSUE TITLE
No output when interactively running a container command

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1593] opened 2016-07-20 22:33 UTC
**Expected behavior:**
```
$ docker run -it busybox /bin/date
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
8ddc19f16526: Pull complete
Digest: sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6
Status: Downloaded newer image for busybox:latest
Wed Jul 20 22:26:46 UTC 2016
```
**Actual behavior:**
```
$ docker -H 192.168.218.235:2376 --tls run -it busybox /bin/date
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
$
```

**Comment by jzt** [comment] 2016-07-20 22:34
Inspection of the container vm log on the ESX shows that the command did run.

**Comment by caglar10ur** [comment] 2016-08-03 18:30
duplicate of #1578 closing

**Closed by caglar10ur** 2016-08-03 18:30 UTC
Labels: area/cli, area/docker, component/docker-api-server, kind/bug, kind/quality
