### ISSUE TITLE
Running multiple CI tests on the same host concurrently

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#2817] opened 2016-10-20 02:39 UTC
Investigating https://ci.vmware.run/vmware/vic/6045

From hostd we can see that these two VCHs are operating on 31.9 at the same time:
VCH-6053-1693 vic-machine log:

```
[34mINFO[0m[2016-10-19T18:09:04Z] Generating CA certificate/key pair - private key in ./VCH-6053-1693/ca-key.pem 
[34mINFO[0m[2016-10-19T18:09:05Z] Generating server certificate/key pair - private key in ./VCH-6053-1693/server-key.pem 
[34mINFO[0m[2016-10-19T18:09:05Z] Generating client certificate/key pair - private key in ./VCH-6053-1693/key.pem 
[34mINFO[0m[2016-10-19T18:09:05Z] Generated browser friendly PFX client certificate - certificate in ./VCH-6053-1693/cert.pfx 
[34mINFO[0m[2016-10-19T18:09:05Z] ### Installing VCH ####                      
[37mDEBU[0m[2016-10-19T18:09:05Z] Using to login by username/password          
[37mDEBU[0m[2016-10-19T18:09:06Z] Session Environment Info:                     [37mAPI Type[0m=HostAgent [37mAPI Version[0m=6.0 [37mBuild[0m=3620759 [37mName[0m=VMware ESXi [37mOS Type[0m=vmnix-x86 [37mProduct ID[0m=embeddedEsx [37mUUID[0m= [37mVendor[0m=VMware, Inc. [37mVersion[0m=6.0.0
[37mDEBU[0m[2016-10-19T18:09:06Z] vSphere resource cache populating...         
[37mDEBU[0m[2016-10-19T18:09:06Z] Cached dc:                                   
[37mDEBU[0m[2016-10-19T18:09:06Z] Cached cluster:                              
[37mDEBU[0m[2016-10-19T18:09:06Z] Cached ds:                                   
[37mDEBU[0m[2016-10-19T18:09:06Z] Cached host:                                 
[37mDEBU[0m[2016-10-19T18:09:06Z] Cached pool:                                 
[37mDEBU[0m[2016-10-19T18:09:06Z] vSphere resource cache populated...          
[34mINFO[0m[2016-10-19T18:09:06Z] Validating supplied configuration            
[37mDEBU[0m[2016-10-19T18:09:06Z] Setting scratch image size to 8000000 KB in VCHConfig 
[37mDEBU[0m[2016-10-19T18:09:06Z] Path is treated as absolute given datacenter prefix "/ha-datacenter" 
[37mDEBU[0m[2016-10-19T18:09:06Z] Converted original path "/ha-datacenter/host/vic-esx-07.ci.drone.local/Resources" to "/ha-datacenter/host/vic-esx-07.ci.drone.local/Resources" 
[37mDEBU[0m[2016-10-19T18:09:06Z] Selected compute resource "/ha-datacenter/host/vic-esx-07.ci.drone.local/Resources" 
[37mDEBU[0m[2016-10-19T18:09:06Z] NetworkEndpoint: &{{  external } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network external }  {<nil> <nil>} true [] [] []} []} 
[37mDEBU[0m[2016-10-19T18:09:06Z] NetworkEndpoint: &{{  client } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network client }  {<nil> <nil>} false [] [] []} []} 
[37mDEBU[0m[2016-10-19T18:09:06Z] NetworkEndpoint: &{{   } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network management }  {<nil> <nil>} false [] [] []} []} 
[37mDEBU[0m[2016-10-19T18:09:06Z] Network configuration:                       
[37mDEBU[0m[2016-10-19T18:09:06Z]     Network: external NetworkEndpoint: &{{  external } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network external }  {<nil> <nil>} true [] [] []} []} 
[37mDEBU[0m[2016-10-19T18:09:06Z]     Network: client NetworkEndpoint: &{{  client } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network client }  {<nil> <nil>} false [] [] []} []} 
[37mDEBU[0m[2016-10-19T18:09:06Z]     Network: management NetworkEndpoint: &{{   } false <nil> {<nil> <nil>} {{ Network:HaNetwork-VM Network management }  {<nil> <nil>} false [] [] []} []} 
[34mINFO[0m[2016-10-19T18:09:06Z] Firewall status: DISABLED on "/ha-datacenter/host/vic-esx-07.ci.drone.local/vic-esx-07.ci.drone.local" 
[33mWARN[0m[2016-10-19T18:09:06Z] Firewall configuration will be incorrect if firewall is reenabled on hosts: 
[33mWARN[0m[2016-10-19T18:09:06Z]   "/ha-datacenter/host/vic-esx-07.ci.drone.local/vic-esx-07.ci.drone.local" 
[33mWARN[0m[2016-10-19T18:09:06Z] Firewall must permit 2377/tcp outbound if firewall is reenabled 
[34mINFO[0m[2016-10-19T18:09:06Z] License check OK                             
[34mINFO[0m[2016-10-19T18:09:06Z] DRS check SKIPPED - target is standalone host 
[37mDEBU[0m[2016-10-19T18:09:06Z] Datacenter: "ha-datacenter", Cluster: "/ha-datacenter/host/vic-esx-07.ci.drone.local", Resource Pool: "/ha-datacenter/host/vic-esx-07.ci.drone.local/Resources" 
[34mINFO[0m[2016-10-19T18:09:06Z]                                              
[34mINFO[0m[2016-10-19T18:09:06Z] Creating Resource Pool "VCH-6053-1693"       
[34mINFO[0m[2016-10-19T18:09:06Z] Creating directory [datastore1] test         
[34mINFO[0m[2016-10-19T18:09:06Z] Datastore path is [datastore1] test          
[34mINFO[0m[2016-10-19T18:09:06Z] Creating appliance on target                 
[37mDEBU[0m[2016-10-19T18:09:06Z] Setting "bridge" to slot 192                 
[37mDEBU[0m[2016-10-19T18:09:06Z] Setting "external" to slot 224               
[34mINFO[0m[2016-10-19T18:09:06Z] Network role "client" is sharing NIC with "external" 
[34mINFO[0m[2016-10-19T18:09:06Z] Network role "management" is sharing NIC with "external" 
[37mDEBU[0m[2016-10-19T18:09:06Z] vm folder name: "VCH-6053-1693"              
[37mDEBU[0m[2016-10-19T18:09:06Z] vm inventory path: "/ha-datacenter/vm/VCH-6053-1693" 
[34mINFO[0m[2016-10-19T18:09:06Z] Uploading images for container               
[34mINFO[0m[2016-10-19T18:09:06Z]     "bin/appliance.iso"                         
[34mINFO[0m[2016-10-19T18:09:06Z]     "bin/bootstrap.iso"                         
[34mINFO[0m[2016-10-19T18:09:14Z] Waiting for IP information                   
[34mINFO[0m[2016-10-19T18:09:28Z] Waiting for major appliance components to launch 
[37mDEBU[0m[2016-10-19T18:09:28Z] waiting for vicadmin to start                
[37mDEBU[0m[2016-10-19T18:09:28Z] waiting for docker personality to start      
[37mDEBU[0m[2016-10-19T18:09:28Z] waiting for port layer to start              
[37mDEBU[0m[2016-10-19T18:09:28Z] Obtained IP address for client interface: "192.168.31.221" 
[37mDEBU[0m[2016-10-19T18:09:28Z] Loading CAs for client auth                  
[37mDEBU[0m[2016-10-19T18:09:28Z] Loading CAs for client auth                  
[37mDEBU[0m[2016-10-19T18:09:28Z] Matched dhcp-192-168-31-221.ci.drone.local. for use against host certificate 
[37mDEBU[0m[2016-10-19T18:09:28Z] Assigning certificates for client auth       
[37mDEBU[0m[2016-10-19T18:09:28Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:29Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:29Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:30Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:30Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:31Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:31Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:32Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:32Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:33Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:33Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:34Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:34Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:35Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:35Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:36Z] Components not yet initialized, retrying     
[37mDEBU[0m[2016-10-19T18:09:36Z] connection refused                           
[37mDEBU[0m[2016-10-19T18:09:37Z] Components not yet initialized, retrying     
[34mINFO[0m[2016-10-19T18:09:37Z] Initialization of appliance successful       
[34mINFO[0m[2016-10-19T18:09:37Z]                                              
[34mINFO[0m[2016-10-19T18:09:37Z] vic-admin portal:                            
[34mINFO[0m[2016-10-19T18:09:37Z] https://dhcp-192-168-31-221.ci.drone.local:2378 
[34mINFO[0m[2016-10-19T18:09:37Z]                                              
[34mINFO[0m[2016-10-19T18:09:37Z] Docker environment variables:                
[34mINFO[0m[2016-10-19T18:09:37Z]   DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/drone/src/github.com/vmware/vic/VCH-6053-1693 DOCKER_HOST=dhcp-192-168-31-221.ci.drone.local:2376 
[34mINFO[0m[2016-10-19T18:09:37Z]                                              
[34mINFO[0m[2016-10-19T18:09:37Z] Environment saved in VCH-6053-1693/VCH-6053-1693.env 
[34mINFO[0m[2016-10-19T18:09:37Z]                                              
[34mINFO[0m[2016-10-19T18:09:37Z] Connect to docker:                           
[34mINFO[0m[2016-10-19T18:09:37Z] docker -H dhcp-192-168-31-221.ci.drone.local:2376 --tlsverify --tlscacert="./VCH-6053-1693/ca.pem" --tlscert="./VCH-6053-1693/cert.pem" --tlskey="./VCH-6053-1693/key.pem" info 
[34mINFO[0m[2016-10-19T18:09:37Z] Installer completed successfully             
[34mINFO[0m[2016-10-19T18:09:48Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:48Z]                                              
[34mINFO[0m[2016-10-19T18:09:48Z] VCH ID: VirtualMachine:2279                  
[34mINFO[0m[2016-10-19T18:09:48Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:48Z] Removing image stores                        
[34mINFO[0m[2016-10-19T18:09:54Z] Removing volume stores                       
[34mINFO[0m[2016-10-19T18:09:54Z] Deleting volume store "default" on Datastore "datastore1" at path "test" 
[34mINFO[0m[2016-10-19T18:09:54Z] Removing appliance VM network devices        
[34mINFO[0m[2016-10-19T18:09:55Z] Bridge network was not created during VCH deployment, leaving it there 
[34mINFO[0m[2016-10-19T18:09:55Z] Removing Resource Pool "VCH-6053-1693"       
[34mINFO[0m[2016-10-19T18:09:55Z] Completed successfully                       
[34mINFO[0m[2016-10-19T18:09:56Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:57Z]                                              
[34mINFO[0m[2016-10-19T18:09:57Z] VCH ID: VirtualMachine:1906                  
[34mINFO[0m[2016-10-19T18:09:57Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:57Z] Delete will attempt to remove datastore files for VM "drunk_engelbart-9f1ce9ea3dd4f8402d5049999af91256c143b0e55cca9f319efa3171a0b4d86e" 
[31mERRO[0m[2016-10-19T18:09:57Z] --------------------                         
[31mERRO[0m[2016-10-19T18:09:57Z] vic-machine-linux failed: runtime error: invalid memory address or nil pointer dereference
```

VCH-6045-5188:

```
[34mINFO[0m[2016-10-19T18:08:47Z] Generating CA certificate/key pair - private key in ./VCH-6045-5188/ca-key.pem 
[34mINFO[0m[2016-10-19T18:08:48Z] Generating server certificate/key pair - private key in ./VCH-6045-5188/server-key.pem 
[34mINFO[0m[2016-10-19T18:08:48Z] Generating client certificate/key pair - private key in ./VCH-6045-5188/key.pem 
[34mINFO[0m[2016-10-19T18:08:48Z] Generated browser friendly PFX client certificate - certificate in ./VCH-6045-5188/cert.pfx 
[34mINFO[0m[2016-10-19T18:08:48Z] ### Installing VCH ####                      
[34mINFO[0m[2016-10-19T18:08:48Z] Validating supplied configuration            
[34mINFO[0m[2016-10-19T18:08:49Z] Firewall status: DISABLED on "/ha-datacenter/host/vic-esx-07.ci.drone.local/vic-esx-07.ci.drone.local" 
[33mWARN[0m[2016-10-19T18:08:49Z] Firewall configuration will be incorrect if firewall is reenabled on hosts: 
[33mWARN[0m[2016-10-19T18:08:49Z]   "/ha-datacenter/host/vic-esx-07.ci.drone.local/vic-esx-07.ci.drone.local" 
[33mWARN[0m[2016-10-19T18:08:49Z] Firewall must permit 2377/tcp outbound if firewall is reenabled 
[34mINFO[0m[2016-10-19T18:08:49Z] License check OK                             
[34mINFO[0m[2016-10-19T18:08:49Z] DRS check SKIPPED - target is standalone host 
[34mINFO[0m[2016-10-19T18:08:49Z]                                              
[34mINFO[0m[2016-10-19T18:08:49Z] Creating Resource Pool "VCH-6045-5188"       
[34mINFO[0m[2016-10-19T18:08:49Z] Creating appliance on target                 
[34mINFO[0m[2016-10-19T18:08:49Z] Network role "external" is sharing NIC with "management" 
[34mINFO[0m[2016-10-19T18:08:49Z] Network role "client" is sharing NIC with "management" 
[34mINFO[0m[2016-10-19T18:08:49Z] Uploading images for container               
[34mINFO[0m[2016-10-19T18:08:49Z]     "bin/bootstrap.iso"                         
[34mINFO[0m[2016-10-19T18:08:49Z]     "bin/appliance.iso"                         
[34mINFO[0m[2016-10-19T18:08:57Z] Waiting for IP information                   
[34mINFO[0m[2016-10-19T18:09:12Z] Waiting for major appliance components to launch 
[34mINFO[0m[2016-10-19T18:09:21Z] Initialization of appliance successful       
[34mINFO[0m[2016-10-19T18:09:21Z]                                              
[34mINFO[0m[2016-10-19T18:09:21Z] vic-admin portal:                            
[34mINFO[0m[2016-10-19T18:09:21Z] https://dhcp-192-168-31-127.ci.drone.local:2378 
[34mINFO[0m[2016-10-19T18:09:21Z]                                              
[34mINFO[0m[2016-10-19T18:09:21Z] Docker environment variables:                
[34mINFO[0m[2016-10-19T18:09:21Z]   DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/drone/src/github.com/vmware/vic/VCH-6045-5188 DOCKER_HOST=dhcp-192-168-31-127.ci.drone.local:2376 
[34mINFO[0m[2016-10-19T18:09:21Z]                                              
[34mINFO[0m[2016-10-19T18:09:21Z] Environment saved in VCH-6045-5188/VCH-6045-5188.env 
[34mINFO[0m[2016-10-19T18:09:21Z]                                              
[34mINFO[0m[2016-10-19T18:09:21Z] Connect to docker:                           
[34mINFO[0m[2016-10-19T18:09:21Z] docker -H dhcp-192-168-31-127.ci.drone.local:2376 --tlsverify --tlscacert="./VCH-6045-5188/ca.pem" --tlscert="./VCH-6045-5188/cert.pem" --tlskey="./VCH-6045-5188/key.pem" info 
[34mINFO[0m[2016-10-19T18:09:21Z] Installer completed successfully             
[34mINFO[0m[2016-10-19T18:09:35Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:35Z]                                              
[34mINFO[0m[2016-10-19T18:09:35Z] VCH ID: VirtualMachine:2280                  
[34mINFO[0m[2016-10-19T18:09:35Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:35Z] Removing image stores                        
[34mINFO[0m[2016-10-19T18:09:35Z] Removing volume stores                       
[34mINFO[0m[2016-10-19T18:09:35Z] Removing appliance VM network devices        
[34mINFO[0m[2016-10-19T18:09:37Z] Bridge network was not created during VCH deployment, leaving it there 
[34mINFO[0m[2016-10-19T18:09:38Z] Removing Resource Pool "VCH-6045-5188"       
[34mINFO[0m[2016-10-19T18:09:38Z] Completed successfully                       
[34mINFO[0m[2016-10-19T18:09:39Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:39Z]                                              
[34mINFO[0m[2016-10-19T18:09:39Z] VCH ID: VirtualMachine:1906                  
[34mINFO[0m[2016-10-19T18:09:39Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:39Z] Delete will attempt to remove datastore files for VM "drunk_engelbart-9f1ce9ea3dd4f8402d5049999af91256c143b0e55cca9f319efa3171a0b4d86e" 
[31mERRO[0m[2016-10-19T18:09:39Z] --------------------                         
[31mERRO[0m[2016-10-19T18:09:39Z] vic-machine-linux failed: runtime error: invalid memory address or nil pointer dereference
```

**Comment by mhagen-vmware** [comment] 2016-10-20 03:11
@cgtexmex tagging Clint as he has been working on the concurrency epic

**Comment by cgtexmex** [comment] 2016-11-04 14:29
dupe of #2043

**Comment by mhagen-vmware** [comment] 2017-01-24 16:29
going to close this at this point as a dupe. we should consolidate and make an effort to address running our test suite concurrently under the epic cited above.

**Closed by mhagen-vmware** 2017-01-24 16:29 UTC
Labels: area/infra, kind/bug, kind/quality
