### ISSUE TITLE
Stopping containers thru vCenter is slower, as of build 5275

### ISSUE THREAD

**Issue by carlsone** [vmware/vic#2568] opened 2016-10-04 23:10 UTC
Stopping 100 containers (sequentially) thru vCenter 6.0 used to take about 50-100ms per container, on average.  This behavior lasted until VIC build 5262.

Starting with **VIC build 5275**, stopping 100 containers (sequentially) thru vCenter 6.0 takes about 10 sec per container, on average.

Logs for build 5262:
[vic5262_vcenter_docker-personality.txt](https://github.com/vmware/vic/files/509694/vic5262_vcenter_docker-personality.txt)
[vic5262_vcenter_install.txt](https://github.com/vmware/vic/files/509696/vic5262_vcenter_install.txt)
[vic5262_vcenter_logs.zip](https://github.com/vmware/vic/files/509695/vic5262_vcenter_logs.zip)
[vic5262_vcenter_run.txt](https://github.com/vmware/vic/files/509697/vic5262_vcenter_run.txt)

Logs for build 5275:
[vic5275_vcenter_docker-personality.txt](https://github.com/vmware/vic/files/509700/vic5275_vcenter_docker-personality.txt)
[vic5275_vcenter_install.txt](https://github.com/vmware/vic/files/509702/vic5275_vcenter_install.txt)
[vic5275_vcenter_logs.zip](https://github.com/vmware/vic/files/509701/vic5275_vcenter_logs.zip)
[vic5275_vcenter_run.txt](https://github.com/vmware/vic/files/509703/vic5275_vcenter_run.txt)

**VIC Version:**

0.1 / master / 5275

**Expected behavior:**

Sequentially stopping 100 containers on Build 5262:

docker_stop_vcenter_median  | 0.051 sec
docker_stop_vcenter_average | 0.132 sec
docker_stop_vcenter_stdev   | 0.793 sec
docker_stop_vcenter_min     | 0.049 sec
docker_stop_vcenter_max     | 8.019 sec

docker_stop_vcenter: 8.0190050601959229, 0.056226015090942383, 0.051657915115356445, 0.052657127380371094, 0.068719148635864258, 0.054202079772949219, 0.052569150924682617, 0.053124904632568359, 0.052706003189086914, 0.050813913345336914, 0.050388097763061523, 0.049915075302124023, 0.053920984268188477, 0.052088022232055664, 0.051412105560302734, 0.050672054290771484, 0.049635887145996094, 0.050817966461181641, 0.068017959594726562, 0.053322076797485352, 0.053229093551635742, 0.050050973892211914, 0.050496101379394531, 0.051756143569946289, 0.052608966827392578, 0.05373692512512207, 0.050464868545532227, 0.049130916595458984, 0.049835205078125, 0.050320148468017578, 0.049310922622680664, 0.049468040466308594, 0.049590110778808594, 0.06223297119140625, 0.055822849273681641, 0.051279067993164062, 0.049366950988769531, 0.049159049987792969, 0.049514055252075195, 0.049597978591918945, 0.050250053405761719, 0.049839973449707031, 0.049242973327636719, 0.049551963806152344, 0.051412820816040039, 0.049870014190673828, 0.049569129943847656, 0.05047297477722168, 0.064324855804443359, 0.050777912139892578, 0.054816961288452148, 0.055144071578979492, 0.05092310905456543, 0.050736188888549805, 0.052218914031982422, 0.058349847793579102, 0.056071043014526367, 0.050496101379394531, 0.04978179931640625, 0.049966096878051758, 0.049749135971069336, 0.052125930786132812, 0.05124211311340332, 0.065195083618164062, 0.051472187042236328, 0.053210973739624023, 0.052537918090820312, 0.049846887588500977, 0.049987077713012695, 0.049892187118530273, 0.048982858657836914, 0.049793004989624023, 0.049142122268676758, 0.051269054412841797, 0.049233198165893555, 0.050333976745605469, 0.049935817718505859, 0.050153970718383789, 0.048731088638305664, 0.063462018966674805, 0.052875041961669922, 0.050693988800048828, 0.057057857513427734, 0.052023887634277344, 0.051121950149536133, 0.048830986022949219, 0.049598932266235352, 0.049451112747192383, 0.049554824829101562, 0.049376964569091797, 0.051014900207519531, 0.04949498176574707, 0.050007104873657227, 0.063684940338134766, 0.054915189743041992, 0.050181150436401367, 0.049835920333862305, 0.049607038497924805, 0.049029111862182617, 0.049417018890380859

**Actual behavior:**

Sequentially stopping 100 containers on Build 5275:

docker_stop_vcenter_median  | 10.012 sec
docker_stop_vcenter_average | 10.019 sec
docker_stop_vcenter_stdev   | 0.601 sec
docker_stop_vcenter_min     | 8.906 sec
docker_stop_vcenter_max     | 11.074 sec

docker_stop_vcenter: 10.292140960693359, 10.103425979614258, 9.8758101463317871, 11.010890007019043, 10.009765148162842, 9.1804471015930176, 10.798622846603394, 8.9940779209136963, 10.004655122756958, 11.048555135726929, 9.9679219722747803, 9.0506539344787598, 10.98485279083252, 9.0225930213928223, 10.960180997848511, 9.0444769859313965, 10.030335187911987, 9.9714400768280029, 9.9935719966888428, 11.065655946731567, 9.9763920307159424, 10.002333164215088, 8.9651968479156494, 10.00761890411377, 10.059558868408203, 9.9889459609985352, 9.9997251033782959, 10.020704030990601, 10.003722906112671, 9.9447212219238281, 10.04040789604187, 10.032562017440796, 10.000971794128418, 10.019444942474365, 11.017830848693848, 9.0618181228637695, 9.9186680316925049, 11.017649173736572, 9.0094859600067139, 10.022332906723022, 9.9813799858093262, 10.868040084838867, 9.1918578147888184, 9.9928929805755615, 9.9657700061798096, 10.043319940567017, 10.013664960861206, 11.001944065093994, 8.9423229694366455, 10.049017906188965, 10.999524831771851, 10.038297891616821, 9.9625968933105469, 10.015815019607544, 9.0034680366516113, 10.026583194732666, 10.001771926879883, 10.001589059829712, 10.030405044555664, 10.97106409072876, 9.0097169876098633, 10.014771223068237, 9.9723989963531494, 10.054370880126953, 9.9393079280853271, 10.105107069015503, 10.952571868896484, 10.077904939651489, 9.9218990802764893, 9.0579831600189209, 10.021233081817627, 9.9649050235748291, 10.004509925842285, 11.001034021377563, 8.9889249801635742, 10.020463943481445, 10.020620107650757, 11.042715072631836, 8.90618896484375, 10.051232099533081, 10.037957906723022, 10.009407997131348, 9.9405348300933838, 11.009900093078613, 9.0284440517425537, 10.022451877593994, 9.9912259578704834, 10.047465085983276, 10.996740102767944, 9.9738907814025879, 9.0138120651245117, 11.073530912399292, 8.94321608543396, 10.017104148864746, 10.052150964736938, 10.021647930145264, 9.9291689395904541, 9.9982218742370605, 10.030799865722656, 11.009554862976074

**Comment by mdubya66** [comment] 2016-10-04 23:54
This is a pretty severe regression. Marking for fixing in GA.

**Comment by dougm** [comment] 2016-10-05 02:07
Can you share how you are creating the containers?  Originally, 'docker stop' would be a hard vm power off.  More recently, with the changes in 80a1c27 and a39f7d9, we are doing a graceful stop.. and the default "docker stop" grace period is 10 seconds.  But those changes were well before 5262.

I can see the ~10 sec in the 5275 logs, for example:
```
time="2016-10-04T22:18:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit:186] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop:421] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).shutdown:384] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=info msg="sending kill -TERM 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).startGuestProgram:461] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).startGuestProgram:461] [51.369911ms] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:18:54Z" level=info msg="waiting 10s for 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154 to power off" 
time="2016-10-04T22:18:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).waitForPowerState:371] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:19:02Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).waitForPowerState:371] [8.193592894s] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:19:02Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).shutdown:384] [8.246226324s] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:19:02Z" level=debug msg="Container(110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154) closing 0 log followers" 
time="2016-10-04T22:19:02Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop:421] [8.247328382s] 110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154" 
time="2016-10-04T22:19:03Z" level=debug msg="Found 1 subscribers to vsphere.VmEvent: grave_shockley-110d6c76af6b0c3b5697263a6395f417181e3c672db4713b08475b340ce2d154 on  w1-parm-wesd.eng.vmware.com in dc is powered off" 
```

But the older build log bundle is html:
```
$ file vic5262_vcenter_logs.zip 
/home/dougm/Downloads/vic5262_vcenter_logs.zip: HTML document, ASCII text
```

**Comment by carlsone** [comment] 2016-10-05 05:19
We create the 100 containers via:
`docker create -it ubuntu sleep 20000`

Here is a new log bundle for VIC build 5262:

[new_vic5262_vcenter_logs.zip](https://github.com/vmware/vic/files/510071/new_vic5262_vcenter_logs.zip)

docker_stop_vcenter_median  | 0.054 sec
docker_stop_vcenter_average | 0.144 sec
docker_stop_vcenter_stdev   | 0.880 sec
docker_stop_vcenter_min     | 0.050 sec
docker_stop_vcenter_max     | 8.903 sec
docker_stop_vcenter: 8.903256893157959, 0.071519136428833008, 0.055182933807373047, 0.054144144058227539, 0.054751157760620117, 0.052069902420043945, 0.050135135650634766, 0.053951025009155273, 0.056454181671142578, 0.057605981826782227, 0.05778193473815918, 0.052835941314697266, 0.056612968444824219, 0.050637960433959961, 0.052610874176025391, 0.067724943161010742, 0.057258844375610352, 0.051542997360229492, 0.058330059051513672, 0.050445079803466797, 0.059026956558227539, 0.049856901168823242, 0.057756185531616211, 0.052949905395507812, 0.057242155075073242, 0.059637069702148438, 0.053235054016113281, 0.050127983093261719, 0.056705951690673828, 0.053008079528808594, 0.069611072540283203, 0.05385279655456543, 0.060612916946411133, 0.051953792572021484, 0.052692890167236328, 0.056087970733642578, 0.052078008651733398, 0.054529905319213867, 0.051997900009155273, 0.051217079162597656, 0.056086063385009766, 0.052670955657958984, 0.057230949401855469, 0.060012102127075195, 0.063931941986083984, 0.053704023361206055, 0.053819894790649414, 0.053448915481567383, 0.054475069046020508, 0.052182912826538086, 0.054083108901977539, 0.060489892959594727, 0.059715986251831055, 0.052072048187255859, 0.057657003402709961, 0.050623893737792969, 0.052192926406860352, 0.055435895919799805, 0.050766944885253906, 0.065165996551513672, 0.054501771926879883, 0.060685873031616211, 0.05064702033996582, 0.054106950759887695, 0.051390886306762695, 0.051105022430419922, 0.050776958465576172, 0.053325891494750977, 0.053039073944091797, 0.05091404914855957, 0.050081014633178711, 0.049972057342529297, 0.050137996673583984, 0.056591987609863281, 0.074177980422973633, 0.055515050888061523, 0.050482988357543945, 0.052995920181274414, 0.054012060165405273, 0.051159143447875977, 0.051201105117797852, 0.049876928329467773, 0.057184934616088867, 0.059368133544921875, 0.058852910995483398, 0.051649093627929688, 0.051416158676147461, 0.055621862411499023, 0.051721096038818359, 0.067996978759765625, 0.061126947402954102, 0.050503015518188477, 0.058405876159667969, 0.050601005554199219, 0.051289081573486328, 0.052257061004638672, 0.054348945617675781, 0.051416873931884766, 0.054567813873291016, 0.052635908126831055

**Comment by hickeng** [comment] 2016-10-05 16:07
Not sure what's occurring here as I see stop taking 10s with sleep for regular docker as well:
```
# docker run -itd --name stoptest busybox sleep 2000
# time docker stop stoptest
da5eb7c0670184591e117d1156d2262b6e695ff230b1b22132ba137872961808
stoptest

real    0m10.107s
user    0m0.012s
sys     0m0.000s
```

However it's almost instant with VIC testing locally against ESX (consistent with ESX perf results):
```
# time docker -H 192.168.78.132:2376 --tls stop 23
23

real    0m0.034s
user    0m0.016s
sys     0m0.000s
```

Looking at the logs for the bundle attached in https://github.com/vmware/vic/issues/2568#issuecomment-251584277 it seems the VMs are stopping cleanly, it's just that they're taking ~9s to do so. Without the container logs I cannot tell whether that's in guest or out of guest, and we're only grabbing 1000 lines of hostd so it's not visible there either.

@carlsone Some questions:
1. does this occur with a single container run manually in this env?
2. if (1) then can you grab the container log bundle prior to 'rm' so we can check the containerVM side as well
3. else can you run a modified test that grabs the contain log bundle prior to rm

**Comment by mdubya66** [comment] 2016-10-05 18:31
Just 3 commits from @sflxn @caglar10ur https://github.com/vmware/vic/compare/ea21908152aa7bac17c536a28c89f76e3caaac82...c361617dbc749fde38df8c08c744eae8f2edc645

**Comment by hickeng** [comment] 2016-10-12 20:06
@caglar10ur Can you see a way that the changeVersion code could cause this delay? I cannot from a quick scan of the changeset, but it's the only major related change in that patchset

**Comment by hickeng** [comment] 2016-10-12 20:13
@carlsone if you deploy the VCH's with `--no-tls` then there's nothing preventing wget from gathering the logs. If you deploy with `--no-tlsverify` it should still succeed as well with `--no-check-certificate` specified.

@gigawhitlocks is currently working on #2691 which would mean it's both secure and amiable to automation by providing wget with the public/private keys.

**Comment by hickeng** [comment] 2016-10-20 17:32
Running with local docker has similar issues (this also had a 10s delay):
```
$ docker run -i --entrypoint=/bin/bash ubuntu:trusty -c "trap 'echo Booh' SIGINT SIGTERM;until read; do :;done"
Booh
Booh
Booh
```
The output came from the following commands:
```
$ docker kill -s INT d1
d1
$ docker kill -s TERM d1
d1
$ docker stop d1
d1
```

@chengwang86 
I've tried various constructions including a Dockerfile to run binaries directly without the /bin/sh wrapper and all behave in the same way. This following fragment is the only one I've found that stops immediately:
```
docker run -i --entrypoint=/bin/ash busybox -c "trap 'exit' SIGINT SIGTERM;until read; do :;done"
```

**Comment by chengwang86** [comment] 2016-10-24 20:00
@hickeng I have tried your code fragment quite a few times. It seems that tether receives the SIG KILL or SIG TERM from "docker kill/stop" almost immediately and then kills the container process successfully. 

However, our VCH **blocks** at "WaitForPowerState()" which returns when the vSphere detects that the power state of the container changes from **VM_STATE_ON -> VM_STATE_OFF**. 

**vSphere only checks and update the status of VMs every 10 seconds**. Therefore, if our "docker stop/kill" hits between two such vSphere events (power state check), vSphere will return the new power state after the second event, which might take 10 sec at the maximum.

Maybe this is a vSphere design issue. I'm still wondering if there is a way for us to workaround it, or just explain it frankly to our customer.

BTW, Hasan also mentioned that he observed similar long delay when doing "docker start" on vSphere.

**Comment by hickeng** [comment] 2016-10-25 00:24
@chengwang86 

To confirm whether it's our handling of events and shutdown path (we do perform a reconfigure on the power off path):
- [ ] use [govc events](https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#events) to see whether it's vCenter being slow with reporting events, or us being slow with handling
- [ ] are we doing a Container.Refresh on that waitForPowerOff path - if so is it that that's blocking? i.e. find the line of code where we're waiting.

If it's related to propertyCollector, there is a toolbox command that forces guestinfo update: `vmware-toolbox-cmd info update network`
You'll have to go to opengrok to find out the details of how that works internally, or @dougm may know.

**Comment by chengwang86** [comment] 2016-10-25 15:15
For the second questions, our vic code enters "waitForPowerState()" in vic/lib/portlayer/exec/base.go:279, then the "waitForPowerState()" function in govmomi is called and blocked (almost 10 sec). I don't see Container.Refresh on this path.

**Comment by chengwang86** [comment] 2016-10-25 16:56
@hickeng Just got confirmed from the life cycle team that there is a periodic host sync between the ESX server and the vCenter every 10-30 seconds. Based on the logs, after we do "docker stop", the tether process kills the container and the VM exits(0) almost immediately; the ESX host also updates the power state at the same time. 

However, **due to the delay in "host sync"**, vCenter only knows about this event after several seconds. Then the vCenter notifies the govmomi client about it (no extra delay).

BTW, according to the life cycle team, if we directly ask the VC to stop the VM, the power state transition can be sent back to govmomi with no delay.

**Comment by chengwang86** [comment] 2016-10-25 17:25
Update: I have created a ticket on bugzilla.

https://bugzilla.eng.vmware.com/show_bug.cgi?id=1753700

According to the last reply in the above ticket, "host sync" between vCenter and ESXi server may not be a good workaround.

**Comment by hickeng** [comment] 2016-10-25 20:17
@chengwang86 We directly ask VC to perform a guest shutdown, to politely kill the container process. If we ask VC to power the VM off we lose that clean path and are just powering off, with the potential for filesystem corruption, etc.

**Comment by chengwang86** [comment] 2016-10-27 15:03
Update:

@carlsone @hickeng @emlin @mdubya66 @matthewavery 

- When we do "docker stop", we need to wait for the power state change event (VM_POWER_ON -> VM_POWER_OFF) from the vCenter. 
- However, the "host sync" between the ESXi server (hosting the containeVM) and the vCenter is done periodically every 20 seconds.
- Therefore, it may take up to 20 seconds (in the worst case) for the ESXi server to propagate the power state change information to the vCenter, which causes the random delay. 
- **As of now, we do not have a good workaround to fix this issue**.

**Comment by hickeng** [comment] 2016-11-08 22:48
@mdubya66 I don't think we've got a solution for this in the 0.8 timeframe.

**Comment by chengwang86** [comment] 2016-12-08 22:12
@carlsone @hickeng I revisited this problem. 

First, "docker stop" being slower on VC than on ESX is due to the host sync delay (somewhat random) between the vCenter and the ESXi host. And we do not have a way to deal with it without sacrificing power state consistency of the containerVM.

Second, when I check out the logs here  https://github.com/vmware/vic/issues/2568#issuecomment-251584277

There are 110 appearances of ContainerStop operations in the docker-personality.log with most of them being < 1 sec but the last 10 ContainerStop operations being around 10 sec.

Then from the portlayer.log, for the majority of the containers, I couldn't find anything indicating ```github.com/vmware/vic/lib/portlayer/exec.(*Container).stop``` is called; whereas only for the last 10 containers, I find something expected as follows:
```
time="2016-10-05T04:07:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop:381] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:07:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).shutdown:344] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:07:54Z" level=info msg="sending kill -TERM fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:07:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).startGuestProgram:421] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:07:54Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).startGuestProgram:421] [173.839439ms] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:07:54Z" level=info msg="waiting 10s for fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a to power off" 
time="2016-10-05T04:07:54Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).waitForPowerState:331] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:08:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).waitForPowerState:331] [9.167407626s] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:08:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).shutdown:344] [9.342962563s] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a" 
time="2016-10-05T04:08:04Z" level=debug msg="Container(fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a) closing 0 log followers" 
time="2016-10-05T04:08:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).stop:381] [9.343936619s] fba67502bedb3e3a26197bffef58992d6443188383072c4a81b8ce90f5ef625a"
```

So I don't think the test run on build 5262 was a valid one (since most of the containers were not stopped via the portlayer appropriately). Also my own test using build 5262 has consistent performance for "docker stop" compared with vic 0.8-rc3 on a Nimbus VC setup. 

@carlsone Do you have more logs for "docker stop" test running on VC using builds prior to 5262, so that we can verify whether these tests are valid or not?

**Comment by hickeng** [comment] 2017-01-17 23:47
@chengwang86 If you cannot find the stop calls being made then I'll say drop it for now. I cannot find 445f81930738e424d1687a98127fcc26f6e732cd93d6d226c0b26fabe93ead31 being powered on in the port layer logs, let alone powered off. I only see 12 instances of VMs being powered on so seeing the last 10 take longer may be due to there only being close to 10 that started.

**Comment by chengwang86** [comment] 2017-01-17 23:59
@hickeng I think we should drop this issue (performance inconsistency) and create a different issue for "docker stop being slow on vc". 

@carlsone said that she agreed with it as long as you can confirm that these containers (with "docker stop" <1 sec ) were not started/stopped appropriately based on the logs.

**Comment by mhagen-vmware** [comment] 2017-01-24 16:21
@chengwang86 please close this issue if/when you get confirmation from @hickeng

**Comment by hickeng** [comment] 2017-01-24 20:36
@chengwang86 drop it - I think something else was wrong in this run. If we see it again we can re-open with a second log set for analysis

**Closed by hickeng** 2017-01-24 20:36 UTC
Labels: kind/bug, priority/medium, status/needs-regression-test
