### ISSUE TITLE
Error response from daemon: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc42014ebb0 Message:File [datastore1] test/VIC/volumes/multiple7/multiple7.vmdk was not found}

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#2285] opened 2016-09-09 14:17 UTC
Saw this on a recent CI run.

Log bundle:
[integration_logs_4698_1e481fdd2b7a79e1d5b4fe6cc555d0e87e966bed_1473371685.zip](https://github.com/vmware/vic/files/464125/integration_logs_4698_1e481fdd2b7a79e1d5b4fe6cc555d0e87e966bed_1473371685.zip)

@matthewavery We need to triage this quickly to understand if it is a regression or a latent problem.

**Comment by anchal-agrawal** [comment] 2016-09-14 15:52
I haven't repro'd this after several successive runs. I'll watch future builds for this failure.

**Comment by mhagen-vmware** [comment] 2016-09-28 19:29
https://ci.vmware.run/vmware/vic/5224

**Comment by anchal-agrawal** [comment] 2016-10-20 22:18
https://ci.vmware.run/vmware/vic/6103

From personality logs:
```
time="2016-10-20T19:52:52Z" level=error msg="Handler for POST /v1.21/containers/create returned error: Server error from portlayer: [POST /storage/volumes/][500] createVolumeInternalServerError  &{Code:0xc4208ee790 Message:ServerFaultCode: File [datastore1] test/volumes/c9916934-96fe-11e6-9fec-000c2967e1a1 was not found}
```

[Test-Cases.Group1-Docker-Commands.1-06-Docker-Run-VCH-6103-1407-container-logs.zip](https://github.com/vmware/vic/files/543055/Test-Cases.Group1-Docker-Commands.1-06-Docker-Run-VCH-6103-1407-container-logs.zip)

**Comment by anchal-agrawal** [comment] 2016-10-24 22:24
https://ci.vmware.run/vmware/vic/6206

**Comment by hickeng** [comment] 2016-10-27 23:33
Also in https://ci.vmware.run/vmware/vic/6315
Although the resulting log bundle is empty of group log archives.

**Comment by anchal-agrawal** [comment] 2016-10-28 22:51
https://ci.vmware.run/vmware/vic/6365

**Comment by mlh78750** [comment] 2016-11-10 17:06
rare CI only.. Pushing for root cause in .9

**Comment by corrieb** [comment] 2017-07-19 19:02
@anchal-agrawal This bug is festering. Is there a case for closing it, since it doesn't appear we've seen it this year?

**Comment by anchal-agrawal** [comment] 2017-07-19 19:06
I don't recall seeing this bug over the last several months. I propose we tag it as `no-repro` and close it - we can re-open it if needed. cc @matthewavery

**Comment by matthewavery** [comment] 2017-07-19 19:41
Originally I wanted to mark this as a `no-repro` and @mhagen-vmware and I kept it open since we were seeing it roughly once a month. I am ok with closing it with a *no-repro* if @mhagen-vmware is.

**Closed** 2017-07-19 19:43 UTC
Labels: kind/bug, kind/bug/no-repro, priority/low
