### ISSUE TITLE
vic-machine-darwin failed: Creating the appliance failed with A specified parameter was not correct.

### ISSUE THREAD

**Issue by ericj** [vmware/vic#2464] opened 2016-09-26 08:58 UTC
**VIC Version:**
v0.6.0-4890-4f98611

**Code**
```ts
./vic-machine-darwin create -t root@10.201.224.187 -i SCRD02 -b vic-container-1 -en "ETS_88%2f24_DSWA" -r "RD-POOL(7-SC11)" -v 1

```

**Expected behavior:**
VHC create successfully...

**Actual behavior:**

vic-machine-darwin failed: Creating the appliance failed with A specified parameter was not correct.

detail command output as below:

DEBU[0000] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams]
INFO[2016-09-26T16:51:53+08:00] Please enter ESX or vCenter password:
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores] [1.338µs]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams] [4.169668566s]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion] [28.604µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion] [527ns]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion] [191ns]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion] [72.027µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion] [14.105µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion] [223ns]
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion] [241ns]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion] [72.096µs]
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles] [197.974µs]
INFO[2016-09-26T16:51:58+08:00] ### Installing VCH ####
DEBU[0004] [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificate]
INFO[2016-09-26T16:51:58+08:00] Generating certificate/key pair - private key in ./virtual-container-host-key.pem
DEBU[0004] [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificate] [251.166632ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck]
DEBU[2016-09-26T16:51:58+08:00] Trying to log in with username/password in lieu of cert
DEBU[2016-09-26T16:51:58+08:00] Session Environment Info:                     API Type=VirtualCenter API Version=5.5 Build=3721164 Name=VMware vCenter Server OS Type=linux-x64 Product ID=vpx UUID=16D18C4F-62F1-4AB1-8F07-52C71E7DD2A3 Vendor=VMware, Inc. Version=5.5.0
DEBU[2016-09-26T16:51:58+08:00] vSphere resource cache populating...
DEBU[2016-09-26T16:51:58+08:00] Cached dc:
DEBU[2016-09-26T16:51:58+08:00] Error count populating vSphere cache: (3)
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck] [230.627693ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate]
INFO[2016-09-26T16:51:58+08:00] Validating supplied configuration
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).basics]
DEBU[2016-09-26T16:51:58+08:00] Setting scratch image size to 8000000 KB in VCHConfig
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).basics] [25.271µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).target]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC] [396ns]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).target] [13.515µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).compute]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper] RD-POOL(7-SC11)
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).computePathToInventoryPath] RD-POOL(7-SC11)
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).computePathToInventoryPath] [1.648µs] RD-POOL(7-SC11)
DEBU[2016-09-26T16:51:58+08:00] Converted original path "RD-POOL(7-SC11)" to "/SC_LAB/host/RD-POOL(7-SC11)/Resources"
DEBU[2016-09-26T16:51:58+08:00] Selected compute resource "/SC_LAB/host/RD-POOL(7-SC11)/Resources"
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper] [14.300145ms] RD-POOL(7-SC11)
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).inventoryPathToCluster] /SC_LAB/host/RD-POOL(7-SC11)/Resources
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).inventoryPathToCluster] [1.185µs] /SC_LAB/host/RD-POOL(7-SC11)/Resources
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).compute] [28.265755ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).storage]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).DatastoreHelper] SCRD02
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).DatastoreHelper] [11.710063ms] SCRD02
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).storage] [11.750209ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).network]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] ETS_88%2f24_DSWA
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] [12.79999ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] [12.84569ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper] [12.864981ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] ETS_88%2f24_DSWA
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] [12.658252ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] [12.698789ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper] [12.714048ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] ETS_88%2f24_DSWA
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] [12.769604ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).networkHelper] [12.811376ms] ETS_88%2f24_DSWA
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).addNetworkHelper] [12.831243ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).dpgHelper] vic-container-1
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] vic-container-1
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).getNetwork] [12.494076ms] vic-container-1
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).dpgHelper] [12.525431ms] vic-container-1
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).checkVDSMembership] dvportgroup-6186
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).inDVP]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).inDVP] [652ns]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).inDVP]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).inDVP] [279ns]
INFO[2016-09-26T16:51:58+08:00] vDS configuration OK on "vic-container-1"
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).checkVDSMembership] [12.705469ms] dvportgroup-6186
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).network] [63.750946ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall]
INFO[2016-09-26T16:51:58+08:00] Firewall status: ENABLED on "/SC_LAB/host/RD-POOL(7-SC11)/10.201.224.7"
INFO[2016-09-26T16:51:58+08:00] Firewall configuration OK on hosts:
INFO[2016-09-26T16:51:58+08:00]   "/SC_LAB/host/RD-POOL(7-SC11)/10.201.224.7"
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall] [81.613272ms]
INFO[2016-09-26T16:51:58+08:00] License check OK on hosts:
INFO[2016-09-26T16:51:58+08:00]   "/SC_LAB/host/RD-POOL(7-SC11)/10.201.224.7"
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckDrs]
INFO[2016-09-26T16:51:58+08:00] DRS check OK on:
INFO[2016-09-26T16:51:58+08:00]   "/SC_LAB/host/RD-POOL(7-SC11)/Resources"
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).CheckDrs] [5.591673ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).certificate]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).certificate] [482.477µs]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).compatibility]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).checkDatastoresAreWriteable]
WARN[2016-09-26T16:51:58+08:00] Only one host can access all of the image/container/volume datastores. This may be a point of contention/performance degradation and HA/DRS may not work as intended.
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).checkDatastoresAreWriteable] [42.999435ms]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).compatibility] [70.476088ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues] [301ns]
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate] [299.142467ms]
DEBU[0004] [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).AddDeprecatedFields]
DEBU[2016-09-26T16:51:58+08:00] Datacenter: "SC_LAB", Cluster: "/SC_LAB/host/RD-POOL(7-SC11)", Resource Pool: "/SC_LAB/host/RD-POOL(7-SC11)/Resources"
DEBU[0004] [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).AddDeprecatedFields] [16.758µs]
DEBU[0005] [BEGIN] [github.com/vmware/vic/lib/install/management.NewDispatcher]
DEBU[0005] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).InitDiagnosticLogs]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).InitDiagnosticLogs] [981.536715ms]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.NewDispatcher] [981.580842ms]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CreateVCH] virtual-container-host
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).checkExistence]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findVirtualApp] /SC_LAB/host/RD-POOL(7-SC11)/Resources/virtual-container-host
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findVirtualApp] [23.277903ms] /SC_LAB/host/RD-POOL(7-SC11)/Resources/virtual-container-host
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findResourcePool] /SC_LAB/host/RD-POOL(7-SC11)/Resources/virtual-container-host
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).findResourcePool] [23.329824ms] /SC_LAB/host/RD-POOL(7-SC11)/Resources/virtual-container-host
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).checkExistence] [46.702452ms]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createVApp]
INFO[2016-09-26T16:52:00+08:00] Creating virtual app "virtual-container-host"
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createVApp] [355.087766ms]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createBridgeNetwork]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createBridgeNetwork] [3.254µs]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createVolumeStores]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createVolumeStores] [352ns]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance]
INFO[2016-09-26T16:52:00+08:00] Creating appliance on target
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createApplianceSpec]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addIDEController]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addIDEController] [6.181µs]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addParaVirtualSCSIController]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addParaVirtualSCSIController] [58.396µs]
DEBU[0006] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addNetworkDevices]
DEBU[2016-09-26T16:52:00+08:00] Setting "external" to slot 192
INFO[2016-09-26T16:52:00+08:00] Network role "client" is sharing NIC with "external"
INFO[2016-09-26T16:52:00+08:00] Network role "management" is sharing NIC with "external"
DEBU[2016-09-26T16:52:00+08:00] Setting "bridge" to slot 224
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).addNetworkDevices] [38.823259ms]
DEBU[0006] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createApplianceSpec] [39.429058ms]
ERRO[2016-09-26T16:52:03+08:00] Task failed with error : A specified parameter was not correct.

ERRO[2016-09-26T16:52:03+08:00] Unable to create appliance VM: A specified parameter was not correct.

DEBU[0009] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).createAppliance] [2.914748621s]
DEBU[0009] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CreateVCH] [3.316700816s] virtual-container-host
DEBU[0009] [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs]
INFO[2016-09-26T16:52:03+08:00] Collecting 16D18C4F-62F1-4AB1-8F07-52C71E7DD2A3 vpxd.log
DEBU[0010] [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs] [261.572154ms]
ERRO[2016-09-26T16:52:03+08:00] --------------------
ERRO[2016-09-26T16:52:03+08:00] vic-machine-darwin failed: Creating the appliance failed with A specified parameter was not correct.
. Exiting...

**Comment by mdubya66** [comment] 2016-09-28 16:33
The error message should certainly be more specific.

**Comment by emlin** [comment] 2016-10-27 15:11
@ericj, by any chance, do you still have the vic-machine.log and vsphere log vpxd.log? If yes, could you please add vic-machine log and the vpxd.log? 
There is error message returned from VC: A specified parameter was not correct. But that's a generic error message, we'll need more details about it.

**Comment by emlin** [comment] 2016-10-27 21:26
@ericj there must be something special in your env. I cannot reproduce this issue even with exactly same resource pool name and network name.

**Comment by emlin** [comment] 2016-10-28 15:02
@ericj Close this issue for cannot reproduce and no enough information to continue. Please feel free to reopen it if you still can reproduce it, and please upload log files to help triage.

**Closed** 2016-10-28 16:50 UTC
Labels: kind/bug
