### ISSUE TITLE
Automate UI plugin install

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#5461] opened 2017-06-13 17:45 UTC
**User Statement:**
As a user I want the UI plugin installation to be user friendly.

**Details:**
Editing the config file to run install.sh is painful. Script this and it can be run on startup of the OVA.
@jooskim 
If we run this from the OVA, it should know where the fileserver is and be able to automatically point to the zip
We can use the demo installer or similar to get the vCenter IP address and thumbprint
Not sure what other parameters we need

**Acceptance Criteria:**
- [x] Script to automatically install the UI plugin
- [ ] Integrated with OVA startup
- [ ] Documentation

**Comment by jooskim** [comment] 2017-06-13 17:57
Here's a sample command that gets called at the end of `install.sh`.
`./vic-ui-darwin install --target https://${VC_IP}/sdk/ --user administrator@vsphere.local --password ${VC_ADMIN_PW} --key com.vmware.vic --name VicUI --version 1.1.1 --summary VicUI --company VMware --url https://${OVA_IP}:9443/com.vmware.vic-v1.1.1.zip --server-thumbprint ${SHA1_THUMBPRINT_OF_FILESERVER}`

Plugin key, name, summary, version and company can be derived from `plugin-manifest`.

**Comment by jooskim** [comment] 2017-06-13 18:08
For an upgrade operation simply add `--force` to the `vic-ui` command

**Comment by andrewtchin** [comment] 2017-06-21 20:58
script is taken care of in #5552, reducing estimate

**Comment by jooskim** [comment] 2017-08-30 20:49
Dupe of https://github.com/vmware/vic-product/issues/705. Closing.

**Closed by jooskim** 2017-08-30 20:49 UTC
Labels: area/ui, area/ux, priority/medium, product/ova
