### ISSUE TITLE
create needs to pull the image, if missing

### ISSUE THREAD

**Issue by caglar10ur** [vmware/vic#474] opened 2016-04-06 20:20 UTC
Right now it just returns an error

```
# $DOCKER create golang
Error response from daemon: No such image: a0204124f28f634f2e2a2b77805f9055e995fda013a351c050369f1674ce20f6
```

whereas it needs to be pulling the image as that's what docker does

```
# docker create golang
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang

004814f54a9a: Downloading [=>                                                 ] 580.3 kB/18.53 MB
4786bcc15aac: Pulling fs layer
9067f1df192a: Downloading [>                                                  ] 539.8 kB/56.9 MB
f4b88e1677e8: Download complete
c26bd5834ea3: Download complete
68b7cbb87172: Download complete
b64637c91ac2: Pulling fs layer
2b72d33ee21c: Download complete
2e14e0fd7541: Download complete
80a76c686c2d: Pulling fs layer
1c5d15a56a6c: Download complete
09ed130abf3a: Pulling fs layer
````

**Comment by hickeng** [comment] 2016-04-06 22:12
This could be a duplicate of #354

**Comment by mdubya66** [comment] 2016-06-30 21:45
(mwilliamson) dubs:~/Downloads/vic $ docker -H 172.16.127.148:2376 --tls create golang
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
b0850b14d0d1: Download complete
5c90d4a2d1a8: Downloading [=================================>                 ] 34.61 MB/51.35 MB
a3ed95caeb02: Download complete
ab30c63719b1: Download complete
c6072700a242: Downloading [=============================================>     ] 38.34 MB/42.53 MB
0ffc1204e0ab: Downloading [==========================>                        ] 29.72 MB/56.92 MB
d8a921df8ce9: Downloading [=============================>                     ] 50.27 MB/84.85 MB
d34bc98c2770: Download complete

(mwilliamson) dubs:~/Downloads/vic $ https://github.com/vmware/vic/issues/445
(mwilliamson) dubs:~/Downloads/vic $ docker -H 172.16.127.148:2376 --tls create golang
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
b0850b14d0d1: Pull complete
5c90d4a2d1a8: Pull complete
a3ed95caeb02: Pull complete
ab30c63719b1: Pull complete
c6072700a242: Pull complete
0ffc1204e0ab: Pull complete
d8a921df8ce9: Pull complete
d34bc98c2770: Pull complete

This is fixed. Closing.

**Closed by mdubya66** 2016-06-30 21:45 UTC
Labels: area/docker, component/docker-api-server, kind/enhancement
