### ISSUE TITLE
1-24-Docker-Link fails against vCenter

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6433] opened 2017-09-25 22:07 UTC
- Link and alias

**Comment by gigawhitlocks** [comment] 2017-09-25 23:05
[1-24-Docker-Link.tar.gz](https://github.com/vmware/vic/files/1331203/1-24-Docker-Link.tar.gz)

**Comment by anchal-agrawal** [comment] 2017-10-13 19:46
This suite passed on my vCenter setup. In the logs above, I looked for the cause for the `ping: unknown error` error. I didn't find a related error log message for this in the personality, portlayer and container logs. Looks like the network alias for the `first` container was set up correctly by the portlayer too:
```
Sep 21 2017 22:11:39.340Z DEBUG adding alias jedi:first -> first
Sep 21 2017 22:11:39.340Z DEBUG adding alias jedi:37ad1cb6ee06 -> first
```

The VCH network configurations in the failure above and the success on my setup were the same. Closing.

**Closed by anchal-agrawal** 2017-10-13 19:46 UTC
Labels: kind/quality, priority/medium, team/container
