### ISSUE TITLE
ova deployment: generate harbor certificate using fqdn

### ISSUE THREAD

**Issue by emlin** [vmware/vic#4721] opened 2017-04-12 14:35 UTC
Currently, the harbor certificate is generated using ip address, that means connect to harbor through secure way, we can only use `docker login <ip address>`, instead of `docker login <fqdn>`.

According to @frapposelli, it is because the localhost is not set correctly.

Expected behavior:
harbor certificate is generated based on fqdn, if that's available, and then user can run `docker login <fqdn>` successfully

@stuclem @frapposelli

**Comment by frapposelli** [comment] 2017-04-12 14:40
by default, the OVA will deploy with FQDN set to `localhost.localdomain`, if that FQDN is not changed (or acquired via DHCP) then the certificate will be generated only with the IP address as Subject Alternate Name.

This is the expected behavior and not a bug, but it would be useful to document (/cc: @stuclem @alextopuzov)

**Comment by emlin** [comment] 2017-04-12 16:57
talked with @frapposelli through slack.
this issue is because FQDN is set to `localhost.localdomain` during ova deployment. If it's reset to empty, the hostname should be set correctly, and then harbor certificate could work well.

Tried a new deployment with empty FQDN, but the hostname of the deployed ova is still localhost:

```root@localhost [ ~ ]# hostname
localhost.localdomain
root@localhost [ ~ ]# cat /etc/hostname 
localhost.localdomain
root@localhost [ ~ ]#

**Comment by frapposelli** [comment] 2017-04-12 18:19
Marking as a bug for further review

**Comment by andrewtchin** [comment] 2017-04-28 20:40
https://github.com/vmware/vic/blob/master/installer/packer/scripts/admiral/configure_admiral.sh#L165
We're setting the hostname, used as CN, to the IP if its `localhost.localdomain` or blank

**Comment by andrewtchin** [comment] 2017-05-01 16:38
```root@Photon [ ~ ]# cat /var/log/cloud-init.log  | grep -i photon
2017-04-28 19:57:54,931 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
2017-04-28 19:57:55,210 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
2017-04-28 19:57:55,362 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
2017-04-28 19:57:55,377 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
2017-04-28 19:57:55,379 - cc_set_hostname.py[DEBUG]: Setting the hostname to photon (photon)
2017-04-28 19:57:55,380 - __init__.py[DEBUG]: Non-persistently setting the system hostname to photon
2017-04-28 19:57:55,380 - util.py[DEBUG]: Running command ['hostname', 'photon'] with allowed return codes [0] (shell=False, capture=True)
2017-04-28 19:57:55,392 - cc_update_hostname.py[DEBUG]: Updating hostname to photon (photon)
2017-04-28 19:57:55,392 - __init__.py[DEBUG]: Attempting to update hostname to photon in 1 files
2017-04-28 19:57:55,698 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
2017-04-28 19:57:55,837 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.photon.Distro'>
```

**Comment by andrewtchin** [comment] 2017-05-01 19:34
I don't think cloudinit is causing this - I removed/changed any place we were setting hostname `photon` and it is still getting set/unable to get transient hostname to use the DHCP value. 
```
May 01 19:03:17 Photon systemd-resolved[294]: Using system hostname 'Photon'.
```

**Comment by andrewtchin** [comment] 2017-05-04 17:07
I verified the correct behavior takes place in Ubuntu (systemd 229) with an isolated network and its own DHCP server sending option host name. 
I also tested on Photon with systemd 233 from photon-dev and the transient hostname was still not set.

**Comment by andrewtchin** [comment] 2017-05-05 18:22
Filed bugzilla 1865714

**Comment by mdubya66** [comment] 2017-10-30 19:19
Issue moved to [vmware/vic-product #1006](https://github.com/vmware/vic-product/issues/1006) via [**ZenHub**](https://www.zenhub.com/)

**Closed by mdubya66** 2017-10-30 19:19 UTC
Labels: kind/bug, priority/medium, product/harbor
