### ISSUE TITLE
Docker rm fails with "no such container" for unknown executable

### ISSUE THREAD

**Issue by corrieb** [vmware/vic#2113] opened 2016-08-24 16:57 UTC
Very simple to reproduce in 0.5.0:

```
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.5.0/vic$ export DOCKER_HOST=10.118.67.217:2375
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.5.0/vic$ docker pull busybox
Using default tag: latest
Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.5.0/vic$ docker run busybox xxxx
docker: Error response from daemon: server error from portlayer : xxxx: no such executable in PATH.
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.5.0/vic$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED                  STATUS              PORTS               NAMES
238d319ad5c2        busybox             "xxxx"              Less than a second ago   Created                                 sharp_lovelace
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/0.5.0/vic$ docker rm 238d319ad5c2
Error response from daemon: No such container: 238d319ad5c2
```

**Comment by corrieb** [comment] 2016-08-24 16:58
[logs (1).zip](https://github.com/vmware/vic/files/435246/logs.1.zip)

**Comment by mdubya66** [comment] 2016-08-24 19:56
@corrieb I reproduce this in 0.5.0. Not sure how it slipped through. @mhagen-vmware?  I just tested on build 4331 and the issue does not reproduce.

**Comment by mdubya66** [comment] 2016-08-24 20:03
from Build 4331 
```
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls create busybox /bin/top
d6df3a88dbd2007941bb0ca02904247cb5e9600446b1e657aad341a185f1b242
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
d6df3a88dbd2        busybox             "/bin/top"          29 minutes ago      Created                                 stoic_austin
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls rm d6
d6
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
(mwilliamson) dubs:~/Downloads/vic_4331 $
```

**Comment by mhagen-vmware** [comment] 2016-08-24 20:03
Probably didn't have the rm tests enabled at the time, due to the issues we were seeing around all the race conditions in rm.

**Comment by mhagen-vmware** [comment] 2016-08-24 20:05
Actually we currently still have 2 out of 6 rm tests still disabled due to p0 bugs.

**Comment by mdubya66** [comment] 2016-08-24 20:07
whelp, I'm wrong. it does occur on 4331 if you use the xxxx as an invald command. 
```
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls run busybox xxxx
docker: Error response from daemon: server error from portlayer : xxxx: no such executable in PATH.
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
506574e22393        busybox             "xxxx"              31 minutes ago      Created                                 goofy_sammet
(mwilliamson) dubs:~/Downloads/vic_4331 $ docker --tls rm 50
Error response from daemon: No such container: 50
(mwilliamson) dubs:~/Downloads/vic_4331 $
```

I think we need a test for this case @mhagen-vmware

**Comment by cgtexmex** [comment] 2016-08-24 20:08
I believe this only occurs in an "unhappy path" situation.  In @corrieb 's example he attempted to run with a bad path -- so the start failed.  I was just looking at this as I hit it while working on Wait...

**Comment by mhagen-vmware** [comment] 2016-08-24 20:13
Yep, need a new test for this:

https://ci.vmware.run/vmware/vic/4344

**Comment by cgtexmex** [comment] 2016-08-24 20:45
This is happening because when the container fails to start the persona removes it from it's local cache.  Then when you issue a rm with only a partial id or the name it will fail.  If instead you use the entire ID then it works.

Here's the line that is removing from the local cache:  https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container.go#L568

I'm not sure why we are removing from the persona cache on start failure -- possibly @sflxn or @jzt have some thoughts...

**Comment by mdubya66** [comment] 2016-08-25 19:44
There's no workaround that I can find for removing the container once you get in this state. making this a P0 and assigning to @jzt .

**Comment by mdubya66** [comment] 2016-08-25 19:46
```
(mwilliamson) dubs:~/Downloads/vic_4384 $ docker --tls stop 17ad2ea5d9f674790f991b28e7182e46e688cb63b61a641b7cdffe9f830a5d05
An error occurred trying to connect: Post https://172.16.127.187:2376/v1.23/containers/17ad2ea5d9f674790f991b28e7182e46e688cb63b61a641b7cdffe9f830a5d05/stop?t=10: EOF
(mwilliamson) dubs:~/Downloads/vic_4384 $ docker --tls stop 17ad2ea5d9f6
Error response from daemon: No such container: 17ad2ea5d9f6
```

**Closed** 2016-08-26 15:27 UTC
Labels: area/docker, kind/bug, kind/bug/p0

**Comment by mdubya66** [comment] 2016-08-27 00:46
Just tested this and can confirm it works
```(mwilliamson) dubs:~/Downloads/vic_0.5.5 $ docker --tls pull busybox
Using default tag: latest
Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
(mwilliamson) dubs:~/Downloads/vic_0.5.5 $ docker --tls run
(mwilliamson) dubs:~/Downloads/vic_0.5.5 $ docker --tls run -it --rm busybox
/ # exit
(mwilliamson) dubs:~/Downloads/vic_0.5.5 $ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES```

Notice that the rm also worked!
