### ISSUE TITLE
Documentation to install plugin is still pointing to 1.2

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic#6879] opened 2017-11-30 19:02 UTC
**VIC version:**
vic-v1.3.0-rc2-2628-9e2a95b6.ova
**Deployment details:**
Nimbus deployment, no VCH
**Steps to reproduce:**
Follow instructions to install the plugin
**Actual behavior:**
Docs link to:
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/install_vic_plugin.html
**Expected behavior:**
Should point to 1.3 docs

**Comment by zjs** [comment] 2017-11-30 19:04
Closing as a duplicate of vmware/vic-product#1081

**Closed by zjs** 2017-11-30 19:04 UTC
