### ISSUE TITLE
Shutdown and (re)Start of VCH has an improper behaviour

### ISSUE THREAD

**Issue by mreferre** [vmware/vic#3137] opened 2016-11-11 21:58 UTC
Version 0.7.0

Freshly deployed VCH.

```
user1@ubuntu:~/vic$ docker run -d -p 81:80 --name nginx1 nginx 
bca2d70d6d85a656d81ac1a5c4bf66697c536bee613b4651422237a3d9dfe85a

user1@ubuntu:~/vic$ docker run -d -p 82:80 --name nginx2 nginx 
ef75aa8277eb110f3bec52407345d2154eb3dac35b129079a17164fea279ee0b

user1@ubuntu:~/vic$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                     NAMES
ef75aa8277eb        nginx               "nginx -g daemon off;"   About a minute ago   Up 36 seconds       192.168.8.57:82->80/tcp   nginx2
bca2d70d6d85        nginx               "nginx -g daemon off;"   2 minutes ago        Up About a minute   192.168.8.57:81->80/tcp   nginx1
```

At this point we *SHUTDOWN THE VCH* 

We then *START THE VCH* back up 

On the vSphere side both containerVMs have re-started (along with the VCH EndPoint Docker VM).  

But the docker client doesn’t seem to be able to cope with what’s going on:
```
user1@ubuntu:~/vic$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
ef75aa8277eb        nginx               "nginx -g daemon off;"   8 minutes ago       Stopped             192.168.8.57:82->80/tcp   nginx2
bca2d70d6d85        nginx               "nginx -g daemon off;"   8 minutes ago       Stopped             192.168.8.57:81->80/tcp   nginx1
```

I believe there are two things here:

https://github.com/vmware/vic/issues/701 should address this inconsistency between the Docker view and the vSphere view.

https://github.com/vmware/vic/issues/744 should implement the proper logic to be applied when the VCH is shut-down and then restarted. Ultimately (IMO) the VCH should behave pretty much like a Docker host that is shutdown and then restarted. 

/cc @emlin

**Comment by hickeng** [comment] 2016-11-12 02:26
@mreferre This is interesting - I try the same effective thing on ESX and it works without issue - which actually surprises me; I thought we would hit problems with the containerVMs coming up without an assigned IP address if they shutdown while the endpoint was still running (the endpoint unbinds the IP addresses on shutdown).

**Comment by mreferre** [comment] 2016-11-16 08:52
Thanks @hickeng. Yeah.. weird (in all aspects). 

I would assume this is something we want to solidify for GA (i.e. 0.8)? Surely being able to vMotion both VCH Endpoints as well as containerVMs will help in many situations where you'd have to shutdown and start back up an entire VCH but still it feels that not having a proper way to (cleanly) shutdown and restart a VCH (vApp) is kind of limiting.  

/cc @mlh78750

**Comment by hickeng** [comment] 2017-01-11 11:33
Added customer found for Stefan Verbist

**Comment by chengwang86** [comment] 2017-01-27 02:27
I was trying to reproduce this issue but was not able to. My VCH runs on an ESXi host nested in a vsphere workstation 6.0. The only step that might cause the difference is: I was not able to "**shut down**" and "**start**" the VCH through the vspher web client
```
At this point we SHUTDOWN THE VCH
We then START THE VCH back up
```
So I simply "**power off**" and then "**power on**" the VCH. After several seconds, the VCH is on and the two containerVMs are also back on. Then the nginx web page can be accessed.

However, I notice that even after the VCH is powered off, the two nginx containerVMs are still "on" (based on the web client) whereas the nginx web page is not accessible.

**Comment by chengwang86** [comment] 2017-01-30 16:59
In my previous update, I was only restarting the VCH on a standalone ESXi host while leaving the containerVMs untouched. There is no problem with the container state or VCH restart.

Since @mreferre mentioned 
```
At this point we SHUTDOWN THE VCH

We then START THE VCH back up

On the vSphere side **both containerVMs have re-started (along with the VCH EndPoint Docker VM).**
```

I suspect the operations are done when deploying the VCH as a vapp on a vcenter. Is that right?

Based on my discussion with @emlin , we don't currently fully-support this functionality yet, and it requires more investigation and design efforts. @hickeng Any comments/suggestions?

**Comment by chengwang86** [comment] 2017-01-30 20:43
I tried restarting the VCH and the existing containers as a whole on the VC. But I didn't find inconsistency between the docker view (container status from docker ps) and the vsphere view (container status from the vsphere web client). 

However, even if "start vapp" is marked as "completed" and "docker ps" shows all containers are running, the nginx servers are not working.

**Comment by emlin** [comment] 2017-01-30 21:01
@chengwang86 hmm.. actually, as we already had event listener works, it should work even if container VMs are restarted at the same time with VCH VM.
For the nginx not working issue even after docker ps, did you try to check that a little bit later?

@mreferre which VC version are you using? Can you still reproduce this issue? As I found that there is one fix for event listener after Nov 11. That fix solved the container power on event in VC 6.5. If that's on VC 6.5, we can think that this issue is fixed already.

**Comment by chengwang86** [comment] 2017-01-30 21:06
@emlin I was using VC 6.5 and I couldn't reproduce the inconsistency issue.

Re: nginx not working issue, actually I have tried several different containers (not just nginx), none of them work after restarting. There is no error msg in the portlayer or docker-persona logs, but "docker network inspect bridge" shows that the containers are not connected to the bridge network.

**Comment by emlin** [comment] 2017-01-30 21:51
@chengwang86 yeah, that's why I want to confirm with @mreferre. There is one fix for VC 6.5 in .8, so if originally this issue is found in VC 6.5, that explains why it's not reproducible now.

**Comment by chengwang86** [comment] 2017-01-30 22:31
I couldn't reproduce this on my vc setup. Waiting for massimo's log bundle (if any) or whether he can reproduce it.

**Comment by mreferre** [comment] 2017-01-30 23:40
Emma, i was using vsphere 6.0. 


Sent from my Samsung device

-------- Original message --------

**Comment by emlin** [comment] 2017-01-31 03:46
@mreferre ah.. it's unfortunate. Then can you still reproduce it now?

**Comment by mreferre** [comment] 2017-01-31 13:27
I don't have a 6.0 env handy right now. But it's fairly easy to get it tested if you have a 6.0 setup around somewhere.


Sent from my Samsung device

-------- Original message --------

**Comment by emlin** [comment] 2017-01-31 15:19
Yeah, sure. We'll try it in VC 6.0

**Comment by chengwang86** [comment] 2017-01-31 16:02
@mreferre @emlin @mhagen-vmware I cannot reproduce it on VC 6.0 either. Probably it has been fixed after Nov as Emma mentioned.

**Comment by hickeng** [comment] 2017-01-31 20:15
@chengwang86 can you confirm there's no race condition with registering for events and the scanning of current state? Specifically we should make sure the event listeners are registered first.

**Comment by chengwang86** [comment] 2017-01-31 22:23
@hickeng when we restart the vapp, we will call this function https://github.com/vmware/vic/blob/master/lib/portlayer/exec/exec.go#L45

```
func Init(ctx context.Context, sess *session.Session, source extraconfig.DataSource, _ extraconfig.DataSink) error {
                 ... ...
		// we want to monitor the cluster, so create a vSphere Event Collector.The cluster managed object will either be a proper vSphere Cluster or a specific host when standalone mode
		ec := vsphere.NewCollector(sess.Vim25(), sess.Cluster.Reference().String())

		// start the collection of vsphere events
		err = ec.Start()
		... ...
		// create the event manager &  register the existing collector
		Config.EventManager = event.NewEventManager(ec)

		// subscribe to host events
		Config.EventManager.Subscribe(events.NewEventType(vsphere.HostEvent{}).Topic(), "host",
			func(ie events.Event) {
				hostEventCallback(ctx, ie)
			},
		)
		// subscribe the exec layer to the event stream for Vm events
		Config.EventManager.Subscribe(events.NewEventType(vsphere.VMEvent{}).Topic(), "exec", eventCallback)
		// subscribe callback to handle vm registered event
		Config.EventManager.Subscribe(events.NewEventType(vsphere.VMEvent{}).Topic(), "registeredVMEvent",
			func(ie events.Event) {
				registeredVMCallback(sess, ie)
			},
		)
                  ... ...
		// sync container cache
		if err = Containers.sync(ctx, sess); err != nil {
			return
		}
	})
	... ...
}
```
In this function, first we start the event collector by **ec.Start()** and subscribe to vsphere VM events, then in **Containers.sync()-->infraContainers()-->populateVMAttributes()** https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L589 we get the containerVMs from infrastructure for the vapp and populate the VM properties (including powerstate) to the VMs.

**Comment by emlin** [comment] 2017-02-06 17:59
Echo the code above, actually even we started the event listener before sync up container cache, the event listener does not actually help because the container cache is still empty.
So if the container sync is running, with powered off VM state, and container VM is powered on in during that time, the container state will be wrong.
But because the cache sync runs fast, it usually finished before vm events coming or vm state changed before the cache sync, which all works well.
Just reopen the issue, and move it back to backlog, and the fix should be considered together with network connection issue #3551, and if we decided to remove vApp in #3644, no need to fix these two issues.

**Comment by hmahmood** [comment] 2017-03-01 16:57
#4032 is re-stating the problem here

**Comment by stuclem** [comment] 2017-03-07 13:48
Proposed text for 0.9 release notes:

----

- <b>Shutting down a VCH restarting it does not behave correctly on vCenter Server. [#3137](https://github.com/vmware/vic/issues/3137)</b><br>If you shut down a VCH and restart it, container VMs appear in the vSphere Client as having restarted but show up as stopped if you run `docker ps -a`. This issue only affects VCHs that you deploy as vApps on vCenter Server. VCHs that you deploy on ESXi hosts are not affected.

----

@emlin and @chengwang86 does this cover it?

**Comment by chengwang86** [comment] 2017-03-08 14:54
@emlin @stuclem How about this?


If you shut down a VCH and the containerVMs as a vApp and restart the vApp, container VMs appear in the vSphere Client as having restarted but **may** show up as stopped if you run `docker ps -a`. Currently the VIC Engine does not support restarting the whole vApp. Workaround: restarting the VCH itself first, then restart the containerVMs if needed.

**Comment by emlin** [comment] 2017-03-08 15:35
Agree with @chengwang86 , and also the impact is not only for inconsistent container status, also might cause network issue mentioned in #3769

**Comment by stuclem** [comment] 2017-03-09 08:43
Thanks @chengwang86 and @emlin. Updated the RN entry as follows:

----

- <b>Shutting down and restarting a VCH does not behave correctly on vCenter Server. [#3137](https://github.com/vmware/vic/issues/3137)</b><br>If you shut down a VCH and its container VMs by powering off the vApp and then restart the vApp, container VMs appear in the vSphere Client as having restarted but might show up as stopped if you run `docker ps -a`. Container VMs might also show up as not being connected to the bridge network when you run  `docker network inspect bridge `. Currently the vSphere Integrated Containers Engine does not support restarting the whole vApp. 


----

**Closed** 2017-03-13 22:57 UTC
Labels: kind/bug, kind/bug/no-repro, kind/customer-found, priority/high
