### ISSUE TITLE
Nightlies VSAN fails to save image cache during rmi busybox

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#4601] opened 2017-04-06 04:02 UTC
```
[Manual-Test-Cases.Group5-Functional-Tests.5-6-1-VSAN-Simple-VCH-0-6646-container-logs.zip](https://github.com/vmware/vic/files/901441/Manual-Test-Cases.Group5-Functional-Tests.5-6-1-VSAN-Simple-VCH-0-6646-container-logs.zip)

[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/901445/5-6-1-VSAN-Simple.zip)

KEYWORD ${rc}, ${output} = OperatingSystem . Run And Return Rc And Output docker %{VCH-PARAMS} rmi busybox
Documentation:	
Runs the given command in the system and returns the RC and output.
Start / End / Elapsed:	20170404 22:50:00.371 / 20170404 22:50:10.748 / 00:00:10.377
22:50:00.378	INFO	Running command 'docker -H sc2-rdops-vm03-dhcp-125-179.eng.vmware.com:2376 --tls rmi busybox 2>&1'.	
22:50:10.748	INFO	${rc} = 1	
22:50:10.748	INFO	${output} = Error response from daemon: failed to save image cache: [PUT /kv/{key}][500] putValueInternalServerError  &{Code:500 Message:Error uploading apiKV.dat: File [vsanDatastore] 5568e458-4f51-10c5-3994-020...

**Comment by rajanashok** [comment] 2017-04-06 04:03
Logs:
[5-6-1-VSAN-Simple.zip](https://github.com/vmware/vic/files/901447/5-6-1-VSAN-Simple.zip)

**Comment by mhagen-vmware** [comment] 2017-04-06 15:20
making this high for now, until we understand the underlying issue

**Comment by matthewavery** [comment] 2017-04-06 15:32
Just taking a further look at this, in the past we have noticed slightly unpredictable behavior from an upload to VSAN. It boiled down to `touch foo && ls foo` would return non-zero. This was because foo had not presented in the datastore in the past.

Looks like we saw this in the portlayer logs agains, it is possible that this error has not been fully handled.

```Apr  5 2017 03:50:10.631Z INFO  Moving [vsanDatastore] 5568e458-4f51-10c5-3994-02002f586cc3/kvStores/apiKV.dat.tmp to [vsanDatastore] 5568e458-4f51-10c5-3994-02002f586cc3/kvStores/apiKV.dat
Apr  5 2017 03:50:10.680Z DEBUG unexpected fault on task retry : &types.FileNotFound{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:"[vsanDatastore] 5568e458-4f51-10c5-3994-02002f586cc3/kvStores/apiKV.dat.tmp"}}
Apr  5 2017 03:50:10.692Z ERROR Operation failed with task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc420b24680)}
Apr  5 2017 03:50:10.692Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.Do:38] [60.737504ms] 
Apr  5 2017 03:50:10.692Z DEBUG failed to move file (apiKV.dat.tmp) to (apiKV.dat) after attempting to recover from a FileNotFoundFault with error (File [vsanDatastore] 5568e458-4f51-10c5-3994-02002f586cc3/kvStores/apiKV.dat.tmp was not found) during a kv store save operation.
Apr  5 2017 03:50:10.692Z ERROR Error Setting Key/Value: Error uploading apiKV.dat: File [vsanDatastore] 5568e458-4f51-10c5-3994-02002f586cc3/kvStores/apiKV.dat.tmp was not found
Apr  5 2017 03:50:10.692Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*KvHandlersImpl).PutValueHandler:67] [695.230435ms] docker.images
 ```

**Comment by matthewavery** [comment] 2017-04-06 16:00
This is the fault we were seeing in #4151 which looks to be a very similar scenario to this one. 

`40:Mar  3 2017 00:23:28.391Z DEBUG unexpected fault on task retry : &types.FileNotFound{FileFault:types.FileFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, File:"[vsanDatastore] 71b6b858-c8af-507c-b407-02002d783eda/kvStores/apiKV.dat.tmp"}}`

**Comment by fdawg4l** [comment] 2017-04-06 17:17
We can't rely on vsan in this way.  @hickeng and I think it has to do with VC routing of operations here.  We upload the file (via VC) and VC assigns the upload to a particular ESX host.  Once the upload is done, we (again, via VC) move the resulting file to its intended destination location and VC (may) assigns this to another worker host.  It's possible the two hosts have not yet synced their VSAN namespaces in this period and we get an `ENOENT` on the move operation.

We have 3 alternatives.  Both are not "good" solutions, but they will probably work for most cases. We could
 1. Keep retrying the `Mv` until the ENOENT goes away.  This is fraught with issues least of which is you're DOS'ing VC and potentially queuing unnecessary operations.  Likewise, it may hide actual issues with the namespace.  But both of those are more palatable than the issue we're seeing.
 1. For the `upload` / `mv` transaction, we could pick a host to execute the operations on serially and be reasonably assured that any namespace issue resulting from this is an actual error and we can bale.  HOWEVER, this assumes a few things:  that there's appropriate routing (which we can almost completely rely on) to the host, and (more importantly) that `hostd` isn't itself queuing operations which may or may not throw spurious namespace issues because of queuing  We can retry for the latter case, but we DOSing hostd is still not really a good solution.
 1. Throw an error to the user when this error presents informing them that the tag / untag operation didn't complete.  They can then retry the operation.  The result is that the underlying db is still consistent if not up to date.  This is better than dataloss, but won't lower the number of GSS calls due to vsan flakiness.  

I prefer 2.  It at least bounds the unknowns to a particular host and makes these operations slightly more consistent until we move away from using the datastore to land files like we are.

**Comment by fdawg4l** [comment] 2017-04-06 17:25
Alternatively, we can do 2 and 3 ASAP and backfill 1 if we still see issues.  Or we can do all of them in one go and hope for the best.

**Comment by mhagen-vmware** [comment] 2017-04-06 19:50
2. seems to really violate the entire VC/DRS/vmotion whole model. I wouldn't think we would want to do that and it would seem to be frought with even more danger if a DRS/vmotion came in during/after we did a direct placement anyways?

3. I am not a big fan of this approach either, we are exposing a pretty glaring flaw in VSANs API guarantees in that we created a file and VSAN said it was created but because it isn't replicated it isn't actually useable, which to me feels like a violation of the API... but we still need to be good citizens here, just pushing that back to the user and not trying to help the matter at all seems to me to be throwing VSAN under the bus and just generally makes us look bad because we are still throwing spurious failures back to the user that will immediately work when you make the call a 2nd time.

**Comment by matthewavery** [comment] 2017-04-06 19:55
I am also not a fan of 3. This issue is mainly occurring during a kvstore save operation. Which means that it can occur during a `vic-machine create`(and does for our tests in a fairly consistent manner). Telling the user to retry the operation is not ideal in this instance because we are taking a `vic-machine create` and telling them that they need to redploy completely again because a pull they did not attempt themselves fails internally.

**Comment by fdawg4l** [comment] 2017-04-06 19:56
@matthewavery every time you `pull` or `rmi` an image, you follow the `upload` / `mv` path.

**Comment by matthewavery** [comment] 2017-04-06 19:59
Yes, the upload/mv path that has been causing this is the `Save` function of the kv store for now. It is possible we we call that combo in other places that we will see this as well. As a user though I would wonder why we did not simply retry until success rather than respond with something like "operation x failed, please retry in a few seconds and it should succeed"

**Comment by matthewavery** [comment] 2017-04-06 20:00
as per the DOS side of things. That is currently what we have for the entire `WaitAndRetry` call line. We have the exponential back off, but even then we are susceptible to DOSing ourselves in a busy enough environment.

**Comment by fdawg4l** [comment] 2017-04-06 20:00
There is a 4th solution which I believe is the right approach and that's to switch the `kvstore` to using NameSpaces instead of the datastore.

**Comment by mhagen-vmware** [comment] 2017-04-06 20:05
We need a solution that allows us to not have continuing failing nightly builds in the near term, so that we can actually have test results that are reliable on VSAN.  Otherwise, we have our current scenario that involves nightly tests failing every single night and nobody looking at them because they don't mean anything and don't provide any reliable test results.  And I don't want to just comment out this test because it has caught a lot of good failures in the past.

**Comment by matthewavery** [comment] 2017-04-06 20:05
I agree with that being the right approach, however I think we need to go with making a ticket for the right approach and move toward a patch solution for now. Implementing number 1 will fix this for now. Eventually VSAN will fix the bug that causes this or we will complete the 4th option. Neither of those are going to happen today though.

**Comment by fdawg4l** [comment] 2017-04-06 20:15
https://github.com/vmware/vic/issues/4061

**Comment by fdawg4l** [comment] 2017-04-06 20:20
>  And I don't want to just comment out this test because it has caught a lot of good failures in the past.

@mhagen-vmware I don't think anyone suggested disabling the test.  The issue is real and needs to be addressed.  The bug is high priority and is part of this Sprint, so it's just down to agreeing on the approach and following through.

**Comment by hickeng** [comment] 2017-04-06 20:24
@mhagen-vmware vMotion is only germane if it causes the original host to hand off the DOM ownership in the middle of the dispatch of upload/mv. It is however a possible problem, which means even if we implement (2) which should reduce the frequency of this issue we'd still need the higher level retry to address this case.

It's an ugly solution and we definitely need an randomised exponential backoff so as not to hammer the VC control plane, but it covers the broadest base of cases at the moment.

I don't think this is a vSAN issue - we're attempting to use it as if it guarantees immediate consistency across the cluster, but it does not. We can confirm with the vSAN team but I wouldn't hold out hope that this is something they will "fix".
The longer term solution is to move off this interim k/v mechanism to one that's correctly managed as part of the VCH lifecycle. In this case the lifecycle pairing is with the VCH, not the disks (tags are not tightly coupled to images, but to usage thereof) - that means shifting it to namespacedb or alternates #3286

**Comment by mhagen-vmware** [comment] 2017-04-06 20:29
Right, understood.  I have had a lengthy conversation with Matt about this throughout the day, I think ultimately the solution needs to be moving this logic to the originating call, i.e. if we take an operation on a datastore that might have delayed consistency we need to wait and confirm it is complete before moving on instead of letting a later call stumble on the inconsistency and retry there, but for now he has a one line fix that will introduce consistency for the time being.  And I think we should take it.

**Comment by mhagen-vmware** [comment] 2017-04-06 20:29
Maybe call this solution #5 :)

**Comment by matthewavery** [comment] 2017-04-06 20:55
proposed short term solution is in PR #4627

**Comment by dougm** [comment] 2017-04-14 17:38
Here is the repro program: https://gist.github.com/dougm/e5f6358432918c440786d2e10fc2ec38

Example failure output:
```
go run main.go
2017/04/14 10:34:06 This is loop number 0
2017/04/14 10:34:06 Upload(dougm-vic-test/test.dat.tmp)...
2017/04/14 10:34:07 Move(dougm-vic-test/test.dat.tmp, dougm-vic-test/test.dat)...
2017/04/14 10:34:07 This is loop number 1
2017/04/14 10:34:07 Upload(dougm-vic-test/test.dat.tmp)...
2017/04/14 10:34:08 Move(dougm-vic-test/test.dat.tmp, dougm-vic-test/test.dat)...
2017/04/14 10:34:08 This is loop number 2
2017/04/14 10:34:08 Upload(dougm-vic-test/test.dat.tmp)...
2017/04/14 10:34:09 Move(dougm-vic-test/test.dat.tmp, dougm-vic-test/test.dat)...
2017/04/14 10:34:09 mv failed, checking if files exist...
2017/04/14 10:34:10 Stat(dougm-vic-test/test.dat): OK
2017/04/14 10:34:10 Stat(dougm-vic-test/test.dat.tmp): cannot stat '[vsanDatastore] dougm-vic-test/test.dat.tmp': No such file
2017/04/14 10:34:11 Stat(dougm-vic-test/test.dat): OK
2017/04/14 10:34:11 Stat(dougm-vic-test/test.dat.tmp): cannot stat '[vsanDatastore] dougm-vic-test/test.dat.tmp': No such file
2017/04/14 10:34:13 Stat(dougm-vic-test/test.dat): OK
2017/04/14 10:34:13 Stat(dougm-vic-test/test.dat.tmp): cannot stat '[vsanDatastore] dougm-vic-test/test.dat.tmp': No such file
2017/04/14 10:34:15 Move did happen, dougm-vic-test/test.dat matches the data uploaded to dougm-vic-test/test.dat.tmp
Error: File [vsanDatastore] dougm-vic-test/test.dat.tmp was not found
exit status 1
```

Never fails when counter is included in the file name:
```
go run main.go -i
```

**Closed** 2017-04-14 18:20 UTC
Labels: kind/bug, priority/high

**Comment by fdawg4l** [comment] 2017-04-14 19:25
@stuclem we're going to need a release node for this on 1.1 specifically for deployment targeting VSAN datastores.


Some background:
```
We store some key-value state for the VCH in a file on the datastore called kvstore. When we update the values we upload a new version as kvstore.tmp and then move the .tmp file on top of the existing file. We found a race condition in VSAN that occurs when you upload a file and then quickly move that file. We have notified the VSAN team and have provided them a reproducible test case. We have also identified a work around and that work around is committed to master, but is not in the 1.1 RTM build.
When this error condition occurs, the user may have some inconsistent state in the kvstore of the VCH. The worst-case condition is that the VCH may have to be reinstalled. This worst case is theoretical and we have not seen it in testing. In testing, running another command that updates the kvstore or a restart of the VCH will resume normal operations. 
```

The error the user will see in this case will look like the following
```
Error response from daemon: failed to save image cache: [PUT /kv/{key}][500] putValueInternalServerError  &{Code:500 Message:Error uploading apiKV.dat: File [vsanDatastore] 5568e458-4f51-10c5-3994-020...```

We've mostly seen the above error when issuing `docker rmi` against VIC, but it's possible the user will get this error when doing a `docker pull` of a new image, `docker run <new image>`, or `docker create <new image>`.  

From our testing, simply retrying the operation should be sufficient to get back into a working state.  In the event that retrying the operation still returns the error mentioned above, restarting the VCH is recommended.  The worst case solution is removing the vch and recreating it, but we have not found a situation where that was necessary.

**Comment by stuclem** [comment] 2017-04-17 17:52
Proposed release note:

-----

- <b>Race condition in vSAN can cause VCH `kvstore` to enter an inconsistent state. [#4601](https://github.com/vmware/vic/issues/4601)</b><br>
VCHs store the key-value state for the VCH in a file on the datastore named `kvstore`. When values are updated a new version is uploaded as `kvstore.tmp`, which then overwrites the existing file. Race conditions can occur in VSAN if you upload a file and then quickly move that file.
If this condition occurs, the `kvstore` of the VCH can enter an inconsistent state. If this error occurs you see the following error:<pre>Error response from daemon: 
failed to save image cache: [PUT /kv/{key}][500] 
putValueInternalServerError  &{Code:500 Message:Error uploading apiKV.dat: 
File [vsanDatastore] 5568e458-4f51-10c5-3994-020...</pre> This error mostly occurs when running `docker rmi`, but could also occur when performing `docker pull`, `docker run`, or `docker create` on a new image.

   Workaround: Rerun the Docker command that resulted in the error.


----

@fdawg4l does this cover it?

**Comment by fdawg4l** [comment] 2017-04-17 17:54
Sounds great to me @stuclem!  Thanks!

**Comment by stuclem** [comment] 2017-04-18 13:46
Thanks @fdawg4l
