### ISSUE TITLE
Panic in portlayer: http: panic serving 192.168.31.143:42152: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#2985] opened 2016-11-02 17:50 UTC
Test failed in https://ci.vmware.run/vmware/vic/6483
We've seen this randomly fail before, but have been unable to determine root cause so far.
Test is disabled temporarily

**Comment by mdubya66** [comment] 2016-11-02 18:23
Dupe of https://github.com/vmware/vic/issues/2985?

**Comment by mhagen-vmware** [comment] 2016-11-08 20:39
This appears to be due to a panic in portlayer:
```
2016/11/02 17:06:31 http: panic serving 192.168.31.143:42152: runtime error: invalid memory address or nil pointer dereference
goroutine 547 [running]:
net/http.(*conn).serve.func1(0xc420877700)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe78f00, 0xc420016040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.convertContainerToContainerInfo(0xc420ab2810, 0x0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:421 +0x48a
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).ContainerWaitHandler(0xc42041c1d0, 0xc4207d0f00, 0xc42075f900, 0x40, 0xffffffffffffffff, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:388 +0x3f6
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).ContainerWaitHandler-fm(0xc4207d0f00, 0xc42075f900, 0x40, 0xffffffffffffffff, 0x30003c420831501, 0xc4204f56e0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:62 +0x52
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.ContainerWaitHandlerFunc.Handle(0xc4206e9c60, 0xc4207d0f00, 0xc42075f900, 0x40, 0xffffffffffffffff, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/container_wait.go:17 +0x4e
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*ContainerWait).ServeHTTP(0xc4205b0c00, 0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/container_wait.go:49 +0x1b5
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4206da730, 0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc420859800, 0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc4206d7120, 0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc4202bf600, 0x1a28e40, 0xc4209ae9c0, 0xc4207d0f00)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420877700, 0x1a299c0, 0xc42035d100)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by cgtexmex** [comment] 2016-11-14 20:45
The panic is certainly an issue -- a conversion function is assuming that a session will always be available via the extra info (vmx file).  I'd say that will be the case 99.8% of the time, but in a system that's heavily loaded / seeing high latency, etc...it appears that the session information didn't get persisted in time.  The panic can be fixed by checking for the existence of the session info prior to conversion.

The test still would've failed without the panic because the call to get the file from ngnix failed -- see the output.log for the following error:
```
Connecting to 192.168.31.143:8085 (192.168.31.143:8085)
wget: can't connect to remote host (192.168.31.143): Network is unreachable
md5sum: can't open 'index.html': No such file or directory
```

**Comment by mdubya66** [comment] 2016-11-19 16:53
Re-opened until we fix the test

**Comment by mdubya66** [comment] 2016-11-19 16:54
wait, closing again. the test was fixed. it was a merge race

**Closed by mdubya66** 2016-11-19 16:54 UTC
Labels: kind/bug, status/has-integration-test
