### ISSUE TITLE
Reference VMs by cannonical paths not assumed paths

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#711] opened 2016-05-18 15:49 UTC
The path of a VM is not guaranteed to be [datastore] displayname/displayname.vmx. In the case of vSAN it is *never* that path because the symbolic reference is only a best effort.

The cannonical path for a VM can be determined only _after_ it is created from the config.Files.VmPathName property.

This is particularly relevant when we configure containerVMs to boot from an ISO file that's stored with the applianceVMs files - the current path construction is not always correct.

**Comment by hickeng** [comment] 2016-05-18 15:53
See pkg/vsphere/vm/vm.go:FolderName

**Comment by fdawg4l** [comment] 2016-06-09 23:27
@hickeng it looks like we're already getting the `VmPathName` for the path.

```
 54 // FolderName returns the name of the namespace(vsan) or directory(vmfs) that holds the VM
 55 // this equates to the normal directory that contains the vmx file, stripped of any parent path
 56 func (vm *VirtualMachine) FolderName(ctx context.Context) (string, error) {
 57 »···var mvm mo.VirtualMachine
 58 
 59 »···if err := vm.Properties(ctx, vm.Reference(), []string{"runtime.host", "config"}, &mvm); err != nil {
 60 »···»···log.Errorf("Unable to get managed config for VM: %s", err)
 61 »···»···return "", err
 62 »···}
 63 
 64 »···path := path.Base(path.Dir(mvm.Config.Files.VmPathName))
 65 »···if path[0] == '[' {
 66 »···»···path = strings.Split(path, "] ")[1]
 67 »···}
 68 »···return path, nil
 69 }
```

**Comment by fdawg4l** [comment] 2016-06-09 23:27
Do we need to do anything else?

**Comment by hickeng** [comment] 2016-06-15 10:52
@fdawg4l this path should also be used to determine the location of bootstrap.iso when creating a VM.

**Comment by fdawg4l** [comment] 2016-06-15 16:44
@hickeng, looking at #990, I can't make the connection between that and this issue.  Can you (briefly) explain the connection?

**Comment by hickeng** [comment] 2016-06-16 16:43
@fdawg4l #990 results from the following:
1. create VCH with appliance VM named my-vch in folder `[datastore1] my-vch`
2. 'delete' VCH - the `[datastore1] my-vch` folder will still be there because it's not empty after deleting the VM files - it still contains the two ISO files.
3. create new VCH, again named my-vch. Appliance VM will be in folder `[datastore1] my-vch_1`
4. create a container with the new VCH and it will be booting from `[datastore1] my-vch/bootstrap.iso`, not `[datastore1] my-vch_1/bootstrap.iso`

**Comment by fdawg4l** [comment] 2016-06-16 16:45
Sounds like `delete` doesn't clean up just as much as the vm's iso path being wrong.

**Comment by dougm** [comment] 2016-06-17 15:36
We should avoid the duplicate name / rename.  Can't we just have the installer stat '[datastore1] my-vch' and abort if it already exists?  Should be able to use `vic-machine rm` to delete even if the other vm files have been deleted.

**Comment by hickeng** [comment] 2016-06-17 16:42
@dougm we've no idea whether it's an existing VM or a name collision with a random non-VM folder. We _could_ just abort the deployment, but there's always going to be a timing hole there where ESX could adjust our name.
We _should_ warn the vic-machine user that the folder exists - otherwise they're not likely to find out unless they have a habit of browsing datastores.

**Comment by dougm** [comment] 2016-06-17 17:20
True, let's put aside auto-cleanup of folders and back to avoiding the rename by vSphere of folders.  We can name the folder/config.vmx anything we want, it won't change when the display name changes.  So for example, something like: `"[DS_Name] vch-${uuid}/${uuid}.vmx"`

Where `$uuid` is generated at vch create time by vic machine, avoiding the vSphere auto-rename.  Thoughts?

**Comment by dougm** [comment] 2016-06-17 17:20
I also like having a hardcoded prefix there, makes it easier find+clean orphaned folders if needed.

**Comment by emlin** [comment] 2016-06-17 18:21
But wouldn't that introduce more messy for VI admin? Sometimes, if we don't clean everything, VI admin is easy to do that, if the name is human readable.

**Comment by dougm** [comment] 2016-06-17 18:31
The prefix `vch-` is human readable and makes it easier for both a human and code to filter out folders that don't have the prefix.  The prefix can also include the original display name, `vch-${display-name}-${uuid}`.  To be clear, you'll only see this name when browsing the datastore, it is not used as an inventory name.

**Comment by corrieb** [comment] 2016-07-14 20:15
@fdawg4l reports work is complete, and just pending integration tests.

**Comment by fdawg4l** [comment] 2016-07-15 16:46
I dont know where the change went in, but i can confirm that after `vic-machine delete` is invoked, the vch directory does go away.  So, after #1518 goes in, I think we can close this.

**Comment by mdubya66** [comment] 2016-08-03 19:54
This needs an estimate

**Comment by fdawg4l** [comment] 2016-08-03 20:17
Looks like this is done.

**Closed by fdawg4l** 2016-08-03 20:17 UTC
Labels: component/portlayer/storage
