### ISSUE TITLE
vMotion a vic-created VM but fails. 

### ISSUE THREAD

**Issue by terpsho** [vmware/vic#2202] opened 2016-08-31 00:15 UTC
vMotion a VM generated by vCH failed for both server vmotion and storage vmotion. 
**VIC Version:**

0.5 / master / commit ID

**Code**

```ts
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**
vMotion to other host or to other storage supposed to be successful.
**Actual behavior:**
vMotion failed for both cases with the same error message “Unable to prepare migration, Migration of virtual machine with remote serial port connected is not possible unless a Virtual Serial Port Concentrator appliance is used."

**Comment by caglar10ur** [comment] 2016-08-31 00:24
duplicate of https://github.com/vmware/vic/issues/770

**Closed by caglar10ur** 2016-08-31 00:24 UTC
