### ISSUE TITLE
Error response from daemon: server error from portlayer : unable to wait for process launch status: Post https://192.168.31.13/sdk: EOF

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1878] opened 2016-08-09 14:45 UTC
Saw this error on a recent PR regression run.

[integration_test_logs_3743_1470753354.zip](https://github.com/vmware/vic/files/409182/integration_test_logs_3743_1470753354.zip)

From portlayer.log:
```
time="2016-08-09T14:34:22Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] Committing handle" 
time="2016-08-09T14:34:22Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).start] Container.start" 
time="2016-08-09T14:34:23Z" level=info msg="attach connector: Received incoming connection" 
time="2016-08-09T14:34:31Z" level=error msg="Property collector error: Post https://192.168.31.13/sdk: EOF" 
time="2016-08-09T14:34:31Z" level=error msg="Unable to wait for extra config property guestinfo..sessions|769460d616e58a2f89964c6e38d2aa38e6a2ecec7651fc2fe94ac8b2ef47d022.started: Post https://192.168.31.13/sdk: EOF" 
time="2016-08-09T14:34:31Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).start] [9.326837186s] Container.start" 
time="2016-08-09T14:34:31Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit] [9.420892367s] Committing handle" 
time="2016-08-09T14:34:31Z" level=error msg="CommitHandler error (4b001ff0e6fcd02a2f33765b4b8e6c4e): unable to wait for process launch status: Post https://192.168.31.13/sdk: EOF" 
```

**Comment by mdubya66** [comment] 2016-08-10 14:48
This is a blocker to CI functioning correctly. Raising it's priority. @hmahmood will you take point on this and the other issues in this list?

#1878, #1870, #1822, #1823, #1109

**Comment by anchal-agrawal** [comment] 2016-08-10 15:42
These errors are originating from [pkg/vsphere/vm/vm.go:199](https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L199) and [pkg/vsphere/vm/vm.go:226](https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L226)

**Comment by jzt** [comment] 2016-08-10 22:28
@mhagen-vmware Are there more logs with this? Specifically, hostd logs would be useful for debugging this issue.

**Comment by hickeng** [comment] 2016-08-28 19:28
I believe this is an issue that @dougm and I discussed back in the bonneville days, and again last week.
While we do have keep-alive configured there exists the possibility that the control connection to ESX or VC drops or is terminated. If that occurs the connection will be re-established on the next keep-alive interval currently.

This sort of global cross cutting error (along with Task in Progress) is what the tasks package is for. That can be used to check for global error conditions and wrap any retry logic.

We may or may not be able to place the reconnect logic into the govmomi client, but I think the retry logic for affected operations is too high level to go in there.

**Comment by hmahmood** [comment] 2016-08-28 22:13
Do we get a specific error back from the client in this case that we can check for in the tasks package? @dougm do you think putting a retry in this case in govmomi is viable?

**Comment by dougm** [comment] 2016-09-01 18:34
Did we get any hostd.log correlation with this error "Post https://192.168.31.13/sdk: EOF" ?  I believe this would be returned by Go's http client if it was able to send the request, but did not get a proper http response.  Not sure that's something we can or want to retry.  If the connection is closed, Go's http client would take care of opening a new one.  In that case we do need to re-authenticate, which the bonneville KeepAlive handler took care of (by checking the http/soap reply for types.NotAuthenticated).  We could look at moving re-auth into govmomi.  But I don't think that's going to help in the case of io.EOF where we don't know what caused it.

**Comment by hmahmood** [comment] 2016-10-10 22:38
I am going to close this for two reasons:

1. Have not seen this in CI in quite a while
2. There seems to be no way to figure out what is causing the EOF. If the ESX died for instance, we have no way to figure that out from just an EOF, and in this case a retry would not make sense at all. And this is only one of the possible causes. So I am not sure adding a retry is a good idea. The client can retry of course, and in all likelihood that will succeed, but the point is the cause is likely something that is external to VIC, and so the user is in the best position to debug/retry.

**Closed by hmahmood** 2016-10-10 22:38 UTC
Labels: kind/bug, kind/bug/p0, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:21
This is not reproduceable. Removing kind/note.
