### ISSUE TITLE
docker create fails on 6.5_RC1 VC

### ISSUE THREAD

**Issue by mlh78750** [vmware/vic#1888] opened 2016-08-09 20:31 UTC
build 3538

installed 6.5b3 VC and two 6.5b3 hosts. 

Installed to VC with 

`./vic-machine-darwin create --target 10.161.245.177 --image-datastore datastore1 --name vic-demo --user Administrator@vsphere.local --password 'Admin!23'  --compute-resource /ha-datacenter/host/10.160.97.176/Resources --bridge-network bridge --external-network vm-network`

Then tried create:

$ docker -H 10.162.13.107:2376 --tls create busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
Error: No such image: busybox

This also leaves files on the host that are marked as "deletable=false" and are unable to be deleted via API.

**Comment by mdubya66** [comment] 2016-08-10 14:38
Assigning to @jzt

**Comment by mlh78750** [comment] 2016-08-10 14:42
@jzt I have a nimbus setup that you can use to repro/test against if you want.

**Comment by mlh78750** [comment] 2016-08-12 03:35
I'm attaching a log bundle. The only commands used on this VCH were the following:

(mikeh) Bauxite:~/vicbin/vic-3538 $ docker -H 10.161.246.167:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
(mikeh) Bauxite:~/vicbin/vic-3538 $ docker -H 10.161.246.167:2376 --tls create busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
Error: No such image: busybox
(mikeh) Bauxite:~/vicbin/vic-3538 $ docker -H 10.161.246.167:2376 --tls create hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a3ed95caeb02: Pull complete
c04b14da8d14: Pull complete
Digest: sha256:548e9719abe62684ac7f01eea38cb5b0cf467cfe67c58b83fe87ba96674a4cdd
Status: Downloaded newer image for library/hello-world:latest
Error: No such image: hello-world
[container-logs.zip](https://github.com/vmware/vic/files/414601/container-logs.zip)

**Comment by mlh78750** [comment] 2016-08-12 03:51
Confirmed this is also failing with today's build 3910. Find bundle attached.
[container-logs build 3910.zip](https://github.com/vmware/vic/files/414608/container-logs.build.3910.zip)

**Comment by mdubya66** [comment] 2016-08-12 15:23
Re-assigning to @hickeng and @fdawg4l. We should look at this to see what we may be doing, if anything, to corrupt the vmdk.

**Comment by mlh78750** [comment] 2016-08-12 15:42
internal bug is open against 6.5 beta 3 for files left un deletable. 1704879

**Comment by mlh78750** [comment] 2016-08-12 21:44
Just reproduced with build 3951 (.5 candidate) and 6.5 RC1 

(mikeh) Bauxite:~/vicbin/vic-3951 $ ./vic-machine-darwin create --target 10.162.4.26 --image-store datastore1 --name vic-test --user Administrator@vsphere.local --password 'Admin!23'  --compute-resource /ha-datacenter/host/cluster/Resources --bridge-network bridge --external-network vm-network
INFO[2016-08-12T16:38:07-05:00] ### Installing VCH ####
INFO[2016-08-12T16:38:07-05:00] Generating certificate/key pair - private key in ./vic-test-key.pem
INFO[2016-08-12T16:38:09-05:00] Validating supplied configuration
INFO[2016-08-12T16:38:12-05:00] vDS configuration OK on "bridge"
INFO[2016-08-12T16:38:13-05:00] Firewall status: DISABLED on "/ha-datacenter/host/cluster/10.162.3.118"
INFO[2016-08-12T16:38:13-05:00] Firewall configuration OK on hosts:
INFO[2016-08-12T16:38:13-05:00]   "/ha-datacenter/host/cluster/10.162.3.118"
INFO[2016-08-12T16:38:14-05:00] License check OK on hosts:
INFO[2016-08-12T16:38:14-05:00]   "/ha-datacenter/host/cluster/10.162.3.118"
INFO[2016-08-12T16:38:14-05:00] DRS check OK on:
INFO[2016-08-12T16:38:14-05:00]   "/ha-datacenter/host/cluster/Resources"
INFO[2016-08-12T16:38:17-05:00] Creating virtual app "vic-test"
INFO[2016-08-12T16:38:17-05:00] Creating appliance on target
INFO[2016-08-12T16:38:18-05:00] Network role "client" is sharing NIC with "external"
INFO[2016-08-12T16:38:18-05:00] Network role "management" is sharing NIC with "external"
INFO[2016-08-12T16:38:22-05:00] Uploading images for container
INFO[2016-08-12T16:38:22-05:00] 	"bootstrap.iso"
INFO[2016-08-12T16:38:22-05:00] 	"appliance.iso"
INFO[2016-08-12T16:40:00-05:00] Registering VCH as a vSphere extension
INFO[2016-08-12T16:40:09-05:00] Waiting for IP information
INFO[2016-08-12T16:40:36-05:00] Waiting for major appliance components to launch
INFO[2016-08-12T16:40:38-05:00] Initialization of appliance successful
INFO[2016-08-12T16:40:38-05:00]
INFO[2016-08-12T16:40:38-05:00] vic-admin portal:
INFO[2016-08-12T16:40:38-05:00] https://10.162.14.69:2378
INFO[2016-08-12T16:40:38-05:00]
INFO[2016-08-12T16:40:38-05:00] DOCKER_HOST=10.162.14.69:2376
INFO[2016-08-12T16:40:38-05:00]
INFO[2016-08-12T16:40:38-05:00] Connect to docker:
INFO[2016-08-12T16:40:38-05:00] docker -H 10.162.14.69:2376 --tls info
INFO[2016-08-12T16:40:38-05:00] Installer completed successfully
(mikeh) Bauxite:~/vicbin/vic-3951 $ docker -H 10.162.14.69:2376 --tls info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Storage Driver: vSphere Integrated Containers Backend Engine
VolumeStores:
vSphere Integrated Containers Backend Engine: RUNNING
 VCH mhz limit: 6144 Mhz
 VCH memory limit: 6.259 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.5.0
Execution Driver: vSphere Integrated Containers Backend Engine
Plugins:
 Volume:
 Network: bridge
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 6144
Total Memory: 6.259 GiB
Name: vic-test
ID: vSphere Integrated Containers
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
Registry: registry-1.docker.io
(mikeh) Bauxite:~/vicbin/vic-3951 $ docker -H 10.162.14.69:2376 --tls create busybox
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
Error: No such image: busybox
(mikeh) Bauxite:~/vicbin/vic-3951 $ docker -H 10.162.14.69:2376 --tls run -it hello-world
Unable to find image 'hello-world:latest' locally
Pulling from library/hello-world
a3ed95caeb02: Pull complete
c04b14da8d14: Pull complete
Digest: sha256:548e9719abe62684ac7f01eea38cb5b0cf467cfe67c58b83fe87ba96674a4cdd
Status: Downloaded newer image for library/hello-world:latest
docker: Error: No such image: hello-world.
See 'docker run --help'.
[container-logs-65rc1-3951.zip](https://github.com/vmware/vic/files/416209/container-logs-65rc1-3951.zip)

**Comment by mlh78750** [comment] 2016-08-12 21:56
This seems to be the spot in the log where things start falling apart.
2016-08-12T21:41:37.287Z info hostd[F503B70] [Originator@6876 sub=Vimsvc.TaskManager opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Task Created : haTask--vim.host.OperationCleanupManager.createEntry-154397396
2016-08-12T21:41:37.287Z verbose hostd[F503B70] [Originator@6876 sub=PropertyProvider opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] RecordOp ADD: recentTask["haTask--vim.host.OperationCleanupManager.createEntry-154397396"], ha-taskmgr. Applied change to temp map.
2016-08-12T21:41:37.287Z verbose hostd[F4C2B70] [Originator@6876 sub=PropertyProvider opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] RecordOp ASSIGN: info, haTask--vim.host.OperationCleanupManager.createEntry-154397396. Applied change to temp map.
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] CopyFromEntry: Hostlog_Dump: Hostlog /vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561-4fd53f76.hlog
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    UUID: 4226c774-5190-f892-60b1-2206a962447b
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    MigID: 3249613719380815658
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    HLState: none
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    ToFrom: none
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    MigType: invalid
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    OpType: create
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    WorldID: 0
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]    Item Dir F "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/"
2016-08-12T21:41:37.292Z info hostd[F4C2B70] [Originator@6876 sub=vm:   Item Vm F "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561.vmx opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser]
2016-08-12T21:41:37.293Z warning hostd[F4C2B70] [Originator@6876 sub=Libs opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Hostlog_Flush: Failed to open hostlog /vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561-4fd53f76.hlog for writing: No such file or directory
2016-08-12T21:41:37.293Z warning hostd[F4C2B70] [Originator@6876 sub=Vcsvc.OCM opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] PersistToDisk: failed to persist entry /vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561-4fd53f76.hlog to disk, operation state may not be correctly reflected.
2016-08-12T21:41:37.293Z info hostd[F4C2B70] [Originator@6876 sub=Default opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] AdapterServer caught exception: vim.fault.CannotCreateFile
2016-08-12T21:41:37.293Z info hostd[F4C2B70] [Originator@6876 sub=Vimsvc.TaskManager opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Task Completed : haTask--vim.host.OperationCleanupManager.createEntry-154397396 Status error
2016-08-12T21:41:37.293Z verbose hostd[F4C2B70] [Originator@6876 sub=PropertyProvider opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] RecordOp ASSIGN: info, haTask--vim.host.OperationCleanupManager.createEntry-154397396. Applied change to temp map.
2016-08-12T21:41:37.294Z info hostd[F4C2B70] [Originator@6876 sub=Solo.Vmomi opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Activation [N5Vmomi10ActivationE:0x0f1c28c8] : Invoke done [createEntry] on [vim.host.OperationCleanupManager:ha-op-cleanup-mgr]
2016-08-12T21:41:37.294Z verbose hostd[F4C2B70] [Originator@6876 sub=Solo.Vmomi opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Arg entry:
--> (vim.host.OperationCleanupManager.OperationEntry) {
-->    hlogFile = "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561-4fd53f76.hlog",
-->    opId = 3249613719380815658,
-->    opState = "running",
-->    opActivity = "create",
-->    curHostUuid = "4226c774-5190-f892-60b1-2206a962447b",
-->    itemList = (vim.host.OperationCleanupManager.CleanupItemEntry) [
-->       (vim.host.OperationCleanupManager.CleanupItemEntry) {
-->          path = "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/",
-->          type = "dir",
-->          removeUpon = "failure"
-->       },
-->       (vim.host.OperationCleanupManager.CleanupItemEntry) {
-->          path = "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561.vmx",
-->          type = "vm",
-->          removeUpon = "failure"
-->       }
-->    ]
--> }
2016-08-12T21:41:37.294Z info hostd[F4C2B70] [Originator@6876 sub=Solo.Vmomi opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Throw vim.fault.CannotCreateFile
2016-08-12T21:41:37.294Z info hostd[F4C2B70] [Originator@6876 sub=Solo.Vmomi opID=7d5ce024-01-45-ad39 user=vpxuser:vpxuser] Result:
--> (vim.fault.CannotCreateFile) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>,
-->    file = "/vmfs/volumes/57ae3c1a-dacd06b2-1fd5-020026fd3763/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561/b77b42ceb35eea102d44deaf514b6742327e960f3b9ca434c854c168cf593561-4fd53f76.hlog"
-->    msg = ""
--> }

**Comment by carlsone** [comment] 2016-08-30 21:13
I am also unable to use VIC version 4478 on vCenter build 4154739 (vsphere65-beta3):
 
$ ./docker/docker --tls pull ubuntu
Using default tag: latest
Pulling from library/ubuntu
a3ed95caeb02: Pull complete 
952132ac251a: Pull complete 
82659f8f1b76: Pull complete 
c19118ca682d: Pull complete 
8296858250fe: Pull complete 
24e0251a0e2c: Pull complete 
Digest: sha256:0cdb7cdc41a288622718832742b4fa935a528cdcaa3f71d7574c2f89ff0d516e
Status: Downloaded newer image for library/ubuntu:latest

  
$ ./docker/docker --tls create -it ubuntu sleep 20000
Unable to find image 'ubuntu:latest' locally
Pulling from library/ubuntu
952132ac251a: Already exists 
82659f8f1b76: Already exists 
c19118ca682d: Already exists 
8296858250fe: Already exists 
24e0251a0e2c: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:0cdb7cdc41a288622718832742b4fa935a528cdcaa3f71d7574c2f89ff0d516e
Status: Image is up to date for library/ubuntu:latest
Error: No such image: ubuntu

**Comment by mhagen-vmware** [comment] 2016-09-09 14:20
Saw this on a recent CI build (not on 6.5 either):
[integration_logs_4690_217af9fe805f9918ebc0a0ad55fd569ac70df197_1473369764.zip](https://github.com/vmware/vic/files/464138/integration_logs_4690_217af9fe805f9918ebc0a0ad55fd569ac70df197_1473369764.zip)

**Comment by mlh78750** [comment] 2016-09-27 23:26
Confirmed still broken on 5203 build:

(mikeh) Bauxite:~/vicbin/vic_5203 $ docker -H 10.160.192.14:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
docker: Error: No such image: busybox.
See 'docker run --help'.
(mikeh) Bauxite:~/vicbin/vic_5203 $ docker -H 10.160.192.14:2376 --tls run -it busybox
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
8ddc19f16526: Already exists
a3ed95caeb02: Already exists
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Image is up to date for library/busybox:latest
docker: Error: No such image: busybox.
See 'docker run --help'.

**Comment by mlh78750** [comment] 2016-09-27 23:28
[container-logs (1).zip](https://github.com/vmware/vic/files/496819/container-logs.1.zip)

**Comment by mlh78750** [comment] 2016-09-27 23:34
time="2016-09-27T23:25:58Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:216] Containers.CommitHandler"
time="2016-09-27T23:25:58Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit:123] Committing handle"
time="2016-09-27T23:25:59Z" level=error msg="Task failed with error : Cannot complete file creation operation."
time="2016-09-27T23:25:59Z" level=error msg="Something failed. Spec was {DynamicData:{} ChangeVersion: Name:hopeful_shaw-d330da71f2b60319d17e15d0a43244796562622fd283d848c3ea9c092f1be650 Version: Uuid:e6220de2-c09
time="2016-09-27T23:25:59Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit:123] [231.746525ms] Committing handle"
time="2016-09-27T23:25:59Z" level=error msg="CommitHandler error (59308b1abb77b44a177af6658dff85a4): Cannot complete file creation operation."
time="2016-09-27T23:25:59Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:216] [232.4064ms] Containers.CommitHandler"
time="2016-09-27T23:25:59Z" level=debug msg="Found 1 subscribers to vsphere.VmEvent: Removed hopeful_shaw-d330da71f2b60319d17e15d0a43244796562622fd283d848c3ea9c092f1be650 on 10.160.211.177 from ha-dc"
time="2016-09-27T23:25:59Z" level=debug msg="Event manager calling back to exec"

**Comment by dougm** [comment] 2016-10-04 16:45
here's the problem: https://github.com/vmware/vic/blob/a7e72f1b574deb32b0a982206d59e435b9d729c9/lib/spec/spec.go#L114

This formats, for example, as:
```
[datastore1]/dougm-test/dougm-test.vmx
```

Needs to be:
```
[datastore1] dougm-test/dougm-test.vmx
```

I could reproduce with this change to govc vm.create;
```
modified   govc/vm/create.go
@@ -322,7 +322,7 @@ func (cmd *create) createVM(ctx context.Context) (*object.Task, error) {
 	folder := cmd.Folder
 
 	spec.Files = &types.VirtualMachineFileInfo{
-		VmPathName: fmt.Sprintf("[%s]", datastore.Name()),
+		VmPathName: fmt.Sprintf("[%s]/%s/%s.vmx", datastore.Name(), cmd.name, cmd.name),
 	}
 
 	return folder.CreateVM(ctx, *spec, cmd.ResourcePool, cmd.HostSystem)
```

**Comment by cgtexmex** [comment] 2016-10-04 18:24
@dougm I don't believe that's it -- here's what's produced in the spec with the code you cited:

```
vmPathName = "ds:///vmfs/volumes/57f28015-c2f00e13-f87d-020028c3a082/serene_dubinsky-d5c076cab15c041a36fe5ac26407846141f57befe1164b3748cebfad608b822c/d5c076cab15c041a36fe5ac26407846141f57befe1164b3748cebfad608b822c.vmx"
```
The path appears correct...So I changed the code to print the existing and what I think you're suggesting should be the new:

```
time="2016-10-04T18:12:45Z" level=debug msg="CDG->NewVMConfigSpec--Not vSan: old([datastore1]/agitated_dijkst-759091a17096ca308e44481a8606096b76124e130b4998500f81bdfe4fdfc132/759091a17096ca308e44481a8606096b76124e130b4998500f81bdfe4fdfc132.vmx)" 
time="2016-10-04T18:12:45Z" level=debug msg="CDG->NewVMConfigSpec--Not vSan: new([datastore1] agitated_dijkst-759091a17096ca308e44481a8606096b76124e130b4998500f81bdfe4fdfc132/759091a17096ca308e44481a8606096b76124e130b4998500f81bdfe4fdfc132.vmx)"
```

The result is the same -- failure due to file create option.  Did I misinterpret your suggested change?

**Comment by dougm** [comment] 2016-10-04 18:53
Yeah the vmPathName looked ok in vpxd.log before the change.  My guess is the format is throwing off something else.  Haven't tried it in VIC yet, but below is what I was suggesting.

```
modified   lib/portlayer/exec/container.go
@@ -226,7 +226,9 @@ func (c *Container) Commit(ctx context.Context, sess *session.Session, h *Handle
 
 			// Create the vm
 			res, err = tasks.WaitForResult(ctx, func(ctx context.Context) (tasks.Task, error) {
-				return parent.CreateVM(ctx, *h.Spec.Spec(), Config.ResourcePool, nil)
+				spec := h.Spec.Spec()
+				log.Debugf("%s vmpath=%q", spec.Name, spec.Files.VmPathName)
+				return parent.CreateVM(ctx, *spec, Config.ResourcePool, nil)
 			})
 		}
 
modified   lib/spec/spec.go
@@ -111,7 +111,7 @@ func NewVirtualMachineConfigSpec(ctx context.Context, session *session.Session,
 	VMPathName := config.VMPathName
 	if !session.IsVSAN(ctx) {
 		// VMFS requires the full path to vmx or everything but the datastore is ignored
-		VMPathName = fmt.Sprintf("%s/%s/%s.vmx", config.VMPathName, config.VMFullName, config.ID)
+		VMPathName = fmt.Sprintf("%s %s/%s.vmx", config.VMPathName, config.VMFullName, config.ID)
 	}
 
 	s := &types.VirtualMachineConfigSpec{
```

**Comment by gigawhitlocks** [comment] 2016-10-04 18:54
We really need a path library and to spend some time going through everywhere we do one of these `fmt.Sprintf` path concatenations and replacing it with something standard. This isn't the first time we've been bit by something like this and these bugs are so hard to track down.

**Comment by cgtexmex** [comment] 2016-10-04 18:55
@dougm ok - then I tried (in VIC) what you're suggesting...and still fails...

**Comment by dougm** [comment] 2016-10-04 19:19
Not sure, but since the same error can be reproduced using govc vm.create with that path, next thing I'd try is just using '[datastore1]' for the path (just as we do with vsan):

```
modified   lib/spec/spec.go
@@ -109,9 +109,9 @@ func NewVirtualMachineConfigSpec(ctx context.Context, session *session.Session,
 	config.VMFullName = fullName
 
 	VMPathName := config.VMPathName
-	if !session.IsVSAN(ctx) {
+	if false {
 		// VMFS requires the full path to vmx or everything but the datastore is ignored
-		VMPathName = fmt.Sprintf("%s/%s/%s.vmx", config.VMPathName, config.VMFullName, config.ID)
+		VMPathName = fmt.Sprintf("%s %s/%s.vmx", config.VMPathName, config.VMFullName, config.ID)
 	}
 
 	s := &types.VirtualMachineConfigSpec{
```

**Comment by mlh78750** [comment] 2016-10-04 19:23
The failure is when VS tries and create a log it wants to create called vmname-rand#.hlog.

It cannot open that file for write and bombs. That's why this works if you go to esx directly, because VC's not writing that file. So I suspect this has something to do with the permissions on the directory for the VM or something. Which might be related to the path, but I think we still need to root cause the problem and not just try different paths until it works.

**Comment by cgtexmex** [comment] 2016-10-04 20:00
I removed the code that formats a full path for non-VSAN (i.e. vmfs) and it works in 6.0 and 6.5.  I'm working with Duenwen (from the Lifecycle team?) to hopefully understand why...

**Closed** 2016-10-05 14:36 UTC
Labels: kind/bug, kind/bug/p0

**Comment by dougm** [comment] 2016-10-05 15:50
Meant to add, I did get into the vpxd code and could see it was deriving the .hlog location from VmPathName, which is what lead to using the govc vm.create change to reproduce.  But it was hard to see where exactly where the vpxd parsing went wrong w/o stepping in there w/ gdb.  Regardless, we should have made the change in #2566 a while back instead of special casing for vSAN.

**Comment by cgtexmex** [comment] 2016-10-05 15:52
FWIW we appear to have hit a bug in the 6.5 ESXi code -- if we would've used a later build we wouldn't have hit the issue.  Regardless, as Doug stated, this change is still appropriate

**Comment by mlh78750** [comment] 2016-10-05 18:07
verified working on newer version of code with the fix that @cgtexmex referenced.
