### ISSUE TITLE
Nightly 5-22-NFS-Volume Kill NFS Server

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6578] opened 2017-10-18 17:37 UTC
![screen shot 2017-10-18 at 12 35 08 pm](https://user-images.githubusercontent.com/3743903/31733300-e067a650-b400-11e7-8810-fb8a6fe1c30e.png)

https://storage.cloud.google.com/vic-ci-logs/functional_logs_10_16_06_09_vic_14037.tar.gz.zip?authuser=1

**Comment by matthewavery** [comment] 2017-11-08 21:18
dupe of #6677 I have this assigned to me already and have seen it as triage master.

**Closed by matthewavery** 2017-11-08 21:18 UTC
Labels: kind/nightly-blocker, priority/high
