### ISSUE TITLE
We are leaking DOM_OBJECTS on VSAN

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3787] opened 2017-01-31 18:19 UTC
After running through a round of longevity testing we leaked the following objects on VSAN:
```
anon@anon-Latitude-E7450:~$ sshpass -p xxxx ssh root@xxxx cmmds-tool find | wc -l
1676
anon@anon-Latitude-E7450:~$ sshpass -p xxxx ssh root@xxxx cmmds-tool find -t DOM_OBJECT | wc -l
242
```

You can use cmmds-tool and /usr/var/lib/vmware/bin/objtool to observe and delete objects:
```
/usr/lib/vmware/osfs/bin/objtool delete -f -u 5ea33658-975d-86ff-287b-1866da1245c8
```
Here I delete all the dom objects that have been leaked:
```
sshpass -p xxxx ssh root@xxxx cmmds-tool find -t DOM_OBJECT -f json | jq -r ".entries[].uuid" | xargs -n1 sshpass -p xxxx ssh root@xxxx /usr/lib/vmware/osfs/bin/objtool delete -f -u
```

Eventually this results in the vsan component count exceeding the limit and you cannot create any VMs.

**Comment by emlin** [comment] 2017-02-03 19:35
The DOM is vsan Distributed Object Manager, which is used to manage vsan object. Not sure about their details, but through the command @mhagen-vmware listed, found following scenarios.

For create:
- Every time one VM or even just one namespace is created, there is one DOM created
- Add one VMDK file to one VM will create one DOM as well
- Copy VMDK file or upload datastore files do not create DOM
- Detach VMDK does not reduce DOM
- If VMDK is chained, the DOM number is less than disk numbers, I guess DOM is only created based on attached VMDK

For delete:
- DOM object will be deleted if VMDK is attached and VM is deleted
- If VMDK is detached, VM delete will leave vm folder there, and then DOM is kept as well
- If delete VMDK file directly, DOM is not deleted
- If delete VM folder through filemanager directly, with VMDK files inside, DOM is cleaned
- If delete folder, but with VMDK deleted early, DOM is left there
- Delete folder through namespace manager or filemanager, does not matter. Both of them can clean the DOM for root folder namespace, but not for the deleted VMDK files. (No need to remember the namespace UUID)

So overall, this issue is caused by our recursive delete operation, but that is the workaround for vSAN datastore cleanup. Although I do see sometimes, delete folder directly can succeed, but most of time, that does not work because our chained vmdk files.

**Comment by emlin** [comment] 2017-02-03 19:36
@hickeng @faijaz any suggestion on this?

**Comment by hickeng** [comment] 2017-02-06 18:58
@emlin 

IMO this is a vSAN defect and we should open an issue against them **immediately**.

From the details you supplied I'm making the following assumptions/clarifications. Please confirm or refute them:
* a VM folder maps directly to a namespace. A VM **is** a namespace for the purposes of this discussion
* there is a DOM per namespace
* there is a DOM per VMDK within a namespace

Which means the behaviour we're seeing can be characterized as:
* deleting a namespace deletes the namespace DOM and DOMs for any VMDKs still present in that namespace.

Which leads to the following questions:
* is a DOM created if a disk is attached to a VM that's powered off?
* Is there a DOM left around if we:
  a. detach a disk from a VM
  b. delete that VMDK via the GUI file browser
* which API calls for deleting VMDKs causes the DOM to be deleted?

**Comment by mlh78750** [comment] 2017-02-06 21:21
@emlin: It looks like we need to file an internal bug.

Can you please do the following: 
1) write a smallish script using govc that demonstrates the leak(s). 
2) file a bug against VSAN and reference @mhagen-vmware original bug as well as your investigation from above and the script to reproduce.

**Comment by emlin** [comment] 2017-02-06 21:48
Your description is right.

>    is a DOM created if a disk is attached to a VM that's powered off?

VM attach/detach does not impact DOM object. 

>    Is there a DOM left around if we:
    a. detach a disk from a VM

no

>    b. delete that VMDK via the GUI file browser

yes

    which API calls for deleting VMDKs causes the DOM to be deleted?
 FileManager methods

Basically, any FileManager operations do not trigger a DOM change. No matter it's upload/download, create/delete. But we're creating through vm creation, which created DOM objects.
Will continue to confirm why no DOM, datastore file still works in vSAN.

**Comment by emlin** [comment] 2017-02-06 21:51
@mlh78750 sounds good

**Comment by emlin** [comment] 2017-02-06 22:53
@mlh78750 unfortunately, I could not create linked clone disks through govc yet. But will still talk with vSAN team for the issue. Will figure out a way to clarify the issue with them.

**Comment by mdubya66** [comment] 2017-02-08 18:56
any updates on this @emlin?

**Comment by emlin** [comment] 2017-02-08 19:27
@mdubya66 I have created bug to vsan team, and talked with them.

Till now, few progress.
1. they give us one more command running in VCVM, to get more information, which potentially can help the DOM object cleaning. Still need to figure out if that command can delete the objects we leaked.
2. the command running in vc is actually using vsphere API, so is looking at those APIs, to see if that's available in govmomi
3. bug status is not promising, and our use model is not what vSAN designed, so do not get any useful suggestion for which API can be used. So is still trying to figure out sth from vSphere API document.

btw, want to confirm, can vSphere internal API, like what Bonneville did, be one option? @hickeng @mdubya66

**Comment by emlin** [comment] 2017-02-09 16:10
After explored possible vSphere API, and read rvc code, figured out couple of methods can be used to delete vSAN DOM object directly.
http://pubs.vmware.com/vsphere-65/index.jsp?topic=/com.vmware.wssdk.apiref.doc/index.html&single=true&__utma=207178772.1951656767.1486418991.1486418991.1486418991.1&__utmb=207178772.0.10.1486418991&__utmc=207178772&__utmx=-&__utmz=207178772.1486418991.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&__utmv=-&__utmk=141596465
This interface is public, but is claimed as draft version only. But it works in VC 6.0 and VC 6.5, so should be fine for our workaround. But still need to push the fix in FileManager for vsphere future releases.

**Comment by mhagen-vmware** [comment] 2017-02-14 17:33
Do we want to close this now, as you have created follow on high priority issues?

**Comment by emlin** [comment] 2017-02-14 18:46
not really yet, cause my PR #3929 is still in review. After that's merged, I'll close this one.

**Comment by dougm** [comment] 2017-02-26 03:58
Note that @emlin has closed PR #3929 and when #3931 is merged we'll no longer be leaking DOM objects.

**Comment by dougm** [comment] 2017-02-26 04:06
Verify when #3931 is closed.

**Comment by dougm** [comment] 2017-02-27 21:34
To verify, run the following before vch-machine create, there should be no output unless your vsan env has leaked objects already:

`govc datastore.vsan.dom.ls -ds vsanDatastore -l -o`

To remove orphan objects, if needed: `govc datastore.vsan.dom.ls -o | xargs govc datastore.vsan.dom.rm`

Run the regression tests, or anything that does:
- vic-machine create
- docker pull busybox
- docker run busybox ...
- vic-machine delete

Check for leaks again: `govc datastore.vsan.dom.ls -ds vsanDatastore -l -o`
There should be no output.

Note that without the fix, you'd see an item listed for every .vmdk created by the VCH with the command above.

**Comment by dougm** [comment] 2017-02-27 21:36
I've done the above myself, who else can verify, @rajanashok @emlin ?
Note that you'd need to use my branch until #3931 is merged (waiting for CI).

**Comment by emlin** [comment] 2017-02-27 21:58
on it

**Comment by emlin** [comment] 2017-02-27 22:37
Verified

**Comment by dougm** [comment] 2017-02-27 22:40
thanks @emlin !

**Comment by rajanashok** [comment] 2017-02-27 22:43
Thanks @emlin ,there is a separate issue logged to create a regression test #4051 closing this issue.

**Closed by rajanashok** 2017-02-27 22:43 UTC
Labels: kind/bug, priority/high
