### ISSUE TITLE
Hetero nightly test fails during busybox create

### ISSUE THREAD

**Issue by rajanashok** [vmware/vic#6100] opened 2017-08-23 21:24 UTC
![screen shot 2017-08-23 at 4 22 53 pm](https://user-images.githubusercontent.com/21340516/29639157-648cfc4a-881f-11e7-98ef-d42c4d2cede1.png)

[5-5-Heterogeneous-ESXi.zip](https://github.com/vmware/vic/files/1247083/5-5-Heterogeneous-ESXi.zip)

**Comment by cgtexmex** [comment] 2017-08-23 22:41
dupe of #5917 which is hopefully fixed...

**Closed by cgtexmex** 2017-08-23 22:41 UTC
Labels: component/portlayer/storage, component/test, priority/high, status/needs-attention
