### ISSUE TITLE
Nightly 05/08/18 VC 6.5 5-4-High-Availability: VCH inspect failed "no client IP address assigned"

### ISSUE THREAD

**Issue by AngieCris** [vmware/vic#7919] opened 2018-05-08 18:51 UTC
Nightly 05/08/18, VC 6.5
5-4-High-Availability

vic-machine install succeeded and output docker endpoint
but later after changing hosts, VCH cannot initialize. vic-machine inspect failed with:
```
May  8 2018 09:55:04.576Z ERROR op=19035.1: No client IP address assigned
May  8 2018 09:55:04.576Z DEBUG [ END ] op=19035.1 [vic/lib/install/management.(*Dispatcher).InspectVCH:40] [39.247844ms] VCH-0-2928
May  8 2018 09:55:04.576Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:267]
May  8 2018 09:55:04.576Z INFO  op=19035.1: Collecting dfb53727-4d24-4031-9761-9f155e5b9709 vpxd.log
May  8 2018 09:55:04.623Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:267] [47.101813ms] 
May  8 2018 09:55:04.624Z ERROR op=19035.1: No client IP address assigned
May  8 2018 09:55:04.663Z ERROR op=19035.1: --------------------
May  8 2018 09:55:04.664Z ERROR op=19035.1: vic-machine-linux inspect  failed: inspect failed
```
No client IP address assigned.

The failed VCH name is: `VCH-0-2928`. VCH appliance log bundle:
[VCH-0-2928.zip](https://github.com/vmware/vic/files/1985242/VCH-0-2928.zip)
vic-machine log: 
[vic-machine.log](https://github.com/vmware/vic/files/1985243/vic-machine.log)
link for complete logs:
https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-05-08-00-14-30.zip?authuser=1

No container log bundle available.

**Comment by AngieCris** [comment] 2018-05-08 18:55
From appliance tether debug log, it shows `failed to find primary IP`:
```
May  8 2018 09:53:26.115Z DEBUG &{Common:{ExecutionEnvironment: ID:1184 Name: Notes:} Static:false IP:<nil> Assigned:{IP:<nil> Mask:<nil>} Network: DHCP:<nil> Ports:[] Internal:false configured:false}
May  8 2018 09:53:26.127Z DEBUG [BEGIN]  [vic/lib/dhcp/client.NewClient:69]
May  8 2018 09:53:26.131Z DEBUG [ END ]  [vic/lib/dhcp/client.NewClient:69] [4.009898ms] 
May  8 2018 09:53:26.134Z DEBUG No gateway IP. Asking DHCP.
May  8 2018 09:53:26.137Z DEBUG No name servers configured. Asking DHCP.
May  8 2018 09:53:26.140Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).SetParameterRequestList:369]
May  8 2018 09:53:26.144Z DEBUG c.params=[]byte{0x1, 0x3, 0x6}
May  8 2018 09:53:26.147Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).SetParameterRequestList:369] [6.914031ms] 
May  8 2018 09:53:26.152Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).Request:237]
May  8 2018 09:53:26.155Z DEBUG id: {Type:255 Iaid:[87 42 186 204] Duid:{Type:2 PEN:6876 ID:5154410137175614068} IfIndex:2 HardwareAddr:00:50:56:be:1f:29}
May  8 2018 09:53:26.162Z DEBUG [BEGIN]  [vic/lib/dhcp/client.withRetry:104]
May  8 2018 09:53:26.165Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).request:187]
May  8 2018 09:53:26.169Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).discoverPacket:155]
May  8 2018 09:53:26.173Z DEBUG [BEGIN]  [vic/lib/dhcp/client.(*client).setOptions:378]
May  8 2018 09:53:26.177Z DEBUG opts=dhcp4.Options{0x35:[]uint8{0x1}, 0x37:[]uint8{0x1, 0x3, 0x6}, 0x3d:[]uint8{0xff, 0x57, 0x2a, 0xba, 0xcc, 0x0, 0x2, 0x0, 0x0, 0x1a, 0xdc, 0x47, 0x88, 0x24, 0xb5, 0xe5, 0x6, 0x62, 0x74}}
May  8 2018 09:53:26.184Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).setOptions:378] [11.081557ms] 
May  8 2018 09:53:26.188Z DEBUG [ END ]  [vic/lib/dhcp/client.(*client).discoverPacket:155] [18.848491ms] 
May  8 2018 09:53:54.192Z DEBUG error looking up client interface by name: Link not found
May  8 2018 09:53:54.196Z ERROR error looking up client interface by alias: Link alias client not found
2018/05/08 09:53:54 failed to find primary IP
```

**Comment by cgtexmex** [comment] 2018-05-08 19:35
I'd say this is just another manifestation of #7718 -- in those cases the VCH is unable to assign an IP..

**Comment by cgtexmex** [comment] 2018-05-09 20:44
Closing as dupe of #7718

**Closed by cgtexmex** 2018-05-09 20:44 UTC
Labels: kind/nightly-blocker, priority/p0, status/needs-estimation, team/foundation
