### ISSUE TITLE
No such image error on docker run

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic#1821] opened 2016-08-04 21:26 UTC
Running the vic-machine command as listed below is successful

Karthik-MB13:vic knarayan$ ./vic-machine-darwin create --target=10.xxx.xxx.xxx --user=Administrator@vsphere.local --image-datastore=local-0 -b=DPortGroup --use-rp --external-network=DPortGroup1 -name=test1

However a docker run command fails. 

Karthik-MB13:vic knarayan$ docker --tls run -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete 
8ddc19f16526: Pull complete 
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
docker: Error: No such image: busybox.
See 'docker run --help'.

Logs attached:
[logs (1).tar.gz](https://github.com/vmware/vic/files/402749/logs.1.tar.gz)

**Comment by mdubya66** [comment] 2016-08-05 14:27
@hickeng for triage

**Comment by dougm** [comment] 2016-08-09 18:16
I ran into similar recently, logs didn't help at all since the actual error was swallowed here:

https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/portlayer/container_proxy.go#L266-L268

I'm going to include a change with the PR for #1870 to at least log the actual error here.

**Comment by lazarin** [comment] 2016-08-11 12:01
I hit the same issue with build 3831. Seems like a regression since I never had this with build 3411.

1. I'm trying to run hello-world container - fails - no such image
2. list images - there are none
3. pull hello-world - seems OK
4. list images - there are none

```ts
lazo@lazo ~ $ docker -H vic-host:2376 --tls run kitematic/hello-world-nginx
Unable to find image 'kitematic/hello-world-nginx:latest' locally
Pulling from kitematic/hello-world-nginx
77c6c00e8b61: Already exists 
9b55a9cb10b3: Already exists 
e6cdd97ba74d: Already exists 
7fecf1e9de6b: Already exists 
6b75f22d7bea: Already exists 
e8e00fb8479f: Already exists 
69fad424364c: Already exists 
b3ba6e76b671: Already exists 
a956773dd508: Already exists 
26d2b0603932: Already exists 
3cdbb221209e: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:ec0ca6dcb034916784c988b4f2432716e2e92b995ac606e080c7a54b52b87066
Status: Image is up to date for kitematic/hello-world-nginx:latest
docker: Error: No such image: kitematic/hello-world-nginx.
See 'docker run --help'.

lazo@lazo ~ $ docker -H vic-host:2376 --tls images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

lazo@lazo ~ $ docker -H vic-host:2376 --tls pull kitematic/hello-world-nginx:latest
Pulling from kitematic/hello-world-nginx
77c6c00e8b61: Already exists 
9b55a9cb10b3: Already exists 
e6cdd97ba74d: Already exists 
7fecf1e9de6b: Already exists 
6b75f22d7bea: Already exists 
e8e00fb8479f: Already exists 
69fad424364c: Already exists 
b3ba6e76b671: Already exists 
a956773dd508: Already exists 
26d2b0603932: Already exists 
3cdbb221209e: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:ec0ca6dcb034916784c988b4f2432716e2e92b995ac606e080c7a54b52b87066
Status: Image is up to date for kitematic/hello-world-nginx:latest

lazo@lazo ~ $ docker -H vic-host:2376 --tls images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

Cannot find useful traces in the logs

**Comment by jzt** [comment] 2016-09-08 01:38
I've been investigating this today, and it appears the problem is caused by the image metadata being altered during write to the storage port layer.  I can see the image metadata (including actual image ID) before the call to `WriteImage` in imagec, but by the time it gets into the storage port layer, the image ID is no longer present in the metadata.

This causes the subsequent call to `ListImages` to return all layers to the caller, but when the docker persona cache receives this data, the image ID is not there and thus it can't cache the image. This is ultimately why the call to `docker images` does not show this image. The question is, why this image?

Turns out another similar image doesn't work either:  `mattes/hello-world-nginx`.

What do they have in common?  Neither has a Dockerfile on docker hub. The `kitematic` image is also shown as being 4MB in the Tags section, even though most of the other `hello-world-nginx` images are 95-100MB.

I think a look at the manifest for these images is in order. I'll do that next.

**Comment by lazarin** [comment] 2016-09-08 13:23
I guess the size is different because of the base for the image.
For example:
  - kitematic starts from scratch : https://github.com/kitematic/html/blob/master/Dockerfile
  - neoof86/hello-world-nginx is based on ubuntu : https://hub.docker.com/r/neoof86/hello-world-nginx/~/dockerfile/

**Comment by ericsmalling** [comment] 2016-10-08 00:41
Seeing similar issue on a new build:
```
$ docker --tls run -it busybox /bin/sh
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
a3ed95caeb02: Pull complete 
56bec22e3559: Pull complete 
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for library/busybox:latest
Error: No such container: 1ec0e0b2c1df0c4c201c1c4d2417cb729d0afb485246892d1a1e249990853d2c

$ docker --tls ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
1ec0e0b2c1df        busybox             "/bin/sh"           About a minute ago   Up 57 seconds                           trusting_euclid

$ docker --tls kill trusting_euclid
Error response from daemon: Cannot kill container trusting_euclid: No such container: trusting_euclid
```

VCH log bundle attached
[logs.zip](https://github.com/vmware/vic/files/517331/logs.zip)

**Comment by hickeng** [comment] 2016-10-08 02:29
@ericsmalling 

This is the same intermediate cause as #2491 - the backchannel is not being established and we're not seeing incoming network connections.

This suggests that it's an inability to establish a network connection between ESX and the appliance. The top two items to check are:
1. the ESX firewall on the host that's running the containerVM is not allowing port 2377 outbound
2. the IP address configured in the containerVM network serial port is not that of the appliance

**Comment by hickeng** [comment] 2016-10-08 02:34
@caglar10ur comment if your recent work changes any of this

@jzt The "No such container" result appears to be because `Resize` is getting a 404 response, and then removes the container from the cache.
Both attach and resize depend on an active backchannel, so not being able to find that connection should not be a 404, but instead should be a 408, and should not remove the container from the cache.

**Comment by caglar10ur** [comment] 2016-10-08 23:49
yep, the waiting pr removes that line (https://github.com/vmware/vic/pull/2584/files#diff-6e989557b980355774bd4187364245fbL369)

**Comment by hickeng** [comment] 2016-10-10 20:27
My comments about #2491 and @caglar10ur 's response are in reply to @ericsmalling's  comment specifically but do not apply to the issue as a whole.

The original comment/issue should still be considered unresolved.

**Comment by jzt** [comment] 2016-11-11 22:23
@hickeng It looks like @caglar10ur fixed this problem in commit [6c4627d4](https://github.com/vmware/vic/commit/6c4627d401f20baa94bf88f8bdec80b99b23dffe#diff-68824f0584e18cbd83689d34c87021c4R146), although not by returning a 408.

Is 408 (timeout) the desired behavior here? If so, I'll update.

**Comment by hickeng** [comment] 2016-11-16 23:17
A 404 is just as legitimate as a 408 so long as we're not deleting the container from the cache as a result.

I think the 408 is less confusing however as it doesn't leak details of the internal implementation (i.e. distinction between container existing and an interaction channel existing) - 404 may well be interpreted by the client to mean container doesn't exist given the data the client provided was a container id.

**Comment by jzt** [comment] 2016-11-17 00:32
Moving to backlog as [6c4627](https://github.com/vmware/vic/commit/6c4627d401f20baa94bf88f8bdec80b99b23dffe#diff-68824f0584e18cbd83689d34c87021c4R146) fixed the destructive behavior.

**Comment by corrieb** [comment] 2017-07-19 19:19
@jzt what still needs fixing here? Let's not let this fester if it can be closed.

**Comment by jzt** [comment] 2017-07-19 19:33
@corrieb I think its good. Not sure why I didn't just close it in the first place.

**Closed by jzt** 2017-07-19 19:33 UTC
Labels: area/docker, component/imagec, kind/bug, priority/low
