### ISSUE TITLE
Deleting container with "-v" option does not remove attached volumes

### ISSUE THREAD

**Issue by mshipkovenski** [vmware/vic#4435] opened 2017-03-29 12:19 UTC
**VIC version:**
Bintray build 9168

**Steps to reproduce:**
Provision a container based on the `kitematic/hello-world-nginx` image:
```
$ docker -H 10.162.62.168:2375 run -d kitematic/hello-world-nginx
d1d6bc2e49879b31a1691273d40bcedb7d81c0c912d8599c41b6faae2efc13f6
```
Observer that a new volume has been created and attached to the container:
```
$ docker -H 10.162.62.168:2375 volume ls
DRIVER              VOLUME NAME
vsphere             fbf2dc46-1476-11e7-9ced-0050568f5db3
```
Initiate container delete request and specify the "-v" option (delete volumes too)
```
$ docker -H 10.162.62.168:2375 rm -v -f d1d6bc2e49879b31a1
d1d6bc2e49879b31a1
```
Check the volumes
```
$ docker -H 10.162.62.168:2375 volume ls
DRIVER              VOLUME NAME
vsphere             fbf2dc46-1476-11e7-9ced-0050568f5db3
```
**Actual behavior:**
The volume is still there.

**Expected behavior:**
The volume should have been deleted. **This requirement does not apply to named volumes!**

**Additional details as necessary:**
https://docs.docker.com/engine/reference/commandline/rm/#remove-a-container-and-its-volumes

**Comment by mhagen-vmware** [comment] 2017-03-29 13:52
@mshipkovenski Thanks, I think this is an unimplemented feature at this point. @matthewavery Trying to classify this as a bug or a feature request... Are we supposed to support -v currently?

**Comment by matthewavery** [comment] 2017-03-29 16:14
@mshipkovenski @mhagen-vmware This would be a feature request :-) we have not implemented it yet, there is a TODO in the code for handling this case. Currently we ignore the `-v` flag. Estimating at a 2 since there will need to be new tests surrounding this issue, the actual implementation is not complex.

**Comment by anchal-agrawal** [comment] 2017-11-02 21:52
Duplicate of https://github.com/vmware/vic/issues/6262.

**Closed by anchal-agrawal** 2017-11-02 21:52 UTC
Labels: area/storage, component/portlayer/storage, priority/medium
