### ISSUE TITLE
Running vic-machine with "-generate-cert false" doesn't work

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#749] opened 2016-05-20 14:13 UTC
If you run vic-machine with the `-generate-cert false` option, it still generates the cert and key pem files. Emma tells me that running `generate-cert=false` does work and that this is probably due to a bug in the golang parser. 

I experienced this with a build that I ran today from the source code in master.

**Comment by mdubya66** [comment] 2016-06-27 21:29
Cannot reproduce. Closing.

**Closed by mdubya66** 2016-06-27 21:29 UTC
Labels: component/vic-machine, kind/bug
