### ISSUE TITLE
Tether test PANIC 

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#1289] opened 2016-06-30 15:12 UTC
From [drone](https://ci.vmware.run/vmware/vic/2401).  Built on top of https://github.com/fdawg4l/vic/commit/df07169aa18f4eefb9071eb323909be0e30f8d3a.

```
=== RUN   TestAttach
time="2016-06-30T00:01:26Z" level=info msg="Started test setup for github.com/vmware/vic/cmd/tether.TestAttach" 
time="2016-06-30T00:01:26Z" level=info msg="Using /tmp/tether.TestAttach301128111 as test prefix" 
time="2016-06-30T00:01:26Z" level=debug msg="created /tmp/tether.TestAttach301128111/ttyS0{c,s} as raw conn pipes" 
time="2016-06-30T00:01:26Z" level=debug msg="created /tmp/tether.TestAttach301128111/ttyS1 as persistent log destinations" 
time="2016-06-30T00:01:26Z" level=debug msg="created /tmp/tether.TestAttach301128111/ttyS2 as persistent log destinations" 
time="2016-06-30T00:01:26Z" level=debug msg="Test configuration: (extraconfig.DataSink)(0x5f0d00)" 
time="2016-06-30T00:01:26Z" level=info msg="Registering tether extension mocker" 
time="2016-06-30T00:01:26Z" level=info msg="Registering tether extension Attach" 
time="2016-06-30T00:01:26Z" level=info msg="opening ttyS0 pipe pair for backchannel (client)" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*tether).Start] main tether loop" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*tether).setup] main tether setup" 
time="2016-06-30T00:01:26Z" level=info msg="Started reaping child processes" 
time="2016-06-30T00:01:26Z" level=info msg="Launching pprof server for test on port 6060" 
time="2016-06-30T00:01:26Z" level=info msg="Starting extension mocker" 
time="2016-06-30T00:01:26Z" level=info msg="Starting extension Attach" 
time="2016-06-30T00:01:26Z" level=info msg="opening ttyS0 pipe pair for backchannel (server)" 
time="2016-06-30T00:01:26Z" level=info msg="creating raw connection from ttyS0 pipe pair (c=7, s=10)\n" 
time="2016-06-30T00:01:26Z" level=info msg="creating raw connection from ttyS0 pipe pair (c=8, s=9)\n" 
time="2016-06-30T00:01:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*tether).setup] [557.731µs] main tether setup" 
time="2016-06-30T00:01:26Z" level=info msg="Loading main configuration" 
time="2016-06-30T00:01:26Z" level=info msg="Loaded executor config" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*Mocker).SetHostname] mocking hostname to attach" 
time="2016-06-30T00:01:26Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*Mocker).SetHostname] [437ns] mocking hostname to attach" 
time="2016-06-30T00:01:26Z" level=debug msg="Processing config for session attach" 
time="2016-06-30T00:01:26Z" level=info msg="Launching process for session attach" 
time="2016-06-30T00:01:26Z" level=debug msg="[0xc820251700] created multireader" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/tether.(*tether).launch] launching session attach" 
time="2016-06-30T00:01:26Z" level=debug msg="Resolved /usr/bin/tee to /usr/bin/tee" 
time="2016-06-30T00:01:26Z" level=info msg="Launching command []string{\"/usr/bin/tee\", \"/tmp/tether.TestAttach301128111/tee.out\"}" 
time="2016-06-30T00:01:26Z" level=debug msg="Launched command with pid 12162" 
time="2016-06-30T00:01:26Z" level=info msg="Passing config to mocker" 
time="2016-06-30T00:01:26Z" level=info msg="Passing config to Attach" 
time="2016-06-30T00:01:26Z" level=info msg="Parsing config in test attach server" 
time="2016-06-30T00:01:26Z" level=info msg="Processing config for session attach" 
time="2016-06-30T00:01:26Z" level=info msg="Session attach is configured for attach" 
time="2016-06-30T00:01:26Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/tether.(*tether).launch] [21.668225ms] launching session attach" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).Reload] attach reload" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).start] start attach server" 
time="2016-06-30T00:01:26Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).start] [191.19µs] start attach server" 
time="2016-06-30T00:01:26Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).Reload] [288.849µs] attach reload" 
time="2016-06-30T00:01:26Z" level=info msg="Started test attach server" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).run] main attach server loop" 
time="2016-06-30T00:01:26Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.backchannel] establish tether backchannel" 
time="2016-06-30T00:01:26Z" level=debug msg="server: reading syn" 
time="2016-06-30T00:01:27Z" level=debug msg="server: received syn: 0x161600\n" 
time="2016-06-30T00:01:27Z" level=debug msg="server: writing synack" 
time="2016-06-30T00:01:27Z" level=debug msg="server: reading ack" 
time="2016-06-30T00:01:27Z" level=info msg="HandshakeClient: received synack: 0x0617 == 0x0617\n" 
time="2016-06-30T00:01:27Z" level=debug msg="client: writing ack" 
time="2016-06-30T00:01:27Z" level=debug msg="Checking for lossiness" 
time="2016-06-30T00:01:27Z" level=info msg="server: received ack: 0x06a3 == 0x06a3\n" 
time="2016-06-30T00:01:27Z" level=debug msg="Checking for lossiness" 
time="2016-06-30T00:01:27Z" level=info msg="lossiness check PASSED" 
time="2016-06-30T00:01:27Z" level=info msg="lossiness check PASSED" 
time="2016-06-30T00:01:27Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.backchannel] [978.218569ms] establish tether backchannel" 
time="2016-06-30T00:01:27Z" level=info msg="ready to service attach requests" 
time="2016-06-30T00:01:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).globalMux] start attach server global request handler" 
time="2016-06-30T00:01:27Z" level=info msg="accepting incoming channel for attach" 
time="2016-06-30T00:01:27Z" level=debug msg="accepted incoming channel for attach" 
time="2016-06-30T00:01:27Z" level=debug msg="binding reader/writers for channel for attach" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820272aa0] added writer - now 3 writers" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820251700] adding reader - now 1 readers" 
time="2016-06-30T00:01:27Z" level=debug msg="reader/writers bound for channel for attach" 
time="2016-06-30T00:01:27Z" level=debug msg="[BEGIN] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).channelMux] start attach server channel request handler" 
time="2016-06-30T00:01:27Z" level=debug msg="sending test data" 
time="2016-06-30T00:01:27Z" level=debug msg="sent test data" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820251700] read \"\" from 0 readers" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820272aa0] writing \"\x1b[32mhello world\x1b[39m!\n\" to 3 writers" 
hello world!
time="2016-06-30T00:01:27Z" level=debug msg="Closing the RawConn (/tmp/tether.TestAttach301128111/ttyS0c:/tmp/tether.TestAttach301128111/ttyS0s)" 
time="2016-06-30T00:01:27Z" level=debug msg="Pushing EOF to any blocked readers on the raw connection (/tmp/tether.TestAttach301128111/ttyS0c:/tmp/tether.TestAttach301128111/ttyS0s)" 
time="2016-06-30T00:01:27Z" level=debug msg="Closing the RawConn (/tmp/tether.TestAttach301128111/ttyS0s:/tmp/tether.TestAttach301128111/ttyS0c)" 
time="2016-06-30T00:01:27Z" level=debug msg="Returning error from read: EOF" 
time="2016-06-30T00:01:27Z" level=debug msg="Close called again on RawConn (/tmp/tether.TestAttach301128111/ttyS0c:/tmp/tether.TestAttach301128111/ttyS0s) - dropping" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820272aa0] removing writer - currently 3 writers" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820272aa0] removed writer - now 2 writers" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820251700] removing reader - currently 1 readers" 
time="2016-06-30T00:01:27Z" level=debug msg="[0xc820251700] removed reader - currently 0 readers" 
time="2016-06-30T00:01:27Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).channelMux] [2.109509ms] start attach server channel request handler" 
time="2016-06-30T00:01:27Z" level=info msg="incoming attach channel closed" 
time="2016-06-30T00:01:27Z" level=debug msg="Close called again on RawConn (/tmp/tether.TestAttach301128111/ttyS0s:/tmp/tether.TestAttach301128111/ttyS0c) - dropping" 
time="2016-06-30T00:01:27Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).run] [984.222223ms] main attach server loop" 
time="2016-06-30T00:01:27Z" level=debug msg="Pushing EOF to any blocked readers on the raw connection (/tmp/tether.TestAttach301128111/ttyS0s:/tmp/tether.TestAttach301128111/ttyS0c)" 
time="2016-06-30T00:01:27Z" level=debug msg="[ END ] [github.com/vmware/vic/cmd/tether.(*attachServerSSH).globalMux] [3.029481ms] start attach server global request handler" 
SIGQUIT: quit
PC=0x463031 m=0

goroutine 0 [idle]:
runtime.futex(0x1eb8f88, 0x0, 0x0, 0x0, 0x0, 0x1eb8050, 0x0, 0x0, 0x410d44, 0x1eb8f88, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:306 +0x21
runtime.futexsleep(0x1eb8f88, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x1eb8f88)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1538 +0x10b
runtime.findrunnable(0xc82001b500, 0x0)
	/usr/local/go/src/runtime/proc.go:1976 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2075 +0x24f
runtime.park_m(0xc820001980)
	/usr/local/go/src/runtime/proc.go:2140 +0x18b
runtime.mcall(0x7ffefae71e00)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive]:
testing.RunTests(0x1681a58, 0x1e93e60, 0x4, 0x4, 0x4ce901)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820047ef8, 0xc820047e40)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/vmware/vic/cmd/tether.TestMain(0xc820047ef8)
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:166 +0x2a
main.main()
	github.com/vmware/vic/cmd/tether/_test/_testmain.go:112 +0x253

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [select, locked to thread]:
runtime.gopark(0x1682260, 0xc82001ff28, 0x132c6b8, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001ff28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001ff28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 3 [chan receive]:
github.com/vmware/vic/cmd/tether.tetherTestTeardown(0xc82022a000, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:234 +0xa3
github.com/vmware/vic/cmd/tether.testTeardown(0xc82022a000)
	/drone/src/github.com/vmware/vic/cmd/tether/main_test.go:107 +0x21
github.com/vmware/vic/cmd/tether.TestAttach(0xc82022a000)
	/drone/src/github.com/vmware/vic/cmd/tether/attach_test.go:312 +0xe3a
testing.tRunner(0xc82022a000, 0x1e93e60)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 4 [chan receive]:
github.com/vmware/vic/lib/tether.(*tether).Start(0xc820250c80, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/tether/tether.go:163 +0x1d8
github.com/vmware/vic/cmd/tether.StartAttachTether.func1(0xc82022a000)
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:185 +0x2f
created by github.com/vmware/vic/cmd/tether.StartAttachTether
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:189 +0x2fc

goroutine 23 [chan receive]:
github.com/vmware/vic/lib/tether.(*tether).childReaper.func1(0xc820250c80)
	/drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:49 +0x51
created by github.com/vmware/vic/lib/tether.(*tether).childReaper
	/drone/src/github.com/vmware/vic/lib/tether/tether_linux.go:88 +0x20f

goroutine 24 [IO wait]:
net.runtime_pollWait(0x7f8e03f64d30, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201a1560, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a1560, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201a1500, 0x0, 0x7f8e03f64e28, 0xc82025e580)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200820a0, 0x63d6b1, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200820a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc820096c80, 0x7f8e03f64df0, 0xc8200820a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc820096c80, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0x1331d10, 0xc, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
github.com/vmware/vic/cmd/tether.(*Mocker).Setup.func1()
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:93 +0x3c
created by github.com/vmware/vic/cmd/tether.(*Mocker).Setup
	/drone/src/github.com/vmware/vic/cmd/tether/tether_test.go:94 +0xf6

goroutine 6 [semacquire]:
sync.runtime_Syncsemacquire(0xc820251750)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc820251740)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/vmware/vic/pkg/dio.(*multiReader).Read(0xc820251700, 0xc820294000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/pkg/dio/multi.go:163 +0x46e
io.copyBuffer(0x7f8e03f5f5b0, 0xc820026098, 0x7f8e03f9f7b0, 0xc820251700, 0xc820294000, 0x8000, 0x8000, 0x17, 0x0, 0x0)
	/usr/local/go/src/io/io.go:380 +0x247
io.Copy(0x7f8e03f5f5b0, 0xc820026098, 0x7f8e03f9f7b0, 0xc820251700, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:350 +0x64
os/exec.(*Cmd).stdin.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:191 +0x92
os/exec.(*Cmd).Start.func1(0xc82020c878, 0xc820272cc0)
	/usr/local/go/src/os/exec/exec.go:344 +0x1d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:345 +0x967

goroutine 7 [syscall]:
syscall.Syscall(0x0, 0xf, 0xc82029c000, 0x8000, 0x3, 0x2, 0x3)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xf, 0xc82029c000, 0x8000, 0x8000, 0xc820287928, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0xf, 0xc82029c000, 0x8000, 0x8000, 0x3, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc8200260b0, 0xc82029c000, 0x8000, 0x8000, 0x1220740, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x53
os.(*File).Read(0xc8200260b0, 0xc82029c000, 0x8000, 0x8000, 0x17, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
io.copyBuffer(0x7f8e03f9f788, 0xc820272aa0, 0x7f8e03f5f4c8, 0xc8200260b0, 0xc82029c000, 0x8000, 0x8000, 0x17, 0x0, 0x0)
	/usr/local/go/src/io/io.go:380 +0x247
io.Copy(0x7f8e03f9f788, 0xc820272aa0, 0x7f8e03f5f4c8, 0xc8200260b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:350 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:236 +0x8b
os/exec.(*Cmd).Start.func1(0xc82020c878, 0xc820272d60)
	/usr/local/go/src/os/exec/exec.go:344 +0x1d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:345 +0x967

rax    0xca
rbx    0x0
rcx    0x463033
rdx    0x0
rdi    0x1eb8f88
rsi    0x0
rbp    0x1
rsp    0x7ffefae71c60
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x6
r13    0x167f07d
r14    0x3
r15    0x8
rip    0x463031
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/vmware/vic/cmd/tether	600.084s
Makefile:205: recipe for target 'test' failed
make: *** [test] Error 1
[info] build failed (exit code 2)
```

**Comment by corrieb** [comment] 2016-07-11 22:27
George/Ben review: Need to triage

**Comment by jzt** [comment] 2016-08-25 18:49
This looks like a dupe of #2139 which is currently being worked on.

**Comment by hickeng** [comment] 2016-09-27 21:15
Closing as dup of #2139

**Closed by hickeng** 2016-09-27 21:15 UTC
Labels: component/tether, kind/bug
