### ISSUE TITLE
install vch, docker run fails to give interactive shell

### ISSUE THREAD

**Issue by tompscanlan** [vmware/vic#4828] opened 2017-04-19 13:21 UTC
**User Statement:**

Created vch.  Initial pull/run of interactive container hangs.  Container starts, but does not result in shell access.

**Details:**

Also refer #4212, #3315, #4223, #4613 (Similar issues)

```
export  vch=vic4;
vic-machine-darwin create \
	--target https://192.168.1.9/Goddard \
	--user administrator@home.local \
	--password 'VMware1!' \
	--name ${vch} \
	--tls-cname "${vch}.home.local" \
	--image-store esx-a-ssd  \
	--bridge-network bridge-${vch} \
	--compute-resource BasementLab \
	--thumbprint "29:03:72:8B:73:ED:D8:B6:D7:36:E8:EE:4F:1D:91:DE:9A:2C:3D:4A"  \
	--bridge-network-range 172.16.0.0/12  \
	--management-network Management \
	--management-network-gateway 0.0.0.0/0:192.168.1.254 \
	--management-network-ip 192.168.1.17/24  \
	--dns-server 192.168.1.1  \
	--public-network VMNet \
	--organization tscanlan   \
	--registry-ca harbor-ca.crt   \
	--volume-store "esx-a-ssd/${vch}-volumes:default"  \
	--timeout 10m

export DOCKER_HOST=tcp://${vch}.home.local:2376
export DOCKER_CERT_PATH=/Users/tscanlan/projects/vic-validataion/${vch}/
export DOCKER_TLS_VERIFY=1
export COMPOSE_TLS_VERSION=TLSv1_2

cmd="docker volume create \
	--opt VolumeStore=default \
	--opt Capacity=2GB \
	--name test"

while ! `$cmd`; do
    sleep 1
done

docker run -it busybox sh
```

Results in:

```
$docker run -it busybox sh
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
7520415ce762: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f
Status: Downloaded newer image for library/busybox:latest
<hangs here without dropping to shell>
```

The container has started:

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
04b908e5fc24        busybox             "sh"                13 minutes ago      Up 13 minutes                           zen_euler
```

Hitting ctl-c and re-running the run command gets me to a shell:

```
$ docker run -it busybox sh
/ #

```

**Acceptance Criteria:**

The docker run should result in being at the busy box shell.

#For bug reports, please include the information below:

**VIC version:**

vic-machine-darwin version v1.1.0-rc5-9735-032392c

**Logs:**

[container-logs (6).zip](https://github.com/vmware/vic/files/934662/container-logs.6.zip)

**Comment by chengwang86** [comment] 2017-04-19 15:04
It looks like a `docker attach` error.

Here is the log snippet from docker-persona:
```
Apr 19 2017 13:02:29.657Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach:1521] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:29.657Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/retry.Do:38]
Apr 19 2017 13:02:30.847Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SubscribeToEvents:277]
Apr 19 2017 13:02:30.847Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SubscribeToEvents:277] [20.247µs] 
Apr 19 2017 13:02:30.868Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:756] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:30.868Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/retry.Do:38]
Apr 19 2017 13:02:43.106Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.Do:38] [12.237833097s] 
Apr 19 2017 13:02:43.106Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:756] [12.237895698s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.107Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:215]
Apr 19 2017 13:02:43.107Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:215] [8.918µs] 
Apr 19 2017 13:02:43.111Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerResize:586] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Resize:829] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Resize:829] [316.734µs] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerResize:586] [367.284µs] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR container attach: stdout (04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149): Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
Apr 19 2017 13:03:00.845Z ERROR container attach: stdin (04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149): context canceled
Apr 19 2017 13:03:00.845Z INFO  returning from stdin as context canceled somewhere else
Apr 19 2017 13:03:00.845Z ERROR container attach: stderr (04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149): Server error from portlayer: context canceled
Apr 19 2017 13:03:00.845Z INFO  returning from stdin as context canceled somewhere else
Apr 19 2017 13:03:00.845Z INFO  cleaned up connections to 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149. Checking errors
Apr 19 2017 13:03:00.845Z ERROR container attach error: Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
Apr 19 2017 13:03:00.845Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc4201d10c0), statusCode:500}
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.Do:38] [31.187973028s] 
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerAttach:1521] [31.188024285s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR Handler for POST /v1.25/containers/04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149/attach returned error: Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
Apr 19 2017 13:03:00.845Z ERROR Error Hijacking: Server error from portlayer: &{0 } (*models.Error) is not supported by the ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
Apr 19 2017 13:08:24.597Z ERROR stdin err: io: read/write on closed pipe
```

From portlayer:
```
Apr 19 2017 13:02:43.111Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:89] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:80] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:80] [10.616µs] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:89] [49.888µs] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:02:43.111Z WARN  No resize connection found (id: 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149): no such connection
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:80] [29.999312748s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:89] [29.999322002s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*InteractionHandlersImpl).ContainerGetStdoutHandler:263] [29.999335077s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z INFO  attach connector:  Connection not found yet for 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z DEBUG attach connector:  Giving up on connection for 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z INFO  attach connector:  Connection not found yet for 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:80] [30.000076019s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:89] [30.000086484s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*InteractionHandlersImpl).ContainerGetStderrHandler:307] [30.000126617s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z DEBUG attach connector:  Giving up on connection for 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z INFO  attach connector:  Connection not found yet for 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Connector).Get:80] [30.000077548s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/attach.(*Server).Get:89] [30.00008306s] 04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149
Apr 19 2017 13:03:00.845Z ERROR attach connector: Connection not found error for id:04b908e5fc249d7791d1a063a1b30624bab7d4a1eb2dc0243b0e839249895149: context deadline exceeded
```

**Comment by hickeng** [comment] 2017-04-19 22:44
@tompscanlan We have made significant changes to this set of code paths to address a collection of issues - they are currently in #4339 and awaiting clean CI and reviews before merge. My suggestion would be take a new build after that PR merges (which should be before the end of this week) and see if that addresses your issues. If not then we can dig further, but with the up-to-date code which should simplify the process sigificantly. Is that viable for you?

**Comment by caglar10ur** [comment] 2017-04-28 20:03
I think this could be still an issue on a slow system. docker run calls attach followed by start and our attach code has a 30 sec. timeout. If the VM takes more than 30 sec. to start then we will end up with a very similar situation. Docker run returns back to shell and docker ps shows that container is running.  Subsequent attach succeeds.

**Comment by hickeng** [comment] 2017-04-28 20:48
@caglar10ur I don't know if we can resolve this until we move away from timeouts completely.

**Comment by caglar10ur** [comment] 2017-04-28 22:45
@hickeng agreed, but I think we can handle it a bit better by showing an error os something :) I managed to reproduce the problem - rarely - by adding sleeps to tether code. stdout timeouts and returns an error but stdin manages to get the connection so we just hang hung. The singleflight supposed to solve this but I think we are just getting unlucky here and our concurrent calls just getting scheduled serially and missing the cache twice and then the 3rd one manages to get the connection. https://github.com/golang/groupcache/blob/master/groupcache.go#L238 has a similar logic to deal with that.

**Comment by caglar10ur** [comment] 2017-04-30 18:39
(withdrawn from it and putting back to to-do as I won't be able to work on this sprint due to PTO)

**Comment by emlin** [comment] 2017-05-15 18:54
@hickeng @caglar10ur mentioned the mismatch between stdout, stdin and stderr, because some of them could get stream connected, but some of them might not.
I think we could avoid that to use channel, instead of waitgroup in persona code, to fail the operation for any channel attachment failure.

**Comment by emlin** [comment] 2017-05-16 02:57
Reproduced with tether sleep 30 seconds, but the docker run failed with error: `docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://10.192.171.116/sdk: context deadline exceeded.`

in this way, all streams failed to connect before tether is started, so docker run returned, but container stay in `starting` status, because attach failed.
then user cannot attach directly because container is not running status.

if it happens in user environment, the solution is to stop container, and restart container with -ai, or after it's started, rerun attach command. (this solution will work after issue #4296 is fixed)

@caglar10ur did you ever reproduce the hung issue after your code change?

**Comment by emlin** [comment] 2017-05-18 14:19
Move this back to TODO, for do not have time to work on this in this sprint.
The current status is we have timeout to return from portlayer and tether connection issue, but the three stream connections (stdin, stdout, stderr) in persona are not atomistic.
This issue is to fix the atomic issue in persona, to make sure docker client does not hung there if some streams are connected, but others are not.

**Comment by emlin** [comment] 2017-05-18 14:22
btw, I didn't reproduce this hung issue, but reproduced the timeout issue for all streams. In that case, docker run failed for launching service, because attach quit before tether finished initialization. So container stuck in starting status.
the starting container issue is fixed in #4296

**Comment by gigawhitlocks** [comment] 2017-05-24 23:33
Finally narrowed this down, leaving this note/status update for anyone following along and also as a reference for myself.

The error stems from bad error handling in the Personality. I haven't quite figured out just yet why the caller isn't returning the error message back to the user, or why it doesn't signal to the docker client that something has gone wrong (until it times out), but forcibly returning an error in `container.go:containerAttach` causes the client to hang until it times out and leaves the container in an indeterminate `Starting` state. 

So it appears that what happened here is that there was an i/o error on the container (visible in tether logs) and that bubbled to the portlayer, which didn't recognize the error (there are a couple of types we try to detect and do something special for, but this one came out of the Swagger stubs as a generic error type) and returned it anyway, that went back up to the personality, which then doesn't properly handle the error, and the bad behavior visible to the user was seen.

Fixing this will mean figuring out where the ball is dropped on that error between `containerAttach` and the response to the docker client, and I'll be figuring that out ASAP.

**Comment by gigawhitlocks** [comment] 2017-05-24 23:34
@sflxn or @caglar10ur : if either of you have any insight into the above, any and all help here is appreciated

**Comment by gigawhitlocks** [comment] 2017-05-25 20:47
Traced the call into vendored Docker code. Docker code tries to hijack the HTTP stream a second time after we've already hijacked it, fails, doesn't recognize the error, and then it looks like it hangs until the context times out.

**Comment by sflxn** [comment] 2017-05-26 17:09
@gigawhitlocks This is a very involved issue.  Pre-exec code, this occurred when the ssh server could not establish a connection, waiting on the tether to finish it's initial work.  Have you tried the latest code on Nimbus (a slow connection) with a big image like ubuntu?  If this is still an issue post-exec code, this might be something for @caglar10ur to look at.

**Comment by gigawhitlocks** [comment] 2017-05-26 17:19
I have been doing all of my testing on Nimbus, although using smaller images.

**Comment by gigawhitlocks** [comment] 2017-05-26 19:09
Also unable to reproduce with larger images -- ubuntu, tomcat, etc, work fine.

**Comment by hickeng** [comment] 2017-06-07 19:58
Maybe seen in #5125 ?

**Comment by mhagen-vmware** [comment] 2017-07-06 15:58
Seen here:
https://ci.vcna.io/vmware/vic/12084

**Comment by caglar10ur** [comment] 2017-08-14 21:05
Will attack this as a tech debt (Remove all timeouts from the codebase)

**Closed by caglar10ur** 2017-08-14 21:05 UTC
Labels: kind/bug, kind/bug/no-repro, kind/customer-found, priority/high
