### ISSUE TITLE
Unrecognized input header: 69 on docker logs command during docker stop test

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#3682] opened 2017-01-19 20:12 UTC
From build:  
https://ci.vmware.run/vmware/vic/7586

This appears to be the calls from docker-personality.log, but I don't see any particular errors here, I wonder if the error came from the client because it didn't like something we sent back?
```
time="2017-01-19T17:46:46Z" level=debug msg="Calling GET /v1.21/containers/f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615/logs?stderr=1&stdout=1&tail=all" 
time="2017-01-19T17:46:46Z" level=debug msg="Client and server don't have the same version (client: 1.11.2, server: 1.22)" 
time=2017-01-19T17:46:46.718247879Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerLogs:975] 
time=2017-01-19T17:46:46.718333453Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerLogs:425] 
time=2017-01-19T17:46:46.809507266Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerLogs:425] [91.167716ms]  
time=2017-01-19T17:46:46.809528511Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerLogs:975] [91.278576ms]  
time="2017-01-19T17:46:46Z" level=debug msg="Calling POST /v1.21/containers/f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615/stop?t=10" 
time="2017-01-19T17:46:46Z" level=debug msg="Client and server don't have the same version (client: 1.11.2, server: 1.22)" 
time=2017-01-19T17:46:46.856067542Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop:801] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time=2017-01-19T17:46:46.856081681Z level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/retry.Do:38] 
time=2017-01-19T17:46:46.856138974Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop:463] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time=2017-01-19T17:46:46.904854777Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).IsRunning:540] 
time=2017-01-19T17:46:46.916322364Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:136] 
time=2017-01-19T17:46:46.916345967Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:176] 
time=2017-01-19T17:46:46.916352895Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:176] [5.479µs]  
time=2017-01-19T17:46:46.916358577Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:136] [37.931µs]  
time="2017-01-19T17:46:46Z" level=debug msg="Docker inspect - network settings = &types.NetworkSettings{NetworkSettingsBase:types.NetworkSettingsBase{Bridge:\"\", SandboxID:\"\", HairpinMode:false, LinkLocalIPv6Address:\"\", LinkLocalIPv6PrefixLen:0, Ports:nat.PortMap{}, SandboxKey:\"\", SecondaryIPAddresses:[]network.Address(nil), SecondaryIPv6Addresses:[]network.Address(nil)}, DefaultNetworkSettings:types.DefaultNetworkSettings{EndpointID:\"\", Gateway:\"\", GlobalIPv6Address:\"\", GlobalIPv6PrefixLen:0, IPAddress:\"\", IPPrefixLen:0, IPv6Gateway:\"\", MacAddress:\"\"}, Networks:map[string]*network.EndpointSettings{\"bridge\":(*network.EndpointSettings)(0xc420820c00)}}" 
time=2017-01-19T17:46:46.916411847Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).IsRunning:540] [11.559032ms]  
time="2017-01-19T17:46:46Z" level=debug msg="UnmapPorts: map[]" 
time=2017-01-19T17:46:46.952348541Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:392] 3f52c441fd23dececaf037410b569a69 
time=2017-01-19T17:46:58.610086486Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:392] [11.657608744s] 3f52c441fd23dececaf037410b569a69 
time=2017-01-19T17:46:58.615634504Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop:463] [11.759492181s] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time="2017-01-19T17:46:58Z" level=debug msg="Will not try again. Operation succeeded" 
time=2017-01-19T17:46:58.615730814Z level=debug msg=[ END ] [github.com/vmware/vic/pkg/retry.Do:38] [11.759647176s]  
time=2017-01-19T17:46:58.615911933Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop:801] [11.759669504s] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time="2017-01-19T17:46:58Z" level=debug msg="Calling GET /v1.21/containers/f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615/json" 
time="2017-01-19T17:46:58Z" level=debug msg="Client and server don't have the same version (client: 1.11.2, server: 1.22)" 
time=2017-01-19T17:46:58.666927872Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerInspect:910] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time="2017-01-19T17:46:58Z" level=debug msg="Found \"f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615\" in cache as \"f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615\"" 
time=2017-01-19T17:46:58.890571076Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:136] 
time=2017-01-19T17:46:58.890621742Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:176] 
time=2017-01-19T17:46:58.890630898Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:176] [7.263µs]  
time=2017-01-19T17:46:58.890637522Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:136] [67.918µs]  
time="2017-01-19T17:46:58Z" level=debug msg="Docker inspect - network settings = &types.NetworkSettings{NetworkSettingsBase:types.NetworkSettingsBase{Bridge:\"\", SandboxID:\"\", HairpinMode:false, LinkLocalIPv6Address:\"\", LinkLocalIPv6PrefixLen:0, Ports:nat.PortMap{}, SandboxKey:\"\", SecondaryIPAddresses:[]network.Address(nil), SecondaryIPv6Addresses:[]network.Address(nil)}, DefaultNetworkSettings:types.DefaultNetworkSettings{EndpointID:\"\", Gateway:\"\", GlobalIPv6Address:\"\", GlobalIPv6PrefixLen:0, IPAddress:\"\", IPPrefixLen:0, IPv6Gateway:\"\", MacAddress:\"\"}, Networks:map[string]*network.EndpointSettings{\"bridge\":(*network.EndpointSettings)(0xc4208212c0)}}" 
time="2017-01-19T17:46:58Z" level=debug msg="ContainerInspect json config = &{Hostname:f6de8b305041 Domainname: User: AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] PublishService: Tty:false OpenStdin:false StdinOnce:true Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Cmd:[sh -c trap 'echo StopSignalUSR1' USR1; echo READY; while true; do sleep 1; done] ArgsEscaped:false Image:busybox Volumes:map[] WorkingDir: Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal:USR1}\n" 
time="2017-01-19T17:46:58Z" level=debug msg="Docker inspect - network settings = &types.NetworkSettings{NetworkSettingsBase:types.NetworkSettingsBase{Bridge:\"\", SandboxID:\"\", HairpinMode:false, LinkLocalIPv6Address:\"\", LinkLocalIPv6PrefixLen:0, Ports:nat.PortMap{}, SandboxKey:\"\", SecondaryIPAddresses:[]network.Address(nil), SecondaryIPv6Addresses:[]network.Address(nil)}, DefaultNetworkSettings:types.DefaultNetworkSettings{EndpointID:\"\", Gateway:\"\", GlobalIPv6Address:\"\", GlobalIPv6PrefixLen:0, IPAddress:\"\", IPPrefixLen:0, IPv6Gateway:\"\", MacAddress:\"\"}, Networks:map[string]*network.EndpointSettings{\"bridge\":(*network.EndpointSettings)(0xc4208212c0)}}" 
time=2017-01-19T17:46:58.890820916Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerInspect:910] [223.892721ms] f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 
time="2017-01-19T17:46:58Z" level=debug msg="Calling GET /v1.21/containers/f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615/logs?stderr=1&stdout=1&tail=all" 
time="2017-01-19T17:46:58Z" level=debug msg="Client and server don't have the same version (client: 1.11.2, server: 1.22)" 
time=2017-01-19T17:46:58.949110874Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerLogs:975] 
time=2017-01-19T17:46:58.949199197Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerLogs:425] 
time=2017-01-19T17:46:58.950102231Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).StreamContainerLogs:425] [902.858µs]  
time=2017-01-19T17:46:58.950112102Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerLogs:975] [1.001585ms]  
```

[integration_logs_7586_358f257ce38d6d0565ceaa8b9728f48912a269b8.zip](https://github.com/vmware/vic/files/717654/integration_logs_7586_358f257ce38d6d0565ceaa8b9728f48912a269b8.zip)

**Comment by hmahmood** [comment] 2017-01-19 20:16
```
11:51:43.148	INFO	Running command 'docker -H dhcp-192-168-31-141.ci.drone.local:2376 --tls logs f6de8b305041f839aa3cb238cd3deb38466be92ad0b621499b911342b95d4615 2>&1'.	
11:51:43.476	INFO	${rc} = 1	
11:51:43.476	INFO	${output} = Unrecognized input header: 69
```

Could be related to: https://github.com/docker/docker/issues/21902

**Comment by mlh78750** [comment] 2017-01-19 20:17
ASCII 69 == 'E'

Likely where it was expecting something we're sending the text "Error..." or something else that starts with a cap E.

**Comment by hmahmood** [comment] 2017-01-20 16:38
See here: https://ci.vmware.run/vmware/vic/7595

**Comment by anchal-agrawal** [comment] 2017-02-09 19:53
The original issue was caused by a portlayer container cache miss in the [`GetContainerLogsHandler`](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go#L342). The portlayer logs for both build failures above show no trace for the `LogReader` func which is called in `GetContainerLogsHandler` [here](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go#L357). PL log snippet for the failing container from build 7595:

```
time=2017-01-19T23:12:11.861480585Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:327] 0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f 
time=2017-01-19T23:12:11.861550736Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:327] [69.424µs] 0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f
```

On a successful run, the logs look like:

```
time=2017-01-19T23:11:58.992180781Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:327] 756db05bd037170f770d7cc9cc353f36bdc0fe44624a9c706083dc64e0c2f274 
time=2017-01-19T23:11:58.992225109Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).LogReader:398] 756db05bd037170f770d7cc9cc353f36bdc0fe44624a9c706083dc64e0c2f274 
time="2017-01-19T23:11:58Z" level=debug msg="get vm properties [runtime.host config] of vm VirtualMachine:18101" 
time="2017-01-19T23:11:58Z" level=debug msg="properties: [runtime.host config summary.runtime.connectionState]" 
time=2017-01-19T23:11:58.992835164Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).RefreshFromHandle:307] 8b48d361edb2c49de14fc7cafa43b750 
time="2017-01-19T23:11:59Z" level=info msg="pulling anjunabeats-756db05bd037170f770d7cc9cc353f36bdc0fe44624a9c706083dc64e0c2f274/output.log" 
time=2017-01-19T23:11:59.068103236Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).LogReader:398] [75.874676ms] 756db05bd037170f770d7cc9cc353f36bdc0fe44624a9c706083dc64e0c2f274 
time=2017-01-19T23:11:59.068114034Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:327] [75.935493ms] 756db05bd037170f770d7cc9cc353f36bdc0fe44624a9c706083dc64e0c2f274
```

Turns out the failing container was in invalid state and was removed from the cache, thereby causing the cache miss (PL logs):
```
time="2017-01-19T23:12:11Z" level=info msg="vm VirtualMachine:18102 is in invalid state" 
time="2017-01-19T23:12:11Z" level=debug msg="Fix invalid state VM: VirtualMachine:18102" 
time=2017-01-19T23:12:11.638067017Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).RefreshFromHandle:307] e742f273c1ece420c8e79fa8e867a7b2 
time="2017-01-19T23:12:11Z" level=debug msg="Current ChangeVersion: 2017-01-19T23:12:01.729364Z" 
time=2017-01-19T23:12:11.638090521Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).RefreshFromHandle:307] [23.301µs] e742f273c1ece420c8e79fa8e867a7b2 
time=2017-01-19T23:12:11.638096276Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] [220.852105ms] 0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f 
time="2017-01-19T23:12:11Z" level=debug msg="Get vm properties [summary.config summary.runtime.host resourcePool parentVApp]" 
time="2017-01-19T23:12:11Z" level=debug msg="Unregister VM abgt250-0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f" 
time="2017-01-19T23:12:11Z" level=debug msg="Found 3 subscribers to vsphere.VMEvent: Removed abgt250-0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f on vic-esx-05.ci.drone.local from ha-datacenter" 
time="2017-01-19T23:12:11Z" level=debug msg="Event manager calling back to exec" 
time="2017-01-19T23:12:11Z" level=debug msg="Container(0d898769cfeaa42c48c2e6c53233853b02502a2d5ab7876d6e8cb76706c2f23f) Removed via event activity" 
```

This has since been fixed in #3722. We now don't remove a container from the PL cache if it's in fixing state, so we won't see this particular failure anymore.

To investigate the `Unrecognized input header: 69` error further, I commented out the entirety of `GetContainerLogsHandler` and replaced it with 

```go
func (handler *ContainersHandlersImpl) GetContainerLogsHandler(params containers.GetContainerLogsParams) middleware.Responder {
	defer trace.End(trace.Begin(params.ID))
	return containers.NewGetContainerLogsNotFound()
}
```

to see what happens when we get a legitimate PL cache miss. This has uncovered another issue in the personality's [`ContainerLogs`](https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container.go#L1006) func. It seems that returning _any_ error (even `fmt.Errorf(...)`) from `ContainerLogs` [here](https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container.go#L1036) causes the Docker CLI to say:

```
$ sudo docker -H 192.168.77.225:2376 --tls run -d busybox sh -c "echo hello"
692dbb02037e737bf46d1a3252909e600e3202893766fb7c6695411299baed16
$ sudo docker -H 192.168.77.225:2376 --tls logs 6
Unrecognized input header: 69
```

Seems that the output stream is getting messed up somehow. FWIW, it looks like Docker [doesn't return an error](https://github.com/docker/docker/blob/master/daemon/logs.go#L97) if there's an error streaming logs.

**Comment by sflxn** [comment] 2017-02-09 22:46
Docker does return errors for logs.  The only way to figure out how they're returning errors is to look at their code.

I just looked at the ContainerLogs() function.  It could be that we need to close the outstream when we return the cache miss error.

**Comment by sflxn** [comment] 2017-02-09 23:27
After some discussion and examining the code a little more, I don't believe this is because of the outstream after all.

**Closed** 2017-02-13 22:37 UTC
Labels: kind/bug, priority/high

**Comment by alexanderkjeldaas** [comment] 2017-03-19 15:05
I'm getting `Unrecognized input header: 69` for most services on 17.03.0 when running `docker service logs <something>`.  Are you sure this is fixed?

**Comment by anchal-agrawal** [comment] 2017-03-19 18:38
@alexanderkjeldaas which version of VIC are you running? VIC Engine 0.8.0 doesn't have this fix. Please use the [0.9.0 release](https://github.com/vmware/vic/releases/tag/v0.9.0). Also, VIC doesn't support `docker service` commands yet. VIC Engine 0.9.0 supports Docker client v1.13 and Docker API v1.25. You can view the list of supported commands in 0.9.0 [here](https://vmware.github.io/vic-product/assets/files/html/latest/vic_app_dev/container_operations.html).

Nevertheless, if you're using VIC Engine 0.9.0 and are able to reproduce the issue with `docker logs`, please post your `vic-machine create` command and the log bundle. Instructions for grabbing the log bundle are [here](https://vmware.github.io/vic-product/assets/files/html/latest/vic_admin/log_bundles.html). Thanks!
