### ISSUE TITLE
Add option to specify distributed switch when port group name is ambiguous

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#6628] opened 2017-10-25 14:46 UTC
@philosifer commented on [Thu Sep 07 2017](https://github.com/vmware/vic-product/issues/747)

VIC Product version:

vic-v1.1.1.56a309fb.ova

Deployment details:

VSCA 6.5 u1 and ESXi 6.5u1

Steps to reproduce:

vic-machine create cannot handle ambiguous port group names

Actual behavior:

Attempting to use a port group name that is identical under multiple distributed switches on the same vcenter results in an error.

Sep  7 2017 10:44:28.408+01:00 ERROR Error checking network for --public-network: ambiguous network dvPortGroup-vLAN100

This is at odds with that same port name being suggested as a possible value

Sep  7 2017 10:44:27.717+01:00 INFO  Suggested values for --public-network:
Sep  7 2017 10:44:27.717+01:00 INFO    "dvPortGroup-vLAN100"

Expected behavior:

Add an option to specify the dvswitch name to remove the ambiguity

**Comment by andrewtchin** [comment] 2017-12-14 21:54
need to see if this applies to other networking related flags

**Comment by galindro** [comment] 2018-08-09 20:07
@andrewtchin any return about this issue? I'm using vic 1.4.2 and this problem still occurs. It is preventing us from use VIC in our Vsphere infrastructure:

```bash
ERRO[0005] --------------------                         
ERRO[0005] Error checking network for --public-network: ambiguous network V1002NPD 
ERRO[0005] Error checking network for --client-network: ambiguous network V1002NPD 
ERRO[0005] Error checking network for --management-network: ambiguous network V1002NPD 
ERRO[0005] Error adding container network "v1242VMware": ambiguous network v1242VMware 
ERRO[0005] Create cannot continue: configuration validation failed 
ERRO[0005] --------------------                         
ERRO[0005] vic-machine-linux create failed: validation of configuration failed
```

**Comment by mark-wolfe** [comment] 2018-08-09 21:49
I ran into this while deploying a test instance of VIC this week.  I can create some uniquely named, but otherwise duplicate, portgroups to move testing along but we're unlikely to do that to put VIC into production.

**Comment by galindro** [comment] 2018-08-10 21:58
I've renamed the port group inside my distributed switch to workarround this limitation.

**Comment by yuyangbj** [comment] 2018-08-27 02:16
@zjs @hickeng for this issue, per my understanding, we can fix it using following methods:

1> Using the mod id instead of name
2> Accept the format [<dvs name>/]<port group name> to limit the port group

I think the second one is better because mod id does not make sense to customer. Which one do you guys prefer? Any comments or advice?

**Comment by zjs** [comment] 2018-08-27 17:16
I think option 2 makes sense for the CLI, where everything is currently name-based.

For the API, we should allow both options. (We _should_ already support option 1 there, as we allow everything to be specified by name or ID, and the work to support option 2 may be entirely addressed by the work to support option 2 for the CLI. However, the various options will need to be _tested_ separately.)

**Comment by yuyangbj** [comment] 2018-08-29 09:19
@zjs using the latest build, I did not reproduce the error. For vSphere, we cannot create port group using same name in one datacenter. So I did an assumption that the customer has more than one datacenter. But we must specify the datacenter in --target if there are more than one in latest build. 

I checked the code, we list the networkFolder in one datacenter and check if the public/client/management network is valid in networkFolder, so we should not see the ambiguous error.

 @andrewtchin could you please confirm if you still see this error using latest build?

**Comment by yuyangbj** [comment] 2018-08-29 09:34
@galindro I cannot reproduce what @andrewtchin reported, could you please explain more for your error scenario? V1002NPD is your distributed port group?

**Comment by galindro** [comment] 2018-08-29 16:57
Hi @yuyangbj . 

I have a standard network called V1002NPD and a distributed port group called V1002NPD too.

Check the bellow prints:

![image](https://user-images.githubusercontent.com/4622097/44802914-4cb0d680-ab93-11e8-9f29-cbd56c452d3c.png)

![image](https://user-images.githubusercontent.com/4622097/44802892-3c98f700-ab93-11e8-9a5e-eb1aab4bbc3f.png)

**Comment by yuyangbj** [comment] 2018-08-30 02:35
@galindro Thanks for the quick response! I will fix it.

**Comment by mark-wolfe** [comment] 2018-08-30 14:54
@yuyangbj Did you try to create duplicate port groups in one datacenter in vCenter 6.5 or 6.7?

I tested, and I am able to do so in 6.5 but not 6.7.

We have duplicate portgroup names, on different VDSs, in one datacenter, in vSphere 6.0 and 6.5.

So for me, being able to specify standard vs distributed switch type will not resolve the issue for me.

Allowing the / delimiter to specify the switch name and port group name seems like a better fix to me as it would address duplicate port group names across multiple VDSs as well as across a VSS and a VDS.

![image](https://user-images.githubusercontent.com/25436399/44859704-acb28600-ac42-11e8-81b1-253811177445.png)

**Comment by zjs** [comment] 2018-08-30 16:40
Thanks for the additional information and screenshot, @mark-wolfe, that's really helpful!

> Allowing the / delimiter to specify the switch name and port group name seems like a better fix to me as it would address duplicate port group names across multiple VDSs as well as across a VSS and a VDS.

For your use case, would it be okay if you needed to supply the full path to the port group name (e.g., `lab.networks/DSwitch.lab.data/lab-nat`)? (Omitting the datacenter, as that's already included in the `--target` argument.)

Allowing networking entities to be specified by name or full inventory path seems like it might be most consistent with other `vic-machine` arguments.

**Comment by mark-wolfe** [comment] 2018-08-30 17:58
I would lean toward requiring the minimum amount of input needed to uniquely identify the target port group, which would be the switch name and portgroup name.  As you can't create multiple switches with the same name in a datacenter (regardless of folder structure), folders aren't needed to uniquely identify the target portgroup.

If including folders aligns better with the other vic-machine arguments, that would be fine too.  

Does `--target` require a folder name if the target datacenter resides inside a folder?  The documentation doesn't mention it.

I'd mirror the format of `--target`, whether it uses a folder path or not.

As long as I can deploy the VCH and the documentation lets me know what input is expected, either option makes sense to me.

**Comment by yuyangbj** [comment] 2018-09-04 09:09
@mark-wolfe @zjs Thanks for the summary. I think the created duplicate port group name is not because you used VC 6.5 not VC 6.7, the root cause is you create a network folder for different dvs in one datacenter.

I changed the code to support full inventory path for distributed network or standard network. But note, as the inventory path does not container the dvs name, so the distributed port group will be used if you have same name between standard network and distributed port group. If you want to use the standard network, please create a network folder to differentiate them. The accept format will be like below:

/<datacenter>/network/<network-folder>/<distributed portgroup name>(standard network instead)
<network-folder>/<distributed portgroup name>(standard network instead)

**Closed** 2018-10-30 03:59 UTC
Labels: kind/enhancement, priority/p2, severity/2-serious, source/customer, team/lifecycle
