### ISSUE TITLE
"docker run ubuntu" will cause inconsistent container status

### ISSUE THREAD

**Issue by thefallentree** [vmware/vic#3599] opened 2017-01-13 23:33 UTC
With release 0.8.0 , if  just do docker run ubuntu (Note the lacking of usual -it) , the Container VM will start,  and power itself off correctly, however the VCH will still think this VM is up,  docker ps will show "up" status, and docker kill will fail, because the machine is already powered off.

**Comment by chengwang86** [comment] 2017-01-17 15:33
@thefallentree I tried your cmds but couldn't reproduce this issue. 
1. Could you please upload your log bundle? 
2. Were you able to reproduce it?
3. What is the cmd you use to create the VCH?

**Comment by mhagen-vmware** [comment] 2017-01-23 15:44
@thefallentree Can you upload your log bundle for us?

**Comment by cgtexmex** [comment] 2017-02-08 05:05
@thefallentree I have tested this and am unable to recreate the issue.  I've tested with the following docker versions and vSphere configurations:

- docker 1.11 --> standalone ESXi 6
- docker 1.11 --> 3 node vSphere 6.5 Cluster
- docker 1.12 --> standalone ESXi 6
- docker 1.12 --> 3 node vSphere 6.5 Cluster

All of the above scenarios were tested with the vic v0.8.0 binary and our current top of tree build.  I'm closing the issue, but if you encounter it again please reopen the issue and upload a log bundle and details.

**Closed by cgtexmex** 2017-02-08 05:05 UTC
Labels: kind/bug, kind/customer-found, priority/high, status/need-info
