### ISSUE TITLE
Setup a harbor registry for use in our CI

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4076] opened 2017-02-28 21:43 UTC
As a developer of VIC, I should expect our CI system to not choke if docker hub is down.

Acceptance Criteria:  Have a harbor instance running that our CI can use.  Add a some switch into our CI suite that will make a PR build use the harbor instance instead of docker hub.

---

This will not only improve reliability of our builds, it will also significantly increase the speed of our tests since we deploy new VCHs all the time and end up pulling the same docker image over and over for a single test run.

This instance must be accessible publicly so the instance should run in our CI infrastructure and not internal Vmware's infrastructure.

**Comment by mhagen-vmware** [comment] 2017-04-13 17:27
dupe of #4181 using that to track

**Closed by mhagen-vmware** 2017-04-13 17:27 UTC
Labels: area/infra, component/test, priority/medium
