### ISSUE TITLE
Removal of a stopped container results in the datastore not being cleaned

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1313] opened 2016-07-01 13:23 UTC
docker ${params} pull busybox
docker ${params} create busybox ls
docker ${params} start ${container}
docker ${params} rm ${container}

Results in the vm being removed but the datastore doesn't get cleaned up.

**Comment by cgtexmex** [comment] 2016-07-03 19:52
This appears to be caused by the fact that we create a container VM specific log and debug file upon container start -- I believe these are created and managed by the tether.  esx is deleting from disk all the files it's aware of and since it's unaware of those it leaves them behind.

**Comment by corrieb** [comment] 2016-07-07 19:43
NOTE: CLOSING THIS ISSUE MAY CAUSE AN INTEGRATION TEST FAILURE. Please re-enable the test in 1-11-Docker-RM.robot as part of a PR to fix this issue. Please also ensure that the test passes cleanly. If the test needs improving or updating, please address it. Thx

**Comment by hickeng** [comment] 2016-07-14 21:10
@corrieb could you try re-enabling this in your local integration build? I'm in the middle of redeploying dev box but this should now be fixed by #1441

**Comment by corrieb** [comment] 2016-07-14 21:10
@hickeng will do

**Comment by matthewavery** [comment] 2016-09-13 16:46
@corrieb I am closing this after confirming that it is resolved by #1441.

**Comment by andrewtchin** [comment] 2016-09-13 21:02
the build is broken! :trollface:

**Comment by matthewavery** [comment] 2016-09-14 18:18
The test has now be re-enabled in master.

**Closed by matthewavery** 2016-09-14 18:18 UTC
Labels: component/portlayer/execution, kind/bug, kind/bug/p0, kind/note

**Comment by stuclem** [comment] 2016-11-07 18:38
This is fixed. Removing kind/note.
