### ISSUE TITLE
Tether not able to establish connection causes orphaned container VMs (resource leak)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#2491] opened 2016-09-27 17:56 UTC
I have found what I believe is a serious issue.  Sometime, when performing 'docker run -it ...', the tether fails to establish a connection, causing the attach to timeout.  VIC, subsequently "forgets" the existence of the container, yet the container is still running, utilizing CPU and memory space.  However, if we then do docker ps, it sees it, but we cannot inspect it.
1. docker run -it busybox /bin/sh
2. outputs: 'no such container'
3. docker ps
4. outputs: container is in the list
5. docker inspect containerID
6. outputs: 'no such image'

**Comment by sflxn** [comment] 2016-09-27 17:59
[container-logs (1).zip](https://github.com/vmware/vic/files/496330/container-logs.1.zip)
Container log bundle.

**Comment by cgtexmex** [comment] 2016-09-27 18:03
Isn't this a case of it being removed from the persona docker cache?  Thus the 'no such container' errors?

**Comment by sflxn** [comment] 2016-09-27 18:04
@cgtexmex I'm not sure.  Investigating the code and looking for that removal, but I am not seeing it.

**Comment by hickeng** [comment] 2016-09-27 19:33
A lossiness check is still present in the handshake code (artifact from tracking down a bug in the go term package). This violates the client as initiator rule in the handshake code.

This can be taken out - I'd prefer it if the code remains, but blocked out with either constant or dynamic check for debug (dynamic would be the debug setting for the VHC in the config). If dynamic it should be when debug > 1 as it's a change to behaviour:

const option:
```
const debug = false
if debug {
   ....
}
```

pkg/serial/handshake.go

**Comment by chengwang86** [comment] 2016-09-27 21:04
Is this similar to #1821  no such image error on docker run ?

**Comment by mdubya66** [comment] 2016-09-28 15:57
Marking as a bug and adding to the GA Milestone.

**Comment by chengwang86** [comment] 2016-09-28 16:33
I observed an interesting thing:

After I create a fresh new container, I do "docker start." 
After "**ContainerStart**" returns and before "**Established connection with container VM: container_ID**" is done, if I do "docker attach," the cmd would 

(i) hang for several sec and succeed finally, 
or 
(ii) return with "**Error: No such container container_ID**". 

For (ii), if I do "docker ps -a", the status of the container is "running". But if I do "inspect", it would not be able to find the container. However, **(ii) is not always reproducible**. 

(ii) is quite similar to your issue IMO. I guess it might be because that neither "docker start"(ContainerStart) nor "docker attach"(ContainerAttach) wait for the connection to the Tether process to be established. 

So after "docker start" or "docker run", the status of the container is changed to "running"; but actually we don't know whether the container is initialized successfully by vSphere or whether the tether process is started and connected.

This is not an issue of the vSphere API. I think vic needs a certain mechanism to check the actual initialization status of the container and tether.

**Comment by matthewavery** [comment] 2016-09-30 15:01
potentially also related to #2531

**Comment by hickeng** [comment] 2016-09-30 15:22
It sounds as though there is a create path where the container doesn't get entered into the personality container cache, but is still present in vsphere.
@chengwang86 If you see (ii) again, please can you attach a log bundle to the issue so we can discover which path isn't populating the cache - we could potentially do it via inspection, but logs should be faster and easier.

**Comment by chengwang86** [comment] 2016-09-30 15:28
@hickeng Sure, I will try to reproduce it and save the log bundle.

**Comment by carsonpadawon** [comment] 2016-10-06 16:43
I have seen this in my lab and with a customer that is testing out the VIC engine code.  I have attached the customer's log bundle.

[container-logs.zip](https://github.com/vmware/vic/files/514350/container-logs.zip)

@hickeng please let me know if you need any more information from/about the customer environment.

**Comment by hickeng** [comment] 2016-10-08 02:25
@carsonpadawon all of these problems derive from the interactive command channel (network serial port) not being established between the container VM and the appliance.

Check the basics:
1. the configuration of the IP in the network serial port for the container VM
2. that it's possible to open an outbound port on 2377 on the host the containerVM was powered on on

**Comment by emlin** [comment] 2016-11-07 16:47
Tried to block tether connection by enable host firewall after vch deployment, the container vm missing issue is already fixed.
I also checked the container.go and container_proxy.go, they are not trying to delete container incorrectly. So I assume this bug is fixed by other PRs.

**Closed by emlin** 2016-11-07 16:47 UTC
Labels: area/docker, component/docker-api-server, component/tether, kind/bug
