### ISSUE TITLE
Cannot name/allias the external network as 'container'

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic#7711] opened 2018-04-11 20:45 UTC
#For bug reports, please include the information below:

**VIC version:** 1.3.1

x.y.z / master / commit ID

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?
Created using wizard

**Steps to reproduce:**
While creating a VCH, name/alias the Container network as 'container'.
While creating the container, use --network=container to attach it to the container network

I suspect, the issue will be similar for the case where name of container network is 'host'. In previous releases of VIC, we were specifying network mode thorough the --net command which might be causing the issue

**Actual behavior:**
$ docker --tls run -d -p 80 --network=container nginx
$ docker: Error response from daemon: --net: invalid net mode: invalid container format container:<name|id>.

**Expected behavior:**
$ docker --tls run -d -p 80 --network=container nginx
A container is created and attached to the container network. 

**Logs:**
Let me know if logs are required as this issue is reproducible pretty easily

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by rogeliosanchez** [comment] 2018-04-18 00:28
Pinging @sgairo for further triage/labeling/estimation.

**Comment by mdubya66** [comment] 2018-04-18 21:39
This is the same behavior as with docker
```(mwilliamson) ib-aus-office-195:~/vic/src/github.com/vmware/vic-ui/tests (master)$ docker run -d -p 80 --network=container nginx
docker: Error response from daemon: Invalid network mode: invalid container format container:<name|id>.
See 'docker run --help'.```

Closing as not a bug

**Closed by mdubya66** 2018-04-18 21:39 UTC
Labels: kind/bug, priority/p2, resolution/not-a-bug, team/container
