### ISSUE TITLE
Failed blueprint provision leaves template network in an un-removable state

### ISSUE THREAD

**Issue by michaelschlies** [vmware/vic#6642] opened 2017-10-27 02:40 UTC
**VIC version:**

1.2.1

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

```
./vic-machine-linux create --target [vsphere ip] --user [username] \
 --thumbprint [thumbprint] --client-network Inside --no-tls --public-network ContainerRoutable \
 --bridge-network Containers --image-store vSphereDS --name vch-app-host --volume-store \
vSphereDS:default --container-network ContainerRoutable:public --container-network-firewall \
ContainerRoutable:open --client-network-ip 192.168.1.231/23 --dns-server 192.168.0.1
```

**Steps to reproduce:**
I created a multi-container application template for Ghost including _/ghost and _/mysql, a connection for ghost -> public, ghost -> "db-network" (network added in VIC designer), and mysql -> "db-network". 

```yaml  
---
name: "Ghost"
components:
  ghost:
    type: "App.Container"
    data:
      name: "ghost"
      image: "registry.hub.docker.com/library/ghost"
      _cluster: 1
      volumes:
      - "ghost_data:/var/lib/ghost"
      hostname: "ghost"
      networks:
      - name: "db-network"
      - name: "public"
      publish_all: false
      restart_policy: "no"
  public:
    type: "App.Network"
    data:
      name: "public"
      external: true
  db-network:
    type: "App.Network"
    data:
      name: "db-network"
      external: false
  mysql:
    type: "App.Container"
    data:
      name: "mysql"
      image: "registry.hub.docker.com/library/mysql"
      _cluster: 1
      volumes:
      - "mysql_data:/var/lib/mysql"
      hostname: "mysql"
      networks:
      - name: "db-network"
      publish_all: true
      health_config:
        protocol: "TCP"
        port: 3306
        autoredeploy: true
        timeout_millis: 2000
        ignore_on_provision: true
      restart_policy: "no"
  ghost_data:
    type: "App.Volume"
    data:
      id: "69ca19bf-f4b0-4117-8acd-6f8db378e3d8"
      name: "ghost_data"
      tenantLinks:
      - "/projects/default-project"
      driver: "local"
  mysql_data:
    type: "App.Volume"
    data:
      id: "dfbe7c16-2e7d-438e-80d9-16ab46edae42"
      name: "mysql_data"
      tenantLinks:
      - "/projects/default-project"
      driver: "local"

```
**Actual behavior:**
I had a failure in building mysql due to a missing env variable but as a result it backed out Ghost as well. Upon doing so it left the db-network in a state where it thought a container was still associated with it.

```
pc:~ user$ docker network inspect 1f02e1d19351 && docker ps --all && docker images
[
    {
        "Name": "db-network-mcm980-57424063049",
        "Id": "1f02e1d193513a5b722e5528dda3f2283b062a1116804f4df9af6e08b0928911",
        "Created": "2017-10-27T02:21:23.120210223Z",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "47b3c5e56fbf510a93e4962e9184d626bc698529aa2239147e4f461e1009af31": {
                "Name": "mysql-mcm981-57424065605",
                "EndpointID": "47b3c5e56fbf510a93e4962e9184d626bc698529aa2239147e4f461e1009af31",
                "MacAddress": "",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": null
    }
]
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
mysql                    latest              11615e225c92        31 hours ago        408MB
ghost                    latest              ebe9f648abbb        32 hours ago        604MB
drone/drone              latest              f294357febc5        13 days ago         30.4MB
drone/drone-exec         latest              f16f9cb38ef9        18 months ago       16.5MB

pc:~ user$ docker network rm 1f02e1d19351
Error response from daemon: db-network-mcm980-57424063049 has active endpoints
pc:~ user$ docker network disconnect -f 1f02e1d19351 47b3c5e56fbf510a93e4962e9184d626bc698529aa2239147e4f461e1009af31
Error response from daemon: vSphere Integrated Containers does not yet implement network.DisconnectContainerFromNetwork

```
**Expected behavior:**
Upon a failure to build an application *ALL* components should be successfully removed or at very least network.DisconnectContainerFromNetwork should be implemented.

**Logs:**

**Additional details as necessary:**

**Comment by anchal-agrawal** [comment] 2017-11-10 16:22
Hi @michaelschlies, thanks for reporting. Some questions:

* How is this application deployed? Using docker compose? Please share the commands if so.
* What is vanilla docker's behavior when the application deployment fails? Does it clean up leftover artifacts?
* We don't currently support `docker network disconnect` - that work is being tracked in https://github.com/vmware/vic/issues/4158.

**Comment by anchal-agrawal** [comment] 2017-11-10 16:43
To remove leftover artifacts manually, you can `docker rm -f` the containers and then `docker network rm` the networks.

**Comment by michaelschlies** [comment] 2017-11-11 00:42
@anchal-agrawal I tried doing a network rm but it indicated to me that containers were still there, even though a docker ps -a showed no containers and the vic interface indicated the same. This is not a simple case of idiot user doesn't know how to use the docker tools/apis available to them, thanks for trying to cover the obvious bases though.

Quote from original filed issue above:  
> pc:~ user$ ... && docker ps --all && ...
> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
>
> pc:~ user$ docker network rm 1f02e1d19351
>Error response from daemon: db-network-mcm980-57424063049 has active endpoints

**Comment by michaelschlies** [comment] 2017-11-11 00:43
@anchal-agrawal 

Missed the first comment

- This blueprint was built in the VIC template builder
- I haven't tried to run this on vanilla docker as my other docker environment at home is k8s
- Thanks for the FYI on docker network disconnect.

Thanks!

**Comment by anchal-agrawal** [comment] 2017-11-20 19:46
Thanks for the replies.

> * This blueprint was built in the VIC template builder

Pardon my lack of knowledge about blueprints/templates w.r.t using VIC - adding @hickeng for input.

@michaelschlies Could you post the VCH Admin log bundle with container logs for the VCH that exhibited the original issue? The bundle will help us root-cause the issue. Thanks!

**Comment by michaelschlies** [comment] 2017-11-21 13:21
[container-logs.zip](https://github.com/vmware/vic/files/1491449/container-logs.zip)
Attached

**Comment by anchal-agrawal** [comment] 2018-01-04 13:35
Persona:

```
Nov 21 2017 13:13:09.543Z ERROR Handler for POST /v1.24/networks/db-network-mcm359-59663183206/connect returned error: [PUT /containers/{handle}][409] commitConflict  &{Code:0 Message:Cannot complete operation due to concurrent modification by another operation.}
...
Nov 21 2017 13:13:12.957Z ERROR Handler for DELETE /v1.24/networks/ab3decf58c8b796e8a258e8d3907ed75dba560f5d7a6b52b2e4ec123cfc83e15 returned error: db-network-mcm359-59663183206 has active endpoints
```

Portlayer:

```
Nov 21 2017 13:12:50.883Z INFO  op=270.157: volume a9531d33-cebd-11e7-8039-0050569406e2 has been joined to a container
Nov 21 2017 13:13:05.943Z INFO  Reconfigure: attempting update to c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320 with change version "2017-11-21T13:16:07.743507Z" (poweredOff)
Nov 21 2017 13:13:05.944Z INFO  Reconfigure: attempting update to c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320 with change version "2017-11-21T13:16:07.743507Z" (poweredOff)
Nov 21 2017 13:13:09.532Z INFO  Reconfigure: committed update to c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320 with change version: 2017-11-21T13:16:07.743507Z
Nov 21 2017 13:13:09.541Z ERROR op=270.159: unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Nov 21 2017 13:13:09.542Z ERROR Reconfigure: failed update to c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320 with change version 2017-11-21T13:16:07.743507Z: Cannot complete operation due to concurrent modification by another operation.
Nov 21 2017 13:13:09.542Z ERROR Reconfigure: failed update to c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320 due to ConcurrentAccess, our change version 2017-11-21T13:16:07.743507Z
Nov 21 2017 13:13:09.542Z ERROR CommitHandler error on handle(b3898c6fbb12864e6d14b87291e8848f) for c8653b7fb9005d706f95ebe5128d2a2b7be75efcdc2a261fcadd835d08919320: exec.ConcurrentAccessError{err:task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc420a70940)}}
```

Unfortunately, there are no function traces in the logs which would've helped narrow down on the conflicting operations here. Digging deeper:

vpxd:

```
2017-11-21T13:18:24.051Z info vpxd[7F51CE5CB700] [Originator@6876 sub=vpxLro opID=6429693e] [VpxLRO] -- BEGIN task-1092 -- vm-58 -- vim.VirtualMachine.reconfigure -- 526c9956-cc91-2dc6-fc02-a1de5709d3b1(527b75ab-fcc6-ac76-2171-ff518ea32d13)
2017-11-21T13:18:24.053Z info vpxd[7F51CF972700] [Originator@6876 sub=vpxLro opID=6f1d2bd7] [VpxLRO] -- BEGIN task-1091 -- vm-58 -- vim.VirtualMachine.reconfigure -- 526c9956-cc91-2dc6-fc02-a1de5709d3b1(527b75ab-fcc6-ac76-2171-ff518ea32d13)
2017-11-21T13:18:24.794Z info vpxd[7F51D4CB6700] [Originator@6876 sub=vpxLro opID=380a0c1e-4a61-4e6d-b2d7-6d550d0f8cec-17017-ngc-30] [VpxLRO] -- BEGIN lro-101380 -- ChangeLogCollector -- vim.cdc.ChangeLogCollector.waitForChanges -- 5224bc0f-8fa2-7f9c-1038-c368ef0e9c64(52c3e5bb-5dd8-2716-5b89-1b29375226a5)
2017-11-21T13:18:24.795Z info vpxd[7F51D4CB6700] [Originator@6876 sub=vpxLro opID=380a0c1e-4a61-4e6d-b2d7-6d550d0f8cec-17017-ngc-30] [VpxLRO] -- FINISH lro-101380
2017-11-21T13:18:24.946Z info vpxd[7F51CFB76700] [Originator@6876 sub=vpxLro opID=auto-name-316:01-8f] [VpxLRO] -- BEGIN lro-101381 -- ResourceModel -- cis.data.provider.ResourceModel.query -- 5224bc0f-8fa2-7f9c-1038-c368ef0e9c64(52c3e5bb-5dd8-2716-5b89-1b29375226a5)
2017-11-21T13:18:24.946Z info vpxd[7F51CFB76700] [Originator@6876 sub=vpxLro opID=auto-name-316:01-8f] [VpxLRO] -- FINISH lro-101381
2017-11-21T13:18:25.798Z info vpxd[7F51D4629700] [Originator@6876 sub=vpxLro opID=380a0c1e-4a61-4e6d-b2d7-6d550d0f8cec-17019-ngc-3e] [VpxLRO] -- BEGIN lro-101382 -- ChangeLogCollector -- vim.cdc.ChangeLogCollector.waitForChanges -- 5224bc0f-8fa2-7f9c-1038-c368ef0e9c64(52c3e5bb-5dd8-2716-5b89-1b29375226a5)
2017-11-21T13:18:26.970Z info vpxd[7F51CE64C700] [Originator@6876 sub=vpxLro opID=HB-SpecSync-host-16@52-52673968] [VpxLRO] -- BEGIN lro-101383 --  -- SpecSyncLRO.Synchronize -- 
2017-11-21T13:18:27.449Z info vpxd[7F51CE64C700] [Originator@6876 sub=vpxLro opID=HB-SpecSync-host-16@52-52673968] [VpxLRO] -- FINISH lro-101383
2017-11-21T13:18:27.461Z warning vpxd[7F51D4425700] [Originator@6876 sub=VpxProfiler opID=6429693e-TaskLoop-d0a6f3] TaskLoop [TotalTime] took 3407 ms
2017-11-21T13:18:27.615Z info vpxd[7F51CE5CB700] [Originator@6876 sub=pbm opID=6429693e] PBMCallback: ReconfigVmAssociations: No association to reconfig for vm vm-58
2017-11-21T13:18:27.617Z info vpxd[7F51CE5CB700] [Originator@6876 sub=vpxLro opID=6429693e] [VpxLRO] -- FINISH task-1092
2017-11-21T13:18:27.618Z error vpxd[7F51CF972700] [Originator@6876 sub=VmProv opID=6f1d2bd7] Unexpected exception (N3Vim5Fault16ConcurrentAccess9ExceptionE(vim.fault.ConcurrentAccess)
--> [context]zKq7AVECAAAAAEklWwAWdnB4ZAAAeF4rbGlidm1hY29yZS5zbwAAEBcbAMppGAEu0VR2cHhkAAFbsskBjrTJARrFyQF4gMkBnRGuAXkVrgHuFa6CfTQGAWxpYnZpbS10eXBlcy5zbwAB/KZ0AUufcwHAlHMBT7hzAYALdABHrCMALq8jADe3KwNUdABsaWJwdGhyZWFkLnNvLjAABB2MDmxpYmMuc28uNgA=[/context]) while reconfiguring VM ghost-mcm363-59663185783-c8653b7fb900.
--> _configInfo (vim.vm.ConfigInfo) {
-->    changeVersion = "2017-11-21T13:16:15.727258Z", 
-->    modified = "1970-01-01T00:00:00Z", 
-->    name = "ghost-mcm363-59663185783-c8653b7fb900",

...

2017-11-21T13:18:27.629Z info vpxd[7F51CF972700] [Originator@6876 sub=VmprovXaction opID=6f1d2bd7] [VpxdVmprovXaction] Starting journal rollback
2017-11-21T13:18:27.629Z info vpxd[7F51CF972700] [Originator@6876 sub=VmprovXaction opID=6f1d2bd7] [VpxdVmprovXaction] Vm provision transaction rollback done
2017-11-21T13:18:27.629Z info vpxd[7F51CF972700] [Originator@6876 sub=vpxLro opID=6f1d2bd7] [VpxLRO] -- FINISH task-1091
2017-11-21T13:18:27.629Z info vpxd[7F51CF972700] [Originator@6876 sub=Default opID=6f1d2bd7] [VpxLRO] -- ERROR task-1091 -- vm-58 -- vim.VirtualMachine.reconfigure: vim.fault.ConcurrentAccess:
--> Result:
--> (vim.fault.ConcurrentAccess) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>
-->    msg = ""
--> }
--> Args:
--> 
--> Arg spec:
--> (vim.vm.ConfigSpec) {
-->    changeVersion = "2017-11-21T13:16:07.743507Z",
...
```

Looks like two VM reconfigure operations collided.

**Comment by anchal-agrawal** [comment] 2018-01-07 11:30
I can repro this reliably on VIC 1.2.1 with the template that @michaelschlies provided. After looking at a setup with debug traces enabled, I believe the root cause is two simultaneous `docker network connect` operations conflicting. Here's my analysis.

Persona logs - here we see one `network connect` call failing:
```
Jan  7 2018 10:55:34.257Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:527] [4.206920817s] 
Jan  7 2018 10:55:34.325Z DEBUG Calling POST /v1.24/networks/db-network-mcm907-63715899776/connect
Jan  7 2018 10:55:34.325Z DEBUG form data: {"Container":"6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b","EndpointConfig":{"Aliases":["ghost"]},"Id":"db-network-mcm907-63715899776"}
Jan  7 2018 10:55:34.326Z DEBUG Calling POST /v1.24/networks/public/connect
Jan  7 2018 10:55:34.326Z DEBUG form data: {"Container":"6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b","EndpointConfig":{"Aliases":["ghost"]},"Id":"public"}
...
Jan  7 2018 10:55:34.434Z DEBUG EndpointsConfig: &network.EndpointSettings{IPAMConfig:(*network.EndpointIPAMConfig)(nil), Links:[]string(nil), Aliases:[]string{"ghost"}, NetworkID:"", EndpointID:"", Gateway:"", IPAddress:"", IPPrefixLen:0, IPv6Gateway:"", GlobalIPv6Address:"", GlobalIPv6PrefixLen:0, MacAddress:""}
Jan  7 2018 10:55:34.434Z DEBUG Aliases: [ghost]
Jan  7 2018 10:55:34.434Z DEBUG Links: []
Jan  7 2018 10:55:34.496Z DEBUG EndpointsConfig: &network.EndpointSettings{IPAMConfig:(*network.EndpointIPAMConfig)(nil), Links:[]string(nil), Aliases:[]string{"ghost"}, NetworkID:"", EndpointID:"", Gateway:"", IPAddress:"", IPPrefixLen:0, IPv6Gateway:"", GlobalIPv6Address:"", GlobalIPv6PrefixLen:0, MacAddress:""}
Jan  7 2018 10:55:34.496Z DEBUG Aliases: [ghost]
Jan  7 2018 10:55:34.496Z DEBUG Links: []
Jan  7 2018 10:55:35.238Z ERROR Handler for POST /v1.24/networks/db-network-mcm907-63715899776/connect returned error: [PUT /containers/{handle}][409] commitConflict  &{Code:0 Message:Cannot complete operation due to concurrent modification by another operation.}
```

Portlayer logs - here we can see the two `Commit` calls interleaving:
```
Jan  7 2018 10:55:34.434Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer:212] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:34.434Z DEBUG Links/Aliases: []string{":ghost"}
Jan  7 2018 10:55:34.434Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).AddContainer:1023]
Jan  7 2018 10:55:34.434Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588]
Jan  7 2018 10:55:34.434Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588] [3.919µs] 
Jan  7 2018 10:55:34.434Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).AddContainer:1023] [13.268µs] 
Jan  7 2018 10:55:34.434Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer:212] [36.877µs] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:34.434Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:116] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.434Z DEBUG Update: refreshing from change version 2018-01-07T10:55:33.897463Z
Jan  7 2018 10:55:34.434Z DEBUG get vm properties [config runtime] of vm VirtualMachine:vm-70
Jan  7 2018 10:55:34.434Z DEBUG properties: [config runtime summary.runtime.connectionState]
Jan  7 2018 10:55:34.435Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetStateHandler:170] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:34.495Z DEBUG Update: change version 2018-01-07T10:55:33.897463Z, extraconfig id: 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.495Z DEBUG [BEGIN] [github.com/vmware/vic/lib/migration.migrateConfig:77] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Jan  7 2018 10:55:34.495Z DEBUG [ END ] [github.com/vmware/vic/lib/migration.migrateConfig:77] [46.013µs] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Jan  7 2018 10:55:34.495Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.(*containerBase).updates:116] [60.864347ms] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.495Z DEBUG [BEGIN] [github.com/vmware/vic/lib/migration.migrateConfig:77] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Jan  7 2018 10:55:34.495Z DEBUG [ END ] [github.com/vmware/vic/lib/migration.migrateConfig:77] [74.986µs] target: ContainerConfigure, version key: guestinfo.vice./version/PluginVersion
Jan  7 2018 10:55:34.496Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetHandler:207] [168.860241ms] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.496Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer:212] handle(a0d3a8256db8ee6bc94c442005729527)
Jan  7 2018 10:55:34.496Z DEBUG Links/Aliases: []string{":ghost"}
Jan  7 2018 10:55:34.496Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).AddContainer:1023]
Jan  7 2018 10:55:34.496Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588]
Jan  7 2018 10:55:34.496Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588] [3.509µs] 
Jan  7 2018 10:55:34.496Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588]
Jan  7 2018 10:55:34.496Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).findScopes:588] [5.093µs] 
Jan  7 2018 10:55:34.496Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetStateHandler:170] [61.765586ms] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:34.497Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:34.497Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.497Z INFO  Reconfigure: attempting update to 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b with change version "2018-01-07T10:55:33.897463Z" (poweredOff)
Jan  7 2018 10:55:34.497Z DEBUG op=283.131 (delta:4.342µs): [NewOperation] op=283.131 (delta:1.968µs) [github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult:68]
Jan  7 2018 10:55:34.806Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/network.(*Context).AddContainer:1023] [309.93645ms] 
Jan  7 2018 10:55:34.806Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ScopesHandlersImpl).ScopesAddContainer:212] [309.979938ms] handle(a0d3a8256db8ee6bc94c442005729527)
Jan  7 2018 10:55:34.806Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetStateHandler:170] handle(a0d3a8256db8ee6bc94c442005729527)
Jan  7 2018 10:55:34.806Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetStateHandler:170] [13.503µs] handle(a0d3a8256db8ee6bc94c442005729527)
Jan  7 2018 10:55:34.819Z DEBUG vSphere Event Created virtual machine ghost-mcm912-63715902377-6c0266f78136 on 10.161.0.234 in ha-datacenter for eventID(23717) ignored by the event collector
Jan  7 2018 10:55:34.819Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218] handle(a0d3a8256db8ee6bc94c442005729527)
Jan  7 2018 10:55:34.820Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.820Z INFO  Reconfigure: attempting update to 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b with change version "2018-01-07T10:55:33.897463Z" (poweredOff)
Jan  7 2018 10:55:34.820Z DEBUG op=283.132 (delta:4.484µs): [NewOperation] op=283.132 (delta:1.457µs) [github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult:68]
Jan  7 2018 10:55:34.916Z DEBUG vSphere Event Task: Reconfigure virtual machine for eventID(23718) ignored by the event collector
Jan  7 2018 10:55:34.973Z INFO  Reconfigure: committed update to 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b with change version: 2018-01-07T10:55:33.897463Z
Jan  7 2018 10:55:34.973Z DEBUG Update: updated change version from handle: 2018-01-07T10:55:33.897463Z
Jan  7 2018 10:55:34.973Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] [475.703348ms] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:34.973Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218] [476.316995ms] handle(5e50a227ceea0a56f7ffe70a65ca3c7d)
Jan  7 2018 10:55:35.103Z ERROR op=283.132 (delta:283.463574ms): unexpected fault on task retry: &types.ConcurrentAccess{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}
Jan  7 2018 10:55:35.238Z ERROR Reconfigure: failed update to 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b with change version 2018-01-07T10:55:33.897463Z: Cannot complete operation due to concurrent modification by another operation.
Jan  7 2018 10:55:35.238Z ERROR Reconfigure: failed update to 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b due to ConcurrentAccess, our change version 2018-01-07T10:55:33.897463Z
Jan  7 2018 10:55:35.238Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] [417.82786ms] 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b
Jan  7 2018 10:55:35.238Z ERROR CommitHandler error on handle(a0d3a8256db8ee6bc94c442005729527) for 6c0266f78136a72cc832eaeab7c6bd34d9b66d942e42120b7e9a764bdb40562b: exec.ConcurrentAccessError{err:task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc420521da0)}}
Jan  7 2018 10:55:35.238Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler:218] [418.490817ms] handle(a0d3a8256db8ee6bc94c442005729527)
```

I believe what happened in @michaelschlies's case is the container was able to connect to the `db-network-mcm980-57424063049` network but not `public` (hence the `active endpoints` error upon trying to delete `db-network-mcm980-57424063049`). Upon failure to provision the template, Admiral removed the container but couldn't remove `db-network` because of the said error. Further, @michaelschlies was unable to remove `db-network` manually because its state still had the container in its metadata, which it shouldn't (I haven't been able to repro this particular behavior so far).

**Comment by anchal-agrawal** [comment] 2018-01-07 11:34
An easy way to repro this issue is to create a container and then issue two `network connect` calls simultaneously:

```
$ sudo docker -H 10.161.6.14:2376 --tls create --name c1 busybox
3505e52cfdf3f95339593ddd2d696c6d24695bb58fc3601e7571a5d02862ef2a
$ sudo docker -H 10.161.6.14:2376 --tls network connect foonet c1
Error response from daemon: [PUT /containers/{handle}][409] commitConflict  &{Code:0 Message:Cannot complete operation due to concurrent modification by another operation.}

(another window)
$ sudo docker -H 10.161.6.14:2376 --tls network connect public c1
<succeeds>
```

**Comment by michaelschlies** [comment] 2018-01-07 13:33
Well, the downer to that whole thing is in k8s or docker-compose scenarios you can have containers reference each other by names which I had/have yet to get working within vic but assumed I just don't know what I'm doing with it specifically. (hence the multiple networks so I can get fixed addressing on required infra such as a db layer)

**Comment by anchal-agrawal** [comment] 2018-01-07 14:38
@michaelschlies We support container name referencing when the containers are connected to the same network (and with the legacy `docker --link` feature). If this doesn't work, please let us know and we'll file an issue.

In the template deployment scenario, the issue stems from the two concurrent calls to `network connect` where only one call succeeds. This is a bug on our end, and we'll work on a fix as part of this ticket. I have yet to see whether `docker compose` behaves the same way when a container in the compose file is to be connected to multiple networks. If using the docker CLI, a retried `network connect` call for the second network will work, however, that's not feasible in a `docker compose` or template deployment.

**Comment by anchal-agrawal** [comment] 2018-01-29 23:12
#7090 is now merged. I'll now verify whether it fully resolves this issue or not.

**Comment by anchal-agrawal** [comment] 2018-02-01 22:58
Ping @sgairo for future triage and assigning - thanks!

**Comment by sgairo** [comment] 2018-02-28 19:42
@lgayatri Would you verify for this please? Thanks so much!

**Comment by lgayatri** [comment] 2018-02-28 19:45
@sgairo , will take a look.

**Comment by lgayatri** [comment] 2018-03-01 11:56
@sgairo , is this issue fixed in 1.3.1?

**Comment by sgairo** [comment] 2018-03-01 16:09
@lgayatri I believe so, let me verify with @anchal-agrawal .

**Comment by sgairo** [comment] 2018-03-01 16:45
@lgayatri He confirmed that it is in 1.3.1, thanks!

**Comment by sgairo** [comment] 2018-03-13 15:00
@lgayatri Just checking in on this issue for updates, wondering if I should add it to our next sprint or not, thanks!

**Comment by sgairo** [comment] 2018-03-22 18:52
without any repro of this, am closing. If @lgayatri sees it in testing, this should be reopened.

**Closed by sgairo** 2018-03-22 18:52 UTC
Labels: component/docker-api-server, kind/bug, kind/customer-found, priority/p1, team/container
