### ISSUE TITLE
Error deploying containers on VCH 0.6.0

### ISSUE THREAD

**Issue by vmwarelab** [vmware/vic#3031] opened 2016-11-06 00:08 UTC
```ts
// A self-contained demonstration of the problem follows...

when executing the following from the client machine against VCH
docker -H 192.168.0.69:2376 --tls  run -p 80:80 vmwarecna/nginx 

```

**Expected behavior:**

run the nginx container

**Actual behavior:**

I get the following erorr
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default  &{Code:0xc42020d2d0 Message:parent (scratch) doesn't exist in http://VCH01/storage/images/421de96b-21dd-8489-9624-2e10936158c7: cannot stat '[MGMT-LocalDisk1] VCH01/VIC/421de96b-21dd-8489-9624-2e10936158c7/images/scratch/manifest': No such file}.

Any help is appreciated. Thank you

**Comment by mlh78750** [comment] 2016-11-07 16:29
@vmwarelab Can you please collect the logs from the vic-admin page? And do you still happen to have the command line params you used to install the VCH?

**Comment by vmwarelab** [comment] 2016-11-07 16:59
[container-logs (1).zip](https://github.com/vmware/vic/files/576026/container-logs.1.zip)

command i have used
```
 ./vic-machine-linux create --name VCH01 -t 'administrator@vmwarelab.local:VMware1!@192.168.0.20' --compute-resource 'Management CL' --external-network dvPortGroup-Management-Network --bridge-network dvPortGroup-Bridge-VCH --image-store MGMT-LocalDisk1
```
i also found out from the documentation that the VIC plugin is not functional in VCH 0.6.0 release 
 https://vmware.github.io/vic/assets/files/html/vic_installation/plugin_verify_deployment.html

**Comment by mlh78750** [comment] 2016-11-07 17:29
From personality log:
time="2016-11-06T21:29:47Z" level=info msg="Creating image store" 
time="2016-11-06T21:29:51Z" level=error msg="Failed to create image store" 
time="2016-11-06T21:29:51Z" level=fatal msg="failed to initialize backend: [POST /storage][500] CreateImageStore default  &{Code:0xc42036b248 Message:Put https://esx-01a.vmwarelab.local/folder/VCH01/VIC/421df1e6-9de7-d684-b8fb-384f2e2fc1c5/images/scratch/manifest?dsName=MGMT-LocalDisk1: dial tcp: lookup esx-01a.vmwarelab.local: no such host}" 


cc: @jzt 

@vmwarelab: can you try with the 0.7.0 release? We are going to root cause this for .6.0 but I'd like to see if you still have a problem with .7.0. If you do have the problem still in .7.0 will you please collect logs as well. .7.0 saw quite a few changes in the image storage code.

**Comment by vmwarelab** [comment] 2016-11-07 17:31
Sure i thought the 0.7.0 isn't yet released . do you happen to have the link handy so i can download it ?

**Comment by fdawg4l** [comment] 2016-11-07 18:11
@vmwarelab 

I'm suspecting this isn't 0.7.0.  What version of VIC did you download?

> dial tcp: lookup esx-01a.vmwarelab.local: no such host

This also looks a bit suspect.  When you log into the esx or VC UI, do you see any alerts related to this?

**Comment by vmwarelab** [comment] 2016-11-07 18:15
@fdawg4l 0.7.0 downloaded from here 
https://bintray.com/vmware/vic/Download/v0.7.0

**Comment by fdawg4l** [comment] 2016-11-07 18:17
Yeah, that's definitely the right place.

**Comment by jzt** [comment] 2016-11-07 18:28
@vmwarelab You can fix this by either specifying the thumbprint, like so:  `-thumbprint=E1:E1:61:DF:72:8F:2B:EB:6B:85:B4:13:62:9C:2B:DF:A6:CC:9C:5B`, or by using `--force`.

**Comment by mhagen-vmware** [comment] 2016-11-07 18:49
Pulling this into 0.8 for now, we need to further triage prior to release.

**Comment by vmwarelab** [comment] 2016-11-07 19:37
the 0.7.0 seems harder to install 

i m using the following command now 
```
  ./vic-machine-linux create --name VCH01 --target  'https://administrator@vmwarelab.local:*****@192.168.0.20/VMWareLab DC' --compute-resource 'Management CL' --external-network dvPortGroup-Management-Network --bridge-network dvPortGroup-Bridge-VCH --image-store MGMT-LocalDisk1 --no-tls --force
```
and its timing out now throwing this error 

ERRO[2016-11-07T14:35:37-05:00] Property collector error: context deadline exceeded
ERRO[2016-11-07T14:35:37-05:00] Unable to wait for extra config property guestinfo.vice..init.networks|client.assigned.IP: context deadline exceeded
INFO[2016-11-07T14:35:37-05:00] Unable to get vm config: context deadline exceeded
INFO[2016-11-07T14:35:37-05:00] Failed to retrieve IP for client interface
INFO[2016-11-07T14:35:37-05:00]   State of all interfaces:
INFO[2016-11-07T14:35:37-05:00]     "external" IP: "waiting for IP"
INFO[2016-11-07T14:35:37-05:00]     "client" IP: "waiting for IP"
INFO[2016-11-07T14:35:37-05:00]     "management" IP: "waiting for IP"
INFO[2016-11-07T14:35:37-05:00]     "bridge" IP: "waiting for IP"
INFO[2016-11-07T14:35:37-05:00]   State of components:
INFO[2016-11-07T14:35:37-05:00]     "vicadmin": "<nil>"
INFO[2016-11-07T14:35:37-05:00]     "docker-personality": "<nil>"
INFO[2016-11-07T14:35:37-05:00]     "port-layer": "<nil>"
INFO[2016-11-07T14:35:37-05:00] Collecting C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log
ERRO[2016-11-07T14:35:37-05:00] Failed to collect C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log: context canceled
WARN[2016-11-07T14:35:37-05:00] No log data for C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log
ERRO[2016-11-07T14:35:37-05:00] --------------------
ERRO[2016-11-07T14:35:37-05:00] vic-machine-linux failed: Create timed out: use --timeout to add more time

**Comment by mlh78750** [comment] 2016-11-07 20:37
@vmwarelab For your original issue, are you deploying to a cluster of more than one host for the compute resource but to local storage on only one host?

For the .7.0 issue do you have DHCP available? If you don't you'll need to specify an IP. It looks like you're not getting any addresses. Is this a nested environment?

**Comment by vmwarelab** [comment] 2016-11-07 20:47
@mlh78750 i m deploying to a cluster with one physical host (not nested) and DHCP is available as each of my deployment had an IP ..

**Comment by mlh78750** [comment] 2016-11-08 16:59
@vmwarelab your PG dvPortGroup-Management-Network can reach the esx host as well? What is serving DHCP for you? it looks like your DNS settings from DHCP didn't make it into the appliance and I'm trying to figure out how that could happen.

**Comment by mlh78750** [comment] 2016-11-08 16:59
cc @hmahmood

**Comment by vmwarelab** [comment] 2016-11-08 17:11
@mlh78750 Yes.. of course its one flat network . my DHCP is my provider's router and it has no awareness of any DNS ? i dont though think thats the probelm.. cause i had no issue deploying the 0.6.0 release. 

is there a way to specify the dns manually within the vic-machine-linux command ? to my knowledge you can no longer use the --dns-server parameter

**Comment by hmahmood** [comment] 2016-11-08 17:33
@vmwarelab `--dns-server` should work if you specify a static ip for the external network (via `--external-network-ip`. I believe otherwise we get the DNS servers from DHCP. The change that does not request DNS servers from DHCP servers did not make it to 0.7.0, but should be present in the upcoming 0.8.0 release. 

Can you give `--dns-server` a shot in any case?

**Comment by vmwarelab** [comment] 2016-11-08 18:23
@hmahmood it accepted the parameter --dns-server but still timed out. if i check the datastore , it doesnt get to creating the vic folder with all its contents . i only see a new folder called kvStores

**Comment by mlh78750** [comment] 2016-11-08 18:26
@vmwarelab can you run the install with --debug=1 and post the output please.

**Comment by mlh78750** [comment] 2016-11-08 18:27
@vmwarelab And my comment from an hour ago was trying to figure out what happened with .6.0.  We can focus on getting your .7.0 setup.

**Comment by hmahmood** [comment] 2016-11-08 18:53
@vmwarelab as far DNS behavior is concerned that is expected with 0.6.0 and 0.7.0. As long as you don't specify static ip for external network DNS servers will continue to get populated from DHCP, and `--dns-server` will have no effect. This will be fixed with 0.8.0.

**Comment by vmwarelab** [comment] 2016-11-08 18:56
@mlh78750 here is output at the end . there tons of connection refused .. i just copied the end of the trail 

DEBU[2016-11-08T13:32:10-05:00] Components not yet initialized, retrying
DEBU[2016-11-08T13:32:10-05:00] connection refused
DEBU[2016-11-08T13:32:11-05:00] Components not yet initialized, retrying
DEBU[2016-11-08T13:32:11-05:00] connection refused
time=2016-11-08T13:32:11.742321376-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:678] [2m19.565902706s]
time=2016-11-08T13:32:11.742500723-05:00 level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:165]
INFO[2016-11-08T13:32:11-05:00] Collecting C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log
ERRO[2016-11-08T13:32:11-05:00] Failed to collect C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log: context deadline exceeded
WARN[2016-11-08T13:32:11-05:00] No log data for C7FB0A62-9D41-4447-A619-5D298B91366C vpxd.log
time=2016-11-08T13:32:11.744234572-05:00 level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:165] [1.734302ms]
ERRO[2016-11-08T13:32:11-05:00] --------------------
ERRO[2016-11-08T13:32:11-05:00] vic-machine-linux failed: Create timed out: use --timeout to add more time

**Comment by vmwarelab** [comment] 2016-11-08 19:04
Looks like we have a winner 
```
./vic-machine-linux create --name VCH01 -t 'administrator@vmwarelab.local:VMware1!@192.168.0.20' --compute-resource 'Management CL' --external-network dvPortGroup-Management-Network --bridge-network dvPortGroup-Bridge-VCH --image-store MGMT-LocalDisk1 --force --no-tlsverify --dns-server 192.168.0.10 --external-network-ip 192.168.0.22 --external-network-gateway 192.168.0.1/24 --debug=1
```
this command deployed the VCH successfully.  now i can test the pulling and running containers so back to the original issue.

**Comment by mlh78750** [comment] 2016-11-08 20:48
@vmwarelab Looking through your original issue on 0.6.0 it looks like the VCH appliance was somehow trying to connect to a FQDN called esx-01a.vmwarelab.local and could no resolve it. However your install command was only using an IP for the target. Hence the questions about your DHCP And DNS setup. If you target a FQDN the VCH appliance needs to be able to resolve that name as well to connect to the vSphere infrastructure to manage the containers, storage, etc.. It looks like on your original issue with 0.6.0 that somehow the host identifier was just a name and the VCH couldn't resolve that name. Does your VC use the names for the hosts and actually have DNS that resolves those names for the VC? Because the VCH needs to point to the same DNS server if you're setup like that. 

And I suspect that is why the install on 0.7.0 worked with the specified DNS server in the command line. You said your DHCP was from your provider which I assume means that the DNS provided in the DHCP offer will also point to that provider.

**Comment by mlh78750** [comment] 2016-11-09 22:22
@vmwarelab Wanted you to be aware of the current networking limitations for the management interface on the VCH. It should work well if it is L2 adjacent to the vsphere endpoints, but if not, you will need to implement the work around in this issue: #3081.

**Comment by vmwarelab** [comment] 2016-11-09 23:28
@mlh78750 your absolutely right . that would be a great idea to provide better feedback so the users knows its a DNS related issue. .. thank you for your help on this. i still have to test the initial issue.

**Comment by vmwarelab** [comment] 2016-11-10 08:46
so testing running a simple container using the following command on the client machine against the vch host
```
 docker -H 192.168.0.22:2376 --tls run -d -p 80:80 vmwarecna/nginx
```
failed with the following error 

docker: Error response from daemon: No volume store named (default) exists.

**Comment by jzt** [comment] 2016-11-10 15:32
@vmwarelab Please see this doc:  https://github.com/vmware/vic/blob/master/doc/user_doc/vic_app_dev/using_volumes_with_vic.md#create-a-volume-in-a-volume-store

This is likely caused by the `vmwarecna/nginx` image specifying a volume to use when creating a container.

If you create a `default` volume store when deploying your VCH, `vmwarecna/nginx` should be able to find and use it without error.

Instructions are here: https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--volume-store

Tagging @matthewavery @fdawg4l in case I'm incorrect. :)

**Comment by jzt** [comment] 2016-11-10 16:00
Following up:  I checked the `vmwarecna/nginx` metadata and was able to verify that it does use a volume:

```json
    "Volumes": {
      "/var/cache/nginx": {}
    }
```

**Comment by vmwarelab** [comment] 2016-11-10 16:06
@jzt from the documentation you mentioned and thank you for that.

it mentioned that if you only require one volume store, you can set the volume store label to default. If you set the volume store label to default, container developers do not need to specify the --opt VolumeStore=volume_store_label option when they run docker volume create.

so i added the volume-store and i set it to default  and the running the container nginx now works 

i personally till don't get what is volume-store is for  and why would you need it or need multiple volumes

**Comment by fdawg4l** [comment] 2016-11-10 17:50
> i personally still don't get what is volume-store is for ? where its created ? and why would you need it or need multiple volumes

Generally, enterprises have storage devices that present as different datastores in vsphere.  Imagine a datastore named `[ReallyFastButNotBackedUp]`, `[MarginallyFastAndBackedUpNightly]`, `[ReallySlowButBackedUpHourly]`.  One can create volumes depending on their storage policy / backup policy for a given set of a containers.  It's to allow the storage options to container admins and users available in vsphere.

**Comment by mhagen-vmware** [comment] 2017-01-24 17:30
this appears to be generally resolved and has strayed quite far from the original issue. Please open a new issue if you are seeing any other problems.

**Closed by mhagen-vmware** 2017-01-24 17:30 UTC
Labels: area/appliance, area/storage, component/docker-api-server, kind/customer-found
