### ISSUE TITLE
run may hang if command completes before attaching

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#1176] opened 2016-06-22 21:41 UTC
When executing a command that exits quickly, run may hang because the container exits before we are able to attach. 

`docker -H 192.168.218.152:2376  --tls run -it busybox /bin/ls`

We should block the execution of the command until after we have attached to the container.

May be related to #1129

**Comment by mdubya66** [comment] 2016-06-27 21:14
Per @hickeng dupe of #1129. Closing as dupe

**Closed by mdubya66** 2016-06-27 21:14 UTC
Labels: kind/bug, status/needs-attention
