### ISSUE TITLE
Error: Failed to write to image store

### ISSUE THREAD

**Issue by vmSmart** [vmware/vic#5635] opened 2017-07-04 20:25 UTC
**User Statement:**

Intend to create container from template using the management web interface.

**VIC version:**

VIC 1.1.1 / vSphere 6.5 

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?  Yes.

**Steps to reproduce:**

1) Login to Management portal  https://{Your IP}:8282
2) Select "Provision" from any Popular Template

**Actual behavior:**

Begins to provision, but then errors out.
[logs.zip](https://github.com/vmware/vic/files/1123001/logs.zip)

**Expected behavior:**

Initialize new container within the vCenter vAPP VCH. 

**Additional details as necessary:**

I can see that the host has been added, but there are no volumes listed.

**Comment by vmSmart** [comment] 2017-07-04 20:32
Here is my installation command, just in case:

`vic-machine-windows.exe create --target "https://vcenter.mydomain.com/Datacenter BM" --user administrator@mydomain.com --ops-user administrator@mydomain.com --name VCH --compute-resource Docker --image-store vsanDatastore --volume-store vsanDatastore:default --container-network CONTAINER --management-network MGMT --bridge-network BRIDGE --public-network MGMT --tls-cname *.mydomain.com --thumbprint 34:C1:0F:E8:4E:69:C4:CD:4C:4C:CF:D4:F3:1E:33:35:54:B8:A4:4E
`

**Comment by sgairo** [comment] 2017-08-09 18:17
from the logs, this appears to be related to: #4666

**Comment by rogeliosanchez** [comment] 2017-08-19 07:46
Looking at the command used to create the VCH, I was able to reproduce almost the exact same environment minus the container network, tls-cname, and ops-user flags.  
I deployed one of the most recent dev versions of the OVA (1.2 - vic-73d10421-dev) to a 6.5 cluster with 4 ESXis maintained by one VC.
After deploying a VCH using a vsanDatastore I added it to the Clusters section in Admiral.  I was able to create containers using the new Admiral/Harbor UI.  I created a container using the Admiral and Harbor methods.
Closing this issue since I couldn't reproduce it in the 1.2 OVA setup.

**Closed by rogeliosanchez** 2017-08-19 07:46 UTC
Labels: kind/bug, kind/customer-found, priority/high, product/admiral, status/needs-triage
