### ISSUE TITLE
Allow choosing ESX host within a cluster while deploying VCH

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic#4982] opened 2017-05-02 10:52 UTC
**User Statement:**

VCSA has a cluster with 64 ESX hosts. I want to deploy VCH on a particular ESX host just like how I will be able to deploy a VM on a chosen ESX within a cluster. VCH deployment should allow this operation.

**Details:**
Having an option to specify ESX host within a cluster will be very helpful to set the HOST-VM affinity rules. 
This also helps to have selected hosts allowing port 2377/tcp outbound instead of all hosts within a cluster

 ./vic-machine-linux create --force -t administrator@vsphere.local:'XXXXXXX'@XX.XX.XX.XX/vc1-dc1 -r vc1-dc1-c1/Resources/w2-stpi-XXX.XX.X.com -i 76-VMFS-6-4TB-2 -b DPortGroup -n U-VIC-01  --no-tlsverify --timeout 30m

**Acceptance Criteria:**
Allow choosing ESX host within a cluster while deploying VCH just like how VCSA allows VM creation.

#For bug reports, please include the information below:

**VIC version:** 
 ./vic-machine-linux --version
vic-machine-linux version v1.1.0-rc3-10004-a035ed1

**Comment by mhagen-vmware** [comment] 2017-05-03 16:39
This is actually a regression, marking it as such

**Comment by stuclem** [comment] 2017-05-04 10:18
@mhagen-vmware is this definitely a regression? I was under the impression that you could select specific resource pools in clusters, but not individual hosts in clusters.

**Comment by chengwang86** [comment] 2017-05-15 14:59
@lgayatri Just for clarification: are you talking about choosing a particular ESXi host within a VC cluster as the destination for the `applianceVM`? The `VCH` itself may span multiple hosts in the cluster, so you cannot specify a particular ESXi host when deploying the VCH.

@mhagen-vmware @stuclem If we are talking about choosing the destination for deploying the `applianceVM` within the cluster, this would be a new `option` (e.g., `--appliance-dest 10.192.168.11`) in `vic-machine create`.

**Comment by chengwang86** [comment] 2017-05-15 16:28
Talked with @mhagen-vmware and he confirmed that we would like to be able to deploy the VCH (not just the applianceVM) to a particular ESXi host within the VC cluster. 

Results with an older version of vic (`v0.8.0-7315-c8ac999`)
- Setup: a VC with three ESXi hosts on Nimubs. The inventory folder is `/ha-datacenter/host/` for these ESXi hosts.
- I was able to deploy the VCH successfully while specifying `--compute-resource=/ha-datacenter/host/ESXi_IP/Resources`
- when I tried `govc ls /ha-datacenter/host/ESXi_IP`, I could find the expected compute resource from the output: `/ha-datacenter/host/ESXi_IP/Resources`

**Comment by chengwang86** [comment] 2017-05-15 16:37
However, if we set up a cluster under a datacenter in the VC (an example here https://github.com/vmware/vic/blob/master/tests/manual-test-cases/Group5-Functional-Tests/5-4-High-Availability.robot#L37), neither vic-0.8 nor the latest code works when I specify the compute resource to incorporate the particular ESXi host where we want to deploy the VCH.

**Comment by lgayatri** [comment] 2017-05-15 16:52
Yes, I want to choose a particular ESXi within a VC cluster for VCH deployment.  As a vSphere Administrator, I get to choose a particular ESXi within a cluster for a VM deployment and was expecting the same for VCH as well.

**Comment by chengwang86** [comment] 2017-05-15 16:57
@lgayatri Thanks for your fast reply. But sorry I'm still a little bit confused. Do you want all your containerVMs on the same VCH and the applianceVM of that VCH to be deployed on the same ESXi host?

**Comment by chengwang86** [comment] 2017-05-15 18:57
Chatted with @emlin over slack. We suspect that this might be due to the recent changes/regression in govmomi.  I will need to confirm with Doug.

**Comment by dougm** [comment] 2017-05-15 19:50
This isn't a regression.  To place the VCH on a specific HostSystem within a cluster's ResourcePool would require the CreateChildVM call to use a specific HostSystem.  And we'd need to add a separate vic-machine flag to support that.  You can currently only use `--compute-resource` to target a specific host if it is a non-clustered standalone host.

**Comment by chengwang86** [comment] 2017-05-15 20:09
@karthik-narayan @mdubya66 According to Doug's comment above, we currently support targeting a specific ESXi host for VCH deployment only if it is a non-clustered host. Do you think if we need to add this feature to vic engine 1.2?

**Comment by emlin** [comment] 2017-05-15 20:24
Just figured out this issue is different with what we supported before. We could work with single host not part of one VC cluster, but not within a cluster.
To support this feature, we'll need to disable VM DRS, and suppose the containers created by this VCH should locate in this host as well. 
This will impact vSphere features integration. So need @karthik-narayan to prioritize.

**Comment by karthik-narayan** [comment] 2017-05-15 20:26
Just to clarify my understanding, this isn't a regression. We can target an ESX directly, but if it's in a cluster, we let VC decide the placement. 

Affinity and anti-affinity are important asks that we have from customers and we should support these requirements. That said, these did not make the cut for the 1.2 release and do not need to worked on right now. HTH.

**Comment by emlin** [comment] 2017-05-15 20:29
@karthik-narayan yeah, it's not a regression, we still support standalone esxi deployment.

agree to support affinity and anti-affinity, but I think we should have new options to define the policy, instead of support this specification in compute-resource option.

**Comment by zjs** [comment] 2018-11-02 19:09
This can now be accomplished using VM-Host affinity rules.

**Closed by zjs** 2018-11-02 19:09 UTC
Labels: kind/feature, priority/p2, team/lifecycle
