### ISSUE TITLE
`docker ps` shows nginx container as `stopped` after `docker kill`

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#6185] opened 2017-08-31 23:21 UTC
**VIC version:**

Latest code on 08/31, 2017. 

**Deployment details:**

```
bin/vic-machine-linux create --name=vch-1 --debug 1 --target=root:pwd@192.168.213.129 --volume-store=datastore1/test:default --image-store=datastore1 --no-tls --no-tlsverify --thumbprint=... --force
```

**Steps to reproduce:**
```
1. docker pull nginx 
2. docker create nginx
3. docker start container_id
4. docker kill container_id
5. docker ps -a
```

**Actual behavior:**
I tried the above cmds for both busybox and nginx
```
docker ps -a   
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                           PORTS               NAMES
967d5b0e104c        nginx               "nginx -g daemon off;"   About a minute ago   Stopped                                              kind_haibt
6c149e14c461        busybox             "/bin/top"               About an hour ago    Exited (137) About an hour ago                       zen_agnesi
```

**Expected behavior:**
The nginx container status should be `exited(137)`. 

**Additional details as necessary:**
- This is reproducible.
- Although similar behavior as reported in #5803 , I don't find any ERROR msgs in portlayer or docker-persona logs.

**Comment by mdubya66** [comment] 2017-10-30 21:29
Closing as cannot reproduce.

```
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls pull nginx
Using default tag: latest
latest: Pulling from library/nginx
bc95e04b23c0: Pull complete
a3ed95caeb02: Pull complete
aee0c172e58a: Pull complete
c2a5d8ccfabc: Pull complete
Digest: sha256:e4b96323faa21a6b84b2cf89aacddff07616136bfdc970f1f295a619ef8ecfa4
Status: Downloaded newer image for library/nginx:latest
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls create nginx
c6e03d989edb3861d606d9876739c957759f3d724bdf303631b06ff0cd50b426
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls start c6
c6
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS                        PORTS               NAMES
c6e03d989edb        nginx                   "nginx -g daemon off;"   About a minute ago   Up 45 seconds                                     priceless_hoover
3da20ef8d2bf        bensdoings/exit         "sleep 1000"             9 minutes ago        Up 8 minutes                                      exit
6e7cccda60a1        busybox                 "top"                    13 minutes ago       Up 13 minutes                                     btest
1ee8aa3785b9        bensdoings/stopsignal   "/trap.sh"               16 minutes ago       Exited (143) 14 minutes ago                       stoptest
17c087fbada5        ubuntu                  "/bin/cat /bin/hos..."   25 minutes ago       Exited (0) 25 minutes ago                         upbeat_sinoussi
be1ff577d1bc        ubuntu                  "/bin/cat /bin/hos..."   27 minutes ago       Exited (0) 26 minutes ago                         confident_roentgen
0f6299111b67        ubuntu                  "/bin/cat /bin/[ /..."   30 minutes ago       Starting                                          confident_golick
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls kill c6
c6
(mwilliamson) ib-aus-office-124:/tmp $ docker -H 10.192.68.209:2376 --tls ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS                                PORTS               NAMES
c6e03d989edb        nginx                   "nginx -g daemon off;"   About a minute ago   Exited (137) Less than a second ago                       priceless_hoover
3da20ef8d2bf        bensdoings/exit         "sleep 1000"             9 minutes ago        Up 9 minutes                                              exit
6e7cccda60a1        busybox                 "top"                    13 minutes ago       Up 13 minutes                                             btest
1ee8aa3785b9        bensdoings/stopsignal   "/trap.sh"               16 minutes ago       Exited (143) 15 minutes ago                               stoptest
17c087fbada5        ubuntu                  "/bin/cat /bin/hos..."   26 minutes ago       Exited (0) 25 minutes ago                                 upbeat_sinoussi
be1ff577d1bc        ubuntu                  "/bin/cat /bin/hos..."   27 minutes ago       Exited (0) 26 minutes ago                                 confident_roentgen
0f6299111b67        ubuntu                  "/bin/cat /bin/[ /..."   30 minutes ago       Starting                                                  confident_golick
(mwilliamson) ib-aus-office-124:/tmp $
```

**Closed by mdubya66** 2017-10-30 21:29 UTC
Labels: kind/bug, kind/bug/no-repro, priority/medium
