### ISSUE TITLE
Support for defining folders where container VM's will be created in.

### ISSUE THREAD

**Issue by marvaini** [vmware/vic#3944] opened 2017-02-14 10:27 UTC
#For stories, please include the information below:

**User Statement:**

As admin I want to organize the container (and vCH) VMs created by VIC better. When creating a new container host, I want to define the VM folder, into which the vCH VM and container VMs created by this vCH will be created into. I want vic-machine-* to create and delete the folder for me with the vCH.

**Details:**
Any details of what you want that might clarify for the developer how to approach the implementation.

**Acceptance Criteria:**

1. vic-machine-* create --vmfolder: will create a VM folder once creating a vCH. The tool will also place the vCH VM into the same folder.
2. All container VM created by this vCH will be placed under the same folder. 
3. vic-machine-* delete will also delete the related VM folder.

#For bug reports, please include the information below:

**VIC version:**

x.y.z / master / commit ID

**Deployment details:**

What was the vic-machine create command used to deploy the VCH?

**Steps to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Logs:**

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

**Comment by dougm** [comment] 2017-02-14 17:48
Duplicate of #3619

**Closed by dougm** 2017-02-14 17:48 UTC
Labels: component/vic-machine, priority/low
