### ISSUE TITLE
Port exposing doesn't seem to be working

### ISSUE THREAD

**Issue by cormachogan** [vmware/vic#1500] opened 2016-07-14 10:38 UTC
**VIC Version:**

0.1 / master / v0.4.0

I downloaded the latest customer facing builds (v0.4.0), and tried to run a very popular demo using nginx. This runs a web server in a container and presents it same IP as the VM/host running docker. This does not seem to work for our docker API endpoint in VCH.

I feel that it is important to have this working, as this might be one of the first demos/examples that customers will use to test VIC.

**Code**

```ts
// A self-contained demonstration of the problem follows...

root@photon-NaTv5i8IA [ /workspace/vic ]# docker -H 10.27.51.41:2376 --tls run --name docker-nginx -p 80:80 nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
a3ed95caeb02: Pull complete
51f5c6a04d83: Pull complete
51d229e136d0: Pull complete
bcd41daec8cc: Pull complete
Digest: sha256:1fd7247f7bdb19ab1ccabb53ec5ecfa31e2ea39a24dfe636f78265980f4eebfb
Status: Downloaded newer image for library/nginx:latest

```

**Expected behavior:**

At this point I would expect to be able to point a browser to 10.27.51.41 and see the "Welcome to Nginx" web page.

**Actual behavior:**

Unable to connect - Firefox can't establish a connection to the server at 10.27.51.41.

// more details

There is nothing wrong with Nginx - it is running fine. I plumbed up an interface to the bridge network, ran the following command:

```
root@photon-NaTv5i8IA [ /workspace/vic ]# curl -Is 172.16.0.2 | head -1
HTTP/1.1 200 OK
```

And I also observed the following from the running nginx container:
```
172.16.0.100 - - [14/Jul/2016:10:24:46 +0000] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.47.1" "-"
```
[container-logs(2).tar.gz](https://github.com/vmware/vic/files/363474/container-logs.2.tar.gz)
[logs(1).tar.gz](https://github.com/vmware/vic/files/363475/logs.1.tar.gz)

**Comment by mlh78750** [comment] 2016-07-14 14:32
@cormachogan: Thanks for testing this out. This is actually a known limitation for VIC at this time. Port forwarding from the VCH is not ready yet.

From https://github.com/vmware/vic/releases:
> The function is still basic and there are some specific limitations worth pulling out:
>
>* stop is not polite - it currently powers off the VM directly without providing for filesystem sync
>* __port forwarding is not available__
>* run does not block the process from starting until attach is complete so may result in missed output and attempt to attach to stopped container
>* no volume ls support or mechanism to list volume store locations

You can track the progress of this feature with this existing issue: #938


I'm going to close your issue as a duplicate of #938.

**Closed by mlh78750** 2016-07-14 14:32 UTC
