### ISSUE TITLE
Nightly 6.7 - 5-22-NFS-Volume - Volume in use

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#7538] opened 2018-03-19 14:03 UTC
**VIC version:**

V1.4.0-DEV-17572-42375AA

**Deployment details:**

Nightly 6.7

**Logs:**

```
Running command 'docker -H 10.162.59.180:2376 --tls volume rm 6bc0c2a0-ee64-4f9d-b9db-70f5c7946ac5 2>&1'.
${output} = Error response from daemon: volume 6bc0c2a0-ee64-4f9d-b9db-70f5c7946ac5 in use by fae3e0d3d092360f550c83030fbea532fabe30fb0fd860430c3c386702abee7a
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-08-19-48.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-19 14:20
Also seen in 6.0 and 6.5 runs for 2018-03-16

6.5 https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-02-36-47.zip?authuser=1
6.0 https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-20-32-56.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-19 15:58
**VIC version:**

v1.4.0-dev-17605-6144b31

**Deployment details:**

Nightly 6.7 2018-03-17
5-22-NFS-Volume Volume rm Tests

**Logs:**

```
Running command 'docker -H 10.161.128.34:2376 --tls volume rm c9d8f9a1-3974-4728-9b16-8270eaf059a9 2>&1'.
${output} = Error response from daemon: volume c9d8f9a1-3974-4728-9b16-8270eaf059a9 in use by f8f5720606d6876b009841821d1878263c9b659f9b3bf208426c1c6130972276
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-17-05-36-01.zip?authuser=1

**Comment by hickeng** [comment] 2018-03-19 17:49
Pretty certain this is due to a failure to clean up when calling (Verify NFS Volume Basic Setup)[https://github.com/vmware/vic/blob/fe9540e9f9df412493686d33d08fc9d11650c837/tests/manual-test-cases/Group5-Functional-Tests/5-22-NFS-Volume.robot#L160] which for some reason also has the side effect of deleting the container as well as verifying that the mount is there.

We should definitely change the name of that Keyword to something less obtuse given it's not just a verification, but I expect these failures to go away when #7543 is merged.

**Comment by hickeng** [comment] 2018-03-19 18:02
Changed the title as it previously was the same title/test as #7537

**Comment by sgairo** [comment] 2018-03-27 20:45
Confirmed with @andrewtchin that this has not been seen again since #7543 was merged, closing the issue.

**Closed by sgairo** 2018-03-27 20:45 UTC
Labels: kind/ci-blocker, priority/p0, status/needs-triage, team/foundation
