### ISSUE TITLE
Test 22-12 on VC - docker run output is truncated

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#7425] opened 2018-02-28 20:59 UTC
This test runs two centos containers and verifies that yum list works in them.  The first container worked fine, but the 2nd container truncated the output from the command:

docker -H dhcp-wdc-pod2-haas01-96.eng.vmware.com:2376 --tls run centos:6 yum list

```
plymouth-plugin-fade-throbber.x86_64    0.8.3-29.el6.centos         base        
plymouth-plugin-label.x86_64            0.8.3-29.el6.centos         base        
plymouth-plugin-script.x86_64           0.8.3-29.el6.centos         base        
plymouth-plugin-space-flares.x86_64     0.8.3-29.el6.centos         base        
plymouth-plugin-throbgress.x86_64       0.8.3-29.el6.centos         base        
plymouth-plugin-two-step.x86_64         0.8.3-29.el6.centos         base        
plymouth-system-theme.noarch            0.8.3-29.el6.centos         base        
plymouth-theme-fade-in.noarch           0.8.3-29.el6.centos         base        
plymouth-theme-rings.noarch             0.8.3-29.el6.centos         base        
plymouth-theme-script.noarch            0.8.3-29.el6.centos         base        
plymouth-theme-solar.noarch             0.8.3-29.el6.centos         base        
plymouth-theme-spinfinity.noarch        0.8.3-29.el6.centos         base        
plymouth-utils.x86_64                   0.8.3-29.el6.centos         base        
pm-utils.x86_64                         1.2.5-11.el6                base        
pm-utils-devel.i686                     1.2.5-11.el6                base        
pm-utils-devel.x86_64                   1.2.5-11.el6                base        
pnm2ppa.x86_64                          1:1.04-19.el6            ' does not contain 'yum-plugin-versionlock.noarch'
```
[Test-Cases.Group22-Docker-Apps.22-12-Centos-VCH-17099-8070-container-logs.zip](https://github.com/vmware/vic/files/1768823/Test-Cases.Group22-Docker-Apps.22-12-Centos-VCH-17099-8070-container-logs.zip)

Haven't seen this test fail on ESX, just saw start failing when moved to VC in HaaS

Output should end in the z's not in the p's.  It truncated a good half or so of the output.  output.log in the bundle looks like it has the proper output.

**Comment by hickeng** [comment] 2018-03-05 23:52
The portlayer says we copied 419875 bytes for the second container
```
Feb 28 2018 16:05:21.700Z DEBUG Finished streaming stdout for dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639 (unwrapped bytes: 419875)
```
That final line in the output contains the offset 419875:
```
pnm2ppa.x86_64                          1:1.04-19.el6            <enf-of-stream>
```
The successful container wrote 803061 bytes on stdout, although of interest there were also 254 on stderr which I believe to be an early timeout contacting package mirrors:
```
eRE1tr2IFxUwAg==Loaded plugins: fastestmirror, ovl
giJhu8mIFxWQDg==http://centos.mirror.constant.com/7.4.1708/updates/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://centos.mirror.constant.com/7.4.1708/updates/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30539 milliseconds')
FdRGvMmIFxVQAQ==Trying other mirror.
dN/cPsqIFxXAAQ==Determining fastest mirrors
lkjBwM2IFxXQAQ== * base: mirrors.oit.uci.edu
ijDywM2IFxXgAQ== * extras: ftpmirror.your.org
eMQhwc2IFxXAAQ== * updates: centos.sonn.com
luWSTc6IFxUwAQ==Installed Packages
```
@mhagen-vmware might be another candidate for local package caching or offline configuration. We certainly don't care about the remote for the purposes of this test.

There's not really any indication of something wrong in the portlayer - we have not dropped the ssh connection or it would not be shutting down cleanly here:
```
Feb 28 2018 16:04:58.742Z DEBUG Found 2 subscribers to 304.66: events.ContainerEvent - Container dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639 Started
Feb 28 2018 16:04:58.742Z DEBUG Event manager calling back to PLE-f5dee5c19cacef643629d697e343170d2c1be819047fba28b8d4e83a35472d7f for Event(304.66): events.ContainerEvent
Feb 28 2018 16:04:58.742Z DEBUG Event manager calling back to netCtx(0xc4205f17a0) for Event(304.66): events.ContainerEvent
Feb 28 2018 16:05:21.694Z DEBUG connection read: EOF
Feb 28 2018 16:05:21.696Z INFO  Closing the connection
Feb 28 2018 16:05:21.696Z DEBUG connection loop write-side closed
Feb 28 2018 16:05:21.697Z INFO  telnet connection closed
Feb 28 2018 16:05:21.697Z DEBUG (vspc) detected closed connection for VM 500382e2b31dafd4-09e64a9ef297906e
Feb 28 2018 16:05:21.697Z DEBUG (vspc) closing connection to the AttachServer
Feb 28 2018 16:05:21.697Z DEBUG (vspc) deleting vm records from the vm manager 500382e2b31dafd4-09e64a9ef297906e
Feb 28 2018 16:05:21.697Z INFO  FSM closed
Feb 28 2018 16:05:21.697Z DEBUG data handler closed
Feb 28 2018 16:05:21.698Z ERROR vspc: RelayReads: telnet connection is already closed
Feb 28 2018 16:05:21.700Z INFO  Droping dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639 from connection map
Feb 28 2018 16:05:21.700Z DEBUG [BEGIN]  [vic/lib/portlayer/attach/communication.(*Connector).RemoveInteraction:198] dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639
Feb 28 2018 16:05:21.700Z DEBUG attach connector: Removing dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639 from the connection map
Feb 28 2018 16:05:21.700Z DEBUG [BEGIN]  [vic/lib/portlayer/attach/communication.(*interaction).Close:182]
Feb 28 2018 16:05:21.700Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*interaction).Close:182] [8.067µs] 
Feb 28 2018 16:05:21.700Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*Connector).RemoveInteraction:198] [31.185µs] dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639
Feb 28 2018 16:05:21.700Z DEBUG [ END ]  [vic/lib/portlayer/attach/communication.(*Connector).reqs:416] [31.762415504s] 
Feb 28 2018 16:05:21.700Z DEBUG Finished streaming stdout for dbb916ba5fc4bd664524091e9a9c5e11dfee51dfc0c67920418ff8b52cefd639 (unwrapped bytes: 419875)
```

The only conclusion I can come to is that the VM powering off caused the vSPC connection to drop with data still buffered on the ESX side. There's no indication of dropping data in the vmware.log, however I am a neophyte at reading that log file.

I've no suggestion for how to go further with this.

It is _possible_ that we could find a path that also allows us to mitigate the host sync latency impacting us on `stop` by having an additional teardown command on the interactive channel that blocks us from shutting down in guest until streams are fully purged but I'm reluctant to add more complexity to that channel without evident need and no alternative.

If this comes up again we should do some one off VC tests with _large_ quantities of streamed data with immediate exit on the container side after write.

**Comment by sgairo** [comment] 2018-03-28 18:43
infrastructure network issues were resolved since this issue was opened. intermittent and not reproducible , lowering to p2.

**Comment by mdubya66** [comment] 2018-04-18 21:34
not seen. closing

**Closed by mdubya66** 2018-04-18 21:34 UTC
Labels: kind/bug, kind/ci-blocker, priority/p2, team/container
