### ISSUE TITLE
Names in /etc/hosts different in VIC than in native Docker.

### ISSUE THREAD

**Issue by MattAtTTU** [vmware/vic#6271] opened 2017-09-11 16:49 UTC
#For stories, please include the information below:

**User Statement:**

Entries to /etc/hosts made by VIC are different than those made by native Docker.  

**Details:**

We have containers that rely on consistent host entries in /etc/hosts made by the Docker engine during runtime.  We perform a lookup on the container's hostname to define its IP address, as reachable by other containers.  In native docker, the hosts file contains an entry for the containers hostname that corresponds to it's IP on the bridge network (accessible by other containers).  In VIC, the hosts file contains an entry for the containers hostname for a loopback address of 127.0.1.1.   

**Acceptance Criteria:**

Should there be a way to instruct VIC to add the hostname to the bridge network IP in /etc/hosts instead of a loopback address?

#For bug reports, please include the information below:

**VIC version:**

1.2.0 / releases/1.2.0 / fbab49bc7e12df2cdd191cbc67687e9209a53712

**Deployment details:**

Using a generic busybox run command to test.

VIC:  docker -H VCH_IP:2376 --tls run -it -h busybox --name=busybox busybox
Native Docker:  docker run -it -h busybox --name=busybox busybox

**Steps to reproduce:**

VIC:  cat /etc/hosts, observe entry 127.0.1.1  busybox.
Native Docker:  cat /etc/hosts, observe entry 172.17.0.4      busybox

**Actual behavior:**

Hosts entry for container in VIC has hostname bound to loopback address.

**Expected behavior:**

Hosts entry for container in VIC has hsotname bound to bridge network IP address.

**Comment by chengwang86** [comment] 2017-09-11 20:05
I can reproduce this with vic-1.2:
```
docker -H 10.192.193.57:2375 run -it -h c1 busybox (vic)
/ # cat /etc/hosts
fe00:: ip6-localnet
ff00:: ip6-mcastprefix
ff02::2 ip6-allrouters
127.0.1.1  c1
127.0.0.1 localhost
::1 ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
172.16.0.2 bridge.localhost
/ # exit

docker run -it -h c1 busybox (vanilla docker)
/ # cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	c1
```

On vic-1.1.1: (probably vic-1.1.1 does not support `docker run -h` yet)
```
docker -H 10.192.198.50:2375 run -it -h c1 busybox
/ # cat /etc/hosts
ff00:: ip6-mcastprefix
ff02::2 ip6-allrouters
127.0.1.1  716de7efef04
::1 ip6-localhost ip6-loopback
fe00:: ip6-localnet
ff02::1 ip6-allnodes
172.16.0.2 bridge.localhost
127.0.0.1 localhost
```

**Comment by chengwang86** [comment] 2017-09-13 15:53
@hasanood Do you happen to know the reason why we add `127.0.0.1 containerName/ID` instead of `bridge-network-IP containerName/ID` to `/etc/hosts`?

**Comment by hickeng** [comment] 2017-09-14 06:41
That used to be the way it worked, however we took it out in favour of the loop back when adding the rename support.
This was because we couldn't alter the name used by the container while it was running given the guest info semantics.
Given we don't currently rename in DNS when container is running this could feasibly be returned to old behavior and an actual check added for power state to reject the rename. That or wait for namespacedb support to allow the online updates.

**Comment by hickeng** [comment] 2017-10-11 17:42
work on #6515 should also look at having resolution of the `hostname` be against the non-loopback by preference.

**Comment by hickeng** [comment] 2017-10-12 00:25
@MattAtTTU I don't know if you can make use of it, but we explicitly generate entries in the hosts file for the networks that the container is attached to so you can differentiate interfaces when listening for incoming connectinos:
```
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker network create other
dac824a68072ff5ebd68dfc883c0f304388f47a7037b450d0c335f73b2b6a93d
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker run -it ^C
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker create -it alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
88286f41530e: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:4b920400cf4c329e048e11be726162df2a23d29ab9dd64eaa652837cd39c2cdf
Status: Downloaded newer image for library/alpine:latest
68b074a4ca3423577b21dd5d440f8160f287090beca2605692b1ef12e23f4757
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker network connect other 68
vagrant@devbox:~/vicsmb/src/github.com/vmware/vic$ docker start -ai 68
/ # cat /etc/hosts
::1 ip6-localhost ip6-loopback
fe00:: ip6-localnet
ff02::2 ip6-allrouters
172.16.0.2 bridge.localhost
172.17.0.2 other.localhost
127.0.0.1 localhost
ff00:: ip6-mcastprefix
ff02::1 ip6-allnodes
127.0.1.1  68b074a4ca34
/ #
```

In the above example you have the following entries:
```
172.16.0.2 bridge.localhost
172.17.0.2 other.localhost
```

**Comment by mdubya66** [comment] 2018-01-04 00:40
Not a ship stopper, lowering the priority

**Comment by renmaosheng** [comment] 2019-01-09 10:51
@MattAtTTU please reopen if you have different opinion of the comments George posted. closing this for now.

**Closed by renmaosheng** 2019-01-09 10:51 UTC
Labels: kind/defect, priority/p2, source/customer, status/need-info, team/foundation
