### ISSUE TITLE
correctly format the image digest output in docker images command

### ISSUE THREAD

**Issue by jzt** [vmware/vic#1083] opened 2016-06-13 17:16 UTC
We are not prepending the `sha256:` to the digest in our `docker images` output.

**Comment by mhagen-vmware** [comment] 2016-08-08 15:50
dupe of #1054 ?

**Comment by jzt** [comment] 2016-08-11 20:22
Actually no, #1054 deals with image IDs, and this one deals with pulling by digest and running `docker images --digests`. They are very similar issues though and can probably be tackled at the same time.

**Comment by corrieb** [comment] 2017-07-19 19:32
It would appear this is now fixed

```
vagrant@ubuntu-1604-vmware:~/vic/src/github.com/vmware/dev-dock/tmp5$ docker images --digests
REPOSITORY                      TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
busybox                         latest              sha256:4c144ac2333af5526dfe7f53cc0ceb31f89aae78583fcba33fd743ef95fc9e3d   d27c8abadd3d        22 hours ago        1.13 MB
golang                          1.8                 sha256:b8bf21db6cf238db5f79cc3b2d773d0982367876d03dc5c8b8da5c336e85e612   6d9bf2aec386        11 days ago         699 MB
morellatosimone/gb-frontend     v4                  sha256:326831ca6538f020f16b90a103a170a8ca14a33904beb5d9735630cb91a7b821   4fbccdaedabf        15 months ago       512 MB
morellatosimone/gb-redisslave   v1                  sha256:1c3750d226380e40cac00860d2560a57554cd78a31b53e8a6d5ac3ad63823662   b85a076faf1f        23 months ago       109 MB
vmwarecna/nginx                 latest              sha256:637f2f942473efca8bf14e623ec793a4fa203ff3e473fcc837b848c85b3b4588   2492b68e515c        2 years ago         93.5 MB
nginx                           1.7.11              sha256:f5f5d46d85aadbc0764907ad960798f0fec4e67797a48b3285482702b2773d00   21aebf23c259        2 years ago         93.4 MB
morellatosimone/redis           e2e                 sha256:8feea4baa0780d23dc0239927c804b23b321d9fbe68552f10e039726930f439b   0ed4d3506038        2 years ago         419 MB
```

**Closed by corrieb** 2017-07-19 19:32 UTC
Labels: area/docker, component/docker-api-server, kind/bug, priority/low
