### ISSUE TITLE
Looks like at least one of our unit tests isn't taking into account path env in busybox

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/vic#1106] opened 2016-06-14 23:53 UTC
Not sure if this is part of unit tests or docker integration or if it is intentional, but from a quick grep through the code, it looks like we are calling top in busy box without it being in the path, should probably switch it to /bin/top:

```
ISOLINUX 4.05 0x4f92e181  Copyright (C) 1994-2011 H. Peter Anvin et al
Setting IP addr to  192.168.31.92/24
Setting route to 192.168.31.1
[34mINFO[0m[0000] Started reaping child processes              
[34mINFO[0m[0000] Launching pprof server on port 6060          
[34mINFO[0m[0000] Starting extension Attach                    
[34mINFO[0m[0000] opening ttyS0 for backchannel                
[34mINFO[0m[0000] s = &terminal.State{termios:syscall.Termios{Iflag:0x500, Oflag:0x5, Cflag:0xcbd, Lflag:0x8a3b, Line:0x0, Cc:[32]uint8{0x3, 0x1c, 0x7f, 0x15, 0x4, 0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Pad_cgo_0:[3]uint8{0x0, 0x0, 0x0}, Ispeed:0x0, Ospeed:0x0}} 
[34mINFO[0m[0000] creating raw connection from ttyS0 (fd=7)
   
[34mINFO[0m[0000] Loaded executor config                       
[34mINFO[0m[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] setting hostname to 7762511b1d4e 
[34mINFO[0m[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).SetHostname] [50.932µs] setting hostname to 7762511b1d4e 
[34mINFO[0m[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] applying endpoint configuration for bridge 
[34mINFO[0m[0000] [ END ] [github.com/vmware/vic/lib/tether.(*BaseOperations).Apply] [329.239µs] applying endpoint configuration for bridge 
[34mINFO[0m[0000] Launching process for session 7762511b1d4e34039caa9b4ec9812b46ea879964a20ece7b02e239fe5f48b454 
[34mINFO[0m[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).launch] launching session 7762511b1d4e34039caa9b4ec9812b46ea879964a20ece7b02e239fe5f48b454 
[34mINFO[0m[0000] [BEGIN] [main.(*operations).SessionLog] configure session log writer 
[34mINFO[0m[0000] opening ttyS2 for session logging            
[34mINFO[0m[0000] [ END ] [main.(*operations).SessionLog] [2.79947ms] configure session log writer 
[31mERRO[0m[0000] Path lookup failed for top: top: no such executable in PATH 
[34mINFO[0m[0000] [ END ] [github.com/vmware/vic/lib/tether.(*tether).launch] [154.318347ms] launching session 7762511b1d4e34039caa9b4ec9812b46ea879964a20ece7b02e239fe5f48b454 
[31mERRO[0m[0000] failed to launch top for 7762511b1d4e34039caa9b4ec9812b46ea879964a20ece7b02e239fe5f48b454: top: no such executable in PATH 
[34mINFO[0m[0000] [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).stopReaper] Shutting down child reaping 
[34mINFO[0m[0000] Shutting down reaper                         
[34mINFO[0m[0000] [ END ] [github.com/vmware/vic/lib/tether.(*tether).stopReaper] [2.675933ms] Shutting down child reaping 
[34mINFO[0m[0000] Stopping extension Attach                    
[34mINFO[0m[0000] [BEGIN] [main.(*attachServerSSH).stop] stop attach server 
[34mINFO[0m[0000] [ END ] [main.(*attachServerSSH).stop] [863ns] stop attach server 
```

**Comment by hickeng** [comment] 2016-06-19 19:39
This is a duplicate of #1032

**Closed by hickeng** 2016-06-19 19:39 UTC
Labels: kind/bug
