### ISSUE TITLE
Containers can get into a state where the container cannot be deleted

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#4269] opened 2017-03-15 21:59 UTC
As a VIC user, I should be able to delete any container using 'docker rm'.

---

We have found a situation during docker-compose up where containers get into a "starting" state and cannot be deleted.

docker-compose down fails
docker rm fails.

```
loc@Devbox:~/docker-tests/compose/link$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                             NAMES
730116258d18        redis:alpine        "docker-entrypoint..."   31 minutes ago      Starting            192.168.218.130:32768->6379/tcp   redis1
loc@Devbox:~/docker-tests/compose/link$ docker rm 73
Error response from daemon: Server error from portlayer: [DELETE /containers/{id}][500] containerRemoveInternalServerError
```

To reproduce, take the following compose file and perform docker-compose up (without -d).
[docker-compose.yml.zip](https://github.com/vmware/vic/files/846137/docker-compose.yml.zip)

**hickeng update**: This is trivially simple to recreate - see #4296 for the steps to create a container that's hung in starting state. The problem we have here is that once the delete fails, the stop will not function.

**Comment by cgtexmex** [comment] 2017-03-15 23:11
@sflxn where's the example compose file?

**Comment by sflxn** [comment] 2017-03-15 23:24
It's in docker-compose.yml.zip above.

**Comment by cgtexmex** [comment] 2017-03-16 00:16
@sflxn way to edit that issue :-) -- Thanks!

**Comment by hickeng** [comment] 2017-03-31 16:59
This is trivially simple to recreate - see #4296 for the steps to create a container that's hung in starting state.

**Comment by hickeng** [comment] 2017-03-31 17:40
@dougm @caglar10ur It looks as though the Pl is sending the guest op but the tether doesn't honor it. I think there's two issues:
1. why aren't we failing over to the vm.poweroff case?
2. why can't tether halt the VM - think this is because of session.Lock() in halt (@caglar there's a couple of places where we could do with being able to inspect a session while `launch` is still holding the lock due to `runblock`)

**Comment by hickeng** [comment] 2017-04-13 10:30
#4296 has recreate steps, #4613 is an example from the field of the inability to shut the container down.

Using this issue as the fix vehicle for the specific problem of containers getting stuck in Starting and being unable to correct the situation.

This inherits the customer-found from #4613.

**Comment by chengwang86** [comment] 2017-04-25 22:10
I tried the docker-compose file reported in the original issue with build `10044` (April 25th) and I was not able to reproduce the error.

**Comment by emlin** [comment] 2017-04-26 01:59
the PR #4840 is to fix this problem from persona, close it.

**Closed by emlin** 2017-04-26 01:59 UTC
Labels: component/portlayer, kind/bug, kind/customer-found, priority/high
