### ISSUE TITLE
Docker-compose bundle not supported due to missing RepoDigests from docker inspect image

### ISSUE THREAD

**Issue by chengwang86** [vmware/vic#3648] opened 2017-01-18 17:15 UTC
As a user of VIC and docker-compose, I should be able to create a distributed application bundle json file from a valid docker compose file.

As a user of VIC, when I pull an image, the repo digest sha shown at the end should be correct.

As a user of VIC, when I inspect a container image, I should see a repo digest that I can use to pull the image in the future.

Acceptance Criteria: Robot scripts to verify that docker-compose can create a bundle, that docker pull shows the correct digest sha, and that docker inspect shows a valid repo digest that can then be used to pull the image.

---

Docker-compose bundle (https://docs.docker.com/compose/reference/bundle/) needs the RepoDigests information from "docker inspect image" to work. Otherwise, it simply prints the following error msg:
```
The following images need to be pulled:

    image_1
    image_2

Use `docker-compose pull image_1 image_2` to pull them.
```

Example of RepoDigest: 
```
busybox@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
```

To solve this problem, we need to check how docker-compose pulls the image when it brings up the service.

Related to #3635

**Comment by sflxn** [comment] 2017-03-08 01:21
@mdubya66 I think we should punt on this.  I'll keep looking to see how we can provide a better message and disable that path, but I do not believe we should support bundles.

This is an experimental feature in docker.  https://docs.docker.com/compose/bundles/#creating-a-stack-from-a-bundle

```
Docker Stacks and Distributed Application Bundles started as experimental features introduced in Docker 1.12 and Docker Compose 1.8, alongside the concept of swarm mode, and nodes and services in the Engine API. Neither Docker Engine nor the Docker Registry support distribution of bundles, and the concept of a bundle is not the emphasis for new releases going forward.```

**Comment by sflxn** [comment] 2017-03-08 01:37
Maybe I read the above paragraph incorrectly.  It says bundle STARTED as experimental.  Ok, maybe we should do it then.

**Comment by sflxn** [comment] 2017-03-08 02:04
Ok, did some more digging.  We should implement this.  We're displaying incorrect digest during our docker pull.  If it was correct, and we populated repodigest, we should be able to just pull the image using the repodigest.

The reason why docker-compose bundle fails is because when it creates the DAB file, it populates it with the repodigest and we do not have that in our inspect data.

**Comment by sflxn** [comment] 2017-03-08 02:06
**From standard Docker:**

```
loc@Devbox:~/docker-tests/compose/lemp$ docker pull php@sha256:81e43f4ff41f00c6ca615e334b06cd7225f51ca061001a3284ed4c41d7092f9c
sha256:81e43f4ff41f00c6ca615e334b06cd7225f51ca061001a3284ed4c41d7092f9c: Pulling from library/php
693502eb7dfb: Already exists 
16328c296404: Pull complete 
8b3c97761df6: Pull complete 
96cc94ef9aa2: Pull complete 
c3c4e4d1b493: Pull complete 
c4e0c6e34d02: Pull complete 
12e76d885b08: Pull complete 
513bff7955a7: Pull complete 
890323f3a3b0: Pull complete 
Digest: sha256:81e43f4ff41f00c6ca615e334b06cd7225f51ca061001a3284ed4c41d7092f9c
Status: Downloaded newer image for php@sha256:81e43f4ff41f00c6ca615e334b06cd7225f51ca061001a3284ed4c41d7092f9c
```

**From VIC:**
```
loc@Devbox:~/docker-tests/compose/lemp$ docker pull php@sha256:81e43f4ff41f00c6ca615e334b06cd7225f51ca061001a3284ed4c41d7092f9c
Pulling from library/php
693502eb7dfb: Already exists 
a3ed95caeb02: Pull complete 
16328c296404: Pull complete 
8b3c97761df6: Pull complete 
abd128032fc4: Pull complete 
44fb02d61ff2: Pull complete 
dbbbd7a317db: Pull complete 
4863a6502db2: Pull complete 
Digest: sha256:5a81dbf4709fc9deed3ff6622bcd35222e60e2228a51fe49d6b9a31f22408463
Status: Downloaded newer image for library/php:latest
```

**Comment by sflxn** [comment] 2017-03-09 08:48
Ok, I know what the problem is.  We're hashing the wrong manifest.  I should have a fix later today.

**Comment by sflxn** [comment] 2017-03-09 20:35
In the instance I showed above, standard docker is pulling a normal manifest and VIC is pulling a signed manifest.

**Comment by sflxn** [comment] 2017-03-09 20:45
Also, note in the above, the manifest that Docker pulls is schema version 2 and VIC pulls a signed manifest with schema version 1.

**Comment by mhagen-vmware** [comment] 2017-03-09 21:07
Should this be in the Sprint 4 milestone?

**Comment by sflxn** [comment] 2017-03-09 22:57
@mhagen-vmware Yes.  It ties in with a feature of Compose.  I can get this done today if I have no interruptions.

**Comment by sflxn** [comment] 2017-03-10 00:54
After digging more, it appears VIC is currently grabbing a manifest with schema 1 format, and the digest needs to be a hash of schema 2 format.

**Comment by sflxn** [comment] 2017-03-10 21:58
Maybe this isn't a 3 after all.  Finding the reason was easy.  Resolving it will take a little longer.

**Closed** 2017-03-15 20:11 UTC
Labels: kind/feature, priority/high
