### ISSUE TITLE
Nightly 6.7 - 5-4-High-Availability - 2018-03-16 - Failed to remove image in use

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic#7537] opened 2018-03-19 13:50 UTC
**VIC version:**

V1.4.0-DEV-17572-42375AA

**Deployment details:**
Nightly 6.7

**Logs:**
```
Running command 'docker -H 10.192.249.19:2376 --tls rmi busybox 2>&1'.
${output} = Error response from daemon: Failed to remove image "busybox": image 02d3847f0b0fb7acd4419040cc53febf91cb112db2451d9b27a245dee5b227c0 in use by d0eff29e99fcab68f81aebfdacaa6d457f92d21eac6938577dadd3c8b...
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-16-08-19-48.zip?authuser=1

**Comment by andrewtchin** [comment] 2018-03-19 15:30
**VIC version:**

v1.4.0-dev-17605-6144b31

**Deployment details:**

Nightly 6.0
5-4-High-Availability Regression Tests

**Logs:**

```
${output} = Error response from daemon: Failed to remove image "busybox": image 02d3847f0b0fb7acd4419040cc53febf91cb112db2451d9b27a245dee5b227c0 in use by 781e5eac314ec38ab12d5055e8d945a0e101f58a7271733a30bf7ddb2...
```

https://storage.cloud.google.com/vic-ci-logs/vic_nightly_logs_2018-03-17-20-32-56.zip?authuser=1

**Comment by hickeng** [comment] 2018-03-19 18:06
Closing as duplicate of #6667

**Closed by hickeng** 2018-03-19 18:06 UTC
Labels: kind/ci-blocker, priority/p0, status/needs-estimation, status/needs-triage, team/foundation
