### ISSUE TITLE
`vic-machine create` throws TLS error when the problem is an unescaped special character

### ISSUE THREAD

**Issue by stuclem** [vmware/vic#3368] opened 2016-11-29 14:34 UTC
I just tested how `vic-machine create` behaves if you don't escape spaces or special characters in an argument by specifying a value of `vic bridge` (with space, but no quotes) for the `--bridge-network` option. I got the following error:

```
$ vic-machine-windows create --target 10.153.199.35 --user 'Administrator@vsphere.local' --password 'xxx' --bridge-network vic bridge --no-tls
INFO[2016-11-29T15:45:33+02:00] ### Installing VCH ####
WARN[2016-11-29T15:45:33+02:00] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2016-11-29T15:45:33+02:00] Loaded server certificate virtual-container-host\server-cert.pem
ERRO[2016-11-29T15:45:33+02:00] Common Name must be provided when generating certificates for client authentication:
INFO[2016-11-29T15:45:33+02:00]   --tls-cname=<FQDN or static IP> # for the appliance VM
INFO[2016-11-29T15:45:33+02:00]   --tls-cname=<*.yourdomain.com>  # if DNS has entries in that form for DHCP addresses (less secure)
INFO[2016-11-29T15:45:33+02:00]   --no-tlsverify                  # disables client authentication (anyone can connect to the VCH)
INFO[2016-11-29T15:45:33+02:00]   --no-tls                        # disables TLS entirely
INFO[2016-11-29T15:45:33+02:00]
ERRO[2016-11-29T15:45:33+02:00] Create cannot continue: unable to generate certificates
ERRO[2016-11-29T15:45:33+02:00] --------------------
ERRO[2016-11-29T15:45:33+02:00] vic-machine-windows.exe failed: provide Common Name for server certificate
```

I did another test by removing the quotes from around the password, which contains @, and got the same error. So, it seems that if you include an argument that includes spaces or special characters, the validator only parses the command as far as that argument. It therefore thinks that you haven't specified any TLS options, even if you have, and so throws the TLS error message. Since this is actually a problem with another argument entirely and not a TLS issue, this is misleading. 

I ran the command again, this time specifying `--no-tls` immediately after `--target`, and this time got a more appropriate error: `vic-machine-windows.exe failed: invalid CLI arguments`.

I have documented this in a troubleshooting topic for 0.8.

**Comment by mdubya66** [comment] 2017-05-24 14:16
closing as a duplicate of the customer found #5186

**Closed by mdubya66** 2017-05-24 14:16 UTC
Labels: kind/bug, priority/low
