### ISSUE TITLE
Containers connected to non-bridge networks should issue gratuitous ARP broadcast

### ISSUE THREAD

**Issue by malginin** [vmware/vic#2932] opened 2016-10-27 23:23 UTC
**VIC Version:**

build 6299

**Expected behavior:**

Containers connected to non-bridge are accessible over the network as soon as they start up.

**Actual behavior:**

tl;dr: No connection to the container until ARP cache on the gateway expires.

Explanation in detail:

Let's take a container that's configured to connect to a real external or any other non-bridge network using static IP assignment. Its default gateway will likely be a proper network device such as a router or a firewall. Very often, these devices have very long ARP cache expiration timeouts (for example, Cisco default is 4 hours). Now, let's take a situation where that container is wiped and recreated, for whatever reason. vSphere will assign it a new MAC address, however, the gateway device will not be aware of that. There is no traffic coming from the container VM, ARP cache is still valid, so the gateway may not issue any ARP requests to the container VM for quite some time. All this time, all attempts to connect to the container from outside its network through the gateway will fail. 

This could also affect clients on the same subnet that have similar ARP behavior (that is, long ARP cache expirations and no attempts to issue ARP requests if their SYNs are not answered).

The solution to this is to issue a gratuitous ARP broadcast once tether finishes configuring the container's network stack.

**Comment by mdubya66** [comment] 2016-10-28 23:11
thanks for the issue. we'll take a look at this after our current release.

**Comment by hmahmood** [comment] 2017-01-06 18:37
@mlh78750 setting `arp_notify` to 1 should fix this? See https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by hmahmood** [comment] 2017-09-18 21:01
`arp_notify` actually does not do what we want: 

https://medium.com/@george.shuklin/arp-stale-cache-and-a-rather-peculiar-arp-notify-behavior-in-linux-9c5105d07a49
https://bugzilla.kernel.org/show_bug.cgi?id=194879

**Comment by hmahmood** [comment] 2017-09-18 21:02
We probably need to do what is laid out in https://github.com/vmware/vic/issues/4715, monitoring for changes in interface address, likely only for container networks.

**Comment by hickeng** [comment] 2017-09-19 11:36
Reopening this - I can confirm that arp_notify is set, but also that the gateway is unaware of the updated MAC address when redeploying a new VCH with the same IP.
Logging into the endpointVM via `vic-machine debug` and directly pinging through the gateways causes the new MAC address to be correctly recorded.

**Comment by hickeng** [comment] 2017-09-19 11:45
@faillax23 and @douggie I've closed your respective issues in favour of reopening this original issue.

**Comment by hickeng** [comment] 2017-09-28 21:21
https://github.com/mdlayher/arp/ or https://github.com/google/gopacket/blob/master/layers/arp.go could be a good place to start to do this programmatically.
We could add `arping` into the set of utilities that we copy into a container, but I'd prefer to avoid that where possible. We only do it for `iptables` because:
a. the Linux community seems to consider that to be the stable interface and directs people not to use the `libiptc` directly, let alone the raw netfilter mechanisms.
b. iptables is rather sizable

**Comment by corrieb** [comment] 2017-10-06 17:18
Adding a note to this issue that I've seen similar problems with containers on the bridge network. Observation is that with two identical containers deployed, one cannot be seen by the endpoint VM, whereas the other can. It seemed to be relatively non deterministic whether the two containers could see each other. All VMs were scheduled to the same ESX host. George suspects this could be due to arp caching in the endpoint VM.

This externally manifested as a failure to connect to a container open port via port mapping. Work around is to create a new docker network on the bridge and use that.

**Comment by stuclem** [comment] 2017-10-17 11:37
@hickeng @corrieb is there a doc impact with this issue?

**Comment by corrieb** [comment] 2017-10-20 15:30
@stuclem I don't think we have enough concrete knowledge of the problem

**Comment by corrieb** [comment] 2017-10-20 15:32
I'm moving this to high priority, because I've been seeing something similar to this at a customer site. I've also been seeing this with my Jenkins cluster

**Comment by hickeng** [comment] 2017-11-21 18:40
CI build: https://ci.vcna.io/vmware/vic/14921
Test failing: Container Firewalls / Checking Open Firewall

```
<msg timestamp="20171121 06:35:16.849" level="INFO">Running command 'docker -H 192.168.31.153:2376 --tls run -d --net=open-net --name p1 harbor.ci.drone.local/library/busybox nc -l -p 1234 2&gt;&amp;1'.</msg>
<msg timestamp="20171121 06:35:28.484" level="INFO">${rc} = 0</msg>
<msg timestamp="20171121 06:35:28.484" level="INFO">${output} = Unable to find image 'harbor.ci.drone.local/library/busybox:latest' locally
latest: Pulling from library/busybox
1cae461a1479: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying C...</msg>
<status status="PASS" endtime="20171121 06:35:28.484" starttime="20171121 06:35:16.846"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
...
<msg timestamp="20171121 06:35:29.180" level="INFO">Running command 'docker -H 192.168.31.153:2376 --tls run --net bridge harbor.ci.drone.local/library/busybox nc 192.168.31.202 1234 2&gt;&amp;1'.</msg>
<msg timestamp="20171121 06:37:44.024" level="INFO">${rc} = 1</msg>
<msg timestamp="20171121 06:37:44.024" level="INFO">${output} = nc: can't connect to remote host (192.168.31.202): Connection timed out</msg>
<status status="PASS" endtime="20171121 06:37:44.024" starttime="20171121 06:35:29.177"></status>
```

The container on the bridge network is unable to get a response from the container on the open network. This should work and does normally.
If this test fails again I suggest we add a command to dump the MAC address for `p1` as known by the endpointVM. This could also be impacted by #6647 if it's the gateway that's holding an invalid arp cache.

**Comment by hickeng** [comment] 2018-01-16 23:38
I suggest the following:
1. install `iputils` package as part of appliance.iso
2. add `arping` to the /.tether/ tmpfs in `bootstrap.iso` 
3. invoke `arping`, if present, any time we assign an IP address to an interface. This change would be in ops_linux code and should be written such that it can use a binary in /.tether/ tmpfs is present and run in the containerVM.

This should be delivered with a follow up issue to just write the arping directly via raw socket - we're starting to have way to many external dependencies loaded into `/.tether` and I want to start burning them down.

**Comment by malikkal** [comment] 2018-01-29 14:15
We encountered this on a particular use case when the cVM lifespan is shorter than 30 minutes, where the same IP is VCH assigned, but the MAC has changed (docker run > docker stop/rm > docker run again in a short span could reproduce).

In our environment, it was 25 minutes to be precise, as Cisco Nexus switches (5K/2K) the default [ip arp timeout](https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/n5k/commands/ip-arp-timeout.html) is 1500s. I am told this is recommended and not to tweak, as it could adversely affect the performance of the switches.

It would be great if the cVM could let the world know by broadcast, though a simple ping of the gateway from the entrypoint is a tactical workaround for the moment.

**Comment by hickeng** [comment] 2018-01-31 15:45
@mdubya66 we should try to add this for 1.3.1 if we need a respin. I’d suggest this along with #6851

**Comment by hickeng** [comment] 2018-03-05 22:33
pulled in to help with HaaS CI transition.

**Closed** 2018-03-12 17:35 UTC
Labels: component/portlayer/network, component/tether, kind/bug, kind/customer-found, kind/quality, priority/p2, team/foundation, triage/proposed-1.4
